### ISSUE TITLE
A TypeError occurred in request#get_attachment

### ISSUE THREAD

**Issue by dracos** [mysociety/alaveteli#1340]
```
can't convert nil into String
app/models/incoming_message.rb:654:in `digest'
```

The issue is that the uuencoded attachment ends with ```````````\n`\nend\n rather than just `\nend\n - so the external call to uudecode returns nil and then no hexdigest can be calculated.

Manually fixing the `raw_email` entry to remove the offending line fixes this issue for one of the two attachments that cause it from https://www.whatdotheyknow.com/request/90720 , though presumably the code should spot this in some way. The other one seems odder in that it is not listed on https://www.whatdotheyknow.com/request/27992 but is there to cause an error when visited directly, not sure if there's been some manual intervention or something else going on there.

**Comment by garethrees** [comment]
Last time we saw this was 2015. Here's a full error report:

```
A TypeError occurred in request#get_attachment:

  can't convert nil into String
  app/models/incoming_message.rb:525:in `digest'


-------------------------------
Request:
-------------------------------

  * URL       : https://www.whatdotheyknow.com/request/61842/response/159386/attach/2/ResponseT4333%2011.doc
  * Parameters: {"controller"=>"request", "action"=>"get_attachment", "id"=>"61842", "incoming_message_id"=>"159386", "part"=>"2", "file_name"=>"ResponseT4333 11.doc", "locale"=>"cy"}
  * Rails root: /REDACTED/www.whatdotheyknow.com/alaveteli-2015-05-26T09-29-42
  * Timestamp : 2015-05-26 13:48:59 +0100

-------------------------------
Backtrace:
-------------------------------

  app/models/incoming_message.rb:525:in `digest'
  app/models/incoming_message.rb:525:in `hexdigest'
  app/models/incoming_message.rb:525:in `block in _uudecode_and_save_attachments'
  app/models/incoming_message.rb:508:in `each'
  app/models/incoming_message.rb:508:in `_uudecode_and_save_attachments'
  app/models/incoming_message.rb:572:in `extract_attachments!'
  app/models/incoming_message.rb:120:in `block in parse_raw_email!'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
  app/models/incoming_message.rb:119:in `parse_raw_email!'
  app/models/foi_attachment.rb:89:in `rescue in body'
  app/models/foi_attachment.rb:71:in `body'
  app/controllers/request_controller.rb:766:in `get_attachment'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:570:in `block (2 levels) in _run__2803366720725968483__process_action__4436804830536049723__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1087'
  app/controllers/request_controller.rb:741:in `cache_attachments'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1087'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:569:in `block in _run__2803366720725968483__process_action__4436804830536049723__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1086'
  app/controllers/application_controller.rb:106:in `record_memory'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1086'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:557:in `_run__2803366720725968483__process_action__4436804830536049723__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__4168021883754801117__call__902989568302060866__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

The attachment in that URL now downloads, so looks like this is no longer an issue.
