### ISSUE TITLE
An Errno::ENOENT occurred in request#get_attachment:

### ISSUE THREAD

**Issue by dracos** [mysociety/alaveteli#1341]
This URL now works fine, so it appears to be some form of condition/ having the wrong hash upon first generation? The hexdigest in the error is not the hexdigest of where the attachment ends up, which appears to be f3e9c4c5dc3b95ba049e4db350d3e401 according to database and file.

```
No such file or directory - FILTERED/www.whatdotheyknow.com/alaveteli-2014-01-27T14-50-43/cache/attachments_production/332/332d50ef41d42b35e50bbc4aef50781f
 app/models/foi_attachment.rb:72:in `initialize'

 * URL: https://www.whatdotheyknow.com/request/91114/response/222253/attach/2/7423289.htm.html
 * Parameters: {"file_name"=>"7423289.htm.html", "incoming_message_id"=>"222253", "part"=>"2", "controller"=>"request", "action"=>"get_attachment", "id"=>"91114", "locale"=>"cy"}

 app/models/foi_attachment.rb:72:in `initialize'
 app/models/foi_attachment.rb:72:in `open'
 app/models/foi_attachment.rb:72:in `body'
 app/controllers/request_controller.rb:724:in `get_attachment'

```

**Comment by garethrees** [comment]
This seems to happen when we switch ruby versions. https://github.com/mysociety/alaveteli/pull/4332 introduces a script to fix these up.
