### ISSUE TITLE
CommentController#new (NoMethodError) "undefined method `merge' for "Array":String

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#1447]
Possibly a quick fix:

``` diff
def new
  if params[:comment]
-    @comment = Comment.new(params[:comment].merge({
+    @comment = Comment.new(params.merge({
      :comment_type => 'request',
      :user => @user
    }))
  end

  # ...
end
```

Stack trace:

```
A NoMethodError occurred in comment#new:

undefined method `merge' for "Array":String
app/controllers/comment_controller.rb:16:in `new'


-------------------------------
Request:
-------------------------------

* URL : http://demo.alaveteli.org/annotate/request/what_kind_of_a_nose_do_you_have_447
* IP address: REDACTED
* Parameters: {"url_title"=>"what_kind_of_a_nose_do_you_have_447", "cache"=>"SIM", "controller"=>"comment", "utf8"=>"✓", "submitted_comment"=>"1", "commit"=>"Preview your annotation", "authenticity_token"=>"l9K5lCkChoyQcin6lOYD5c9BIebJpFptXrnzrLWT+yI=", "subscribe_to_request"=>"on", "comment"=>"Array", "action"=>"new", "type"=>"request", "preview"=>"1"}
* Rails root: /data/vhost/demo.alaveteli.org/alaveteli-2014-03-24T11-16-19
* Timestamp : 2014-04-18 16:40:08 +0100

-------------------------------
Session:
-------------------------------

* session id: nil
* data: {:locale=>"en"}

-------------------------------
Environment:
-------------------------------

* CONTENT_LENGTH : 924
* CONTENT_TYPE : multipart/form-data; boundary=----------------------------1d802a5343dd
* DOCUMENT_ROOT : /data/vhost/demo.alaveteli.org/docs
* HTTP_ACCEPT : */*
* HTTP_HOST : demo.alaveteli.org
* HTTP_X_FORWARDED_FOR : REDACTED
* HTTP_X_FORWARDED_PROTO : http
* HTTP_X_FORWARDED_USER : (null)
* HTTP_X_VARNISH : 2107549301
* ORIGINAL_FULLPATH : /annotate/request/what_kind_of_a_nose_do_you_have_447
* PASSENGER_APP_ENV : production
* PASSENGER_APP_GROUP_NAME : /data/vhost/demo.alaveteli.org/alaveteli
* PASSENGER_APP_ROOT : /data/vhost/demo.alaveteli.org/alaveteli
* PASSENGER_APP_TYPE : rack
* PASSENGER_CONNECT_PASSWORD : [FILTERED]
* PASSENGER_DEBUGGER : false
* PASSENGER_FRIENDLY_ERROR_PAGES : true
* PASSENGER_MAX_PRELOADER_IDLE_TIME : -1
* PASSENGER_MAX_REQUESTS : 2000
* PASSENGER_RESTART_DIR :
* PASSENGER_RUBY : /usr/bin/ruby
* PASSENGER_SHOW_VERSION_IN_HEADER : true
* PASSENGER_SPAWN_METHOD : direct
* PASSENGER_STATUS_LINE : false
* PASSENGER_STAT_THROTTLE_RATE : 0
* PATH_INFO : /annotate/request/what_kind_of_a_nose_do_you_have_447
* QUERY_STRING :
* REMOTE_ADDR : REDACTED
* REMOTE_PORT : 36724
* REQUEST_METHOD : POST
* REQUEST_URI : /annotate/request/what_kind_of_a_nose_do_you_have_447
* SCRIPT_NAME :
* SCRIPT_URI : http://demo.alaveteli.org/annotate/request/what_kind_of_a_nose_do_you_have_447
* SCRIPT_URL : /annotate/request/what_kind_of_a_nose_do_you_have_447
* SERVER_ADDR : 127.0.0.1
* SERVER_ADMIN : webmaster@alaveteli.org
* SERVER_NAME : demo.alaveteli.org
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.1
* SERVER_SOFTWARE : Apache
* action_controller.instance : comment#new
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x7fcc3a390c98>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x7fcc3722ad48>
* action_dispatch.logger : #<ActiveSupport::TaggedLogging:0x7fcc3b0b70e8>
* action_dispatch.parameter_filter : [:password, /RAW_POST_DATA/]
* action_dispatch.remote_ip : REDACTED
* action_dispatch.request.accepts : [#<Mime::Type:0x7fcc372c1b80 @synonyms=[], @string="*/*", @symbol=nil>]
* action_dispatch.request.content_type : multipart/form-data
* action_dispatch.request.flash_hash :
* action_dispatch.request.formats : [#<Mime::Type:0x7fcc372c1b80 @synonyms=[], @string="*/*", @symbol=nil>]
* action_dispatch.request.parameters : {"url_title"=>"what_kind_of_a_nose_do_you_have_447", "cache"=>"SIM", "controller"=>"comment", "utf8"=>"✓", "submitted_comment"=>"1", "commit"=>"Preview your annotation", "authenticity_token"=>"l9K5lCkChoyQcin6lOYD5c9BIebJpFptXrnzrLWT+yI=", "subscribe_to_request"=>"on", "comment"=>"Array", "action"=>"new", "type"=>"request", "preview"=>"1"}
* action_dispatch.request.path_parameters : {:type=>"request", :controller=>"comment", :action=>"new", :url_title=>"what_kind_of_a_nose_do_you_have_447"}
* action_dispatch.request.query_parameters : {}
* action_dispatch.request.request_parameters : {"cache"=>"SIM", "utf8"=>"✓", "submitted_comment"=>"1", "commit"=>"Preview your annotation", "authenticity_token"=>"l9K5lCkChoyQcin6lOYD5c9BIebJpFptXrnzrLWT+yI=", "subscribe_to_request"=>"on", "comment"=>"Array", "preview"=>"1"}
* action_dispatch.request.unsigned_session_cookie: {"session_id"=>"20eb0b146540bee699a08e23ab8b8bd9"}
* action_dispatch.request_id : f3c0a275350187fb5c812b983402db0f
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x7fcc3adc5998>
* action_dispatch.secret_token : REDACTED
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* newrelic.agent_hooks_before_fired : true
* rack.errors : #<IO:0x7fcc499c8ac0>
* rack.hijack : #<Proc:0x00007fcc47b8f810@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:69>
* rack.hijack? : true
* rack.input : #<PhusionPassenger::Utils::TeeInput:0x7fcc37232c28>
* rack.multiprocess : true
* rack.multithread : false
* rack.request.cookie_hash : {}
* rack.request.form_hash : {"cache"=>"SIM", "utf8"=>"✓", "submitted_comment"=>"1", "commit"=>"Preview your annotation", "authenticity_token"=>"l9K5lCkChoyQcin6lOYD5c9BIebJpFptXrnzrLWT+yI=", "subscribe_to_request"=>"on", "comment"=>"Array", "preview"=>"1"}
* rack.request.form_input : #<PhusionPassenger::Utils::TeeInput:0x7fcc37232c28>
* rack.request.query_hash : {}
* rack.request.query_string :
* rack.run_once : false
* rack.session : {:locale=>"en"}
* rack.session.options : {:httponly=>true, :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x7fcc3a867cd0>, :expire_after=>nil, :secret=>"REDACTED", :secure=>false, :renew=>false, :domain=>nil, :defer=>false, :path=>"/", :id=>nil}
* rack.url_scheme : http
* rack.version : [1, 2]
* Process: 3274
* Server : mastodon

-------------------------------
Backtrace:
-------------------------------

app/controllers/comment_controller.rb:16:in `new'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:492:in `_run__1619787101__process_action__520105620__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:215:in `_conditional_callback_around_853'
app/controllers/application_controller.rb:98:in `record_memory'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_853'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:480:in `_run__1619787101__process_action__520105620__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.6.8.164/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.6.8.164/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:324:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.6.8.164/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_controller/metal.rb:246:in `action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:68:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.6.8.164/lib/new_relic/rack/error_collector.rb:43:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.6.8.164/lib/new_relic/rack/agent_hooks.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.6.8.164/lib/new_relic/rack/browser_monitoring.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/cookies.rb:341:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.17/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `_run__475779968__call__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.17/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.17/lib/action_dispatch/middleware/static.rb:63:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `send'
vendor/bundle/ruby/1.8/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:442:in `initialize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:442:in `new'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:442:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:441:in `times'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:441:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `synchronize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:205:in `main_loop'
/usr/share/passenger/helper-scripts/rack-loader.rb:133
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
