### ISSUE TITLE
A NoMethodError occurred in admin_request#show_raw_email

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#1818]
`RawEmail` 554555 doesn't have an `incoming_message`.

https://github.com/mysociety/alaveteli/blob/rails-3-develop/app/controllers/admin_request_controller.rb#L218

```
undefined method `info_request' for nil:NilClass
app/controllers/admin_request_controller.rb:218:in `show_raw_email'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/request/show_raw_email/554555
* IP address: ~~~~~
* Parameters: {"controller"=>"admin_request", "action"=>"show_raw_email", "id"=>"554555"}
* Rails root:~~~/alaveteli-2014-08-28T14-37-01
* Timestamp : 2014-08-28 23:06:20 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"locale"=>"en",
"flash"=>
#<ActionDispatch::Flash::FlashHash:0x7f77720af348
@closed=false,
@flashes={},
@now=nil,
@used=#<Set: {}>>,
"session_id"=>"~~~",
"using_admin"=>1,
"post_redirect_token"=>"khrvrybadkrvg6s4gi4",
"admin_name"=>"~~~",
"remember_me"=>true,
"_csrf_token"=>"~~~",
"user_id"=>~~~,
"user_circumstance"=>"normal"}

-------------------------------
Environment:
-------------------------------

* DOCUMENT_ROOT : ~~~
* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_ACCEPT_LANGUAGE : en-US,en;q=0.8
* HTTP_CACHE_CONTROL : max-age=0
* HTTP_COOKIE : ; last_request_id=221507; last_body_id=; _wdtk_cookie_session=~~
* HTTP_HOST : www.whatdotheyknow.com
* HTTP_USER_AGENT : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36
* HTTP_X_FORWARDED_FOR : ~~~~~
* HTTP_X_FORWARDED_PROTO : https
* HTTP_X_FORWARDED_USER : (null)
* HTTP_X_REAL_IP : 82.153.21.1
* HTTP_X_SENDFILE_TYPE : X-Sendfile
* HTTP_X_VARNISH : 1699053460
* ORIGINAL_FULLPATH : /admin/request/show_raw_email/554555
* PASSENGER_APP_ENV : production
* PASSENGER_APP_GROUP_NAME : /data/vhost/www.whatdotheyknow.com/alaveteli
* PASSENGER_APP_ROOT : /data/vhost/www.whatdotheyknow.com/alaveteli
* PASSENGER_APP_TYPE : rack
* PASSENGER_CONNECT_PASSWORD : [FILTERED]
* PASSENGER_DEBUGGER : false
* PASSENGER_FRIENDLY_ERROR_PAGES : true
* PASSENGER_MAX_PRELOADER_IDLE_TIME : -1
* PASSENGER_MAX_REQUESTS : 2000
* PASSENGER_RESTART_DIR :
* PASSENGER_RUBY : /usr/bin/ruby
* PASSENGER_SHOW_VERSION_IN_HEADER : true
* PASSENGER_SPAWN_METHOD : direct
* PASSENGER_STATUS_LINE : false
* PASSENGER_STAT_THROTTLE_RATE : 0
* PATH_INFO : /admin/request/show_raw_email/554555
* QUERY_STRING :
* REMOTE_ADDR : 82.153.21.1
* REMOTE_PORT : 40109
* REQUEST_METHOD : GET
* REQUEST_URI : /admin/request/show_raw_email/554555
* SCRIPT_NAME :
* SCRIPT_URI : http://www.whatdotheyknow.com/admin/request/show_raw_email/554555
* SCRIPT_URL : /admin/request/show_raw_email/554555
* SERVER_ADDR : 127.0.0.1
* SERVER_ADMIN : webmaster@whatdotheyknow.com
* SERVER_NAME : www.whatdotheyknow.com
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.0
* SERVER_SOFTWARE : Apache
* action_controller.instance : admin_request#show_raw_email
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x7f7774e05090>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x7f77720b81c8>
* action_dispatch.logger : #<ActiveSupport::TaggedLogging:0x7f7775b6eba0>
* action_dispatch.parameter_filter : [:password, /RAW_POST_DATA/, /RAW_POST_DATA/]
* action_dispatch.remote_ip : ~~~~~~~
* action_dispatch.request.content_type :
* action_dispatch.request.formats : [#<Mime::Type:0x7f777c2bfea8 @synonyms=["application/xhtml+xml"], @string="text/html", @symbol=:html>]
* action_dispatch.request.parameters : {"controller"=>"admin_request", "action"=>"show_raw_email", "id"=>"554555"}
* action_dispatch.request.path_parameters : {:action=>"show_raw_email", :controller=>"admin_request", :id=>"554555"}
* action_dispatch.request.query_parameters : {}
* action_dispatch.request.request_parameters : {}
* action_dispatch.request.unsigned_session_cookie: {"locale"=>"en", "session_id"=>"~~~", "flash"=>#<ActionDispatch::Flash::FlashHash:0x7f77720af348 @now=nil, @used=#<Set: {}>, @closed=false, @flashes={}>, "post_redirect_token"=>"khrvrybadkrvg6s4gi4", "using_admin"=>1, "admin_name"=>"~~~", "remember_me"=>true, "_csrf_token"=>"~~~", "user_id"=>~~~, "user_circumstance"=>"normal"}
* action_dispatch.request_id : 195c1a2b5dea053992389777db581be1
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x7f77757e01a0>
* action_dispatch.secret_token : ~~~
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* exception_notifier.options : {:background_sections=>["backtrace", "data"], :email_prefix=>"[ERROR] ", :smtp_settings=>nil, :sections=>["request", "session", "environment", "backtrace"], :ignore_exceptions=>["ActiveRecord::RecordNotFound", "AbstractController::ActionNotFound", "ActionController::RoutingError"], :sender_address=>"do-not-reply-to-this-address@whatdotheyknow.com", :verbose_subject=>true, :ignore_crawlers=>[], :email_format=>:text, :email_headers=>{}, :template_path=>"exception_notifier", :ignore_if=>#<Proc:0x00007f7781489b80@/data/vhost/www.whatdotheyknow.com/alaveteli-2014-08-28T14-37-01/vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:37>, :exception_recipients=>["cron-alaveteli@mysociety.org"], :normalize_subject=>false}
* newrelic.agent_hooks_before_fired : true
* newrelic.captured_request : true
* rack.errors : #<IO:0x7f778579eab0>
* rack.hijack : #<Proc:0x00007f7783962218@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:69>
* rack.hijack? : true
* rack.input : #<PhusionPassenger::Utils::TeeInput:0x7f77720ce8b0>
* rack.multiprocess : true
* rack.multithread : false
* rack.request.cookie_hash : {"_wdtk_cookie_session"=>"BAh7DyIPYWRtaW5fbmFtZSIXZ2FuZXNoX3NpdHRhbXBhbGFtIhZ1c2VyX2NpcmN1bXN0YW5jZSILbm9ybWFsIhB1c2luZ19hZG1pbmkGIgtsb2NhbGUiB2VuIhByZW1lbWJlcl9tZVQiCmZsYXNobzolQWN0aW9uRGlzcGF0Y2g6OkZsYXNoOjpGbGFzaEhhc2gJOgpAdXNlZG86CFNldAY6CkBoYXNoewY6C25vdGljZVQ6CUBub3cwOgxAY2xvc2VkRjoNQGZsYXNoZXN7BjsJIkBNZXNzYWdlIGhhcyBiZWVuIG1vdmVkIHRvIHJlcXVlc3QocykuIFNob3dpbmcgdGhlIGxhc3Qgb25lOiIMdXNlcl9pZGkBnCIQX2NzcmZfdG9rZW4iMTQ1S2NLVzMzMXBuWDlUODgrbzFodm5vTnlYaGQ3L2RiaCtxY1FOdDdsQVE9Ig9zZXNzaW9uX2lkIiVhYjY4MDZlZTY3ZTI0MDJjZjZlOWU3Mjk1OThlNWUyYSIYcG9zdF9yZWRpcmVjdF90b2tlbiIYa2hydnJ5YmFka3J2ZzZzNGdpNA==--a82bac7e6ca295c2833e2d6d6a2aef9e27dd2b92", "last_body_id"=>"", "last_request_id"=>"221507"}
* rack.request.cookie_string : ; last_request_id=221507; last_body_id=; _wdtk_cookie_session=BAh7DyIPYWRtaW5fbmFtZSIXZ2FuZXNoX3NpdHRhbXBhbGFtIhZ1c2VyX2NpcmN1bXN0YW5jZSILbm9ybWFsIhB1c2luZ19hZG1pbmkGIgtsb2NhbGUiB2VuIhByZW1lbWJlcl9tZVQiCmZsYXNobzolQWN0aW9uRGlzcGF0Y2g6OkZsYXNoOjpGbGFzaEhhc2gJOgpAdXNlZG86CFNldAY6CkBoYXNoewY6C25vdGljZVQ6CUBub3cwOgxAY2xvc2VkRjoNQGZsYXNoZXN7BjsJIkBNZXNzYWdlIGhhcyBiZWVuIG1vdmVkIHRvIHJlcXVlc3QocykuIFNob3dpbmcgdGhlIGxhc3Qgb25lOiIMdXNlcl9pZGkBnCIQX2NzcmZfdG9rZW4iMTQ1S2NLVzMzMXBuWDlUODgrbzFodm5vTnlYaGQ3L2RiaCtxY1FOdDdsQVE9Ig9zZXNzaW9uX2lkIiVhYjY4MDZlZTY3ZTI0MDJjZjZlOWU3Mjk1OThlNWUyYSIYcG9zdF9yZWRpcmVjdF90b2tlbiIYa2hydnJ5YmFka3J2ZzZzNGdpNA%3D%3D--a82bac7e6ca295c2833e2d6d6a2aef9e27dd2b92
* rack.request.query_hash : {}
* rack.request.query_string :
* rack.run_once : false
* rack.session : {"locale"=>"en", "session_id"=>"~~~", "flash"=>#<ActionDispatch::Flash::FlashHash:0x7f77720af348 @now=nil, @used=#<Set: {}>, @closed=false, @flashes={}>, "post_redirect_token"=>"khrvrybadkrvg6s4gi4", "using_admin"=>1, "admin_name"=>"~~~", "remember_me"=>true, "_csrf_token"=>"~~~, "user_id"=>~~~, "user_circumstance"=>"normal"}
* rack.session.options : {:domain=>nil, :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x7f77753d78d8>, :defer=>false, :secret=>"~~~", :expire_after=>1 month, :secure=>false, :httponly=>true, :renew=>false, :path=>"/", :id=>"ab6806ee67e2402cf6e9e729598e5e2a"}
* rack.url_scheme : http
* rack.version : [1, 2]
* Process: 3981
* Server : ~~~~~

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_request_controller.rb:218:in `show_raw_email'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:492:in `_run__1715066548__process_action__1637535306__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:215:in `_conditional_callback_around_894'
app/controllers/application_controller.rb:98:in `record_memory'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_894'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:480:in `_run__1715066548__process_action__1637535306__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:40:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:364:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:39:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:68:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/error_collector.rb:50:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__755474161__call__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.19/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.19/lib/action_dispatch/middleware/static.rb:63:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `send'
vendor/bundle/ruby/1.8/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:442:in `initialize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:442:in `new'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:442:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:441:in `times'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:441:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `synchronize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:205:in `main_loop'
/usr/share/passenger/helper-scripts/rack-loader.rb:133
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
