### ISSUE TITLE
Transient spec failure: when generating urls should generate URLs that include the locale when using one that includes an underscore

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2196]
``` sh
Failures:

  1) when generating urls should generate URLs that include the locale when using one that includes an underscore
     Failure/Error: response.body.should match /href="\/en_GB\//
       expected "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Action Controller: Exception caught</title>\n  <style>\n    body { background-color: #fff; color: #333; }\n\n    body, p, ol, ul, td {\n      font-family: helvetica, verdana, arial, sans-serif;\n      font-size:   13px;\n      line-height: 18px;\n    }\n\n    pre {\n      background-color: #eee;\n      padding: 10px;\n      font-size: 11px;\n      white-space: pre-wrap;\n    }\n\n    a { color: #000; }\n    a:visited { color: #666; }\n    a:hover { color: #fff; background-color:#000; }\n  </style>\n</head>\n<body>\n\n<h1>\n  ApplicationController::RouteNotFound\n    in GeneralController#not_found\n</h1>\n<pre>ApplicationController::RouteNotFound</pre>\n\n\n<p><code>Rails.root: /home/vagrant/alaveteli</code></p>\n\n<div id=\"traces\">\n    <a href=\"#\" onclick=\"document.getElementById(&#x27;Framework-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Full-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Application-Trace&#x27;).style.display=&#x27;block&#x27;;; return false;\">Application Trace</a> |\n    <a href=\"#\" onclick=\"document.getElementById(&#x27;Application-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Full-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Framework-Trace&#x27;).style.display=&#x27;block&#x27;;; return false;\">Framework Trace</a> |\n    <a href=\"#\" onclick=\"document.getElementById(&#x27;Application-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Framework-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Full-Trace&#x27;).style.display=&#x27;block&#x27;;; return false;\">Full Trace</a> \n\n    <div id=\"Application-Trace\" style=\"display: block;\">\n      <pre><code>app/controllers/general_controller.rb:182:in `not_found&#x27;\napp/controllers/application_controller.rb:103:in `record_memory&#x27;\nlib/whatdotheyknow/strip_empty_sessions.rb:14:in `call&#x27;</code></pre>\n    </div>\n    <div id=\"Framework-Trace\" style=\"display: none;\">\n      <pre><code>actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action&#x27;\nactionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action&#x27;\nactionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `process_action&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:459:in `_run__620098491__process_action__659417228__callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:215:in `_conditional_callback_around_1127&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1127&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:458:in `_run__620098491__process_action__659417228__callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks&#x27;\nactionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `process_action&#x27;\nactivesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument&#x27;\nactivesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument&#x27;\nactivesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument&#x27;\nactionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action&#x27;\nactiverecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action&#x27;\nactionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process&#x27;\nactionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process&#x27;\nactionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch&#x27;\nactionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch&#x27;\nactionpack (3.2.21) lib/action_controller/metal.rb:246:in `action&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call&#x27;\njourney (1.0.4) lib/journey/router.rb:68:in `call&#x27;\njourney (1.0.4) lib/journey/router.rb:56:in `each&#x27;\njourney (1.0.4) lib/journey/router.rb:56:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call&#x27;\nexception_notification (3.0.1) lib/exception_notifier.rb:41:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call&#x27;\nrack (1.4.5) lib/rack/etag.rb:23:in `call&#x27;\nrack (1.4.5) lib/rack/conditionalget.rb:25:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call&#x27;\nrack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context&#x27;\nrack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call&#x27;\nactiverecord (3.2.21) lib/active_record/query_cache.rb:64:in `call&#x27;\nactiverecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `call&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__2039451579__call__4__callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call&#x27;\nrailties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app&#x27;\nrailties (3.2.21) lib/rails/rack/logger.rb:16:in `call&#x27;\nactivesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged&#x27;\nrailties (3.2.21) lib/rails/rack/logger.rb:16:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call&#x27;\nrack (1.4.5) lib/rack/methodoverride.rb:21:in `call&#x27;\nrack (1.4.5) lib/rack/runtime.rb:17:in `call&#x27;\nactivesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call&#x27;\nrack (1.4.5) lib/rack/lock.rb:15:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call&#x27;\nrailties (3.2.21) lib/rails/engine.rb:484:in `call&#x27;\nrailties (3.2.21) lib/rails/application.rb:231:in `call&#x27;\nrack-test (0.6.2) lib/rack/mock_session.rb:30:in `request&#x27;\nrack-test (0.6.2) lib/rack/test.rb:230:in `process_request&#x27;\nrack-test (0.6.2) lib/rack/test.rb:123:in `request&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:299:in `process&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:33:in `get&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:333:in `__send__&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:333:in `get&#x27;\nspec/integration/localisation_spec.rb:10\nrspec-core (2.13.1) lib/rspec/core/example.rb:114:in `instance_eval&#x27;\nrspec-core (2.13.1) lib/rspec/core/example.rb:114:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/example.rb:254:in `with_around_each_hooks&#x27;\nrspec-core (2.13.1) lib/rspec/core/example.rb:111:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:390:in `run_examples&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:386:in `map&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:386:in `run_examples&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:371:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:28:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:28:in `map&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:28:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/reporter.rb:34:in `report&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:25:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/runner.rb:77:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/runner.rb:17:in `autorun&#x27;\n/home/vagrant/gems/ruby/1.8/bin/rspec:19</code></pre>\n    </div>\n    <div id=\"Full-Trace\" style=\"display: none;\">\n      <pre><code>app/controllers/general_controller.rb:182:in `not_found&#x27;\nactionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action&#x27;\nactionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action&#x27;\nactionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `process_action&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:459:in `_run__620098491__process_action__659417228__callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:215:in `_conditional_callback_around_1127&#x27;\napp/controllers/application_controller.rb:103:in `record_memory&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1127&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:458:in `_run__620098491__process_action__659417228__callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks&#x27;\nactionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `process_action&#x27;\nactivesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument&#x27;\nactivesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument&#x27;\nactivesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument&#x27;\nactionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action&#x27;\nactionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action&#x27;\nactiverecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action&#x27;\nactionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process&#x27;\nactionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process&#x27;\nactionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch&#x27;\nactionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch&#x27;\nactionpack (3.2.21) lib/action_controller/metal.rb:246:in `action&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call&#x27;\njourney (1.0.4) lib/journey/router.rb:68:in `call&#x27;\njourney (1.0.4) lib/journey/router.rb:56:in `each&#x27;\njourney (1.0.4) lib/journey/router.rb:56:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call&#x27;\nexception_notification (3.0.1) lib/exception_notifier.rb:41:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call&#x27;\nrack (1.4.5) lib/rack/etag.rb:23:in `call&#x27;\nrack (1.4.5) lib/rack/conditionalget.rb:25:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call&#x27;\nrack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context&#x27;\nrack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call&#x27;\nlib/whatdotheyknow/strip_empty_sessions.rb:14:in `call&#x27;\nactiverecord (3.2.21) lib/active_record/query_cache.rb:64:in `call&#x27;\nactiverecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `call&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__2039451579__call__4__callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send&#x27;\nactivesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call&#x27;\nrailties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app&#x27;\nrailties (3.2.21) lib/rails/rack/logger.rb:16:in `call&#x27;\nactivesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged&#x27;\nrailties (3.2.21) lib/rails/rack/logger.rb:16:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call&#x27;\nrack (1.4.5) lib/rack/methodoverride.rb:21:in `call&#x27;\nrack (1.4.5) lib/rack/runtime.rb:17:in `call&#x27;\nactivesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call&#x27;\nrack (1.4.5) lib/rack/lock.rb:15:in `call&#x27;\nactionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call&#x27;\nrailties (3.2.21) lib/rails/engine.rb:484:in `call&#x27;\nrailties (3.2.21) lib/rails/application.rb:231:in `call&#x27;\nrack-test (0.6.2) lib/rack/mock_session.rb:30:in `request&#x27;\nrack-test (0.6.2) lib/rack/test.rb:230:in `process_request&#x27;\nrack-test (0.6.2) lib/rack/test.rb:123:in `request&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:299:in `process&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:33:in `get&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:333:in `__send__&#x27;\nactionpack (3.2.21) lib/action_dispatch/testing/integration.rb:333:in `get&#x27;\nspec/integration/localisation_spec.rb:10\nrspec-core (2.13.1) lib/rspec/core/example.rb:114:in `instance_eval&#x27;\nrspec-core (2.13.1) lib/rspec/core/example.rb:114:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/example.rb:254:in `with_around_each_hooks&#x27;\nrspec-core (2.13.1) lib/rspec/core/example.rb:111:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:390:in `run_examples&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:386:in `map&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:386:in `run_examples&#x27;\nrspec-core (2.13.1) lib/rspec/core/example_group.rb:371:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:28:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:28:in `map&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:28:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/reporter.rb:34:in `report&#x27;\nrspec-core (2.13.1) lib/rspec/core/command_line.rb:25:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/runner.rb:77:in `run&#x27;\nrspec-core (2.13.1) lib/rspec/core/runner.rb:17:in `autorun&#x27;\n/home/vagrant/gems/ruby/1.8/bin/rspec:19</code></pre>\n    </div>\n</div>\n\n\n\n<h2 style=\"margin-top: 30px\">Request</h2>\n<p><b>Parameters</b>: <pre>{&quot;path&quot;=&gt;&quot;en_GB&quot;}</pre></p>\n\n<p><a href=\"#\" onclick=\"document.getElementById('session_dump').style.display='block'; return false;\">Show session dump</a></p>\n<div id=\"session_dump\" style=\"display:none\"><pre>locale: &quot;en&quot;\nsession_id: &quot;48dfbd5731fe1c37eabfb67a55e144a2&quot;</pre></div>\n\n<p><a href=\"#\" onclick=\"document.getElementById('env_dump').style.display='block'; return false;\">Show env dump</a></p>\n<div id=\"env_dump\" style=\"display:none\"><pre>HTTP_ACCEPT: &quot;text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5&quot;\nREMOTE_ADDR: &quot;127.0.0.1&quot;\nSERVER_NAME: &quot;www.example.com&quot;</pre></div>\n\n\n<h2 style=\"margin-top: 30px\">Response</h2>\n<p><b>Headers</b>: <pre>None</pre></p>\n\n\n\n</body>\n</html>\n" to match /href="\/en_GB\//
     # ./spec/integration/localisation_spec.rb:11

Finished in 7 minutes 33.43 seconds
1680 examples, 1 failure, 8 pending

Failed examples:

rspec ./spec/integration/localisation_spec.rb:9 # when generating urls should generate URLs that include the locale when using one that includes an underscore

Randomized with seed 13434
```

**Comment by garethrees** [comment]
Can't reproduce this now.

**Comment by garethrees** [comment]
Just had an instance like this:

```
Failures:
  1) when generating urls should generate URLs that include the locale when using one that includes an underscore
     Failure/Error: raise RouteNotFound
     
     ApplicationController::RouteNotFound:
       ApplicationController::RouteNotFound
     # ./app/controllers/general_controller.rb:217:in `not_found'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:464:in `block in _run__3879423602589600806__process_action__callbacks'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_122'
     # ./app/controllers/application_controller.rb:113:in `record_memory'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_122'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:453:in `_run__3879423602589600806__process_action__callbacks'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
     # ./.bundle/ruby/2.3.0/gems/bullet-5.1.1/lib/bullet/rack.rb:10:in `call'
     # ./.bundle/ruby/2.3.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
     # ./lib/strip_empty_sessions.rb:13:in `call'
     # ./.bundle/ruby/2.3.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
     # ./.bundle/ruby/2.3.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__1971745316943516037__call__callbacks'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # ./.bundle/ruby/2.3.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
     # ./.bundle/ruby/2.3.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:26:in `tagged'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `tagged'
     # ./.bundle/ruby/2.3.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
     # ./.bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/static.rb:84:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
     # ./.bundle/ruby/2.3.0/gems/secure_headers-3.1.2/lib/secure_headers/middleware.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
     # ./.bundle/ruby/2.3.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
     # ./.bundle/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # ./.bundle/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # ./.bundle/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/testing/integration.rb:311:in `process'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/testing/integration.rb:32:in `get'
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.0.13/lib/action_dispatch/testing/integration.rb:345:in `block (2 levels) in <module:Runner>'
     # ./spec/integration/localisation_spec.rb:11:in `block (2 levels) in <top (required)>'
Finished in 14 minutes 42 seconds (files took 10.61 seconds to load)
4280 examples, 1 failure, 1 pending
Failed examples:
rspec ./spec/integration/localisation_spec.rb:10 # when generating urls should generate URLs that include the locale when using one that includes an underscore
```

https://travis-ci.org/mysociety/alaveteli/jobs/218799964

**Comment by garethrees** [comment]
Possibly fixed by https://github.com/mysociety/alaveteli/pull/5893.
