### ISSUE TITLE
load-sample-data fails

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2202]
```sh
$ bundle exec rake db:drop
NOTICE:  database "alaveteli_test" does not exist, skipping


$ bundle exec rake db:setup
psql:/home/vagrant/alaveteli/db/structure.sql:22: ERROR:  must be owner of extension plpgsql


$ script/load-sample-data
/home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec': PG::Error: ERROR:  permission denied: "RI_ConstraintTrigger_1966421" is a system trigger (ActiveRecord::StatementInvalid)
: ALTER TABLE "acts_as_xapian_jobs" ENABLE TRIGGER ALL;ALTER TABLE "foi_attachments" ENABLE TRIGGER ALL;ALTER TABLE "general_laws" ENABLE TRIGGER ALL;ALTER TABLE "has_tag_string_tags" ENABLE TRIGGER ALL;ALTER TABLE "holidays" ENABLE TRIGGER ALL;ALTER TABLE "info_request_batches_public_bodies" ENABLE TRIGGER ALL;ALTER TABLE "incoming_messages" ENABLE TRIGGER ALL;ALTER TABLE "comments" ENABLE TRIGGER ALL;ALTER TABLE "info_request_batches" ENABLE TRIGGER ALL;ALTER TABLE "mail_server_log_dones" ENABLE TRIGGER ALL;ALTER TABLE "public_body_versions" ENABLE TRIGGER ALL;ALTER TABLE "profile_photos" ENABLE TRIGGER ALL;ALTER TABLE "public_body_categories" ENABLE TRIGGER ALL;ALTER TABLE "public_body_category_links" ENABLE TRIGGER ALL;ALTER TABLE "public_body_category_translations" ENABLE TRIGGER ALL;ALTER TABLE "public_body_change_requests" ENABLE TRIGGER ALL;ALTER TABLE "public_body_heading_translations" ENABLE TRIGGER ALL;ALTER TABLE "public_body_headings" ENABLE TRIGGER ALL;ALTER TABLE "public_body_translations" ENABLE TRIGGER ALL;ALTER TABLE "purge_requests" ENABLE TRIGGER ALL;ALTER TABLE "outgoing_messages" ENABLE TRIGGER ALL;ALTER TABLE "post_redirects" ENABLE TRIGGER ALL;ALTER TABLE "request_classifications" ENABLE TRIGGER ALL;ALTER TABLE "schema_migrations" ENABLE TRIGGER ALL;ALTER TABLE "spam_addresses" ENABLE TRIGGER ALL;ALTER TABLE "track_things_sent_emails" ENABLE TRIGGER ALL;ALTER TABLE "user_info_request_sent_alerts" ENABLE TRIGGER ALL;ALTER TABLE "track_things" ENABLE TRIGGER ALL;ALTER TABLE "censor_rules" ENABLE TRIGGER ALL;ALTER TABLE "public_bodies" ENABLE TRIGGER ALL;ALTER TABLE "users" ENABLE TRIGGER ALL;ALTER TABLE "mail_server_logs" ENABLE TRIGGER ALL;ALTER TABLE "info_request_events" ENABLE TRIGGER ALL;ALTER TABLE "raw_emails" ENABLE TRIGGER ALL;ALTER TABLE "info_requests" ENABLE TRIGGER ALL
        from /home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `execute'
        from /home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
        from /home/vagrant/gems/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
        from /home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
        from /home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:526:in `disable_referential_integrity'
        from /home/vagrant/gems/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/fixtures.rb:476:in `create_fixtures'
        from /dev/stdin:15
        from /dev/stdin:14:in `each'
        from /dev/stdin:14
        from /home/vagrant/gems/ruby/1.8/gems/railties-3.2.21/lib/rails/commands.rb:64:in `eval'
        from /home/vagrant/gems/ruby/1.8/gems/railties-3.2.21/lib/rails/commands/runner.rb:52
        from /home/vagrant/gems/ruby/1.8/gems/railties-3.2.21/lib/rails/commands.rb:64:in `require'
        from /home/vagrant/gems/ruby/1.8/gems/railties-3.2.21/lib/rails/commands.rb:64
        from script/rails:6:in `require'
        from script/rails:6
Loaded fixtures. You may now wish to run script/update-xapian-index

**Comment by garethrees** [comment]
Solved by upgrading `vagrant` user to a superuser:

```sh
$ sudo -u postgres psql
> ALTER USER vagrant WITH SUPERUSER;
```
