### ISSUE TITLE
PG::ForeignKeyViolation occurred in admin_request#destroy

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2401]
When fully destroying a request in the admin interface of nicaragua alaveteli

```
A PG::ForeignKeyViolation occurred in admin_request#destroy:

ERROR: update or delete on table "info_requests" violates foreign key constraint "fk_censor_rules_info_request" on table "censor_rules"
DETAIL: Key (id)=(34) is still referenced from table "censor_rules".

vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'

-------------------------------
Request:
-------------------------------

* URL : https://derechoapreguntar.org/admin/requests/34
* Parameters: {"authenticity_token"=>"8ba2D0ghmFH+ZLvASpjUYi33TBpJrspAZgHoQkQzygU=", "id"=>"34", "_method"=>"delete", "commit"=>"Destroy request entirely", "controller"=>"admin_request", "action"=>"destroy", "utf8"=>"✓"}
* Timestamp : 2015-04-30 03:42:41 -0600

-------------------------------
Backtrace:
-------------------------------

vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log_without_newrelic_instrumentation'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log_without_newrelic_instrumentation'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/active_record.rb:55:in `log'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/method_tracer.rb:69:in `trace_execution_scoped'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/active_record.rb:52:in `log'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/relation.rb:413:in `delete_all'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/persistence.rb:141:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/locking/optimistic.rb:103:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:414:in `_run__1754867383__destroy__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `with_transaction_returning_status'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
app/models/info_request.rb:921:in `fully_destroy'
app/controllers/admin_request_controller.rb:87:in `destroy'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:569:in `_run__607506605__process_action__1854688183__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `_conditional_callback_around_1115'
app/controllers/application_controller.rb:106:in `record_memory'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1115'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:557:in `_run__607506605__process_action__1854688183__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:68:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__1561311642__call__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `send'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `initialize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `new'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `times'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `synchronize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:208:in `main_loop'
/usr/share/passenger/helper-scripts/rack-loader.rb:133

```

**Comment by garethrees** [comment]
Probably related to https://github.com/mysociety/alaveteli/issues/2290
