### ISSUE TITLE
Admin view of request should not break if data is bad

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2578]
Apply this:

``` diff
diff --git a/app/views/outgoing_mailer/initial_request.text.erb b/app/views/outgoing_mailer/initial_request.text.erb
index b0f1dc9..bad414c 100644
--- a/app/views/outgoing_mailer/initial_request.text.erb
+++ b/app/views/outgoing_mailer/initial_request.text.erb
@@ -1,3 +1,5 @@
+<%= raise 'oops' %>
+
 <%= raw @outgoing_message.body.strip %>
```

Make a new request. Sending the request will raise the exception.

```
RuntimeError in RequestController#new
oops
```

The `InfoRequest` is created:

``` ruby
InfoRequest.select([:id, :title]).last
# => #<InfoRequest id: 142, title: "This will break">
```

Visiting the request in the admin interface raises an error:

```
# GET http://10.10.10.30:3000/admin/requests/142

RuntimeError in AdminRequestController#show

internal error, last_event_forming_initial_request gets nil for request 142 outgoing messages count 1 all events: --- []

app/models/info_request.rb:728:in `last_event_forming_initial_request'
app/models/info_request.rb:735:in `date_initial_request_last_sent_at'
app/models/info_request.rb:754:in `date_very_overdue_after'
app/models/info_request.rb:626:in `base_calculate_status'
app/models/info_request.rb:618:in `calculate_status'
app/views/admin_request/show.html.erb:41:in `_app_views_admin_request_show_html_erb__1089785687_69948312022320'
app/models/concerns/admin_column.rb:14:in `for_admin_column'
app/models/concerns/admin_column.rb:13:in `each'
app/models/concerns/admin_column.rb:13:in `for_admin_column'
app/views/admin_request/show.html.erb:27:in `_app_views_admin_request_show_html_erb__1089785687_69948312022320'
app/views/admin_request/show.html.erb:5:in `_app_views_admin_request_show_html_erb__1089785687_69948312022320'
app/controllers/application_controller.rb:111:in `record_memory'
lib/whatdotheyknow/strip_empty_sessions.rb:15:in `call'

Parameters:

{"id"=>"142"}
```

**Comment by lizconlan** [comment]
oddly pushing this back into new just so it gets looked at again after it got caused a lot by an unexpected translation issue

**Comment by gorm** [comment]
Hey,

I encountered this issue now on our site because of another error with an template.

Just wonder how it can be fixed?

```
A RuntimeError occurred in admin_request#index:

  internal error, last_event_forming_initial_request gets nil for request 296 outgoing messages count 1 all events: --- []

  app/models/info_request.rb:713:in `last_event_forming_initial_request'
```

```
irb(main):003:0> InfoRequest.find(296)
  InfoRequest Load (0.9ms)  SELECT "info_requests".* FROM "info_requests" WHERE "info_requests"."id" = $1 LIMIT 1  [["id", 296]]
=> #<InfoRequest id: 296, title: "Innsyn i oversikt over rammeavtaler", user_id: 9, public_body_id: 1723, created_at: "2017-02-11 01:39:58", updated_at: "2017-02-11 01:39:58", described_state: "waiting_response", awaiting_description: false, prominence: "normal", url_title: "innsyn_i_oversikt_over_rammeavta", law_used: "foi", allow_new_responses_from: "anybody", handle_rejected_responses: "bounce", idhash: "dc7d4b51", external_user_name: nil, external_url: nil, attention_requested: false, comments_allowed: true, info_request_batch_id: nil, last_public_response_at: nil, reject_incoming_at_mta: false, rejected_incoming_count: 0, date_initial_request_last_sent_at: nil, date_response_required_by: nil, date_very_overdue_after: nil, last_event_forming_initial_request_id: nil>

```

**Comment by garethrees** [comment]
Hi @gorm.

What state is the request's outgoing message in?

```ruby
InfoRequest.find(296).outgoing_messages.last.status
```

If it's `"ready"`, you can [manually send it](https://github.com/mysociety/alaveteli/wiki/Sending-Failed-Outgoing-Messages) through the rails console.

**Comment by nigeljonez** [comment]
Just noticed this issue because of the just referenced issue, after mentioning the problem in passing on #5120.

FYI (NZ) is looking at implementing AWS's SES ActionMailer service (mostly trivial patch we'd be willing to send up sometime) when we update our instance, the downside is, it will unscrupulously throw exceptions for issues - regardless, we shouldn't assume sendmail and SMTP are flawless either.

An initial V1 patch that only handles outgoing messages for new requests is nigeljonez/alaveteli@ae0262bd1d45cd6b780729a8716c863d95031f7f the idea is, since the outgoing message/request is recorded - which is good, the user doesn't lose what they've written - we should provide instant feedback that the site has accepted the request, but the outgoing e-mail failed to send, and it will appear on the Admin Summary page, without effectively DoS'ing multiple pages, including parts of the Admin site.

I'd like to discuss ways of generalising this patch so that it would be acceptable for Alaveteli, while also covering other user/request critical processes (i.e. follow-up's, etc).  At the moment because of our general overhaul plans (and desire to improve reliability), this is a blocker for us for updating to 0.32 or develop.

**Comment by garethrees** [comment]
Just noting that the [specific case above](https://github.com/mysociety/alaveteli/issues/2578#issuecomment-467835879) will be fixed by https://github.com/mysociety/alaveteli/pull/5121.

**Comment by lizconlan** [comment]
reopening as I think there's a more general case of unhandled errors causing this to break

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
