### ISSUE TITLE
ActionView::MissingTemplate, :formats=>["application/text", "application/octet-stream"]

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2591]
Lots like this for various pages:

```
An ActionView::MissingTemplate occurred in general#blog:

Missing template general/blog, application/blog with {:locale=>[:en], :formats=>["application/text", "application/octet-stream"], :handlers=>[:erb, :builder, :coffee]}. Searched in:
* "/data/vhost/www.whatdotheyknow.com/alaveteli-2015-06-22T14-38-59/lib/themes/whatdotheyknow-theme/lib/views"
* "/data/vhost/www.whatdotheyknow.com/alaveteli-2015-06-22T14-38-59/app/views"
* "/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/1.9.1/gems/foundation-rails-5.2.1.0/app/views"

vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_view/path_set.rb:58:in `find'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/blog
* IP address: 98.113.59.129
* Parameters: {"controller"=>"general", "action"=>"blog"}
* Rails root: /data/vhost/www.whatdotheyknow.com/alaveteli-2015-06-22T14-38-59
* Timestamp : 2015-06-23 08:55:43 +0100
```

Looks like a bot.

Related: 
- http://stackoverflow.com/questions/5557010/missing-template-blogs-index-on-ruby-on-rails-project
- https://github.com/rails/rails/issues/701
- https://github.com/rails/rails/issues/4127

**Comment by garethrees** [comment]
Just had 100's of these through from infoprovsechny.cz.

```
An ActionView::MissingTemplate occurred in user#signin:

Missing template user/sign, application/sign with {:handlers=>[:coffee, :erb, :builder], :formats=>[:text], :locale=>[:cs]}. Searched in:
* "/srv/www/www.infoprovsechny.cz/releases/20150112120816/lib/themes/ipvtheme/lib/views"
* "/srv/www/www.infoprovsechny.cz/releases/20150112120816/app/views"
* "/srv/www/www.infoprovsechny.cz/shared/bundle/ruby/1.8/gems/foundation-rails-5.2.1.0/app/views"

actionpack (3.2.21) lib/action_view/path_set.rb:58:in `find'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
