### ISSUE TITLE
Unknown encoding 72

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2674]
```
[cron-alaveteli] Cron <foi@> run-with-lockfile -n /APP_ROOT/change-xapian-database.lock "/APP_ROOT/script/update-xapian-index verbose=true" >> /APP_ROOT/log/update-xapian-index.log || echo "stalled?"

[09:40:31 /APP_ROOT/vendor/bundle/ruby/1.9.1/bundler/gems/ruby-msg-44526e009d13/lib/mapi/msg.rb:244:parse_substg]
WARN   unknown encoding 72
[09:40:31 /APP_ROOT/vendor/bundle/ruby/1.9.1/bundler/gems/ruby-msg-44526e009d13/lib/mapi/msg.rb:244:parse_substg]
WARN   unknown encoding 72
[09:40:31 /APP_ROOT/vendor/bundle/ruby/1.9.1/bundler/gems/ruby-msg-44526e009d13/lib/mapi/property_set.rb:277:body_html]
WARN   creating html body from rtf
```

**Comment by garethrees** [comment]
Don't think we've seen this for a while so closing.

**Comment by garethrees** [comment]
Probably https://github.com/aquasync/ruby-msg/issues/17

**Comment by garethrees** [comment]
I've just had a look and we've been getting these fairly frequently of late.

```
[17:54:06 /APP_ROOT/shared/vendor/bundle/ruby/2.6.0/bundler/gems/ruby-msg-fae72e547299/lib/mapi/msg.rb:244:parse_substg]
WARN unknown encoding 72
[17:54:06 /APP_ROOT/shared/vendor/bundle/ruby/2.6.0/bundler/gems/ruby-msg-fae72e547299/lib/mapi/property_set.rb:277:body_html]
WARN creating html body from rtf
FAILED ActsAsXapian.update_index job 749576 Encoding::CompatibilityError model InfoRequestEvent id 79693.

Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT.

This job will be removed from the queue. Once the underlying problem is fixed, manually re-index the model record.

You can do this in a rails console with `InfoRequestEvent.find(79693).xapian_mark_needs_index`.

---------
Backtrace
---------

/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/bundler/gems/ruby-msg-fae72e547299/lib/mapi/mime.rb:129:in `to_s'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:60:in `mail_from_outlook'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:188:in `decode_attached_part'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:241:in `expand_and_normalize_parts'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:216:in `block in expand_and_normalize_parts'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/delegate.rb:349:in `each'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:216:in `expand_and_normalize_parts'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:284:in `get_attachment_leaves'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/mail_handler/backends/mail_backend.rb:355:in `get_attachment_attributes'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/app/models/incoming_message.rb:536:in `extract_attachments!'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/app/models/incoming_message.rb:98:in `block in parse_raw_email!'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:210:in `transaction'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/app/models/incoming_message.rb:97:in `parse_raw_email!'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/app/models/incoming_message.rb:523:in `get_attachments_for_display'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/app/models/incoming_message.rb:709:in `get_present_file_extensions'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/app/models/info_request_event.rb:269:in `filetype'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:925:in `single_xapian_value'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:918:in `xapian_value'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:1018:in `block in xapian_index'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:1017:in `each'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:1017:in `xapian_index'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:754:in `run_job'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:725:in `block (2 levels) in update_index'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:210:in `transaction'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:714:in `block in update_index'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:711:in `each'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/acts_as_xapian.rb:711:in `update_index'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/lib/acts_as_xapian/tasks/xapian.rake:12:in `block (2 levels) in <top (required)>'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/APP_ROOT/shared/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
/APP_ROOT/alaveteli-2020-07-07T08-18-09/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/opt/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/opt/rbenv/versions/2.6.6/bin/bundle:23:in `load'
/opt/rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
