### ISSUE TITLE
[ERROR] request#list (RuntimeError) "QueryParserError: Syntax: <expression> AND <expression>"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2919]
Should handle these and show error to user so that they can correct their query:

```
A RuntimeError occurred in request#list:

  QueryParserError: Syntax: <expression> AND <expression>
  lib/acts_as_xapian/acts_as_xapian.rb:481:in `parse_query'


-------------------------------
Request:
-------------------------------

  * URL       : https://www.whatdotheyknow.com/list/successful?utf8=%E2%9C%93&query=AND+sheffield&request_date_after=2014%2F09%2F01&request_date_before=2015%2F11%2F23&commit=Search
  * IP address: REDACTED
  * Parameters: {"utf8"=>"✓", "query"=>"AND sheffield", "request_date_after"=>"2014/09/01", "request_date_before"=>"2015/11/23", "commit"=>"Search", "view"=>"successful", "controller"=>"request", "action"=>"list"}
  * Rails root: /APP_ROOT/alaveteli-2015-11-23T09-57-18
  * Timestamp : 2015-11-23 17:09:35 +0000
```

**Comment by garethrees** [comment]
Another one on 2016-06-20

```
A RuntimeError occurred in request#list:

  QueryParserError: Syntax: <expression> AND <expression>
  lib/acts_as_xapian/acts_as_xapian.rb:483:in `parse_query'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/list/successful?utf8=%E2%9C%93&query=AND+sheffield&request_date_after=2014%2F09%2F01&request_date_before=2015%2F11%2F23&commit=Search
  * HTTP Method: GET
  * Parameters : {"utf8"=>"✓", "query"=>"AND sheffield", "request_date_after"=>"2014/09/01", "request_date_before"=>"2015/11/23", "commit"=>"Search", "view"=>"successful", "controller"=>"request", "action"=>"list"}
  * Timestamp  : 2016-06-20 07:39:31 +0100
```

**Comment by garethrees** [comment]
Okay so that's strange – URL is exactly the same. I wonder if someone's linked to that search query?

**Comment by garethrees** [comment]
Similar to https://github.com/mysociety/askyourgovug-theme/issues/18

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
