### ISSUE TITLE
[ERROR] info_request_batch#show (RuntimeError) "internal error, last_event_forming_initial_reqest gets nil for request 325290 outgoing messages count 1 all events: --- []"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3131]
```
A RuntimeError occurred in info_request_batch#show:

internal error, last_event_forming_initial_request gets nil for request 325290 outgoing messages count 1 all events: --- []

app/models/info_request.rb:683:in `last_event_forming_initial_request'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/info_request_batch/49
* IP address: [FILTERED]
* Parameters: {"action"=>"show", "controller"=>"info_request_batch", "id"=>"49"}
* Rails root: /[FILTERED]/www.whatdotheyknow.com/alaveteli-2016-03-24T14-40-12
* Timestamp : 2016-03-30 12:46:46 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"[FILTERED]",
"locale"=>"en",
"ttl"=>2016-03-30 12:46:45 +0100,
"_csrf_token"=>"[FILTERED]",
"remember_me"=>false,
"user_id"=>96390,
"post_redirect_token"=>"[FILTERED]"}

-------------------------------
Environment:
-------------------------------

* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_ACCEPT_LANGUAGE : en-GB,en-US;q=0.8,en;q=0.6
* HTTP_COOKIE : ; last_request_id=325268; last_body_id=; _wdtk_cookie_session=[FILTERED]
* HTTP_DNT : 1
* HTTP_HOST : www.whatdotheyknow.com
* HTTP_IF_NONE_MATCH : "6388304aa3e1e0a4f248168c84f3278a"
* HTTP_REFERER : https://www.whatdotheyknow.com/user/gavin_chait/requests
* HTTP_UPGRADE_INSECURE_REQUESTS : 1
* HTTP_USER_AGENT : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
* HTTP_VERSION : HTTP/1.1
* HTTP_X_FORWARDED_FOR : [FILTERED]
* HTTP_X_FORWARDED_PROTO : https
* HTTP_X_REAL_IP : [FILTERED]
* HTTP_X_SENDFILE_TYPE : X-Sendfile
* HTTP_X_VARNISH : 264574730
* ORIGINAL_FULLPATH : /info_request_batch/49
* PASSENGER_CONNECT_PASSWORD : [FILTERED]
* PATH_INFO : /info_request_batch/49
* QUERY_STRING :
* REMOTE_ADDR : [FILTERED]
* REMOTE_PORT : 44949
* REQUEST_METHOD : GET
* REQUEST_URI : /info_request_batch/49
* SCRIPT_NAME :
* SCRIPT_URI : http://www.whatdotheyknow.com/info_request_batch/49
* SCRIPT_URL : /info_request_batch/49
* SERVER_NAME : www.whatdotheyknow.com
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.1
* SERVER_SOFTWARE : Apache/2.2.22 (Debian) mod_fastcgi/mod_fastcgi-SNAP-0910052141 Phusion_Passenger/5.0.26
* action_controller.instance : info_request_batch#show
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x00000004b40ec0>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x0000000e0ab2d0>
* action_dispatch.logger : #<ActiveSupport::TaggedLogging:0x000000048669e8>
* action_dispatch.parameter_filter : [:password, /RAW_POST_DATA/]
* action_dispatch.remote_ip : [FILTERED]
* action_dispatch.request.content_type :
* action_dispatch.request.flash_hash : #<ActionDispatch::Flash::FlashHash:0x0000000e0484c8>
* action_dispatch.request.formats : [text/html]
* action_dispatch.request.parameters : {"action"=>"show", "controller"=>"info_request_batch", "id"=>"49"}
* action_dispatch.request.path_parameters : {:action=>"show", :controller=>"info_request_batch", :id=>"49"}
* action_dispatch.request.query_parameters : {}
* action_dispatch.request.request_parameters : {}
* action_dispatch.request.unsigned_session_cookie: {"session_id"=>"[FILTERED]", "locale"=>"en", "ttl"=>2016-03-30 12:46:45 +0100, "_csrf_token"=>"[FILTERED]", "remember_me"=>false, "user_id"=>96390, "post_redirect_token"=>"cc1e8jwbhkkn406ejq5"}
* action_dispatch.request_id : 6c31da415f9f3098408c29aabbd9b07e
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x000000021c6658>
* action_dispatch.secret_token : [FILTERED]
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* newrelic.transaction_started : true
* rack.errors : #<IO:0x00000001a26240>
* rack.hijack : #<Proc:0x0000000e0b09d8@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
* rack.hijack? : true
* rack.input : #<PhusionPassenger::Utils::TeeInput:0x0000000e0b0bb8>
* rack.multiprocess : true
* rack.multithread : false
* rack.request.cookie_hash : {"last_request_id"=>"325268", "last_body_id"=>"", "_wdtk_cookie_session"=>"[FILTERED]"}
* rack.request.cookie_string : ; last_request_id=325268; last_body_id=; _wdtk_cookie_session=[FILTERED]
* rack.request.query_hash : {}
* rack.request.query_string :
* rack.run_once : false
* rack.session : {"session_id"=>"[FILTERED]", "locale"=>"en", "ttl"=>2016-03-30 12:46:45 +0100, "_csrf_token"=>"l1e/ClnsahTRf9BSjKBEm+yAzmRAh65A9xpAmS5vFuA=", "remember_me"=>false, "user_id"=>96390, "post_redirect_token"=>"cc1e8jwbhkkn406ejq5"}
* rack.session.options : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"[FILTERED]", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000004915538>, :id=>"77703f360d7b40967765a1248d815f4d"}
* rack.url_scheme : http
* rack.version : [1, 2]
* Process: 729
* Server : [FILTERED]

-------------------------------
Backtrace:
-------------------------------

app/models/info_request.rb:683:in `last_event_forming_initial_request'
app/views/info_request_batch/show.html.erb:16:in `block in _app_views_info_request_batch_show_html_erb__744749433206991292_117615660'
app/views/info_request_batch/show.html.erb:15:in `each'
app/views/info_request_batch/show.html.erb:15:in `_app_views_info_request_batch_show_html_erb__744749433206991292_117615660'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:125:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/template_renderer.rb:46:in `render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/template_renderer.rb:18:in `render'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:152:in `block in render_with_newrelic'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:151:in `render_with_newrelic'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/renderer.rb:41:in `render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_view/renderer/renderer.rb:22:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:110:in `_render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/streaming.rb:225:in `_render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:103:in `render_to_body'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:88:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rendering.rb:16:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/core_ext/benchmark.rb:5:in `ms'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:39:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:602:in `block in _run__4008244307132175863__process_action__1511357269753564984__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1437'
app/controllers/application_controller.rb:105:in `record_memory'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1437'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:601:in `_run__4008244307132175863__process_action__1511357269753564984__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:246:in `block in action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
lib/strip_empty_sessions.rb:13:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `_run__2541763004669113261__call__478299468859820231__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/static.rb:83:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-utf8_sanitizer-1.3.0/lib/rack/utf8_sanitizer.rb:15:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by garethrees** [comment]
[The request](https://www.whatdotheyknow.com/info_request_batch/49) url works now. Not sure if someone made a manual fix or whether the `send-batch-requests` script caught up?
