### ISSUE TITLE
[ERROR] request#get_attachment_as_html (Errno::EEXIST) "File exists…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3253]
```
An Errno::EEXIST occurred in request#get_attachment_as_html:

File exists - /APP_ROOT/www.whatdotheyknow.com/alaveteli-2016-05-16T07-44-32/cache/views/cy/request/306/306198/response/763090/attach/html
/usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/cy/request/306198/response/763090/attach/html/2/P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf.html
* HTTP Method: GET
* IP address : [FILTERED]
* Parameters : {"controller"=>"request", "action"=>"get_attachment_as_html", "id"=>"306198", "incoming_message_id"=>"763090", "part"=>"2", "file_name"=>"P 2013 1064.INSTALLATION OF A SINGLE WIND TURBINE 24.8M TO HUB AND 34.5M TO BLADE TIP.pdf.html", "locale"=>"cy"}
* Timestamp : 2016-05-16 10:53:47 +0100
* Server : [FILTERED]
* Rails root : /APP_ROOT/www.whatdotheyknow.com/alaveteli-2016-05-16T07-44-32
* Process: 20027

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"[FILTERED]",
"locale"=>"cy",
"remember_me"=>false,
"_csrf_token"=>"[FILTERED]",
"request_game"=>2016-02-22 10:49:32 +0000,
"user_id"=>60565,
"ttl"=>2016-05-16 10:01:21 +0100,
"post_redirect_token"=>"[FILTERED]"}

-------------------------------
Environment:
-------------------------------

* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_ACCEPT_LANGUAGE : en-US,en;q=0.8
* HTTP_COOKIE : ; last_request_id=334751; last_body_id=; _wdtk_cookie_session=[FILTERED]
* HTTP_DNT : 1
* HTTP_HOST : www.whatdotheyknow.com
* HTTP_UPGRADE_INSECURE_REQUESTS : 1
* HTTP_USER_AGENT : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
* HTTP_VERSION : HTTP/1.1
* HTTP_X_FORWARDED_FOR : [FILTERED]
* HTTP_X_FORWARDED_PROTO : https
* HTTP_X_REAL_IP : [FILTERED]
* HTTP_X_SENDFILE_TYPE : X-Sendfile
* HTTP_X_VARNISH : 289476295
* ORIGINAL_FULLPATH : /cy/request/306198/response/763090/attach/html/2/P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf.html
* PASSENGER_CONNECT_PASSWORD : [FILTERED]
* PATH_INFO : /cy/request/306198/response/763090/attach/html/2/P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf.html
* QUERY_STRING :
* REMOTE_ADDR : [FILTERED]
* REMOTE_PORT : 38970
* REQUEST_METHOD : GET
* REQUEST_URI : /cy/request/306198/response/763090/attach/html/2/P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf.html
* SCRIPT_NAME :
* SCRIPT_URI : http://www.whatdotheyknow.com/cy/request/306198/response/763090/attach/html/2/P 2013 1064.INSTALLATION OF A SINGLE WIND TURBINE 24.8M TO HUB AND 34.5M TO BLADE TIP.pdf.html
* SCRIPT_URL : /cy/request/306198/response/763090/attach/html/2/P 2013 1064.INSTALLATION OF A SINGLE WIND TURBINE 24.8M TO HUB AND 34.5M TO BLADE TIP.pdf.html
* SERVER_NAME : www.whatdotheyknow.com
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.1
* SERVER_SOFTWARE : Apache/2.2.22 (Debian) mod_fastcgi/mod_fastcgi-SNAP-0910052141 Phusion_Passenger/5.0.26
* action_controller.instance : #<RequestController:0x0000000b186fb8>
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x00000003e74188>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x0000000b180e38>
* action_dispatch.logger : #<ActiveSupport::TaggedLogging:0x00000002dbce58>
* action_dispatch.parameter_filter : [:password, /RAW_POST_DATA/]
* action_dispatch.remote_ip : [FILTERED]
* action_dispatch.request.content_type :
* action_dispatch.request.formats : [text/html]
* action_dispatch.request.parameters : {"controller"=>"request", "action"=>"get_attachment_as_html", "id"=>"306198", "incoming_message_id"=>"763090", "part"=>"2", "file_name"=>"P 2013 1064.INSTALLATION OF A SINGLE WIND TURBINE 24.8M TO HUB AND 34.5M TO BLADE TIP.pdf.html", "locale"=>"cy"}
* action_dispatch.request.path_parameters : {:controller=>"request", :action=>"get_attachment_as_html", :id=>"306198", :incoming_message_id=>"763090", :part=>"2", :file_name=>"P 2013 1064.INSTALLATION OF A SINGLE WIND TURBINE 24.8M TO HUB AND 34.5M TO BLADE TIP.pdf.html", :locale=>"cy"}
* action_dispatch.request.query_parameters : {}
* action_dispatch.request.request_parameters : {}
* action_dispatch.request.unsigned_session_cookie: {"session_id"=>"[FILTERED]", "locale"=>"en", "remember_me"=>false, "_csrf_token"=>"[FILTERED]", "request_game"=>2016-02-22 10:49:32 +0000, "user_id"=>60565, "ttl"=>2016-05-16 10:01:21 +0100, "post_redirect_token"=>"[FILTERED]"}
* action_dispatch.request_id : 6ee06d21d70897837f7c69373730ce6f
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x00000002947080>
* action_dispatch.secret_token : [FILTERED]
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* newrelic.transaction_started : true
* rack.errors : #<IO:0x00000001aeb220>
* rack.hijack : #<Proc:0x0000000b172770@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
* rack.hijack? : true
* rack.input : #<PhusionPassenger::Utils::TeeInput:0x0000000b172978>
* rack.multiprocess : true
* rack.multithread : false
* rack.request.cookie_hash : {"last_request_id"=>"334751", "last_body_id"=>"", "_wdtk_cookie_session"=>"[FILTERED]"}
* rack.request.cookie_string : ; last_request_id=334751; last_body_id=; _wdtk_cookie_session=[FILTERED]
* rack.request.query_hash : {}
* rack.request.query_string :
* rack.run_once : false
* rack.session : {"session_id"=>"[FILTERED]", "locale"=>"cy", "remember_me"=>false, "_csrf_token"=>"[FILTERED]", "request_game"=>2016-02-22 10:49:32 +0000, "user_id"=>60565, "ttl"=>2016-05-16 10:01:21 +0100, "post_redirect_token"=>"[FILTERED]"}
* rack.session.options : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"[FILTERED]", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x000000060fb6c0>, :id=>"[FILTERED]"}
* rack.url_scheme : http
* rack.version : [1, 2]

-------------------------------
Backtrace:
-------------------------------

/usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
/usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
/usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
/usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
/usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
/usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
/usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
app/controllers/request_controller.rb:612:in `get_attachment_as_html'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:614:in `block (2 levels) in _run__189810607882237211__process_action__2487138069390189173__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1352'
app/controllers/request_controller.rb:562:in `cache_attachments'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1352'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:613:in `block in _run__189810607882237211__process_action__2487138069390189173__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1351'
app/controllers/application_controller.rb:105:in `record_memory'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1351'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:601:in `_run__189810607882237211__process_action__2487138069390189173__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:246:in `block in action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
lib/strip_empty_sessions.rb:13:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `_run__485947210659674793__call__3586948820140778583__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/static.rb:83:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by garethrees** [comment]
This was caused by visiting a "view attachment as HTML" URL.

For some reason, the `html` directory was created as a file:

```
$ tree attach/
attach/
├── 2
│   └── P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf
└── html

$ ls -al /[FILTERED]/www.whatdotheyknow.com/alaveteli-2016-05-16T07-44-32/cache/views/cy/request/306/306198/response/763090/attach/html/
ls: cannot access /data/vhost/www.whatdotheyknow.com/alaveteli-2016-05-16T07-44-32/cache/views/cy/request/306/306198/response/763090/attach/html/: Not a directory
```

I deleted the `html` file and visited the URL again to regenerate the attachment, which worked successfully. Here's what the directory tree _should_ look like:

```
$ tree attach/
attach/
├── 2
│   └── P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf
└── html
    └── 2
        ├── foiextract20160516-19797-1fwap4d-1_1.jpg
        ├── foiextract20160516-19797-1fwap4d-2_1.jpg
        ├── foiextract20160516-19797-1fwap4d-3_1.jpg
        ├── foiextract20160516-19797-1fwap4d-3_2.jpg
        └── P%202013%201064.INSTALLATION%20OF%20A%20SINGLE%20WIND%20TURBINE%2024.8M%20TO%20HUB%20AND%2034.5M%20TO%20BLADE%20TIP.pdf.html

3 directories, 6 files
```
