### ISSUE TITLE
[ERROR] request#show (Encoding::ConverterNotFoundError) "code converter not found (UTF-7 to UTF-8)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3328]
Error on IPV. They're on 0.24.1.4, which includes https://github.com/mysociety/alaveteli/commit/abfb6eb34831dfac3dbb1086ebb08ab9380c1b30 – the only commit I found RE UTF-7. 

Related? https://github.com/mysociety/alaveteli/issues/2863

```
An Encoding::ConverterNotFoundError occurred in request#show:

code converter not found (UTF-7 to UTF-8)
lib/mail_handler/backends/mail_extensions.rb:51:in `encode'


-------------------------------
Request:
-------------------------------

* URL : http://www.infoprovsechny.cz/request/zlodejna_o2?nocache=incoming-8463
* IP address: FILTERED
* Parameters: {"nocache"=>"incoming-8463", "controller"=>"request", "action"=>"show", "url_title"=>"zlodejna_o2"}
* Rails root: /FILTERED/www.infoprovsechny.cz/releases/20160520113907
* Timestamp : 2016-06-17 09:50:31 +0200

-------------------------------
Backtrace:
-------------------------------

lib/mail_handler/backends/mail_extensions.rb:51:in `encode'
lib/mail_handler/backends/mail_extensions.rb:51:in `b_value_decode'
mail (2.5.4) lib/mail/encodings.rb:245:in `b_value_decode'
mail (2.5.4) lib/mail/encodings.rb:135:in `block (3 levels) in value_decode'
mail (2.5.4) lib/mail/encodings.rb:128:in `map'
mail (2.5.4) lib/mail/encodings.rb:128:in `block (2 levels) in value_decode'
mail (2.5.4) lib/mail/encodings.rb:123:in `map'
mail (2.5.4) lib/mail/encodings.rb:123:in `block in value_decode'
mail (2.5.4) lib/mail/encodings.rb:122:in `map'
mail (2.5.4) lib/mail/encodings.rb:122:in `value_decode'
mail (2.5.4) lib/mail/encodings.rb:101:in `decode_encode'
mail (2.5.4) lib/mail/fields/unstructured_field.rb:73:in `do_decode'
mail (2.5.4) lib/mail/fields/unstructured_field.rb:55:in `decoded'
mail (2.5.4) lib/mail/fields/unstructured_field.rb:59:in `default'
mail (2.5.4) lib/mail/field.rb:167:in `method_missing'
mail (2.5.4) lib/mail/message.rb:1186:in `default'
mail (2.5.4) lib/mail/message.rb:1121:in `subject'
app/models/incoming_message.rb:130:in `block in parse_raw_email!'
activerecord (3.2.22.2) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
activerecord (3.2.22.2) lib/active_record/transactions.rb:208:in `transaction'
app/models/incoming_message.rb:127:in `parse_raw_email!'
app/models/incoming_message.rb:172:in `mail_from'
app/models/incoming_message.rb:177:in `safe_mail_from'
app/models/incoming_message.rb:183:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:8:in `_app_views_request__incoming_correspondence_html_erb__2479586976606580673_53896520'
actionpack (3.2.22.2) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22.2) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22.2) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22.2) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.22.2) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.22.2) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:46:in `render_partial'
actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:20:in `render'
actionpack (3.2.22.2) lib/action_view/helpers/rendering_helper.rb:24:in `render'
app/views/request/_correspondence.html.erb:4:in `_app_views_request__correspondence_html_erb__4106921476725012527_51838640'
actionpack (3.2.22.2) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22.2) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22.2) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22.2) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.22.2) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.22.2) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:46:in `render_partial'
actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:20:in `render'
actionpack (3.2.22.2) lib/action_view/helpers/rendering_helper.rb:24:in `render'
app/views/request/show.html.erb:169:in `block in _app_views_request_show_html_erb___275116125166584751_8796000'
activerecord (3.2.22.2) lib/active_record/associations/collection_proxy.rb:91:in `each'
activerecord (3.2.22.2) lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
app/views/request/show.html.erb:167:in `_app_views_request_show_html_erb___275116125166584751_8796000'
actionpack (3.2.22.2) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22.2) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22.2) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22.2) lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.22.2) lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
actionpack (3.2.22.2) lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
actionpack (3.2.22.2) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
actionpack (3.2.22.2) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:41:in `render_template'
actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:22:in `render'
actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.22.2) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.22.2) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.22.2) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.22.2) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
activesupport (3.2.22.2) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.22.2) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:39:in `render'
app/controllers/request_controller.rb:131:in `block (3 levels) in show'
actionpack (3.2.22.2) lib/action_controller/metal/mime_responds.rb:196:in `call'
actionpack (3.2.22.2) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
app/controllers/request_controller.rb:130:in `block in show'
i18n (0.7.0) lib/i18n.rb:257:in `with_locale'
app/controllers/request_controller.rb:79:in `show'
actionpack (3.2.22.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.22.2) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:602:in `block in _run__1724251462244170111__process_action__63066031993410999__callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1315'
app/controllers/application_controller.rb:110:in `record_memory'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1315'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:601:in `_run__1724251462244170111__process_action__63066031993410999__callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.22.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.22.2) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.22.2) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.22.2) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.22.2) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:608:in `call'
exception_notification (3.0.1) lib/exception_notifier.rb:41:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/cookies.rb:341:in `call'
lib/strip_empty_sessions.rb:13:in `call'
activerecord (3.2.22.2) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.22.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `_run__1907836604457939814__call__2538406635481559692__callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.22.2) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.22.2) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.22.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/static.rb:83:in `call'
rack-utf8_sanitizer (1.3.0) lib/rack/utf8_sanitizer.rb:15:in `call'
railties (3.2.22.2) lib/rails/engine.rb:484:in `call'
railties (3.2.22.2) lib/rails/application.rb:231:in `call'
railties (3.2.22.2) lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by garethrees** [comment]
The mail causing this _looks_ legit.

**Comment by garethrees** [comment]
Its the `Subject:` header

```
From bob@localhost Fri Jun 17 08:39:09 2016
Received: from bob@localhost ([213.175.37.187]:52820)
	by vmd11.farma.gigaserver.cz with esmtp (Exim 4.80)
	(envelope-from <bob@localhost>)
	id 1bDnQr-0006YM-89
	for foi+request-1234-jnc73ba@localhost; Fri, 17 Jun 2016 08:39:09 +0200
Received: from ESCAS02.NKU.CZ (10.10.101.133) by ESEDGE01.nku.cz
 (10.21.32.247) with Microsoft SMTP Server (TLS) id 14.3.235.1; Fri, 17 Jun
 2016 08:39:08 +0200
Received: from (10.10.101.158) by bob@localhost (10.10.101.153) with
 Microsoft SMTP Server id 14.3.235.1; Fri, 17 Jun 2016 08:39:08 +0200
X-Mailer: PILSCOM smtp mailer
From: =?utf-7?b?RXBvZGF0ZWxuYQ==?= <bob@localhost>
To: =?utf-7?b?S2xvdWRh?= <foi+request-1234-jnc73ba@localhost>
MIME-Version: 1.0
Subject: =?utf-7?b?VmErQVdFLWUgZW1haWxvditBT0UtIHpwcitBT0UtdmEgYnlsYSBwK0FWay1ldnphdGE=?=
Date: Fri, 17 Jun 2016 08:39:00 +0200
Content-Type: multipart/signed; boundary="--Next_000";
	protocol="application/x-pkcs7-signature"; micalg=SHA1
Message-ID: <7d042199-6765-4c9c-a77e-bb0ba02b92b2@ESCAS02.NKU.CZ>
```

**Comment by garethrees** [comment]
```ruby
[186](main)> mail = MailHandler.mail_from_raw_email(File.read('./spec/fixtures/files/utf-7-attachment.email'))
=> #<Mail::Message:71041780, Multipart: true, Headers: <Received: from bob@localhost ([213.175.37.187]:52820) by vmd11.farma.gigaserver.cz with esmtp (Exim 4.80) (envelope-from <bob@localhost>) id 1bDnQr-0006YM-89 for foi+request-1234-jnc73ba@localhost; Fri, 17 Jun 2016 08:39:09 +0200>, <Received: from ESCAS02.NKU.CZ (10.10.101.133) by ESEDGE01.nku.cz (10.21.32.247) with Microsoft SMTP Server (TLS) id 14.3.235.1; Fri, 17 Jun 2016 08:39:08 +0200>, <Received: from (10.10.101.158) by bob@localhost (10.10.101.153) with Microsoft SMTP Server id 14.3.235.1; Fri, 17 Jun 2016 08:39:08 +0200>, <Date: Fri, 17 Jun 2016 08:39:00 +0200>, <From: =?utf-7?b?RXBvZGF0ZWxuYQ==?= <bob@localhost>>, <To: =?utf-7?b?S2xvdWRh?= <foi+request-1234-jnc73ba@localhost>>, <Message-ID: <7d042199-6765-4c9c-a77e-bb0ba02b92b2@ESCAS02.NKU.CZ>>, <Subject: =?utf-7?b?VmErQVdFLWUgZW1haWxvditBT0UtIHpwcitBT0UtdmEgYnlsYSBwK0FWay1ldnphdGE=?=>, <Mime-Version: 1.0>, <Content-Type: multipart/signed; boundary="--Next_000"; protocol="application/x-pkcs7-signature"; micalg=SHA1>, <X-Mailer: PILSCOM smtp mailer>>
[187](main)> mail.subject
Encoding::ConverterNotFoundError: code converter not found (UTF-7 to UTF-8)
from /home/vagrant/alaveteli/lib/mail_handler/backends/mail_extensions.rb:51:in `encode'
```

**Comment by garethrees** [comment]
[Fixed](http://www.infoprovsechny.cz/request/zlodejna_o2) by https://github.com/mysociety/alaveteli/pull/3329 – Deployed to IPV at 15:23.
