### ISSUE TITLE
Importing CSV breaks if DEFAULT_LOCALE is not first in AVAILABLE_LOCALES

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3472]
This breaks…

``` yaml
AVAILABLE_LOCALES: 'fr nl en'
DEFAULT_LOCALE: 'en'
```

So does this…

``` yaml
AVAILABLE_LOCALES: 'en nl fr'
DEFAULT_LOCALE: 'fr'
```

…and this…

``` yaml
AVAILABLE_LOCALES: 'fr nl en'
DEFAULT_LOCALE: 'nl'
```

```
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "first_letter" violates not-null constraint
: INSERT INTO "public_bodies" ("api_key", "created_at", "disclosure_log", "first_letter", "home_page", "info_requests_count", "info_requests_not_held_count", "info_requests_overdue_count", "info_requests_successful_count", "info_requests_visible_classified_count", "info_requests_visible_count", "last_edit_comment", "last_edit_editor", "name", "notes", "publication_scheme", "request_email", "short_name", "updated_at", "url_name", "version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "id"
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record.rb:59:in `block in log_with_newrelic_instrumentation'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record.rb:56:in `log_with_newrelic_instrumentation'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/relation.rb:66:in `insert'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/persistence.rb:367:in `create'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/timestamp.rb:58:in `create'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/callbacks.rb:268:in `block in create'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:403:in `_run__2982407138966574159__create__1376753837943364156__callbacks'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/callbacks.rb:268:in `create'
/home/vagrant/bundle/ruby/1.9.1/bundler/gems/globalize-5fd95f2389df/lib/globalize/active_record/instance_methods.rb:167:in `block in create'
/home/vagrant/bundle/ruby/1.9.1/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/vagrant/bundle/ruby/1.9.1/bundler/gems/globalize-5fd95f2389df/lib/globalize/active_record/instance_methods.rb:166:in `create'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/persistence.rb:348:in `create_or_update'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/callbacks.rb:264:in `block in create_or_update'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:458:in `_run__2982407138966574159__save__1376753837943364156__callbacks'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
/home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/callbacks.rb:264:in `create_or_update'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/persistence.rb:104:in `save!'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/validations.rb:56:in `save!'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/transactions.rb:264:in `block in save!'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/transactions.rb:208:in `transaction'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/transactions.rb:264:in `save!'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb:34:in `block in save!'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent.rb:571:in `with_database_metric_name'
/home/vagrant/bundle/ruby/1.9.1/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `save!'
/home/vagrant/alaveteli/app/models/public_body.rb:457:in `block (2 levels) in import_values_from_csv_row'
/home/vagrant/bundle/ruby/1.9.1/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/vagrant/alaveteli/app/models/public_body.rb:448:in `block in import_values_from_csv_row'
/home/vagrant/alaveteli/app/models/public_body.rb:447:in `each'
/home/vagrant/alaveteli/app/models/public_body.rb:447:in `import_values_from_csv_row'
/home/vagrant/alaveteli/app/models/public_body.rb:408:in `block (2 levels) in import_csv_from_file'
/home/vagrant/alaveteli/app/models/public_body.rb:377:in `block in import_csv_from_file'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22.3/lib/active_record/transactions.rb:208:in `transaction'
/home/vagrant/alaveteli/app/models/public_body.rb:346:in `import_csv_from_file'
/home/vagrant/alaveteli/lib/tasks/import.rake:58:in `block (2 levels) in <top (required)>'
/home/vagrant/bundle/ruby/1.9.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
```

These work…

``` yaml
AVAILABLE_LOCALES: 'en nl fr'
DEFAULT_LOCALE: 'en'
```

``` yaml
AVAILABLE_LOCALES: 'fr nl en'
DEFAULT_LOCALE: 'fr'
```

I haven't checked whether the ordering of `AVAILABLE_LOCALES` affects which columns are picked from the CSV if they are not in the same order.

Here's the header line of the CSV I was using:

```
#id,name,request_email,name.nl,name.fr,request_email.nl,request_email.fr,short_name.nl,short_name.fr,home_page,tag_string
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
