### ISSUE TITLE
CI failures on Ruby 2.3.0

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3489]
Recently lots of specs have been failing on Ruby 2.3.0 on Travis.

I've pinned this down to the combination of rubygems 2.1.11 being used with bundler 1.13.1.

```
Failures:

  1) When filtering when not in test mode should not fail handling a bounce mail
     Failure/Error: expect(xc.err).to eq("")

       expected: ""
            got: "LoadError: cannot load such file -- html/sanitizer\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:251:in `require'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:251:in `block in require'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:236:in `load_dependency'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:251:in `require'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/helpers/sanitize_helper.rb:204:in `sanitized_allowed_tags='\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:42:in `block (3 levels) in <class:Railtie>'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:41:in `each'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:41:in `block (2 levels) in <class:Railtie>'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:25:in `each'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:25:in `on_load'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:40:in `block in <class:Railtie>'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:30:in `instance_exec'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:30:in `run'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:55:in `block in run_initializers'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:54:in `each'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:54:in `run_initializers'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/application.rb:136:in `initialize!'\n  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/railtie/configurable.rb:30:in `method_missing'\n  /home/vagrant/alaveteli/config/environment.rb:6:in `<top (required)>'\n  /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'\n  /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:178:in `load_rails'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:182:in `record_bounce'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:48:in `block (2 levels) in main'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:47:in `each'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:47:in `block in main'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:32:in `chdir'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:32:in `main'\n  /home/vagrant/alaveteli/script/handle-mail-replies.rb:187:in `<top (required)>'\n"

       (compared using ==)

       Diff:
       @@ -1 +1,34 @@
       +LoadError: cannot load such file -- html/sanitizer
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:251:in `require'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:251:in `block in require'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:236:in `load_dependency'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/dependencies.rb:251:in `require'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/helpers/sanitize_helper.rb:204:in `sanitized_allowed_tags='
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:41:in `each'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:41:in `block (2 levels) in <class:Railtie>'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:25:in `each'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_view/railtie.rb:40:in `block in <class:Railtie>'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:30:in `instance_exec'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:30:in `run'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:55:in `block in run_initializers'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:54:in `each'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/initializable.rb:54:in `run_initializers'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/application.rb:136:in `initialize!'
       +  /home/vagrant/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
       +  /home/vagrant/alaveteli/config/environment.rb:6:in `<top (required)>'
       +  /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       +  /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:178:in `load_rails'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:182:in `record_bounce'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:48:in `block (2 levels) in main'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:47:in `each'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:47:in `block in main'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:32:in `chdir'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:32:in `main'
       +  /home/vagrant/alaveteli/script/handle-mail-replies.rb:187:in `<top (required)>'

     # ./spec/script/handle-mail-replies_spec.rb:23:in `block (3 levels) in <top (required)>'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'

Finished in 3.22 seconds (files took 3.92 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/script/handle-mail-replies_spec.rb:19 # When filtering when not in test mode should not fail handling a bounce mail

Randomized with seed 34887

```

**Comment by garethrees** [comment]
For reference and me later wondering how on earth I isolated this…

First I build two VMs:

- One by setting up a precise development environment as per the usual vagrant install, then installing rvm and Ruby 2.3.0-p0.
- The other I created a fresh precise VM and then manually ran the steps in `.travis.yml`. I remember having to explicitly enable the multiverse repo and add a `pg_hba.conf` rule because of failed ident auth.

I tried a bunch of things but given I could reproduce the problem outside of Travis, figured it must be something under our control in some way.

I ran `bundle env` on each VM and compared the two using `vim -d`:

![screen shot 2016-09-14 at 16 37 41](https://cloud.githubusercontent.com/assets/282788/18518874/9c82540e-7a99-11e6-834f-4404ac124abc.png)

The left split is the "travis" VM. Here I can see rubygems is pinned at 2.1.11 as per the `.travis.yml` config. The right pane is showing `2.5.1`, which is the version Travis CI is installing at the time of writing. I have no idea when either of these changed in the Travis env.

I'm also really not sure what version of rubygems we "should" be using. I have my dev machine on `1.8.11` – close to production's `1.8.23`.
