### ISSUE TITLE
Batch mark confirmed not spam users

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3571]
- whitelisted email domains
- 3 requests visible for 3 months
- is admin user

**Comment by garethrees** [comment]
Distinct domains:

```sql
SELECT DISTINCT(split_part(lower(email), '@', 2)) AS domain
FROM users
ORDER BY domain ASC;
```

**Comment by garethrees** [comment]
Count of users using an email domain:

```sql
SELECT domain, COUNT(domain) AS user_count
FROM (
  SELECT split_part(lower(email), '@', 2) AS domain
  FROM users
) AS domains
GROUP BY domain
ORDER BY user_count DESC;
```

**Comment by garethrees** [comment]
Here's what I ran:

```ruby
# Admins
User.where(:admin_level => 'super').find_each do |user|
  puts "User #{user.email} is a super user"
  user.update_column(:confirmed_not_spam, true)
end;nil

# Whitelisted Domains
# A bit of an arbitrary selection but covers most of the well known ones
# that are likely to be okay. Should have made these postgres-compatible
# regexps so that e.g. whatdotheyknow.com@DOMAIN didn't get matched
# (see cleanup below)
whitelisted_email_domains = %w(ac.uk gov.uk access-info.org barclays.com
barnardos.org.uk bbc.co.uk blackpoolgazette.co.uk bloomberg.net
cambrian-news.co.uk cisco.com consumerfocus.org.uk courier.co.uk
dailymail.co.uk dailypost.co.uk edinburghnews.com essexchronicle.co.uk
eveninggazette.co.uk express.co.uk expressandstar.co.uk ft.com
fullfact.org gmb.org.uk gov.je guardian.co.uk halifaxcourier.co.uk
ieee.org independent.co.uk itn.co.uk itv.com leicestermercury.co.uk
mailonsunday.co.uk mediawales.co.uk mirror.co.uk mod.uk mysociety.org
networkrail.co.uk newburynews.co.uk nhs.uk nottinghameveningpost.co.uk
openrightsgroup.org parliament.uk police.uk rnib.org.uk rtaylor.co.uk
sainsburys.co.uk salvationarmy.org.uk scottish.parliament.uk
shropshirestar.co.uk southwalesargus.co.uk standard.co.uk sunday-times.co.uk
telegraph.co.uk telegraphandargus.co.uk the-sun.co.uk the-times.co.uk
theargus.co.uk thecourier.co.uk theguardian.com theherald.co.uk
theregister.co.uk thetimes.co.uk trinitymirror.com trinitysouth.co.uk
tuc.org.uk unison.co.uk vice.com walesonline.co.uk
westernmorningnews.co.uk whatdotheyknow.com which.net wsj.com)

whitelisted_email_domains.each do |domain|
  User.where(["email ~ '@?'", domain]).find_each do |user|
    puts "User #{user.email} is in a whitelisted domain"
    user.update_column(:confirmed_not_spam, true)
  end
end;nil

# whatdotheyknow.com@DOMAIN got matched so clean up those users
User.where(["email ~ 'whatdotheyknow.com@'"]).find_each do |user|
  puts "User #{user.email} incorrectly identified as a whitelisted domain"
  user.update_column(:confirmed_not_spam, false)
end

# 3 requests visible for 3 months
User.where("info_requests_count > 2 AND confirmed_not_spam = 'f' AND ban_text = ''").find_each do |user|
  requests = user.info_requests.visible.where(['created_at > ?', 3.months.ago])
  if requests.count >= 3
    puts "User #{user.id} has #{user.info_requests.count} requests and #{requests.count} are > 3 months old and visible"
    user.update_column(:confirmed_not_spam, true)
  end
end;nil
```

That's confirmed 5450 users:

```ruby
User.where(:confirmed_not_spam => true).count
# => 5450
```

**Comment by schlos** [comment]
I'm getting error (probably db schema changed in the meantime) - I'm on Alaveteli 0.33.0.0:

```
irb(main):001:0> User.where(:admin_level => 'super').find_each do |user|
irb(main):002:1*   puts "User #{user.email} is a super user"
irb(main):003:1>   user.update_column(:confirmed_not_spam, true)
irb(main):004:1> end;nil
Traceback (most recent call last):
       16: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/batches.rb:117:in `find_in_batches'
       15: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:243:in `to_a'
       14: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:515:in `load'
       13: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:639:in `exec_queries'
       12: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/querying.rb:39:in `find_by_sql'
       11: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
       10: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
        9: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
        8: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
        7: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
        6: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
        5: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
        4: from /home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        3: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
        2: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
        1: from /home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column users.admin_level does not exist)
LINE 1: SELECT  "users".* FROM "users" WHERE "users"."admin_level" =...
                                             ^
: SELECT  "users".* FROM "users" WHERE "users"."admin_level" = 'super'  ORDER BY "users"."id" ASC LIMIT 1000
```

**Comment by garethrees** [comment]
Yeah, the `admin_level` attribute has been [replaced with a roles system](https://github.com/mysociety/alaveteli/blob/master/doc/CHANGES.md#upgrade-notes-9).

You can replace `User.where(:admin_level => 'super')` with `User.with_role(:admin)`, which should do the same thing.

Note that you'll have had to have [followed the 0.29.0.0 upgrade notes](https://github.com/mysociety/alaveteli/blob/master/doc/CHANGES.md#upgrade-notes-10) to migrate each admin to the roles system.

**Comment by schlos** [comment]
Thanks!

This works as expected:
```
User.with_role(:admin).find_each do |user|
  puts "User #{user.email} is a super user"
  user.update_column(:confirmed_not_spam, true)
end;nil
```
