### ISSUE TITLE
ActionController::RoutingError (No route matches [OPTIONS] "/country_message"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3828]
Just spotted this fly by in `production.log`

```
I, [2017-03-15T11:41:43.439476 #24988]  INFO -- :   Rendered lib/themes/whatdotheyknow-theme/lib/views/general/_before_body_end.html.erb (0.8ms)
I, [2017-03-15T11:41:43.439961 #24988]  INFO -- : PID: 24988    CONSUME MEMORY: 0 KB    Now: 328572 KB  https://www.whatdotheyknow.com/body/nhs_barking_and_dagenham_clinical_commiss
ioning_group/awaiting
I, [2017-03-15T11:41:43.440160 #24988]  INFO -- : Completed 200 OK in 517ms (Views: 216.4ms | ActiveRecord: 264.4ms)
I, [2017-03-15T11:41:43.441015 #28221]  INFO -- :   Rendered lib/themes/whatdotheyknow-theme/lib/views/request/_next_actions.html.erb (0.8ms)
I, [2017-03-15T11:41:43.442118 #28221]  INFO -- : Read fragment views/request/similar/293497/cy/50ead153653871c329f500b6332c7f2b (0.7ms)
I, [2017-03-15T11:41:43.499820 #24988]  INFO -- : Started OPTIONS "/country_message" for 94.10.200.104 at 2017-03-15 11:41:43 +0000
I, [2017-03-15T11:41:43.502488 #28814]  INFO -- : Write fragment views/outgoing_messages/511438/delivery_status/6aeb8018fe43c61ee70ac8872f8e37fc (0.7ms)
F, [2017-03-15T11:41:43.503748 #24988] FATAL -- :
ActionController::RoutingError (No route matches [OPTIONS] "/country_message"):
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.13/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.13/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/secure_headers-3.1.2/lib/secure_headers/middleware.rb:12:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'



```

**Comment by garethrees** [comment]
Doesn't seem to be causing a problem, but we should prevent this so that we don't have to serve lots of pointless requests.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
