### ISSUE TITLE
[ERROR] statistics#index (ArgumentError) "comparison of Array with Array failed"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3834]
```
An ArgumentError occurred in statistics#index:

comparison of Array with Array failed
app/models/statistics.rb:136:in `sort'

-------------------------------
Backtrace:
-------------------------------

app/models/statistics.rb:136:in `sort'
app/models/statistics.rb:136:in `by_week_to_today_with_noughts'
app/controllers/statistics_controller.rb:9:in `index'
app/controllers/application_controller.rb:108:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Fixed by #3881
