### ISSUE TITLE
The load-sample-data script breaks in Rails 4.1

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#3977]
The `/dev/stdin <<END` syntax we were no longer works and produces this instead 

```
$ bundle exec ./script/load-sample-data
/home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands/runner.rb:60:in `load': No such file or directory - /tmp/sh-thd-849333849 (deleted) (Errno::ENOENT)
	from /home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:128:in `require'
	from /home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:128:in `require_command!'
	from /home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:95:in `runner'
	from /home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/vagrant/bundle/ruby/1.9.1/gems/railties-4.1.16/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
Loaded fixtures. You may now wish to run ./script/update-xapian-index
```

(AFAICT it looks to see whether `/dev/stdin` is a file, decides that it is, tries to open it and falls over)

Someone else has fallen over the same thing and suggested a fix https://github.com/rails/rails/pull/26343 but it doesn't seem to have made it into the Rails codebase.

**Comment by lizconlan** [comment]
blocker for #3638

**Comment by lizconlan** [comment]
For a  bonus point `disable_referential_integrity` fails (also occurs under Rails 4.0 on master) and the script fails anyway
