### ISSUE TITLE
[ERROR] info_requests#index (ArgumentError) "'nil' is not an ActiveModel-compatible object. It …

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4014]
```
An ArgumentError occurred in info_requests#index:

  'nil' is not an ActiveModel-compatible object. It must implement :to_partial_path.
  app/views/alaveteli_pro/info_requests/_request_list.html.erb:53:in `_app_views_alaveteli_pro_info_requests__request_list_html_erb__2858665686847453975_185893640'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/alaveteli_pro/info_requests?alaveteli_pro_request_filter%5Bfilter%5D=other
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"alaveteli_pro_request_filter"=>{"filter"=>"other"}, "action"=>"index", "controller"=>"alaveteli_pro/info_requests"}
  * Timestamp  : 2017-05-24 03:47:37 +0100
  * Server : FILTERED
  * Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-05-19T10-45-40
  * Process: 20448

-------------------------------
Backtrace:
-------------------------------

  app/views/alaveteli_pro/info_requests/_request_list.html.erb:53:in `_app_views_alaveteli_pro_info_requests__request_list_html_erb__2858665686847453975_185893640'
  app/views/alaveteli_pro/info_requests/index.html.erb:20:in `_app_views_alaveteli_pro_info_requests_index_html_erb___665009065710844227_186425340'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Had 4 of these on 24th May. Couldn't find any issue reported so raising in case it hasn't been dealt with.

**Comment by stevenday** [comment]
@kingqueen3065 raised this on the pro repo as https://github.com/mysociety/alaveteli-professional/issues/290 - I fixed the immediate issue by removing the errant RequestSummary that was no longer attached to a request, but we still have an open issue to figure out why the destroy callback didn't work. It's low priority at the moment mainly because only Doug can cause it :)
