### ISSUE TITLE
[ERROR] load-mail-server-logs No such file or directory - /var/log/exim4/exim-mainlog-20170531 (Errno::ENOENT)

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4017]
Exim logs not being found by overnight run of `load-mail-server-logs` script

```
/data/vhost/eu.alaveteli.org/alaveteli-2017-05-25T11-37-06/vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.3/lib/rails/commands/runner.rb:54:in `eval': No such file or directory - /var/log/exim4/exim-mainlog-20170531 (Errno::ENOENT)
        from /data/vhost/eu.alaveteli.org/alaveteli-2017-05-25T11-37-06/app/models/mail_server_log.rb:33:in `load_file'
        from (eval):1:in `<top (required)>'
        from /data/vhost/eu.alaveteli.org/alaveteli-2017-05-25T11-37-06/vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.3/lib/rails/commands/runner.rb:54:in `eval'
        from /data/vhost/eu.alaveteli.org/alaveteli-2017-05-25T11-37-06/vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.3/lib/rails/commands/runner.rb:54:in `<top (required)>'
        from /data/vhost/eu.alaveteli.org/alaveteli-2017-05-25T11-37-06/vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.3/lib/rails/commands.rb:64:in `require'
        from /data/vhost/eu.alaveteli.org/alaveteli-2017-05-25T11-37-06/vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.3/lib/rails/commands.rb:64:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by garethrees** [comment]
This is failing for belgium, nicaragua, eu and colombia – all on the same host

**Comment by garethrees** [comment]
pasting irc convo for context about what we think is happening here

```irc
[14:20:25]  <gareth>	liz so what investigation has been done so far in to the vhosts on mastodon that are failing to read the exim log?
[14:26:18]  <liz>	gareth: not much - just a quick scramble to see if the check mark was appearing on recent requests (used AskTheEU as it has enough traffic to be able to tell), checked the files exists, checked the site user can see them, have not passed it on to Sam yet
[14:27:50]  <sam>	blinks, yawns and looks around
[14:31:25]  <gareth>	liz is there a ticket for this yet?
[14:35:28]  <gareth>	its also failing for Nicaragua, which don't have the delivery status feature because they're on 0.22, so I don't think looking at that is a particularly great indicator of everything working OK.
[14:36:38]  <gareth>	sam TL;DR is that some (all?) sites on mastodon are failing to parse a mail server log file https://groups.google.com/a/mysociety.org/forum/#!topic/cron-alaveteli/lTExslLWdXs
[14:36:52]  <liz>	having a little twitter shout at Travis
[14:38:11]  <liz>	there is not a ticket yet, there will be in a minute but my machine is playing up so the browser’s stuck in slow motion mode
[14:38:59]  <gareth>	sam started on 12th May as far as I can tell, but coming at this from 3 weeks off so not sure what might have started causing it. Any sysadmin stuff happen on mastodon on the 12th?
[14:40:28]  <sam>	I’ll have to look back
[14:41:20]  <liz>	https://github.com/mysociety/alaveteli/issues/4017 
[14:42:32]  <sam>	Ah, it might be that the logrotate time changed
[14:44:59]  <gareth>	sounds plausible
[14:45:36]  <liz>	we once had a similar looking problem on Ocelot (July 2015), not sure how it was resolved
[14:46:04]  <gareth>	liz " checked the files exists" – doesn't look like it exists to me
[14:46:05]  <gareth>	$ sudo stat /var/log/exim4/exim-mainlog-20170531
[14:46:05]  <gareth>	stat: cannot stat `/var/log/exim4/exim-mainlog-20170531': No such file or directory
[14:46:31]  <sam>	Well, that file only exists for a day
[14:46:33]  <gareth>	yeah
[14:46:35]  <sam>	until it gets gzipped
[14:47:23]  <sam>	ooh, hang on
[14:47:27]  <sam>	that’s odd
[14:49:13]  <gareth>	I get that, but the error message is correct in saying that the app is trying to load a file that doesn't exist
[14:49:42]  <sam>	yes, sorry - I’m kind of thinking out loud (unwisely)
[14:49:58]  <gareth>	yeah likewise tbh
[14:52:31]  <gareth>	logrotate change sounds like a plausible explanation – I think the app stores the filename and checks the last few files every run in case its changed since the last parse
[14:53:06]  <liz>	if that’s the case it would explain why it wasn’t looking at the gzipped files
[14:53:54]  <sam>	The dates tie in to when I did the final upgrade to Puppet 4. One consequence of this was a slight change to some of the cron timings. The Exim logs on mastodon look a bit odd, though, and the times don’t seem to correspond.
[14:54:03]  <sam>	I’ll have to do a bit more digging.
[14:54:07]  <gareth>	well, it would have looked at the unzipped file at some point, because AIUI you get exim-mainlog as the current file, exim-mainlog-1234 as the last rotated file, and then after that you get zipped versions
[14:54:25]  <sam>	Yes, that’s correct.
[14:55:24]  <gareth>	and I'm 99% sure that alaveteli parses the unzipped log as well as the gzipped ones, otherwise we'd be waiting 48 hours for the mail log ingestion
```

**Comment by garethrees** [comment]
```irc
[10:10:19]  <gareth>	morning :) having a bit of a look in to this log importing error
[10:10:29]  <sam>	Morning
[10:10:50]  <gareth>	how do I find out what time logrotate is happening?
[10:11:23]  <sam>	Well, the timestamps on the files will show that, plus the timestamps of the log entries inside them
[10:11:45]  <sam>	Although I’m a bit confused, and need to check, as the logrotate job should be being called via cron.daily
[10:12:05]  <sam>	and that’s specified in `/etc/crontab`, and the times weren’t matching up
[10:12:08]  <gareth>	Yeah in /etc/cron.d/vhost-eu-alaveteli-org-logrotate for example its 5 0 * * *
[10:12:34]  <sam>	The exim logs should be being rotated by the core logrotate task
[10:12:37]  <gareth>	ah, sorry yes
[10:12:38]  <sam>	I think…
[10:12:46]  <gareth>	Yeah that just clicked in my head as I said it
[10:14:27]  <sam>	Ah, logrotate job is commented.
[10:15:33]  <gareth>	yeah says it should be in etc/cron.d/logrotate, but that doesn't exist (but same on e.g. stork and that's not erroring)
[10:16:57]  <sam>	Ah, sorry - I’m forgetting - it’s in root’s crontab
[10:17:08]  <sam>	So actually, that won’t have changed
[10:17:22]  <sam>	and it ties in to the timings, so makes sense.
[10:17:40]  <sam>	But, it doesn’t help…
[10:19:38]  <sam>	Is this always failing?
[10:20:29]  <sam>	The timestamp on the email is pretty much exactly the same time as the logrotate ocurrs
[10:21:46]  <sam>	Ah, hang on…
[10:23:14]  <gareth>	its been failing every night on mastodon alavetelis since 12th may
[10:23:51]  <sam>	The nicaragua job is set for 00:45, the logrotate for 00:46
[10:23:55]  <gareth>	ha
[10:24:13]  <sam>	So I’m just checking the code that deploys the logrotate to root’s crontab
[10:26:49]  <sam>	Yes, that’s it: `minute => fqdn_rand(60);`
[10:27:09]  <sam>	The `fqdn_rand` function changed in Puppet 4.4
[10:27:19]  <sam>	Thing is, it’s actually just luck.
[10:28:04]  <gareth>	ooh
[10:28:29]  <gareth>	so it could be any minute of 00:nn?
[10:28:46]  <sam>	It could have used an minute up to 59, even before. I’m guessing that the import script looks for yesterday’s logfile? It really needs to run after 01:00 to be certain that the logrotate will have run.
[10:28:47]  <sam>	Yes
[10:29:31]  <sam>	So the change alerts us to an existing false assumption :slightly_smiling_face:
[10:30:02]  <gareth>	ah interesting. Yes, it does this https://github.com/mysociety/alaveteli/blob/develop/script/load-mail-server-logs#L21-L27
[10:30:11]  <gareth>	thats so strange that we haven't seen this before
[10:30:12]  <sam>	(Essentially, fqdn_rand(60) uses the fqdn as a seed for a random number and does modulus 60 to get a minute)
[10:30:34]  <sam>	As I say - luck. It probably comes out less that 45 everywhere.
[10:30:46]  <sam>	I’ll check my assumptions though
[10:32:46]  <sam>	So, logrotate runs >45 on: buffalo, pluto, milo and mastodon.
[10:33:39]  <sam>	I think mastodon is the only one with any alavetelis?
[10:34:20]  <sam>	(Soz, I guess you’re on your standup.)
[10:47:00]  <gareth>	yeah, sorry, back now
[10:47:19]  <gareth>	off the top of my head, yeah, only mastodon there has alavetelis
[10:48:38]  <gareth>	yeah, confirmed
[10:54:02]  <sam>	I think the best fix is to move the alaveteli crons to run after 1am, tbh.
[11:06:24]  <gareth>	okay cool, I'll ticket that in and should be able to do it early next week.
[11:06:52]  <gareth>	I can't think of any problems from the app end immediately, but think it deserves a bit of thought before just doing it :)
[11:07:11]  <gareth>	Thanks for your help. much appreciated
```

**Comment by garethrees** [comment]
The gist of this is that the logrotate is happening after the import is called.

We should make the log import run after 01:00 to guarantee the logrotate has happened.

**Comment by garethrees** [comment]
Yesterday I changed nicaragua's crontab so that `load-mail-server-logs` runs on the 59th minute. All good.

Just changed the shared `crontab.ugly` in `9347dce0f7c9109d3fff06919802a5f802c3eee9` and redeployed sites on the affected host.
