### ISSUE TITLE
[ERROR] admin_general#timeline (NoMethodError) "undefined method `each_with_index' for nil:NilC

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4042]
Nothing too concerning – this happens when you manually increment the `page` parameter beyond the number of available pages.

Should 404, but no big deal.

```
A NoMethodError occurred in admin_general#timeline:

undefined method `each_with_index' for nil:NilClass
app/controllers/admin_general_controller.rb:92:in `block in timeline'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/timeline?page=33
* HTTP Method: GET
* IP address : FILTERED
* Parameters : {"page"=>"33", "controller"=>"admin_general", "action"=>"timeline"}
* Timestamp : 2017-06-15 12:23:17 +0100
* Server : FILTERED
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-06-15T10-09-28
* Process: FILTERED

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_general_controller.rb:92:in `block in timeline'
app/controllers/admin_general_controller.rb:87:in `timeline'
app/controllers/application_controller.rb:108:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
More of these:

```
A NoMethodError occurred in admin_general#timeline:

undefined method `each_with_index' for nil:NilClass
app/controllers/admin_general_controller.rb:109:in `block in timeline'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/timeline?event_type=authority_change&page=2
* HTTP Method: GET
* Parameters : {"event_type"=>"authority_change", "page"=>"2", "controller"=>"admin_general", "action"=>"timeline"}
* Timestamp : 2019-02-04 21:53:32 +0000
* Rails root : /REDACTED/alaveteli-2019-01-29T15-20-21

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_general_controller.rb:109:in `block in timeline'
app/controllers/admin_general_controller.rb:103:in `timeline'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
