### ISSUE TITLE
[ERROR] admin_track#destroy (NoMethodError) "undefined method `destroy' for nil:NilClass"

### ISSUE THREAD

**Issue by mbimmler** [mysociety/alaveteli#4045]
A user's request tracking emails keep bouncing back (as the email address doesn't exist anymore). I therefore wanted to manually destroy the tracks concerned on the /admin/users page.
When I click on "destroy track", I get the following error message:

```
NoMethodError in AdminTrackController#destroy
undefined method `destroy' for nil:NilClass

Extracted source (around line #26):
24 
25 def destroy
26 @track_thing.destroy
27 flash[:notice] = 'Track destroyed'
28 redirect_to admin_user_url(@track_thing.tracking_user)
29 end
         
Rails.root: /FILTERED/www.whatdotheyknow.com/alaveteli-2017-06-15T14-04-01

Application Trace | Framework Trace | Full Trace
app/controllers/admin_track_controller.rb:26:in `destroy'
app/controllers/application_controller.rb:108:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'


Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"delete",
 "authenticity_token"=>"z0tCQGBxQ0qv0m2i21cx86L9jUuzWrqRyLaMfQClPn8=",
 "commit"=>"Destroy track",
 "id"=>"71718"}

Toggle session dump

Toggle env dump

Response

Headers:
None
```

**Comment by garethrees** [comment]
```
A NoMethodError occurred in admin_track#destroy:

undefined method `destroy' for nil:NilClass
app/controllers/admin_track_controller.rb:26:in `destroy'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/tracks/71718
* HTTP Method: DELETE
* IP address : FILTERED
* Parameters : {"utf8"=>"✓", "_method"=>"delete", "authenticity_token"=>"z0tCQGBxQ0qv0m2i21cx86L9jUuzWrqRyLaMfQClPn8=", "commit"=>"Destroy track", "action"=>"destroy", "controller"=>"admin_track", "id"=>"71718"}
* Timestamp : 2017-06-16 14:27:56 +0100
* Server : FILTERED
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-06-15T14-04-01
* Process: 2649

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_track_controller.rb:26:in `destroy'
app/controllers/application_controller.rb:108:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
