### ISSUE TITLE
[ERROR] request#new (PG::TRDeadlockDetected) "ERROR: deadlock detected

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4115]
```
A PG::TRDeadlockDetected occurred in request#new:

  ERROR:  deadlock detected
DETAIL:  Process 5314 waits for ShareLock on transaction 521599739; blocked by process 17178.
Process 17178 waits for ExclusiveLock on tuple (51,6) of relation 411111 of database 16558; blocked by process 5314.
HINT:  See server log for query details.

  app/controllers/request_controller.rb:413:in `new'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new
  * HTTP Method: POST
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>[FILTERED], "outgoing_message"=>{"body"=>"Dear Merton Borough Council,\r\n\r\nThis is to ask for details of all outstanding planning enforcement cases broken down by ward, including the date they commenced.\r\n\r\nYours faithfully,\r\n\r\nTony Burton"}, "info_request"=>{"title"=>"Planning enforcement casework", "public_body_id"=>"259", "tag_string"=>""}, "submitted_new_request"=>"1", "preview"=>"0", "submit"=>"Send and publish request", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2017-07-20 11:00:06 +0100
  * [FILTERED]
  * Process: 20717

-------------------------------
Backtrace:
-------------------------------

  app/controllers/request_controller.rb:413:in `new'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
This has happened [again](https://groups.google.com/a/mysociety.org/forum/#!topic/cron-alaveteli/tfDCnBCyz8Q) and prevented an incoming message from being saved.

**Comment by gbp** [comment]
Actually this isn't from a web request, rather mailin:  #4681

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
