### ISSUE TITLE
[ERROR] request#download_entire_request (NoMethodError) "undefined method `[]' for nil:NilClass...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4148]
Introduced by Rails 4.2, seems to be a Sprockets (or SprocketRails) issue

```
A NoMethodError occurred in request#download_entire_request:

  undefined method `[]' for nil:NilClass
  app/views/general/_stylesheet_includes.html.erb:4:in `_app_views_general__stylesheet_includes_html_erb___3349839874082148774_66274660'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/organisational_structure_chart_f_3474/download
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"controller"=>"request", "action"=>"download_entire_request", "url_title"=>"organisational_structure_chart_f_3474"}
  * Timestamp  : 2017-08-08 12:11:58 +0100
  * Rails root : FILTERED/www.whatdotheyknow.com/alaveteli-2017-08-08T09-11-37
  * Process: 21279

-------------------------------
Backtrace:
-------------------------------

  app/views/general/_stylesheet_includes.html.erb:4:in `_app_views_general__stylesheet_includes_html_erb___3349839874082148774_66274660'
  app/views/layouts/default.html.erb:17:in `_app_views_layouts_default_html_erb__1695932967868905343_62073620'
  app/controllers/request_controller.rb:974:in `make_request_summary_file'
  app/controllers/request_controller.rb:951:in `block in make_request_zip'
  app/controllers/request_controller.rb:950:in `make_request_zip'
  app/controllers/request_controller.rb:842:in `block in download_entire_request'
  app/controllers/request_controller.rb:821:in `download_entire_request'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Now that the default for production is `config.assets.compile = false` (to prevent on-the-fly asset compilation), `Rails.application.assets` is nil so when we try to get the stylesheet path from `Rails.application.assets["responsive/application.css"].to_s`(to try to write to a file to produce the downloadable copy), it fails with the above error.

(For ease of reference, we are using sprockets 3.7.1 and sprockets-rails 3.2.0)

**Comment by lizconlan** [comment]
TODO: clear affected caches (August 8th, morning of the 9th)
