### ISSUE TITLE
[ERROR] user#signup (ArgumentError) "invalid address"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4151]
```
An ArgumentError occurred in user#signup: 

  invalid address 
  lib/alaveteli_rate_limiter/ip_rate_limiter.rb:58:in `new' 

------------------------------- 
Request: 
------------------------------- 

  ERROR: Failed to generate exception summary: 
  
  ActionView::Template::Error: IP spoofing attack?! HTTP_CLIENT_IP=FILTERED HTTP_X_FORWARDED_FOR=FILTERED

 FILTERED/gems/actionpack-4.1.16/lib/action_dispatch/middleware/remote_ip.rb:149:in `calculate_ip'
 FILTERED/gems/actionpack-4.1.16/lib/action_dispatch/middleware/remote_ip.rb:168:in `to_s'
 FILTERED/gems/actionpack-4.1.16/lib/action_dispatch/http/request.rb:205:in `remote_ip'

-------------------------------
Backtrace:
-------------------------------

  lib/alaveteli_rate_limiter/ip_rate_limiter.rb:58:in `new'
  lib/alaveteli_rate_limiter/ip_rate_limiter.rb:58:in `clean_ip'
  lib/alaveteli_rate_limiter/ip_rate_limiter.rb:39:in `record'
  app/controllers/user_controller.rb:168:in `signup'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
So far this has come up about 4 times over 8 days.

Backlogging until it comes up again.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
