### ISSUE TITLE
[ERROR] request#describe_state (PG::UniqueViolation) "ERROR: duplicate key value violates uniq...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4162]
```
A PG::UniqueViolation occurred in request#describe_state:

  ERROR:  duplicate key value violates unique constraint "index_request_summaries_summary_categories_unique"
DETAIL:  Key (request_summary_id, request_summary_category_id)=(254128, 2) already exists.

  app/models/alaveteli_pro/request_summary.rb:69:in `update_from'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/366763/describe
  * HTTP Method: PATCH
  * IP address : FILTERED
  * Parameters : {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"gNoQKfzVxxHltrqwO4rowbPbqdf4wYODXsMsywIq2sc=", "incoming_message"=>{"described_state"=>"successful"}, "last_info_request_event_id"=>"1994895", "commit"=>"Submit status", "controller"=>"request", "action"=>"describe_state", "id"=>"366763"}
  * Timestamp  : 2017-08-11 23:48:01 +0100
  * Server : FILTERED
  * Rails root : FILTERED/www.whatdotheyknow.com/alaveteli-2017-08-11T08-42-49
  * Process: 20282

-------------------------------
Backtrace:
-------------------------------

  app/models/alaveteli_pro/request_summary.rb:69:in `update_from'
  app/models/alaveteli_pro/request_summary.rb:61:in `create_or_update_from'
  app/models/concerns/alaveteli_pro/request_summaries.rb:20:in `create_or_update_request_summary'
  app/models/info_request.rb:656:in `set_described_state'
  app/controllers/request_controller.rb:490:in `describe_state'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
This has happened again since we moved to the new server setup so there might be something else going on...

```
A PG::UniqueViolation occurred in request#describe_state:

  ERROR:  duplicate key value violates unique constraint "index_request_summaries_summary_categories_unique"
DETAIL:  Key (request_summary_id, request_summary_category_id)=(440401, 4) already exists.

  app/models/alaveteli_pro/request_summary.rb:69:in `update_from'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/447184/describe
  * HTTP Method: PATCH
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"qQiiwz+kf0CFZUyjDbYtRuqhqyy+h7AfbN+edx7Cfp4=", "incoming_message"=>{"described_state"=>"waiting_response"}, "last_info_request_event_id"=>"2635366", "commit"=>"Submit status", "controller"=>"request", "action"=>"describe_state", "id"=>"447184"}
  * Timestamp  : 2017-11-17 11:50:07 +0000
  * Process: 1934

-------------------------------
Backtrace:
-------------------------------

  app/models/alaveteli_pro/request_summary.rb:69:in `update_from'
  app/models/alaveteli_pro/request_summary.rb:61:in `create_or_update_from'
  app/models/concerns/alaveteli_pro/request_summaries.rb:20:in `create_or_update_request_summary'
  app/models/info_request.rb:657:in `set_described_state'
  app/controllers/request_controller.rb:489:in `describe_state'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
