### ISSUE TITLE
[ERROR] request#get_attachment_as_html (ArgumentError) "string contains null byte"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4170]
Appears to have come from Yahoo's web crawler - user agent string `"Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"`

```
An ArgumentError occurred in request#get_attachment_as_html:

  string contains null byte
  app/models/incoming_message.rb:579:in `block in extract_attachments!'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/50071/response/122729/attach/html/3/utf%208%20B%20MTk2MTA0MTEgLSAyMTIxNDMgLSBMQVdTXzEuUERGAA.pdf.html
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"controller"=>"request", "action"=>"get_attachment_as_html", "id"=>"50071", "incoming_message_id"=>"122729", "part"=>"3", "file_name"=>"utf 8 B MTk2MTA0MTEgLSAyMTIxNDMgLSBMQVdTXzEuUERGAA.pdf.html"}
  * Timestamp  : 2017-08-15 05:30:17 +0100
  * Server : FILTERED
  * Rails root : FILTERED www.whatdotheyknow.com/alaveteli-2017-08-11T08-42-49
  * Process: 13612

-------------------------------
Backtrace:
-------------------------------

  app/models/incoming_message.rb:579:in `block in extract_attachments!'
  app/models/incoming_message.rb:577:in `each'
  app/models/incoming_message.rb:577:in `extract_attachments!'
  app/models/incoming_message.rb:139:in `block in parse_raw_email!'
  app/models/incoming_message.rb:138:in `parse_raw_email!'
  app/models/foi_attachment.rb:90:in `rescue in body'
  app/models/foi_attachment.rb:77:in `body'
  app/models/foi_attachment.rb:105:in `default_body'
  lib/attachment_to_html/adapter.rb:60:in `attachment_body'
  lib/attachment_to_html/adapters/pdf.rb:50:in `convert'
  lib/attachment_to_html/adapters/pdf.rb:32:in `parse_body'
  lib/attachment_to_html/adapter.rb:25:in `body'
  lib/attachment_to_html/adapters/pdf.rb:44:in `number_of_images_in_body'
  lib/attachment_to_html/adapters/pdf.rb:40:in `contains_too_many_images?'
  lib/attachment_to_html/adapters/pdf.rb:25:in `success?'
  lib/attachment_to_html/attachment_to_html.rb:16:in `to_html'
  app/models/foi_attachment.rb:306:in `body_as_html'
  app/controllers/request_controller.rb:683:in `get_attachment_as_html'
  app/controllers/request_controller.rb:626:in `cache_attachments'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
```
An ArgumentError occurred in request#get_attachment_as_html:

  string contains null byte
  app/models/incoming_message.rb:579:in `block in extract_attachments!'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/50071/response/122737/attach/html/3/utf%208%20B%20MTg3MDA3MTQgLSAyNDI1NTIgLSBVbml0ZWQgU3luYWdvZ3VlcyBBY3QgW2luY2x1ZGluZyBzY2hlbWVzIG9mMTg4MCwgMTkyNiBhbmQgMTk1NC5wZGYA.pdf.html
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"controller"=>"request", "action"=>"get_attachment_as_html", "id"=>"50071", "incoming_message_id"=>"122737", "part"=>"3", "file_name"=>"utf 8 B MTg3MDA3MTQgLSAyNDI1NTIgLSBVbml0ZWQgU3luYWdvZ3VlcyBBY3QgW2luY2x1ZGluZyBzY2hlbWVzIG9mMTg4MCwgMTkyNiBhbmQgMTk1NC5wZGYA.pdf.html"}
  * Timestamp  : 2017-08-15 05:33:39 +0100
  * Server : FILTERED
  * Rails root : FILTERED www.whatdotheyknow.com/alaveteli-2017-08-11T08-42-49
  * Process: 13213

-------------------------------
Backtrace:
-------------------------------

  app/models/incoming_message.rb:579:in `block in extract_attachments!'
  app/models/incoming_message.rb:577:in `each'
  app/models/incoming_message.rb:577:in `extract_attachments!'
  app/models/incoming_message.rb:139:in `block in parse_raw_email!'
  app/models/incoming_message.rb:138:in `parse_raw_email!'
  app/models/foi_attachment.rb:90:in `rescue in body'
  app/models/foi_attachment.rb:77:in `body'
  app/models/foi_attachment.rb:105:in `default_body'
  lib/attachment_to_html/adapter.rb:60:in `attachment_body'
  lib/attachment_to_html/adapters/pdf.rb:50:in `convert'
  lib/attachment_to_html/adapters/pdf.rb:32:in `parse_body'
  lib/attachment_to_html/adapter.rb:25:in `body'
  lib/attachment_to_html/adapters/pdf.rb:44:in `number_of_images_in_body'
  lib/attachment_to_html/adapters/pdf.rb:40:in `contains_too_many_images?'
  lib/attachment_to_html/adapters/pdf.rb:25:in `success?'
  lib/attachment_to_html/attachment_to_html.rb:16:in `to_html'
  app/models/foi_attachment.rb:306:in `body_as_html'
  app/controllers/request_controller.rb:683:in `get_attachment_as_html'
  app/controllers/request_controller.rb:626:in `cache_attachments'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
