### ISSUE TITLE
[ERROR] ActionController::UrlGenerationError in AdminGeneralController#index

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4177]
```
An ActionController::UrlGenerationError occurred in admin_general#index:

  No route matches {:action=>"edit", :change_request_id=>27, :controller=>"admin_public_body", :format=>nil, :id=>nil, :locale=>"fr_BE"} missing required keys: [:id]
  lib/routing_filters.rb:28:in `around_generate'


-------------------------------
Request:
-------------------------------

  * URL        : https://transparencia.be/fr_BE/admin
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"controller"=>"admin_general", "action"=>"index", "locale"=>"fr_BE"}
  * Timestamp  : 2017-08-16 17:54:50 +0200
  * Server : FILTERED
  * Rails root : /FILTERED/belgium.alaveteli.org/alaveteli-2017-08-16T15-47-12
  * Process: 11713

-------------------------------
Backtrace:
-------------------------------

  lib/routing_filters.rb:28:in `around_generate'
  app/views/admin_general/index.html.erb:253:in `block (2 levels) in _app_views_admin_general_index_html_erb__21321736094588450_63466400'
  app/views/admin_general/index.html.erb:242:in `block in _app_views_admin_general_index_html_erb__21321736094588450_63466400'
  app/views/admin_general/index.html.erb:239:in `_app_views_admin_general_index_html_erb__21321736094588450_63466400'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Not what I first thought - the change request does not have a PublicBody associated with it so I think _that's_ the "id" it's complaining about

**Comment by lizconlan** [comment]
This maybe a request for a authority to be added that is being treated as a change to an existing authority. (Or a change request for an authority which is no longer in the database? Hard to tell)

**Comment by lizconlan** [comment]
Fixed - was a change request made by one of the site admins back in April against a PublicBody record that has since been removed from the site. I've deleted it and the site works again.

Closing unless it reoccurs then we'll need to look at how the data was invalidated
