### ISSUE TITLE
[ERROR] followups#create (PG::UniqueViolation) "ERROR: duplicate key value violates unique con...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4193]
```
A PG::UniqueViolation occurred in followups#create:

  ERROR:  duplicate key value violates unique constraint "index_request_summaries_summary_categories_unique"
DETAIL:  Key (request_summary_id, request_summary_category_id)=(416563, 8) already exists.

  app/models/alaveteli_pro/request_summary.rb:69:in `update_from'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/421631/followups
  * HTTP Method: POST
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"✓", "authenticity_token"=> [FILTERED], "outgoing_message"=>{"body"=> [FILTERED], "what_doing"=>"internal_review"}, "submitted_followup"=>"1", "internal_review"=>"1", "submit"=>"Send and publish message", "controller"=>"followups", "action"=>"create", "request_id"=>"421631"}
  * Timestamp  : 2017-08-30 06:41:29 +0100
  * Server : [FILTERED]
  * Rails root : [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-08-16T09-27-44
  * Process: 26591

-------------------------------
Backtrace:
-------------------------------

  app/models/alaveteli_pro/request_summary.rb:69:in `update_from'
  app/models/alaveteli_pro/request_summary.rb:61:in `create_or_update_from'
  app/models/concerns/alaveteli_pro/request_summaries.rb:20:in `create_or_update_request_summary'
  app/models/info_request_event.rb:88:in `block in <class:InfoRequestEvent>'
  app/models/info_request.rb:816:in `log_event'
  app/models/outgoing_message.rb:195:in `record_email_delivery'
  app/controllers/followups_controller.rb:148:in `send_followup'
  app/controllers/followups_controller.rb:28:in `create'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
FWIW the request itself is not a Pro request – just that its unable to update the `RequestSummary`.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
