### ISSUE TITLE
[ERROR] admin_public_body#create (PG::NotNullViolation) "ERROR: null value in column \"name\" violat...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4197]
I think this might be another effect of the underscore default locale bug  - note the default locale (`fr_BE`) appearing in the URL, leading to this incorrect parameter nesting:

`{"translations_attributes"=>{"fr_BE"=>{"locale"=>"fr_BE", "name"=>"`

```
A PG::NotNullViolation occurred in admin_public_body#create:

  ERROR:  null value in column "name" violates not-null constraint

  app/controllers/admin_public_body_controller.rb:54:in `block in create'


-------------------------------
Request:
-------------------------------

  * URL        : https://transparencia.be/fr_BE/admin/bodies
  * HTTP Method: POST
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"PWMCv4IcAEj8ZeFMBEzav8reqYuRs6FyJ5vHGpN8oxw=", "public_body"=>{"translations_attributes"=>{"fr_BE"=>{"locale"=>"fr_BE", "name"=>"SPF economie (service public fédéral Économie, PME, Classes moyennes et Énergie)", "short_name"=>"SPF economie", "request_email"=>"[FILTERED]", "publication_scheme"=>"http://economie.fgov.be", "notes"=>""}, "nl_BE"=>{"locale"=>"nl_BE", "name"=>" FOD Economie (Federale Overheidsdienst Economie, KMO, Middenstand en Energie)", "short_name"=>"FOD economie", "request_email"=>"[FILTERED]", "publication_scheme"=>"http://economie.fgov.be", "notes"=>""}}, "tag_string"=>"", "home_page"=>"", "disclosure_log"=>"", "last_edit_comment"=>"Requested by: Niek Bartholomeus ([FILTERED])\r\nSource URL: http://economie.fgov.be/nl/\r\nNotes: De bedoeling is om een vraag te stellen over de KBO die deel uitaakt van de FOD economie"}, "change_request_id"=>"45", "subject"=>"Votre demande d'ajout de FOD Economie sur Transparencia", "response"=>"Cher/Chère Niek Bartholomeus,\r\n\r\nMerci de votre suggestion d'ajouter l'autorité FOD Economie. Nous l'avons ajoutée ici :\r\n\r\n[L'URL de l'autorité publique sera insérée ici]\r\n\r\nSincèrement,\r\n\r\nL'équipe de Transparencia.\r\n", "commit"=>"Create", "action"=>"create", "controller"=>"admin_public_body", "locale"=>"fr_BE"}
  * Timestamp  : 2017-09-01 12:30:11 +0200
  * Server : [FILTERED]
  * Rails root : [FILTERED]/belgium.alaveteli.org/alaveteli-2017-08-23T09-14-41
  * Process: 23500

-------------------------------
Backtrace:
-------------------------------

  app/controllers/admin_public_body_controller.rb:54:in `block in create'
  app/controllers/admin_public_body_controller.rb:48:in `create'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Duplicate of https://github.com/mysociety/belgium-theme/issues/54

**Comment by lizconlan** [comment]
(it's not enough to backport the routing filter fix, the error remains - will have to wait for 0.30)

**Comment by garethrees** [comment]
Reopening as this is still an issue. Linking to https://github.com/mysociety/alaveteli/issues/3804 so that we know when this is fixable.

**Comment by garethrees** [comment]
Ah, missed this was marked as a duplicate. Will add the release link over in mysociety/belgium-theme#54.
