### ISSUE TITLE
[ERROR] request#describe_state (RuntimeError) "unknown calculate_status waiting_classification"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4199]
```
A RuntimeError occurred in request#describe_state:

  unknown calculate_status waiting_classification
  app/controllers/request_controller.rb:538:in `describe_state'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/428028/describe
  * HTTP Method: PATCH
  * IP address :  [FILTERED]
  * Parameters : {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"gTip1gT5uGMdjjZdbhAy9KyiCTJCOTtpCw9Q/NNJCKU=", "incoming_message"=>{"described_state"=>"waiting_response"}, "last_info_request_event_id"=>"2521893", "commit"=>"Submit status", "controller"=>"request", "action"=>"describe_state", "id"=>"428028"}
  * Timestamp  : 2017-09-01 16:28:59 +0100
  * Server : [FILTERED]
  * Rails root :  [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-01T09-58-02
  * Process: 27007

-------------------------------
Backtrace:
-------------------------------

  app/controllers/request_controller.rb:538:in `describe_state'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Another of these yesterday

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
