### ISSUE TITLE
[ERROR] public_body#view_email (Recaptcha::RecaptchaError) "IP spoofing attack?! HTTP_CLIENT_IP...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4205]
Similar to #4151. Same HTTP_CLIENT_IP and HTTP_X_FORWARDED_FOR

If it's legit, it might be an odd proxy config

```
A Recaptcha::RecaptchaError occurred in public_body#view_email:

  IP spoofing attack?! HTTP_CLIENT_IP="[FILTERED]" HTTP_X_FORWARDED_FOR="[FILTERED]"
  app/controllers/public_body_controller.rb:104:in `block in view_email'


-------------------------------
Request:
-------------------------------

  ERROR: Failed to generate exception summary:

  ActionView::Template::Error: IP spoofing attack?! HTTP_CLIENT_IP="[FILTERED]" HTTP_X_FORWARDED_FOR="[FILTERED]"

  [FILTERED]/gems/actionpack-4.1.16/lib/action_dispatch/middleware/remote_ip.rb:149:in `calculate_ip'
  [FILTERED]/gems/actionpack-4.1.16/lib/action_dispatch/middleware/remote_ip.rb:168:in `to_s'
  [FILTERED]/gems/actionpack-4.1.16/lib/action_dispatch/http/request.rb:205:in `remote_ip'
  [FILTERED]/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_request.text.erb:3:in

-------------------------------
Backtrace:
-------------------------------

  app/controllers/public_body_controller.rb:104:in `block in view_email'
  lib/alaveteli_localization.rb:43:in `with_locale'
  app/controllers/public_body_controller.rb:102:in `view_email'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Haven't seen any of these since 2018
