### ISSUE TITLE
[ERROR] public_body#search_typeahead (NoMethodError) "undefined method `strip' for nil:NilClass...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4206]
```
A NoMethodError occurred in public_body#search_typeahead:

  undefined method `strip' for nil:NilClass
  lib/typeahead_search.rb:50:in `check_query'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/body/search_ahead
  * HTTP Method: GET
  * IP address : [FILTERED]
  * Parameters : {"controller"=>"public_body", "action"=>"search_typeahead"}
  * Timestamp  : 2017-09-06 08:37:29 +0100
  * Server : [FILTERED]
  * Rails root : [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-01T09-58-02
  * Process: 14467

-------------------------------
Backtrace:
-------------------------------

  lib/typeahead_search.rb:50:in `check_query'
  lib/typeahead_search.rb:16:in `xapian_search'
  app/controllers/application_controller.rb:485:in `typeahead_search'
  app/controllers/public_body_controller.rb:305:in `search_typeahead'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
(Googlebot - ` HTTP_USER_AGENT: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`)

```
A NoMethodError occurred in public_body#search_typeahead:

  undefined method `strip' for nil:NilClass
  lib/typeahead_search.rb:50:in `check_query'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/body/search_ahead
  * HTTP Method: GET
  * IP address : [FILTERED]
  * Parameters : {"controller"=>"public_body", "action"=>"search_typeahead"}
  * Timestamp  : 2017-09-07 22:35:36 +0100
  * Server : [FILTERED]
  * Rails root : [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-01T09-58-02
  * Process: 29809

-------------------------------
Backtrace:
-------------------------------

  lib/typeahead_search.rb:50:in `check_query'
  lib/typeahead_search.rb:16:in `xapian_search'
  app/controllers/application_controller.rb:485:in `typeahead_search'
  app/controllers/public_body_controller.rb:305:in `search_typeahead'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
I think we should also fix https://github.com/mysociety/alaveteli/issues/4617 at the same time as this.
