### ISSUE TITLE
[ERROR] admin_general#index (PG::QueryCanceled) "ERROR: canceling statement due to user reques...

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4208]
```
A PG::QueryCanceled occurred in admin_general#index:

ERROR: canceling statement due to user request

app/controllers/admin_general_controller.rb:60:in `block in index'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin
* HTTP Method: GET
* IP address : FILTERED
* Parameters : {"controller"=>"admin_general", "action"=>"index"}
* Timestamp : 2017-09-07 14:22:00 +0100
* Server : FILTERED
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-01T09-58-02
* Process: 18153

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_general_controller.rb:60:in `block in index'
app/controllers/admin_general_controller.rb:60:in `any?'
app/controllers/admin_general_controller.rb:60:in `index'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
This is getting caused by https://github.com/mysociety/alaveteli/blob/1eff715/app/controllers/admin_general_controller.rb#L55-L57.

See https://docs.google.com/document/d/1_bDeethGcXyvHFhVBnucpr1EXW5h7YC_WvVCk3Fgzu4/edit# for more info.
