### ISSUE TITLE
[ERROR] execution expired (Net::OpenTimeout) in POP Poller

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4221]
```
/opt/rbenv/versions/2.3.4/lib/ruby/2.3.0/net/pop.rb:545:in `initialize': execution expired (Net::OpenTimeout)
  from /opt/rbenv/versions/2.3.4/lib/ruby/2.3.0/net/pop.rb:545:in `open'
  from /opt/rbenv/versions/2.3.4/lib/ruby/2.3.0/net/pop.rb:545:in `block in do_start'
  from /opt/rbenv/versions/2.3.4/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  from /opt/rbenv/versions/2.3.4/lib/ruby/2.3.0/net/pop.rb:544:in `do_start'
  from /opt/rbenv/versions/2.3.4/lib/ruby/2.3.0/net/pop.rb:537:in `start'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/lib/alaveteli_mail_poller.rb:113:in `start'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/runner.rb:62:in `<top (required)>'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/runner.rb:62:in `eval'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/runner.rb:62:in `<top (required)>'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:123:in `require'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:90:in `runner'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /FILTERED/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:9:in `require'
  from bin/rails:9:in `<main>'
```

**Comment by garethrees** [comment]
```
zgrep -l OpenTimeout foi-poll-for-incoming.log*
foi-poll-for-incoming.log.1
foi-poll-for-incoming.log.2.gz
foi-poll-for-incoming.log.9.gz
```

**Comment by garethrees** [comment]
I think we just want to handle [`Net::OpenTimeout`](http://ruby-doc.org/stdlib-2.3.4/libdoc/net/pop/rdoc/Net/POP3.html#open_timeout).

```ruby
begin
  retries ||= 0
  pop3.start(settings[:user_name], settings[:password])
rescue Net::OpenTimeout => e
  sleep 60
  retry if (retries += 1) < 3
  # Send exception notification…
end
```

While we're at it, we should also handle [`Net::ReadTimeout`](http://ruby-doc.org/stdlib-2.3.4/libdoc/net/pop/rdoc/Net/POP3.html#read_timeout) when we read the mail.

**Comment by garethrees** [comment]
Another one of these at 12:55 today (2017-09-22).

**Comment by garethrees** [comment]
Notes for local setup https://github.com/mysociety/alaveteli/pull/3840/commits/f9df879d32b58907381bbee3a127461206088fd1
