### ISSUE TITLE
[ERROR] request#new (ActionView::MissingTemplate) "Missing template request/new, application/ne...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4228]
```
An ActionView::MissingTemplate occurred in request#new:

  Missing template request/new, application/new with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
  * "[FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/lib/themes/whatdotheyknow-theme/lib/views"
  * "[FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28/app/views"
  * "[FILTERED]/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.3.0/gems/foundation-rails-5.5.3.2/app/views"

  app/controllers/request_controller.rb:1088:in `render_new_compose'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new/liverpool_city_council.json
  * HTTP Method: GET
  * IP address : [FILTERED]
  * Parameters : {"controller"=>"request", "action"=>"new", "url_name"=>"liverpool_city_council", "format"=>"json"}
  * Timestamp  : 2017-09-11 11:36:32 +0100
  * Server : [FILTERED]
  * Rails root : [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-08T13-15-28
  * Process: 8612

-------------------------------
Backtrace:
-------------------------------

  app/controllers/request_controller.rb:1088:in `render_new_compose'
  app/controllers/request_controller.rb:323:in `new'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
Still an issue updated line number:

```
An ActionView::MissingTemplate occurred in request#new:

  Missing template request/new, application/new with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
  * "[FILTERED]/www.whatdotheyknow.com/alaveteli-2021-08-04T11-59-57/lib/themes/whatdotheyknow-theme/lib/views"
  * "[FILTERED]/www.whatdotheyknow.com/alaveteli-2021-08-04T11-59-57/app/views"

  app/controllers/request_controller.rb:790:in `render_new_compose'
```
