### ISSUE TITLE
[ERROR] general#search_redirect (ActionController::BadRequest) "Invalid query parameters: inval...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4266]
This is an odd one, looks like the request was: `REQUEST_URI : /search?query=%s`

```
An ActionController::BadRequest occurred in general#search_redirect:

  Invalid query parameters: invalid %-encoding (%s)
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  ERROR: Failed to generate exception summary:

  ActionView::Template::Error: Invalid query parameters: invalid %-encoding (%s)

  [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-27T11-56-09/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/utils.rb:127:in `rescue in parse_nested_query'
  [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-27T11-56-09/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/utils.rb:117:in `parse_nested_query'
  [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-27T11-56-09/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/request.rb:371:in `parse_query'
  [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-27T11-56-09/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/http/request.rb:339:in `parse_query'
  [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-09-27T11-56-09/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/request.rb:191:in `GET'
  ...

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
