### ISSUE TITLE
[ERROR] [www.whatdotheyknow.com] user#signin (ActionView::Template::Error) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4319]
```
An ActionView::Template::Error occurred in user#signin:

undefined method `[]' for nil:NilClass
app/views/general/_locale_switcher.html.erb:1:in `_app_views_general__locale_switcher_html_erb___1115593439394127169_70096671614640'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/sign_in
* HTTP Method: POST
* IP address : 86.154.149.97
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "user_signin"=>{"email"=>"[REDACTED]", "password"=>"[FILTERED]"}, "token"=>"[REDACTED]", "modal"=>"", "commit"=>"Sign in", "controller"=>"user", "action"=>"signin"}
* Timestamp : 2017-10-26 07:05:05 +0100
* Server : FILTERED
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-10-25T10-17-24
* Process: 16518


-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"en",
"user_id"=>143362,
"user_circumstance"=>"normal",
"post_redirect_token"=>"d1g7rjqfygf5o26o55f",
"ttl"=>"2017-10-26T07:04:52.988+01:00",
"_csrf_token"=>"FILTERED"}

-------------------------------
Backtrace:
-------------------------------

app/views/general/_locale_switcher.html.erb:1:in `_app_views_general__locale_switcher_html_erb___1115593439394127169_70096671614640'
app/views/general/_responsive_header.html.erb:16:in `_app_views_general__responsive_header_html_erb___1827291118500993025_70096485793060'
app/views/layouts/default.html.erb:74:in `_app_views_layouts_default_html_erb__4323909512064535773_47091730663040'
app/controllers/application_controller.rb:201:in `block (2 levels) in render_exception'
app/controllers/application_controller.rb:200:in `render_exception'
lib/strip_empty_sessions.rb:13:in `call'

```

**Comment by garethrees** [comment]
Not 100% on what's going on here, but I think its a failed authenticity token check getting masked by not being able to render the locale switcher on the error page.

Log snippet:

```
I, [2017-10-26T07:05:05.203862 #16518]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "user_signin"=>{"email"=>"s.ali@[FILTERED].net", "password"=>"[FILTERED]"}, "token"=>"mqhr4wnoz9v3zplb4ir", "modal"=>"", "commit"=>"Sign in"}
W, [2017-10-26T07:05:05.204564 #16518]  WARN -- : Can't verify CSRF token authenticity
F, [2017-10-26T07:05:05.205713 #16518] FATAL -- :
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  lib/strip_empty_sessions.rb:13:in `call'


I, [2017-10-26T07:05:05.227532 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.5ms)
I, [2017-10-26T07:05:05.229928 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.6ms)
I, [2017-10-26T07:05:05.232682 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.0ms)
I, [2017-10-26T07:05:05.232985 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
I, [2017-10-26T07:05:05.236697 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (1.9ms)
I, [2017-10-26T07:05:05.237048 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
I, [2017-10-26T07:05:05.239685 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.6ms)
I, [2017-10-26T07:05:05.239968 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
I, [2017-10-26T07:05:05.240097 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (16.9ms)
I, [2017-10-26T07:05:05.280122 #16518]  INFO -- :
Sent mail to cron-[FILTERED]@mysociety.org (39.4ms)
I, [2017-10-26T07:05:05.281727 #16518]  INFO -- :   Rendered general/exception_caught.html.erb within layouts/default (0.7ms)
I, [2017-10-26T07:05:05.282885 #16518]  INFO -- :   Rendered layouts/_favicon.html.erb (0.5ms)
I, [2017-10-26T07:05:05.284327 #16518]  INFO -- :   Rendered general/_responsive_stylesheets.html.erb (1.0ms)
I, [2017-10-26T07:05:05.284720 #16518]  INFO -- :   Rendered general/_stylesheet_includes.html.erb (1.6ms)
I, [2017-10-26T07:05:05.285373 #16518]  INFO -- :   Rendered general/_opengraph_tags.html.erb (0.4ms)
I, [2017-10-26T07:05:05.286987 #16518]  INFO -- :   Rendered general/_before_head_end.html.erb (0.8ms)
I, [2017-10-26T07:05:05.288451 #16518]  INFO -- :   Rendered general/_popup_banner.html.erb (0.6ms)
I, [2017-10-26T07:05:05.294473 #16518]  INFO -- :   Rendered general/_locale_switcher.html.erb (3.2ms)
I, [2017-10-26T07:05:05.294643 #16518]  INFO -- :   Rendered general/_responsive_header.html.erb (5.3ms)
I, [2017-10-26T07:05:05.294883 #16518]  INFO -- : Completed 500 Internal Server Error in 91ms (ActiveRecord: 0.0ms)
I, [2017-10-26T07:05:05.301840 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.6ms)
I, [2017-10-26T07:05:05.302587 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
I, [2017-10-26T07:05:05.303838 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.6ms)
I, [2017-10-26T07:05:05.304217 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
I, [2017-10-26T07:05:05.306496 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (1.7ms)
I, [2017-10-26T07:05:05.306910 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
I, [2017-10-26T07:05:05.308055 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
I, [2017-10-26T07:05:05.308402 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
I, [2017-10-26T07:05:05.308596 #16518]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (8.0ms)
I, [2017-10-26T07:05:05.344025 #16518]  INFO -- :
Sent mail to cron-[FILTERED]@mysociety.org (34.7ms)
F, [2017-10-26T07:05:05.347019 #16518] FATAL -- :
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: <% if @locales[:available].any? %>
    2:   <div id="user_locale_switcher" class="locale-list">
    3:     <p class="locale-list-trigger <% @locales[:current] %>">
    4:       <strong class="current-locale"><%= locale_name(@locales[:current]) %></strong>
  app/views/general/_locale_switcher.html.erb:1:in `_app_views_general__locale_switcher_html_erb___1115593439394127169_70096671614640'
  app/views/general/_responsive_header.html.erb:16:in `_app_views_general__responsive_header_html_erb___1827291118500993025_70096485793060'
  app/views/layouts/default.html.erb:74:in `_app_views_layouts_default_html_erb__4323909512064535773_47091730663040'
  app/controllers/application_controller.rb:201:in `block (2 levels) in render_exception'
  app/controllers/application_controller.rb:200:in `render_exception'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
These appear after one of https://github.com/mysociety/alaveteli/issues/4318, which tallies with the two mails to `cron-`.

**Comment by garethrees** [comment]
To solve these errors I think we just need to set `@locales` in the correct controller action ([`render_exception`](https://github.com/mysociety/alaveteli/blob/develop/app/controllers/application_controller.rb#L172))

**Comment by garethrees** [comment]
These have stopped appearing since https://github.com/mysociety/alaveteli/pull/4338, because now if there's a signed in user we won't ever render the sign-in form.

**Comment by garethrees** [comment]
Ah, they occur for a different action:

```
An ActionView::Template::Error occurred in request#new:

  undefined method `[]' for nil:NilClass
  app/views/general/_locale_switcher.html.erb:1:in `_app_views_general__locale_switcher_html_erb__3963037750594685524_70031215677200'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new
  * HTTP Method: POST
  * IP address : REDACTED
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "info_request"=>{"title"=>"", "public_body_id"=>"1611"}, "outgoing_message"=>{"body"=>"Dear Network Rail Limited,\r\n\r\nI would like to request information as to the name of every railway tunnel upon the Calder Valley Line that runs between Leeds & Manchester Victoria.\r\n\r\nYours faithfully,\r\nMBradley\r\n"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Preview your public request", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2018-01-24 12:45:19 +0000

```

**Comment by garethrees** [comment]
Tracking in https://github.com/mysociety/alaveteli/issues/4479
