### ISSUE TITLE
[ERROR] admin_general#index (NoMethodError) "undefined method `in_time_zone' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4326]
Marking a request as "needing attention" through the admin interface breaks the summary.

The error occurs because a `report_comment` event doesn't get created, and the dashboard calls `last_reported_at`.

When updating `attention_requested` through `AdminCommentController#update`, we should call `Comment#report!`.

```
A NoMethodError occurred in admin_general#index:

undefined method `in_time_zone' for nil:NilClass
app/helpers/date_time_helper.rb:39:in `simple_date_html'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin
* HTTP Method: GET
* IP address : FILTERED
* Parameters : {"controller"=>"admin_general", "action"=>"index"}
* Timestamp : 2017-10-27 10:24:39 +0100
* Server : FILTERED
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-10-26T19-38-38
* Process: 19257

-------------------------------
Backtrace:
-------------------------------

app/helpers/date_time_helper.rb:39:in `simple_date_html'
app/helpers/date_time_helper.rb:26:in `simple_date'
app/views/admin_general/_to_do_list.html.erb:44:in `block in _app_views_admin_general__to_do_list_html_erb___2208061734204758292_70011832342620'
app/views/admin_general/_to_do_list.html.erb:15:in `each'
app/views/admin_general/_to_do_list.html.erb:15:in `_app_views_admin_general__to_do_list_html_erb___2208061734204758292_70011832342620'
app/views/admin_general/index.html.erb:169:in `_app_views_admin_general_index_html_erb__233494462981526963_70011848313640'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Alternatively we could handle the lack of `Comment#last_reported_at` in the dashboard.

**Comment by gbp** [comment]
This happened again https://groups.google.com/a/mysociety.org/forum/#!topic/cron-alaveteli/VLS5VOuJ_xA

Fixed by finding the comment in `Comment.where(attention_requested: true)` and then running `comment.report!('', '', User.find(comment.user_id))`

**Comment by gbp** [comment]
```ruby
Comment.where(attention_requested: true).find_each { |c| next unless c.last_reported_at.nil?; c.report!('', '', User.find(comment.user_id)) }
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
