### ISSUE TITLE
[ERROR] request#new (ArgumentError) "string contains null byte"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4339]
I assume this is someone pasting from an editor introducing the null bytes.

```
An ArgumentError occurred in request#new:

string contains null byte
app/models/info_request.rb:504:in `find_existing'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/new
* HTTP Method: POST
* IP address : FILTERED
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"FILTERED", "info_request"=>{"title"=>"Traffic Management Providers", "public_body_id"=>"4311"}, "outgoing_message"=>{"body"=>"Dear Central Bedfordshire Council,\r\n\r\nCould you please provide information on the costings to the council to provide and imply this project on the A5505/Boscombe Rd / Amazon Road entrance junction in Dunstable.\r\n—\u0000—\u0000—\u0000—\u0000—\u0000—\u0000—\r\nInformation for Operational Teams\r\nHighway Authority:\r\nCentral Bedfordshire Council\r\nLocation:\r\nENTRANCE TO AMAZON\r\nDescription:\r\nTHREE WAY TRAFFIC LIGHTS IN OPERATION TO ENABLE SAFE PEDSTRIAN MANAGEMENT FOR AMAZON STAFF - MANUAL...\r\nWorks ref:\r\nCBC01L-MAIN-00006191\r\nProject ref:\r\nL-MAIN-00006191\r\nCurrent status:\r\nAdvanced planning\r\nWork info last updated:\r\n11:16 on 09/10/2017\r\nLast updated on roadworks.org:\r\n17:32 on 03/11/2017\r\nData source:\r\nCentral Bedfordshire Council\r\n—\u0000—\u0000—\u0000—\u0000—\u0000-\r\n\r\n\r\n\r\nYours faithfully,\r\n\r\nFILTERED"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Preview your public request", "controller"=>"request", "action"=>"new"}
* Timestamp : 2017-11-04 06:41:20 +0000
* Server : FILTERED
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-10-30T12-11-28
* Process: 6612

-------------------------------
Backtrace:
-------------------------------

app/models/info_request.rb:504:in `find_existing'
app/controllers/request_controller.rb:337:in `new'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Had another one of these, but it was [spam](https://groups.google.com/a/mysociety.org/forum/#!topic/cron-alaveteli/CltE7CW33bo) so this actually helped us out :)
