### ISSUE TITLE
Transient spec failure: …should show a full trace for general errors

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4346]
```
$ be rspec --seed=16271 spec/integration/errors_spec.rb

Randomized with seed 16271
............FF

Failures:

  1) When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
     Failure/Error: expect(response.body).to match('<div id="traces"')
       expected "" to match "<div id=\"traces\""
     # ./spec/integration/errors_spec.rb:149:in `block (4 levels) in <top (required)>'

  2) When errors occur when considering all requests local (by default all in development) should show a full trace for general errors
     Failure/Error: expect(response.body).to match('<div id="traces"')
       expected "" to match "<div id=\"traces\""
     # ./spec/integration/errors_spec.rb:39:in `block (3 levels) in <top (required)>'

Finished in 3.63 seconds (files took 12.54 seconds to load)
14 examples, 2 failures

Failed examples:

rspec ./spec/integration/errors_spec.rb:146 # When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
rspec ./spec/integration/errors_spec.rb:36 # When errors occur when considering all requests local (by default all in development) should show a full trace for general errors

Randomized with seed 16271
```

**Comment by garethrees** [comment]
Possibly related to https://github.com/mysociety/alaveteli/issues/4346

**Comment by garethrees** [comment]
> Possibly related to #4346

Dammit, I suck at copy-pasting issue IDs :(
