### ISSUE TITLE
0.30.1 - Adding suggested Holidays in admin causes 500 crash

### ISSUE THREAD

**Issue by handelaar** [mysociety/alaveteli#4363]
Hola

Title is fairly explanatory. Go to Admin. Tools->Holidays. Create new from suggestions. Choose 2018 instead of 2017 on dropdowns. Go to bottom of page and press Import. Receive 500 error and (more usefully) the email below:

```
An ActiveModel::ForbiddenAttributesError occurred in admin_holiday_imports#=
create:

  ActiveModel::ForbiddenAttributesError
  app/models/holiday_import.rb:50:in `block in holidays_attributes=3D'


-------------------------------
Request:
-------------------------------

  * URL        : https://foi.ie/admin/holiday_imports
  * HTTP Method: POST
  * IP address : 109.255.164.197
  * Parameters : {"utf8"=3D>"=E2=9C=93", "authenticity_token"=3D>"AokEexnGh=
y8///SRLudeXLbgfknj6909gmq7+llfWd4=3D", "holiday_import"=3D>{"holidays_attr=
ibutes"=3D>{"0"=3D>{"description"=3D>"New Year's Day", "day(1i)"=3D>"2018",=
 "day(2i)"=3D>"1", "day(3i)"=3D>"1"}, "1"=3D>{"description"=3D>"St. Patrick=
's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"3", "day(3i)"=3D>"19"}, "2"=3D>=
{"description"=3D>"Easter Monday", "day(1i)"=3D>"2018", "day(2i)"=3D>"4", "=
day(3i)"=3D>"2"}, "3"=3D>{"description"=3D>"May Day", "day(1i)"=3D>"2018", =
"day(2i)"=3D>"5", "day(3i)"=3D>"7"}, "4"=3D>{"description"=3D>"June Bank Ho=
liday", "day(1i)"=3D>"2018", "day(2i)"=3D>"6", "day(3i)"=3D>"4"}, "5"=3D>{"=
description"=3D>"August Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=3D>"8=
", "day(3i)"=3D>"6"}, "6"=3D>{"description"=3D>"October Bank Holiday", "day=
(1i)"=3D>"2018", "day(2i)"=3D>"10", "day(3i)"=3D>"29"}, "7"=3D>{"descriptio=
n"=3D>"Christmas Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"12", "day(3i)"=3D=
>"25"}, "8"=3D>{"description"=3D>"St. Stephen's Day", "day(1i)"=3D>"2018", =
"day(2i)"=3D>"12", "day(3i)"=3D>"26"}}}, "commit"=3D>"Import", "controller"=
=3D>"admin_holiday_imports", "action"=3D>"create"}
  * Timestamp  : 2017-11-14 01:46:36 +0000
  * Server : mygov.ie
  * Rails root : /home/genghis/sites/alaveteli
  * Process: 17801

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=3D>"a20342145500de4a07bba4c8ed152cdc",
   "locale"=3D>"en",
   "remember_me"=3D>true,
   "_csrf_token"=3D>"AokEexnGhy8///SRLudeXLbgfknj6909gmq7+llfWd4=3D",
   "user_id"=3D>1,
   "post_redirect_token"=3D>"ifgao9734qgndhczd14",
   "using_admin"=3D>1,
   "admin_name"=3D>"john_handelaar"}

-------------------------------
Environment:
-------------------------------

  * CONTENT_LENGTH                                 : 2646
  * CONTENT_TYPE                                   : application/x-www-form=
-urlencoded
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/html,application/=
xhtml+xml,application/xml;q=3D0.9,image/webp,image/apng,*/*;q=3D0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br
  * HTTP_ACCEPT_LANGUAGE                           : en-IE,en-US;q=3D0.8,en=
;q=3D0.6
  * HTTP_AUTHORIZATION                             : Basic YmVydGllYWhlcm46=
aWFtYWN1bnQ=3D
  * HTTP_CACHE_CONTROL                             : max-age=3D0
  * HTTP_CONNECTION                                : close
  * HTTP_COOKIE                                    : _ga=3DGA1.2.495328324.=
1510530069; _gid=3DGA1.2.66372717.1510530069; _wdtk_cookie_session=3DcVp2YU=
VselErWmpxWHhPYi95RHRxa0k0UVNhM1ZDZXFSbysxell3Zk10U2RRREw1d01MV2tpSWhoelQxS=
2pLL291US9RQXNsVlQ2bEk0c0l6c3VDcTNRd2lOYjdpK2JMNVBIbitwb3JORWxRak5pUkVjSmoy=
YXRhS2g4MjZpZzRYaWRjZDE3d0lLNXdaMmRPU2dKTFhTUnB1c0F1OWpsck14ZVlDeDl6VlRJYi9=
zZllMY0k4a3lJNmdZT3dvNWdPVmUvSjd0UXdqOGRtR2tHQklTWGdSb0V0NVg1d2xwZkFWTk1kWD=
hiWi9veUUreXZhTTJTZkY2aHU0aUlLUzE3VHBENlJ0eForMTdFVVdRVW1oWStaZzUwcENtR2FON=
mhmMitETnZOVUZ6SStNcFVRZFVOWVBxMTVXMFZDcXF6OFJMWjF2S3pGYXFZWlNzem9TSXBCUVVR=
PT0tLWxtRjQvWVlFKy93QkdxdjNVSUxJQUE9PQ%3D%3D--165537b4ef7ee60e1c7911b4feb26=
b971b063848
  * HTTP_DNT                                       : 1
  * HTTP_HOST                                      : foi.ie
  * HTTP_ORIGIN                                    : https://foi.ie
  * HTTP_REFERER                                   : https://foi.ie/admin/h=
oliday_imports/new?utf8=3D%E2%9C%93&holiday_import%5Bstart_year%5D=3D2018&h=
oliday_import%5Bend_year%5D=3D2018&holiday_import%5Bsource%5D=3Dsuggestions
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows N=
T 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163=
.100 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.0
  * HTTP_X_ACCEL_MAPPING                           : /home/genghis/sites/al=
aveteli/alaveteli/cache/zips/production/download=3D/download
  * HTTP_X_FORWARDED_FOR                           : 109.255.164.197
  * HTTP_X_FORWARDED_PROTO                         : https
  * HTTP_X_REAL_IP                                 : 109.255.164.197
  * HTTP_X_SENDFILE_TYPE                           : X-Accel-Redirect
  * ORIGINAL_FULLPATH                              : /admin/holiday_imports
  * ORIGINAL_SCRIPT_NAME                           :=20
  * PATH_INFO                                      : /admin/holiday_imports
  * QUERY_STRING                                   :=20
  * REMOTE_ADDR                                    : 127.0.0.1
  * REQUEST_METHOD                                 : POST
  * REQUEST_PATH                                   : /admin/holiday_imports
  * REQUEST_URI                                    : /admin/holiday_imports
  * ROUTES_29515260_SCRIPT_NAME                    :=20
  * SCRIPT_NAME                                    :=20
  * SERVER_NAME                                    : foi.ie
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.5.1 codename St=
raight Razor
  * action_controller.instance                     : #<AdminHolidayImportsC=
ontroller:0x00000007eda600>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceClea=
ner:0x000000074c20c8>
  * action_dispatch.cookies                        : #<ActionDispatch::Cook=
ies::CookieJar:0x000000079f67b0>
  * action_dispatch.cookies_digest                 :=20
  * action_dispatch.cookies_serializer             : hybrid
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cooki=
e
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::Cachi=
ngKeyGenerator:0x000000074d0100>
  * action_dispatch.logger                         : #<ActiveSupport::Logge=
r:0x00000005d832e0>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 109.255.164.197
  * action_dispatch.request.content_type           : application/x-www-form=
-urlencoded
  * action_dispatch.request.formats                : [text/html]
  * action_dispatch.request.parameters             : {"utf8"=3D>"=E2=9C=93"=
, "authenticity_token"=3D>"AokEexnGhy8///SRLudeXLbgfknj6909gmq7+llfWd4=3D",=
 "holiday_import"=3D>{"holidays_attributes"=3D>{"0"=3D>{"description"=3D>"N=
ew Year's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"1", "day(3i)"=3D>"1"}, "=
1"=3D>{"description"=3D>"St. Patrick's Day", "day(1i)"=3D>"2018", "day(2i)"=
=3D>"3", "day(3i)"=3D>"19"}, "2"=3D>{"description"=3D>"Easter Monday", "day=
(1i)"=3D>"2018", "day(2i)"=3D>"4", "day(3i)"=3D>"2"}, "3"=3D>{"description"=
=3D>"May Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"5", "day(3i)"=3D>"7"}, "4=
"=3D>{"description"=3D>"June Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=
=3D>"6", "day(3i)"=3D>"4"}, "5"=3D>{"description"=3D>"August Bank Holiday",=
 "day(1i)"=3D>"2018", "day(2i)"=3D>"8", "day(3i)"=3D>"6"}, "6"=3D>{"descrip=
tion"=3D>"October Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=3D>"10", "d=
ay(3i)"=3D>"29"}, "7"=3D>{"description"=3D>"Christmas Day", "day(1i)"=3D>"2=
018", "day(2i)"=3D>"12", "day(3i)"=3D>"25"}, "8"=3D>{"description"=3D>"St. =
Stephen's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"12", "day(3i)"=3D>"26"}}=
}, "commit"=3D>"Import", "controller"=3D>"admin_holiday_imports", "action"=
=3D>"create"}
  * action_dispatch.request.path_parameters        : {:controller=3D>"admin=
_holiday_imports", :action=3D>"create"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {"utf8"=3D>"=E2=9C=93"=
, "authenticity_token"=3D>"AokEexnGhy8///SRLudeXLbgfknj6909gmq7+llfWd4=3D",=
 "holiday_import"=3D>{"holidays_attributes"=3D>{"0"=3D>{"description"=3D>"N=
ew Year's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"1", "day(3i)"=3D>"1"}, "=
1"=3D>{"description"=3D>"St. Patrick's Day", "day(1i)"=3D>"2018", "day(2i)"=
=3D>"3", "day(3i)"=3D>"19"}, "2"=3D>{"description"=3D>"Easter Monday", "day=
(1i)"=3D>"2018", "day(2i)"=3D>"4", "day(3i)"=3D>"2"}, "3"=3D>{"description"=
=3D>"May Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"5", "day(3i)"=3D>"7"}, "4=
"=3D>{"description"=3D>"June Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=
=3D>"6", "day(3i)"=3D>"4"}, "5"=3D>{"description"=3D>"August Bank Holiday",=
 "day(1i)"=3D>"2018", "day(2i)"=3D>"8", "day(3i)"=3D>"6"}, "6"=3D>{"descrip=
tion"=3D>"October Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=3D>"10", "d=
ay(3i)"=3D>"29"}, "7"=3D>{"description"=3D>"Christmas Day", "day(1i)"=3D>"2=
018", "day(2i)"=3D>"12", "day(3i)"=3D>"25"}, "8"=3D>{"description"=3D>"St. =
Stephen's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"12", "day(3i)"=3D>"26"}}=
}, "commit"=3D>"Import"}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=3D>"a203=
42145500de4a07bba4c8ed152cdc", "locale"=3D>"en", "remember_me"=3D>true, "_c=
srf_token"=3D>"AokEexnGhy8///SRLudeXLbgfknj6909gmq7+llfWd4=3D", "user_id"=
=3D>1, "post_redirect_token"=3D>"ifgao9734qgndhczd14", "using_admin"=3D>1, =
"admin_name"=3D>"john_handelaar"}
  * action_dispatch.request_id                     : 34bfd06c-f27c-4fd0-bc3=
4-693bdb8498c2
  * action_dispatch.routes                         : #<ActionDispatch::Rout=
ing::RouteSet:0x0000000384bbf8>
  * action_dispatch.secret_key_base                : this default is insecu=
re as code is open source, please override for live sites in config/general=
; this will do for local development
  * action_dispatch.secret_token                   :=20
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connec=
tion#post_process>
  * async.close                                    : #<EventMachine::Defaul=
tDeferrable:0x00000009cf7fe8>
  * rack.errors                                    : #<IO:0x000000021d4230>
  * rack.input                                     : #<Rack::UTF8Sanitizer:=
:SanitizedRackInput:0x00000009d2d170>
  * rack.multiprocess                              : false
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"_ga"=3D>"GA1.2.49532=
8324.1510530069", "_gid"=3D>"GA1.2.66372717.1510530069", "_wdtk_cookie_sess=
ion"=3D>"cVp2YUVselErWmpxWHhPYi95RHRxa0k0UVNhM1ZDZXFSbysxell3Zk10U2RRREw1d0=
1MV2tpSWhoelQxS2pLL291US9RQXNsVlQ2bEk0c0l6c3VDcTNRd2lOYjdpK2JMNVBIbitwb3JOR=
WxRak5pUkVjSmoyYXRhS2g4MjZpZzRYaWRjZDE3d0lLNXdaMmRPU2dKTFhTUnB1c0F1OWpsck14=
ZVlDeDl6VlRJYi9zZllMY0k4a3lJNmdZT3dvNWdPVmUvSjd0UXdqOGRtR2tHQklTWGdSb0V0NVg=
1d2xwZkFWTk1kWDhiWi9veUUreXZhTTJTZkY2aHU0aUlLUzE3VHBENlJ0eForMTdFVVdRVW1oWS=
taZzUwcENtR2FONmhmMitETnZOVUZ6SStNcFVRZFVOWVBxMTVXMFZDcXF6OFJMWjF2S3pGYXFZW=
lNzem9TSXBCUVVRPT0tLWxtRjQvWVlFKy93QkdxdjNVSUxJQUE9PQ=3D=3D--165537b4ef7ee6=
0e1c7911b4feb26b971b063848"}
  * rack.request.cookie_string                     : _ga=3DGA1.2.495328324.=
1510530069; _gid=3DGA1.2.66372717.1510530069; _wdtk_cookie_session=3DcVp2YU=
VselErWmpxWHhPYi95RHRxa0k0UVNhM1ZDZXFSbysxell3Zk10U2RRREw1d01MV2tpSWhoelQxS=
2pLL291US9RQXNsVlQ2bEk0c0l6c3VDcTNRd2lOYjdpK2JMNVBIbitwb3JORWxRak5pUkVjSmoy=
YXRhS2g4MjZpZzRYaWRjZDE3d0lLNXdaMmRPU2dKTFhTUnB1c0F1OWpsck14ZVlDeDl6VlRJYi9=
zZllMY0k4a3lJNmdZT3dvNWdPVmUvSjd0UXdqOGRtR2tHQklTWGdSb0V0NVg1d2xwZkFWTk1kWD=
hiWi9veUUreXZhTTJTZkY2aHU0aUlLUzE3VHBENlJ0eForMTdFVVdRVW1oWStaZzUwcENtR2FON=
mhmMitETnZOVUZ6SStNcFVRZFVOWVBxMTVXMFZDcXF6OFJMWjF2S3pGYXFZWlNzem9TSXBCUVVR=
PT0tLWxtRjQvWVlFKy93QkdxdjNVSUxJQUE9PQ%3D%3D--165537b4ef7ee60e1c7911b4feb26=
b971b063848
  * rack.request.form_hash                         : {"utf8"=3D>"=E2=9C=93"=
, "authenticity_token"=3D>"AokEexnGhy8///SRLudeXLbgfknj6909gmq7+llfWd4=3D",=
 "holiday_import"=3D>{"holidays_attributes"=3D>{"0"=3D>{"description"=3D>"N=
ew Year's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"1", "day(3i)"=3D>"1"}, "=
1"=3D>{"description"=3D>"St. Patrick's Day", "day(1i)"=3D>"2018", "day(2i)"=
=3D>"3", "day(3i)"=3D>"19"}, "2"=3D>{"description"=3D>"Easter Monday", "day=
(1i)"=3D>"2018", "day(2i)"=3D>"4", "day(3i)"=3D>"2"}, "3"=3D>{"description"=
=3D>"May Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"5", "day(3i)"=3D>"7"}, "4=
"=3D>{"description"=3D>"June Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=
=3D>"6", "day(3i)"=3D>"4"}, "5"=3D>{"description"=3D>"August Bank Holiday",=
 "day(1i)"=3D>"2018", "day(2i)"=3D>"8", "day(3i)"=3D>"6"}, "6"=3D>{"descrip=
tion"=3D>"October Bank Holiday", "day(1i)"=3D>"2018", "day(2i)"=3D>"10", "d=
ay(3i)"=3D>"29"}, "7"=3D>{"description"=3D>"Christmas Day", "day(1i)"=3D>"2=
018", "day(2i)"=3D>"12", "day(3i)"=3D>"25"}, "8"=3D>{"description"=3D>"St. =
Stephen's Day", "day(1i)"=3D>"2018", "day(2i)"=3D>"12", "day(3i)"=3D>"26"}}=
}, "commit"=3D>"Import"}
  * rack.request.form_input                        : #<Rack::UTF8Sanitizer:=
:SanitizedRackInput:0x00000009d2d170>
  * rack.request.form_vars                         : [FILTERED]
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :=20
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Requ=
est::Session:0x000000070087d0>
  * rack.session.options                           : #<ActionDispatch::Requ=
est::Session::Options:0x00000007008348>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]

-------------------------------
Backtrace:
-------------------------------

  app/models/holiday_import.rb:50:in `block in holidays_attributes=3D'
  app/models/holiday_import.rb:50:in `holidays_attributes=3D'
  app/models/holiday_import.rb:29:in `initialize'
  app/controllers/admin_holiday_imports_controller.rb:10:in `new'
  app/controllers/admin_holiday_imports_controller.rb:10:in `create'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gavinrozzi** [comment]
I have been getting the same error when I try to add the suggested holidays.

**Comment by handelaar** [comment]
(Prob may be that '=' is being converted to '=3D' in a way that it should not in this context)

**Comment by lizconlan** [comment]
Hmm, looks like creating holidays one by one is fine but the feed import is broken

**Comment by lizconlan** [comment]
(that's an observation/temporary workaround rather than a suggested solution BTW!)

**Comment by lizconlan** [comment]
The blocking error is `ActiveModel::ForbiddenAttributesError` around mass assignments

**Comment by handelaar** [comment]
(Fwiw feed import also fails if you remove all but one item from the suggested list of dates to import)

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/4417

**Comment by lizconlan** [comment]
Hi @handelaar - if you redeploy with hotfix/0.30.0.2, (or the latest version in master which adds new translations as well) this should be working again!

**Comment by handelaar** [comment]
Indeed it is :)

**Comment by lizconlan** [comment]
\*phew\* thanks for confirming - and sorry for breaking it!
