### ISSUE TITLE
[ERROR] user#signup (NoMethodError) "undefined method `reason_params' for nil:NilClass" 

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4378]
This appears to be an attempted spam attack to signup users with [random-number]@yahoo.com, we've suddenly started getting quite a lot of them (from around 8 Nov). This feels to me like an automated process.

The IP address varies but I suspect it's a single origin.

```
A NoMethodError occurred in user#signup:

  undefined method `reason_params' for nil:NilClass
  app/controllers/user_controller.rb:158:in `signup'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/profile/sign_up
  * HTTP Method: POST
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"&#x2713;", "authenticity_token"=>"", "user_signup"=>{"name"=>"", "email"=>"74988@yahoo.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "g-recaptcha-response"=>"", "token"=>"m8otwygcjj1d2ks7y0c", "modal"=>"", "commit"=>"Sign up", "controller"=>"user", "action"=>"signup"}
  * Timestamp  : 2017-11-08 07:09:27 +0000
  * Process: 19155

-------------------------------
Backtrace:
-------------------------------

  app/controllers/user_controller.rb:158:in `signup'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
This shouldn't be an issue anymore since #4360 was merged with commit e513a67. Indeed there haven't been anymore similar errors since yesterday's deploy.

Closing.
