### ISSUE TITLE
[ERROR] request#show (NoMethodError) "undefined method `is_pro?' for nil:NilClass\nDid you mean...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4404]
```
A NoMethodError occurred in request#show:

  undefined method `is_pro?' for nil:NilClass
Did you mean?  is_a?
  app/models/ability.rb:77:in `block in initialize'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/homeless_stats_7
  * HTTP Method: GET
  * IP address : [FILTERED]
  * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"homeless_stats_7"}
  * Timestamp  : 2017-11-29 15:56:46 +0000
  * Rails root : [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55
  * Process: 15625

-------------------------------
Backtrace:
-------------------------------

  app/models/ability.rb:77:in `block in initialize'
  lib/themes/whatdotheyknow-theme/lib/views/request/_sidebar.html.erb:12:in `_lib_themes_whatdotheyknow_theme_lib_views_request__sidebar_html_erb___81792862452503128_70023289000160'
  lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:115:in `_lib_themes_whatdotheyknow_theme_lib_views_request_show_html_erb___1407790278222032256_70023434871540'
  app/controllers/request_controller.rb:133:in `block (3 levels) in show'
  app/controllers/request_controller.rb:132:in `block in show'
  lib/alaveteli_localization.rb:43:in `with_locale'
  app/controllers/request_controller.rb:83:in `show'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Looks like we're passing the anonymous user (from foi-register) to some ability check.

**Comment by garethrees** [comment]
Keep getting these – generally a trickle, but sometimes a user will refresh the page a lot and we'll get a bunch in one go.
