### ISSUE TITLE
[ERROR] A RuntimeError occurred in request#show:   main body text more than 1 MB

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#4412]
A user has been unable to view an authority's response to a request. I have been unable to view it myself either. The request is https://opramachine.com/request/opra_requests_5 and is the first time we have experienced this issue.

Here is the full text of the error:

```
A RuntimeError occurred in request#show:

 main body text more than 1 MB, need to implement clipping like for attachment text, or there is some other MIME decoding problem or similar
 app/models/incoming_message.rb:426:in `_cache_main_body_text'


-------------------------------
Request:
-------------------------------

 * URL        : https://opramachine.com/request/opra_requests_5
 * HTTP Method: GET
 * IP address : [redacted]
 * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"opra_requests_5"}
 * Timestamp  : 2017-12-04 05:27:35 -0500
 * Server : opramachine.com
 * Rails root : /var/www/opramachine.com/alaveteli
 * Process: 3615

-------------------------------
Session:
-------------------------------

 * session id: [FILTERED]
 * data: {"session_id"=>"287421f075096dbf1e88a3aeaa73ba41", "locale"=>"en"}

-------------------------------
Environment:
-------------------------------

 * GATEWAY_INTERFACE                              : CGI/1.2
 * HTTP_ACCEPT                                    : */*
 * HTTP_ACCEPT_ENCODING                           : gzip
 * HTTP_CONNECTION                                : close
 * HTTP_HOST                                      : opramachine.com
 * HTTP_USER_AGENT                                : Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)
 * HTTP_VERSION                                   : HTTP/1.0
 * HTTP_X_ACCEL_MAPPING                           : /var/www/opramachine.com/alaveteli/cache/zips/production/download=/download
 * HTTP_X_FORWARDED_FOR                           : [redacted]
 * HTTP_X_FORWARDED_PROTO                         : https
 * HTTP_X_REAL_IP                                 : [redacted]
 * HTTP_X_SENDFILE_TYPE                           : X-Accel-Redirect
 * ORIGINAL_FULLPATH                              : /request/opra_requests_5
 * ORIGINAL_SCRIPT_NAME                           : 
 * PATH_INFO                                      : /request/opra_requests_5
 * QUERY_STRING                                   : 
 * REMOTE_ADDR                                    : 127.0.0.1
 * REQUEST_METHOD                                 : GET
 * REQUEST_PATH                                   : /request/opra_requests_5
 * REQUEST_URI                                    : /request/opra_requests_5
 * ROUTES_41371200_SCRIPT_NAME                    : 
 * SCRIPT_NAME                                    : 
 * SERVER_NAME                                    : opramachine.com
 * SERVER_PORT                                    : 80
 * SERVER_PROTOCOL                                : HTTP/1.1
 * SERVER_SOFTWARE                                : thin 1.5.1 codename Straight Razor
 * action_controller.instance                     : #<RequestController:0x00000009cd77c0>
 * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0000000911dd30>
 * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00000009ccc618>
 * action_dispatch.cookies_digest                 : 
 * action_dispatch.cookies_serializer             : hybrid
 * action_dispatch.encrypted_cookie_salt          : encrypted cookie
 * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
 * action_dispatch.http_auth_salt                 : http authentication
 * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x00000007e49d80>
 * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000004de1c88>
 * action_dispatch.parameter_filter               : [:password]
 * action_dispatch.redirect_filter                : []
 * action_dispatch.remote_ip                      : [redacted]
 * action_dispatch.request.accepts                : [#<Mime::Type:0x00000009cd40e8 @synonyms=[], @symbol=nil, @string="*/*", @hash=-3464415217138319891>]
 * action_dispatch.request.content_type           : 
 * action_dispatch.request.flash_hash             : #<ActionDispatch::Flash::FlashHash:0x0000000e9511a0>
 * action_dispatch.request.formats                : [#<Mime::Type:0x00000009cd40e8 @synonyms=[], @symbol=nil, @string="*/*", @hash=-3464415217138319891>]
 * action_dispatch.request.parameters             : {"controller"=>"request", "action"=>"show", "url_title"=>"opra_requests_5"}
 * action_dispatch.request.path_parameters        : {:controller=>"request", :action=>"show", :url_title=>"opra_requests_5"}
 * action_dispatch.request.query_parameters       : {}
 * action_dispatch.request.request_parameters     : {}
 * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"287421f075096dbf1e88a3aeaa73ba41"}
 * action_dispatch.request_id                     : 2fc27f0e-ab53-4459-a2ab-48acca636868
 * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000004ee8c80>
 * action_dispatch.secret_key_base                : this default is insecure as code is open source, please override for live sites in config/general; this will do for local development
 * action_dispatch.secret_token                   : 
 * action_dispatch.show_detailed_exceptions       : false
 * action_dispatch.show_exceptions                : true
 * action_dispatch.signed_cookie_salt             : signed cookie
 * async.callback                                 : #<Method: Thin::Connection#post_process>
 * async.close                                    : #<EventMachine::DefaultDeferrable:0x0000000be44818>
 * newrelic.transaction_started                   : true
 * rack.errors                                    : #<IO:0x000000008ddba0>
 * rack.input                                     : #<StringIO:0x0000000be45970>
 * rack.multiprocess                              : false
 * rack.multithread                               : false
 * rack.request.cookie_hash                       : {}
 * rack.request.query_hash                        : {}
 * rack.request.query_string                      : 
 * rack.run_once                                  : false
 * rack.session                                   : #<ActionDispatch::Request::Session:0x0000000a2bfb88>
 * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x0000000a2bfac0>
 * rack.url_scheme                                : http
 * rack.version                                   : [1, 0]

-------------------------------
Backtrace:
-------------------------------

 app/models/incoming_message.rb:426:in `_cache_main_body_text'
 app/models/incoming_message.rb:452:in `get_main_body_text_unfolded'
 app/models/incoming_message.rb:616:in `get_body_for_html_display'
 app/views/request/_incoming_correspondence.html.erb:24:in `_app_views_request__incoming_correspondence_html_erb__3546678720284831302_105676420'
 app/views/request/_correspondence.html.erb:4:in `_app_views_request__correspondence_html_erb___4066288440436047912_101050920'
 app/views/request/show.html.erb:68:in `block in _app_views_request_show_html_erb__3731061642019055843_100407660'
 app/views/request/show.html.erb:66:in `_app_views_request_show_html_erb__3731061642019055843_100407660'
 app/controllers/request_controller.rb:133:in `block (3 levels) in show'
 app/controllers/request_controller.rb:132:in `block in show'
 lib/alaveteli_localization.rb:43:in `with_locale'
 app/controllers/request_controller.rb:89:in `show'
 app/controllers/application_controller.rb:120:in `record_memory'
 lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gavinrozzi** [comment]
Cc @aliteralmind

**Comment by garethrees** [comment]
Hey @gavinrozzi.

This one is a bit tricky to debug without the actual email.

Could you download the raw email through the admin interface and send it over to clientsupport [at] alaveteli [dot] org? I can then import it locally and investigate.

**Comment by garethrees** [comment]
Been seeing quite a few of these recently.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
