### ISSUE TITLE
[ERROR] stats:show (PG::UndefinedTable): ERROR:  missing FROM-clause entry for table "info_requests"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4420]
```
$ bundle exec rake stats:show START_YEAR=2017 START_MONTH=1
Period  Requests sent   Pro requests sent       Visible comments        Track this request email signups        Comments on own requests        Follow up messages sent Confirmed users Confirmed pro users     Request classifications Public body change requests     Widget votes    Total tracks
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "info_requests"
LINE 1: ...OUNT(*) FROM "comments" WHERE (comments.user_id = info_reque...
                                                             ^
: SELECT COUNT(*) FROM "comments" WHERE (comments.user_id = info_requests.user_id
                                            AND comments.created_at >= '2017-01-01'
                                            AND comments.created_at < '2017-02-01')
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:270:in `execute_simple_calculation'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:133:in `calculate'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_record_helper.rb:70:in `block in calculate'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:586:in `with_database_metric_name'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_record_helper.rb:69:in `calculate'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:48:in `count'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/lib/tasks/stats.rake:65:in `block (3 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/lib/tasks/stats.rake:30:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/lib/tasks/stats.rake:30:in `block (2 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/opt/rbenv/versions/2.3.5/bin/bundle:22:in `load'
/opt/rbenv/versions/2.3.5/bin/bundle:22:in `<main>'
PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "info_requests"
LINE 1: ...OUNT(*) FROM "comments" WHERE (comments.user_id = info_reque...
                                                             ^
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:270:in `execute_simple_calculation'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:133:in `calculate'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_record_helper.rb:70:in `block in calculate'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:586:in `with_database_metric_name'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_record_helper.rb:69:in `calculate'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/calculations.rb:48:in `count'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/lib/tasks/stats.rake:65:in `block (3 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/lib/tasks/stats.rake:30:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/lib/tasks/stats.rake:30:in `block (2 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-11-28T15-06-55/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/opt/rbenv/versions/2.3.5/bin/bundle:22:in `load'
/opt/rbenv/versions/2.3.5/bin/bundle:22:in `<main>'
Tasks: TOP => stats:show
(See full trace by running task with --trace)
```

**Comment by lizconlan** [comment]
looks like it's just missing `references(:info_request)`
