### ISSUE TITLE
[ERROR] statistics#index (Math::DomainError) "Numerical argument is out of domain - \"sqrt\""

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#4433]
The public authority statistics page is broken for us and we have begun receiving this error as of Wednesday:

```
A Math::DomainError occurred in statistics#index:

 Numerical argument is out of domain - "sqrt"
 lib/confidence_intervals.rb:28:in `sqrt'


-------------------------------
Request:
-------------------------------

 * URL        : https://opramachine.com/statistics
 * HTTP Method: GET
 * IP address : [FILTERED]
 * Parameters : {"controller"=>"statistics", "action"=>"index"}
 * Timestamp  : 2017-12-20 21:55:36 -0500
 * Server : opramachine.com
 * Rails root : [FILTERED]/opramachine.com/alaveteli
 * Process: 23591

-------------------------------
Backtrace:
-------------------------------

 lib/confidence_intervals.rb:28:in `sqrt'
 lib/confidence_intervals.rb:28:in `ci_bounds'
 app/models/public_body.rb:722:in `block in get_request_percentages'
 app/models/public_body.rb:721:in `each'
 app/models/public_body.rb:721:in `each_with_index'
 app/models/public_body.rb:721:in `each'
 app/models/public_body.rb:721:in `map'
 app/models/public_body.rb:721:in `get_request_percentages'
 app/models/statistics.rb:49:in `block (2 levels) in public_bodies'
 app/models/statistics.rb:43:in `each'
 app/models/statistics.rb:43:in `block in public_bodies'
 app/models/statistics.rb:42:in `each'
 app/models/statistics.rb:42:in `public_bodies'
 app/controllers/statistics_controller.rb:7:in `index'
 app/controllers/application_controller.rb:120:in `record_memory'
 lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
this might be as "simple" a fix as requiring 'mathn' http://ruby-doc.org/stdlib-2.1.5/libdoc/mathn/rdoc/Math.html

(although my lazy reading of this implies we're asking for the square root of a negative number so it might be worth having a dig into what's happening here)

**Comment by gavinrozzi** [comment]
Just checked the statistics page and strangely enough this error is no longer occurring on https://opramachine.com/statistics#public_bodies No changes have been made to the site since the creation of this issue.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
