### ISSUE TITLE
[ERROR] request#similar (ArgumentError) "Wrong arguments for overloaded method 'Enquire.mset'.\...

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4447]
Appears to have been triggered by Bing crawling the site. Might be related to #420 (caused by  passing page=0 in the URL)

```
An ArgumentError occurred in request#similar:

  Wrong arguments for overloaded method 'Enquire.mset'.
Possible C/C++ prototypes are:
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems, Xapian::doccount checkatleast, Xapian::RSet const *omrset, Xapian::MatchDecider const *mdecider, Xapian::MatchDecider const *matchspy)
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems, Xapian::doccount checkatleast, Xapian::RSet const *omrset, Xapian::MatchDecider const *mdecider)
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems, Xapian::doccount checkatleast, Xapian::RSet const *omrset)
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems, Xapian::doccount checkatleast)
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems)
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems, Xapian::RSet const *omrset, Xapian::MatchDecider const *mdecider)
    Xapian::MSet Enquire.mset(Xapian::doccount first, Xapian::doccount maxitems, Xapian::RSet const *omrset)

  lib/acts_as_xapian/acts_as_xapian.rb:326:in `mset'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/similar/request/park_and_ride_3?page=0
  * HTTP Method: GET
  * IP address : [FILTERED]
  * Parameters : {"page"=>"0", "controller"=>"request", "action"=>"similar", "url_title"=>"park_and_ride_3"}
  * Timestamp  : 2018-01-03 01:30:55 +0000
  * Rails root : [FILTERED]/www.whatdotheyknow.com/alaveteli-2017-12-20T16-14-18
  * Process: 24127

-------------------------------
Environment:
-------------------------------

  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip
  * HTTP_FROM                                      : bingbot(at)microsoft.com

-------------------------------
Backtrace:
-------------------------------

  lib/acts_as_xapian/acts_as_xapian.rb:326:in `mset'
  lib/acts_as_xapian/acts_as_xapian.rb:326:in `block in initialize_query'
  lib/acts_as_xapian/acts_as_xapian.rb:297:in `initialize_query'
  lib/acts_as_xapian/acts_as_xapian.rb:597:in `initialize'
  app/controllers/request_controller.rb:169:in `new'
  app/controllers/request_controller.rb:169:in `similar'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Had another of these today

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
