### ISSUE TITLE
[ERROR] request#new (ActionView::Template::Error) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4479]
Similar to https://github.com/mysociety/alaveteli/issues/4319.

An instance of https://github.com/mysociety/alaveteli/issues/4484.

```
An ActionView::Template::Error occurred in request#new:

  undefined method `[]' for nil:NilClass
  app/views/general/_locale_switcher.html.erb:1:in `_app_views_general__locale_switcher_html_erb__3963037750594685524_70031215677200'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new
  * HTTP Method: POST
  * IP address : REDACTED
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "info_request"=>{"title"=>"", "public_body_id"=>"1611"}, "outgoing_message"=>{"body"=>"Dear Network Rail Limited,\r\n\r\nI would like to request information as to the name of every railway tunnel upon the Calder Valley Line that runs between Leeds & Manchester Victoria.\r\n\r\nYours faithfully,\r\nMBradley\r\n"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Preview your public request", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2018-01-24 12:45:19 +0000

-------------------------------
Backtrace:
-------------------------------

  app/views/general/_locale_switcher.html.erb:1:in `_app_views_general__locale_switcher_html_erb__3963037750594685524_70031215677200'
  app/views/general/_responsive_header.html.erb:16:in `_app_views_general__responsive_header_html_erb__2195614607868482890_70031093800740'
  app/views/layouts/default.html.erb:74:in `_app_views_layouts_default_html_erb___1462981884040226555_70031191442460'
  app/controllers/application_controller.rb:197:in `block (2 levels) in render_exception'
  app/controllers/application_controller.rb:196:in `render_exception'
  lib/strip_empty_sessions.rb:13:in `call'

```

**Comment by garethrees** [comment]
Here's how I think this is happening:

* Signed out user starts writing a request
* They sign in in a new tab
* They then submit the request (for preview)

The form wouldn't have had an authenticity token initially, but the receiving action _will_ try to verify it now there's a user.

**Comment by garethrees** [comment]
The related `InvalidAuthenticityToken` error:

```
An ActionController::InvalidAuthenticityToken occurred in request#new:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new
  * HTTP Method: POST
  * IP address : 80.1.120.20
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "info_request"=>{"title"=>"", "public_body_id"=>"1611"}, "outgoing_message"=>{"body"=>"Dear Network Rail Limited,\r\n\r\nI would like to request information as to the name of every railway tunnel upon the Calder Valley Line that runs between Leeds & Manchester Victoria.\r\n\r\nYours faithfully,\r\nMBradley\r\n"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Preview your public request", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2018-01-24 12:45:19 +0000


-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"[FILTERED]",
   "locale"=>"en",
   "remember_me"=>false,
   "_csrf_token"=>"4HRhUlo+np3Lyu6ge5SRUu1eUH/U9c9K/NccxByzyek=",
   "user_id"=>95713,
   "ttl"=>"2018-01-24T12:45:18.511+00:00",
   "post_redirect_token"=>"7tg5296uto8k6le9jn8"}

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'

```

**Comment by garethrees** [comment]
More recent backtrace:

```
-------------------------------
Backtrace:
-------------------------------

app/views/general/_locale_switcher.html.erb:2:in `_app_views_general__locale_switcher_html_erb__4209333805987675435_70106659167140'
app/views/general/_responsive_header.html.erb:16:in `_app_views_general__responsive_header_html_erb__3461969133566255974_70106527582900'
app/views/layouts/default.html.erb:60:in `_app_views_layouts_default_html_erb___2738229643753278196_70106653710040'
app/controllers/application_controller.rb:192:in `block (2 levels) in render_exception'
app/controllers/application_controller.rb:191:in `render_exception'
lib/strip_empty_sessions.rb:13:in `call'
```
