### ISSUE TITLE
[ERROR] admin_public_body#import_csv (CSV::MalformedCSVError) "Unclosed quoted field on line 2....

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4483]
This happens when an admin tries to upload a badly formatted CSV file. In this case it was tab rather than comma separated (this one has been fixed). The admin the gets a generic error message which is not ideal.

> Sorry, there was a problem processing this page
> 
> You have found a bug. Please contact us to tell us about the problem

```
A CSV::MalformedCSVError occurred in admin_public_body#import_csv:

  Unclosed quoted field on line 2.
  app/models/public_body.rb:459:in `block in import_csv_from_file'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/bodies/import_csv
  * HTTP Method: POST
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "csv_file"=>#<ActionDispatch::Http::UploadedFile:0x00007f38ed5ad5c0 @tempfile=#<Tempfile:/tmp/RackMultipart20180125-5175-1v1nrh6.csv>, @original_filename="Copy of Primaries 5.csv", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"csv_file\"; filename=\"Copy of Primaries 5.csv\"\r\nContent-Type: application/vnd.ms-excel\r\n">, "tag"=>"", "tag_behaviour"=>"add", "commit"=>"Upload", "controller"=>"admin_public_body", "action"=>"import_csv"}
  * Timestamp  : 2018-01-25 18:37:07 +0000

-------------------------------
Backtrace:
-------------------------------

  app/models/public_body.rb:459:in `block in import_csv_from_file'
  app/models/public_body.rb:427:in `import_csv_from_file'
  app/models/public_body.rb:416:in `import_csv'
  app/controllers/admin_public_body_controller.rb:178:in `import_csv'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Related to #2109

**Comment by garethrees** [comment]
Had another similar case:

```
A CSV::MalformedCSVError occurred in admin_public_body#import_csv:

Any value after quoted field isn't allowed in line 2.
app/models/public_body.rb:491:in `block in import_csv_from_file'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/bodies/import_csv
* HTTP Method: POST
* IP address : REDACTED
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"REDACTED", "csv_file"=>#<ActionDispatch::Http::UploadedFile:0x00007f79a8a11bb0 @tempfile=#<Tempfile:/tmp/RackMultipart20210613-5316-os3n8r.csv>, @original_filename="Copy of Wales Secondary Schools Gaps - Sheet1.csv", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"csv_file\"; filename=\"Copy of Wales Secondary Schools Gaps - Sheet1.csv\"\r\nContent-Type: application/vnd.ms-excel\r\n">, "tag"=>"", "tag_behaviour"=>"replace", "commit"=>"Dry run", "controller"=>"admin_public_body", "action"=>"import_csv"}
* Timestamp : 2021-06-13 20:12:51 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>true,
"user_id"=>184915,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED",
"using_admin"=>1,
"admin_name"=>"REDACTED",
"user_circumstance"=>"normal"}

-------------------------------
Backtrace:
-------------------------------

app/models/public_body.rb:491:in `block in import_csv_from_file'
app/models/public_body.rb:459:in `import_csv_from_file'
app/models/public_body.rb:448:in `import_csv'
app/controllers/admin_public_body_controller.rb:184:in `import_csv'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
