### ISSUE TITLE
[ERROR] announcements#destroy (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4495]
```
An ActionController::InvalidAuthenticityToken occurred in announcements#destroy:

ActionController::InvalidAuthenticityToken
lib/strip_empty_sessions.rb:13:in `call'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/announcements/1
* HTTP Method: DELETE
* Parameters : {"controller"=>"announcements", "action"=>"destroy", "id"=>"1"}
* Timestamp : 2018-01-31 19:22:13 +0000

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"en",
"user_id"=>151713,
"user_circumstance"=>"normal",
"post_redirect_token"=>"mkwbhlvr5yn21c123bx",
"ttl"=>"2018-01-31T19:18:22.287+00:00",
"_csrf_token"=>"rQdxPreNFPi648faghyzyHqTWiX3SOpVz+FILTERED="}

-------------------------------
Backtrace:
-------------------------------

lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Related to #4484

**Comment by garethrees** [comment]
Had a couple of these between deployment and this morning.

**Comment by garethrees** [comment]
I just replicated this.

* Open app in tab; **sign out**.
* Open app in another tab; **sign in**.
* Go back to first tab; **close announcement**.
* _The announcement gets cleared._
* _We receive an exception notification._
* **Sign out**.
* _The announcement re-appears._
