### ISSUE TITLE
[ERROR] password_changes#create (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4496]
```
An ActionController::InvalidAuthenticityToken occurred in password_changes#create:

ActionController::InvalidAuthenticityToken
lib/strip_empty_sessions.rb:13:in `call'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/change_password
* HTTP Method: POST
* IP address : FILTERED
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "password_change_user"=>"[FILTERED]", "pretoken"=>"b6pu7xauyb6br7iixxb", "commit"=>"Send me the email", "controller"=>"password_changes", "action"=>"create"}
* Timestamp : 2018-01-30 18:04:25 +0000

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"en",
"user_id"=>151302,
"ttl"=>"2018-01-30T08:41:43.766+00:00",
"remember_me"=>false,
"post_redirect_token"=>"c7h0rg2nm178raszgzp",
"_csrf_token"=>"1EQh4QMaa8slP41ePeXkTQWLlxDrHoFILTERED="}

-------------------------------
Backtrace:
-------------------------------

lib/strip_empty_sessions.rb:13:in `call'

```

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/4484.
