### ISSUE TITLE
[ERROR] info_requests#preview (NoMethodError) "undefined method `title' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4497]
```
A NoMethodError occurred in info_requests#preview:

undefined method `title' for nil:NilClass
app/models/info_request.rb:1079:in `from_draft'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/info_requests/new/preview?post_redirect=1
* HTTP Method: GET
* IP address : FILTERED
* Parameters : {"post_redirect"=>"1", "controller"=>"alaveteli_pro/info_requests", "action"=>"preview"}
* Timestamp : 2018-01-30 12:36:49 +0000

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"en",
"user_id"=>134426,
"ttl"=>"2018-01-30T12:36:49.703+00:00",
"remember_me"=>false,
"post_redirect_token"=>"FILTERED"}

-------------------------------
Backtrace:
-------------------------------

app/models/info_request.rb:1079:in `from_draft'
app/controllers/alaveteli_pro/info_requests_controller.rb:98:in `load_data_from_draft'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Another one of these today

**Comment by gbp** [comment]
Seeing these on EU

**Comment by gbp** [comment]
Updated backtrace:

```
-------------------------------
Backtrace:
-------------------------------

  app/models/info_request.rb:451:in `from_draft'
  app/controllers/alaveteli_pro/info_requests_controller.rb:87:in `load_data_from_draft'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:14:in `call'
```
