### ISSUE TITLE
[ERROR] followups#preview (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4501]
```
An ActionController::InvalidAuthenticityToken occurred in followups#preview:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/448529/followups/preview?incoming_message_id=1099830
  * HTTP Method: POST
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"FILTERED", "outgoing_message"=>{"body"=>"Dear HMCTS Wales KILO,\r\n\r\nThanks for your response from 22.01.2018.\r\nIt appears you have misunderstood – the files/papers went from the Tribunal to Swansea Family Court. It is in the latter court where papers/files have, apparently, gone missing. It is therefore in Swansea where the information lies in order for you to provide the information first requested viz\r\n\r\n1. The guidance on handling case transfers from another court.\r\n\r\n2. The procedures/policies put in place [and any subsequent review of effectiveness] following my raising of the loss of court bundles [including private, personal and sensitive information/data] with the then HMCS Mid and West Wales Board on 26.09.2008 [open meeting] – as recorded in the minutes;\r\n\r\nThe delay in Swansea has permitted the Mother to [again] make false stalking/harassment allegations presumably for obtaining legal aid or other advantage. She will [again] presumably withdraw the allegations once court proceedings are underway at no cost to herself.\r\n\r\nThe apparent delay in finding the files does not benefit the child/children.\r\n\r\nYours sincerely,\r\n\r\nGwynne Davies", "what_doing"=>"normal_sort"}, "submitted_followup"=>"1", "commit"=>"Preview your message", "incoming_message_id"=>"1099830", "controller"=>"followups", "action"=>"preview", "request_id"=>"448529"}
  * Timestamp  : 2018-02-03 12:35:52 +0000

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"FILTERED",
   "locale"=>"en",
   "user_id"=>130611,
   "ttl"=>"2018-02-03T12:35:49.044+00:00",
   "remember_me"=>false,
   "post_redirect_token"=>"i6uxfhypla2g0oneu5m",
   "_csrf_token"=>"GK2xVxSnEth2c74HNiOjNs8Aj3c1nuJlGWEfZ2xQGPg="}

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Related to #4484

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
