### ISSUE TITLE
[ERROR] request#new (ActionController::InvalidAuthenticityToken) 

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4502]
```
An ActionController::InvalidAuthenticityToken occurred in request#new:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new
  * HTTP Method: POST
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "info_request"=>{"title"=>"Email list for UK primary schools and nurseries. ", "public_body_id"=>"6009"}, "outgoing_message"=>{"body"=>"Dear Department for Education,\r\n\r\nPlease can you provide me with an up to date list of all primary schools and nurseries in the UK with their email addresses and in which local authority they reside in?  This would be appreciated on an excel/speadsheet document. \r\nThank you \r\n\r\nYours faithfully,\r\n\r\nFiona Green"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Preview your public request", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2018-02-03 14:41:57 +0000

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"FILTERED",
   "locale"=>"en",
   "user_id"=>151905,
   "user_circumstance"=>"normal",
   "post_redirect_token"=>"ffs47gy3p64lgbdk87s",
   "ttl"=>"2018-02-03T14:41:55.894+00:00",
   "_csrf_token"=>"sB1AlugISGPucARqenJ2ijE1IxHjikHdPATcLrUkQeI="}

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Related to #4484

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
