### ISSUE TITLE
[ERROR] [www.whatdotheyknow.com] password_changes#update (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4503]
```
An ActionController::InvalidAuthenticityToken occurred in password_changes#update:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/profile/change_password/k5kp4x8gekowudr1pri
  * HTTP Method: PUT
  * Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"", "password_change_user"=>"[FILTERED]", "pretoken"=>"btqt7dndbhro1z3ksah", "commit"=>"Change your password on WhatDoTheyKnow", "controller"=>"password_changes", "action"=>"update", "id"=>"k5kp4x8gekowudr1pri"}
  * Timestamp  : 2018-02-04 20:59:15 +0000

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"FILTERED",
   "locale"=>"en",
   "remember_me"=>false,
   "user_id"=>112473,
   "ttl"=>"2018-02-04T20:59:13.990+00:00",
   "flash"=>
    {"discard"=>[], "flashes"=>{"notice"=>"Your password has been changed."}}}

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Related to #4484

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
