### ISSUE TITLE
[ERROR] user#set_receive_email_alerts (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4519]
Related to #4484.

The POST parameters _do_ have an authenticity token, so it must have expired by the time the user posted the form?

```
An ActionController::InvalidAuthenticityToken occurred in user#set_receive_email_alerts:

ActionController::InvalidAuthenticityToken
lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/profile/set_receive_alerts
* HTTP Method: POST
* IP address : FILTERED
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"6eEI2oMJR2ng4SGW2dvZPZxusOPLkPHtFDpUlFxjeNM=", "receive_email_alerts"=>"false", "came_from"=>"https://transparencia.be/user/bareyt?post_redirect=1", "commit"=>"Désactiver les alertes email", "controller"=>"user", "action"=>"set_receive_email_alerts"}
* Timestamp : 2018-02-11 10:04:47 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"fr_BE",
"user_id"=>440,
"user_circumstance"=>"normal",
"post_redirect_token"=>"g62xberjl7mj5tfht2d",
"ttl"=>"2018-02-11T10:04:17.087+01:00",

-------------------------------
Backtrace:
-------------------------------

lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
