### ISSUE TITLE
[ERROR] Net::ReadTimeout in POP Poller

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4526]
We had a similar error in https://github.com/mysociety/alaveteli/issues/4221, so we fixed in https://github.com/mysociety/alaveteli/pull/4392.

This error is actually happening in the [`ensure` section of `#start`](https://github.com/mysociety/alaveteli/blob/b0c7626/lib/alaveteli_mail_poller.rb#L122) (Line 122):

```ruby
  rescue Timeout::Error => error
    if send_exception_notifications?
      ExceptionNotifier.notify_exception(error)
    end
  ensure
    if defined?(pop3) && pop3 && pop3.started?
      pop3.finish # <--- Net::ReadTimeout raised here
    end
  end
```

```
/opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/protocol.rb:154:in `readuntil'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/protocol.rb:164:in `readline'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:997:in `recv_response'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:993:in `get_response'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:981:in `block in quit'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:1013:in `critical'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:981:in `quit'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:600:in `do_finish'
        from /opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:588:in `finish'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/lib/alaveteli_mail_poller.rb:122:in `start'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `eval'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-02-08T17-05-18/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

**Comment by garethrees** [comment]
We've completed the migration to maildir format in https://github.com/mysociety/sysadmin/issues/1036#issuecomment-443684254, so moving this to review whether we still get these errors over the next week or two.

**Comment by garethrees** [comment]
None of these since last week when we changed to maildir. Thanks @sagepe!
