### ISSUE TITLE
[ERROR] request#describe_state (ActionController::InvalidAuthenticityToken) 

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4539]
There is an authenticity token here so ... expired?

```
An ActionController::InvalidAuthenticityToken occurred in request#describe_state:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/464920/describe
  * HTTP Method: PATCH
  * Parameters : {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"t2Z5QCdSMVwJxgNpw8ymxrXCK5mW8XA0FbsDICMlggg=", "incoming_message"=>{"described_state"=>"waiting_response"}, "last_info_request_event_id"=>"2752137", "commit"=>"Submit status", "controller"=>"request", "action"=>"describe_state", "id"=>"464920"}
  * Timestamp  : 2018-03-05 10:08:31 +0000

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"FILTERED",
   "locale"=>"en",
   "user_id"=>41400,
   "ttl"=>"2018-03-05T10:08:19.655+00:00",
   "remember_me"=>false,
   "post_redirect_token"=>"kon7cdmz2t2a7xmy728",
   "_csrf_token"=>"ipDlB7vwqCmbzJeZBkaIPQH60s/hPa+sojYCvZOxJ4g="}

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'

```

Related to #4484

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
