### ISSUE TITLE
[ERROR] comment#new (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4546]
There is an authenticity token here so ... expired?

```
An ActionController::InvalidAuthenticityToken occurred in comment#new:

  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/annotate/request/universal_credit_programme_proje
  * HTTP Method: POST
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"mzjCT45TYIym79KGwAueOk8YLgdzovjtF6ryWoD/DBg=", "comment"=>{"body"=>"I'm not sure whether this is the correct thread but I spot from the papers that congratulations are in order..."}, "subscribe_to_request"=>"1", "submitted_comment"=>"1", "preview"=>"0", "submit"=>"Post annotation", "type"=>"request", "controller"=>"comment", "action"=>"new", "url_title"=>"universal_credit_programme_proje"}
  * Timestamp  : 2018-03-09 09:38:35 +0000

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"FILTERED",
   "locale"=>"en",
   "user_id"=>41400,
   "ttl"=>"2018-03-09T09:35:48.204+00:00",
   "remember_me"=>false,
   "post_redirect_token"=>"9tu5zegz3xbc7tq6por",
   "_csrf_token"=>"hJYUArTEmZJNOWbEkiqgvM17M1zU0Z3S51tUZFcCu7Y=",
   "flash"=>
    {"discard"=>[],
     "flashes"=>{"search_params"=>{"query"=>"NHS England", "bodies"=>"1"}}}}

-------------------------------
Backtrace:
-------------------------------

  lib/strip_empty_sessions.rb:13:in `call'
```

Related to #4484

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
