### ISSUE TITLE
PublicBody.with_tag transient spec failure

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4631]
```
Failures:
  1) PublicBody.with_tag should returns all authorities
     Failure/Error:
       expect(pbs).to eq([
         public_bodies(:geraldine_public_body),
         public_bodies(:humpadink_public_body),
         public_bodies(:forlorn_public_body),
         public_bodies(:silly_walks_public_body),
         public_bodies(:sensible_walks_public_body),
         public_bodies(:other_public_body)
       ])
       expected: [#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid...quests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
            got: #<ActiveRecord::Relation [#<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comm...uests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>]>
       (compared using ==)
       Diff:
       @@ -1,7 +1,98 @@
       -[#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid quango.", created_at: "2007-10-24 10:51:01", updated_at: "2018-04-25 12:08:48", home_page: nil, api_key: "1", info_requests_count: 4, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>,
       - #<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comment: "Not sure what this new department does.", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "2", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 1, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 4, version: 1, last_edit_editor: "robin", last_edit_comment: "Aw, bless.", created_at: "2011-01-26 14:11:02", updated_at: "2011-01-26 14:11:02", home_page: nil, api_key: "3", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>,
       - #<PublicBody id: 5, version: 1, last_edit_editor: "robin", last_edit_comment: "Is a comment really required?", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "4", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 2, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 6, version: 1, last_edit_editor: "robin", last_edit_comment: "Another stunning innovation from your friendly nat...", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "5", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 1, info_requests_visible_count: 1>,
       - #<PublicBody id: 7, version: 1, last_edit_editor: "louise", last_edit_comment: "Another edit", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "6", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
       +[#<PublicBody:0x0000002fcc4ff0
       +  id: 3,
       +  version: 2,
       +  last_edit_editor: "francis",
       +  last_edit_comment: "Not sure what this new department does.",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "2",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 1,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002fcc4e60
       +  id: 4,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment: "Aw, bless.",
       +  created_at: Wed, 26 Jan 2011 14:11:02 UTC +00:00,
       +  updated_at: Wed, 26 Jan 2011 14:11:02 UTC +00:00,
       +  home_page: nil,
       +  api_key: "3",
       +  info_requests_count: 0,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 0,
       +  info_requests_visible_count: 0>,
       + #<PublicBody:0x0000002fcc4cd0
       +  id: 5,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment: "Is a comment really required?",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "4",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 2,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002fcc4b40
       +  id: 6,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment:
       +   "Another stunning innovation from your friendly national government",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "5",
       +  info_requests_count: 1,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 1,
       +  info_requests_visible_count: 1>,
       + #<PublicBody:0x0000002fcc49b0
       +  id: 7,
       +  version: 1,
       +  last_edit_editor: "louise",
       +  last_edit_comment: "Another edit",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "6",
       +  info_requests_count: 0,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 0,
       +  info_requests_visible_count: 0>,
       + #<PublicBody:0x0000002fcc47f8
       +  id: 2,
       +  version: 1,
       +  last_edit_editor: "mark",
       +  last_edit_comment: "Mark named this stupid quango.",
       +  created_at: Wed, 24 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Wed, 25 Apr 2018 12:08:48 UTC +00:00,
       +  home_page: nil,
       +  api_key: "1",
       +  info_requests_count: 4,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 3,
       +  info_requests_visible_classified_count: 3,
       +  info_requests_visible_count: 4>]
     # ./spec/models/public_body_spec.rb:97:in `block (3 levels) in <top (required)>'
  2) PublicBody.with_tag should returns authorities without categories
     Failure/Error:
       expect(pbs).to eq([
         public_bodies(:geraldine_public_body),
         public_bodies(:humpadink_public_body),
         public_bodies(:silly_walks_public_body),
         public_bodies(:sensible_walks_public_body),
         public_bodies(:other_public_body)
       ])
       expected: [#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid...quests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
            got: #<ActiveRecord::Relation [#<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comm...uests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>]>
       (compared using ==)
       Diff:
       @@ -1,6 +1,82 @@
       -[#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid quango.", created_at: "2007-10-24 10:51:01", updated_at: "2018-04-25 12:08:48", home_page: nil, api_key: "1", info_requests_count: 4, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>,
       - #<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comment: "Not sure what this new department does.", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "2", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 1, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 5, version: 1, last_edit_editor: "robin", last_edit_comment: "Is a comment really required?", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "4", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 2, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 6, version: 1, last_edit_editor: "robin", last_edit_comment: "Another stunning innovation from your friendly nat...", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "5", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 1, info_requests_visible_count: 1>,
       - #<PublicBody id: 7, version: 1, last_edit_editor: "louise", last_edit_comment: "Another edit", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "6", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
       +[#<PublicBody:0x0000002c224440
       +  id: 3,
       +  version: 2,
       +  last_edit_editor: "francis",
       +  last_edit_comment: "Not sure what this new department does.",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "2",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 1,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002c2242b0
       +  id: 5,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment: "Is a comment really required?",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "4",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 2,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002c224120
       +  id: 6,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment:
       +   "Another stunning innovation from your friendly national government",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "5",
       +  info_requests_count: 1,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 1,
       +  info_requests_visible_count: 1>,
       + #<PublicBody:0x0000002c25ff40
       +  id: 7,
       +  version: 1,
       +  last_edit_editor: "louise",
       +  last_edit_comment: "Another edit",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "6",
       +  info_requests_count: 0,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 0,
       +  info_requests_visible_count: 0>,
       + #<PublicBody:0x0000002c25fd88
       +  id: 2,
       +  version: 1,
       +  last_edit_editor: "mark",
       +  last_edit_comment: "Mark named this stupid quango.",
       +  created_at: Wed, 24 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Wed, 25 Apr 2018 12:08:48 UTC +00:00,
       +  home_page: nil,
       +  api_key: "1",
       +  info_requests_count: 4,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 3,
       +  info_requests_visible_classified_count: 3,
       +  info_requests_visible_count: 4>]
     # ./spec/models/public_body_spec.rb:109:in `block (3 levels) in <top (required)>'
Finished in 18 minutes 21 seconds (files took 11.39 seconds to load)
5493 examples, 2 failures, 7 pending
Failed examples:
rspec ./spec/models/public_body_spec.rb:95 # PublicBody.with_tag should returns all authorities
rspec ./spec/models/public_body_spec.rb:107 # PublicBody.with_tag should returns authorities without categories
Randomized with seed 51845
```

**Comment by gbp** [comment]
Think we want to switch to `match_array`

```ruby
expect(%w[a b]).to match_array(%w[b a]) => passes
expect(%w[a b]).to match(%w[b a]) => errors

Failure/Error: expect(%w[a b]).to match(%w[b a])
  expected ["a", "b"] to match ["b", "a"]
```
