### ISSUE TITLE
NotificationMailer#daily_summary transient spec failure

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4633]
```
Failures:
  1) NotificationMailer#daily_summary sets the right subject line
     Failure/Error: info_request.save!
     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "info_requests_pkey"
       DETAIL:  Key (id)=(1001) already exists.
       : INSERT INTO "info_requests" ("title", "url_title", "described_state", "user_id", "public_body_id", "info_request_batch_id", "idhash", "created_at", "updated_at", "use_notifications") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/relation.rb:64:in `insert'
     # ./.bundle/ruby/2.0.0/gems/globalize-5.0.1/lib/patches/active_record/persistence.rb:19:in `_create_record'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/counter_cache.rb:139:in `_create_record'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/locking/optimistic.rb:75:in `_create_record'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:306:in `block in _create_record'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:306:in `_create_record'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/timestamp.rb:57:in `_create_record'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:504:in `create_or_update'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `block in create_or_update'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # ./.bundle/ruby/2.0.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `create_or_update'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:142:in `save!'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
     # ./.bundle/ruby/2.0.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:27:in `block in transaction_with_transactional_fixtures'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
     # ./.bundle/ruby/2.0.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:21:in `transaction_with_transactional_fixtures'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `save!'
     # ./app/models/info_request_batch.rb:105:in `create_request!'
     # ./app/models/info_request_batch.rb:68:in `block (2 levels) in create_batch!'
     # ./.bundle/ruby/2.0.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:27:in `block in transaction_with_transactional_fixtures'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # ./.bundle/ruby/2.0.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:21:in `transaction_with_transactional_fixtures'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
     # ./app/models/info_request_batch.rb:67:in `block in create_batch!'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:46:in `each'
     # ./.bundle/ruby/2.0.0/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:46:in `each'
     # ./app/models/info_request_batch.rb:64:in `create_batch!'
     # ./spec/mailers/notification_mailer_spec.rb:77:in `block (3 levels) in <top (required)>'
Finished in 19 minutes 2 seconds (files took 21.66 seconds to load)
5493 examples, 1 failure, 7 pending
Failed examples:
rspec ./spec/mailers/notification_mailer_spec.rb:374 # NotificationMailer#daily_summary sets the right subject line
```

**Comment by garethrees** [comment]
Might get fixed by https://github.com/mysociety/alaveteli/pull/4572

**Comment by garethrees** [comment]
Ah sorry yeah, duplicate of https://github.com/mysociety/alaveteli/issues/4487
