### ISSUE TITLE
integration/signin_spec transient spec failure

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4635]
```
Failures:
  1) Signing in when you give the right credentials logs you in
     Failure/Error:
       expect(page).
         to have_content user.name
       expected #has_content?("Example User 4") to return true, got false
     # ./spec/integration/signin_spec.rb:38:in `block (3 levels) in <top (required)>'
  2) Signing in when you give the right credentials if an account is not confirmed sends a confirmation email_token, logs you in and redirects you
     Failure/Error: expect(page).to have_content user.name
       expected #has_content?("Example User 6") to return true, got false
     # ./spec/integration/signin_spec.rb:63:in `block (4 levels) in <top (required)>'
  3) Signing in when you give the right credentials if an account is not confirmed if an admin clicks the confirmation link should keep you logged in if you click a confirmation link
     Failure/Error: expect(page).to have_content admin_user.name
       expected #has_content?("Admin User 1") to return true, got false
     # ./spec/integration/signin_spec.rb:78:in `block (6 levels) in <top (required)>'
     # ./.bundle/ruby/2.3.0/gems/capybara-2.15.4/lib/capybara.rb:351:in `using_session'
     # ./.bundle/ruby/2.3.0/gems/capybara-2.15.4/lib/capybara/dsl.rb:21:in `using_session'
     # ./spec/integration/signin_spec.rb:75:in `block (5 levels) in <top (required)>'
Finished in 16 minutes 31 seconds (files took 8.14 seconds to load)
5492 examples, 3 failures, 7 pending
Failed examples:
rspec ./spec/integration/signin_spec.rb:36 # Signing in when you give the right credentials logs you in
rspec ./spec/integration/signin_spec.rb:57 # Signing in when you give the right credentials if an account is not confirmed sends a confirmation email_token, logs you in and redirects you
rspec ./spec/integration/signin_spec.rb:70 # Signing in when you give the right credentials if an account is not confirmed if an admin clicks the confirmation link should keep you logged in if you click a confirmation link
Randomized with seed 19901
```

**Comment by gbp** [comment]
Using the same seed I can't replicate before or after 2cf1284a0f0e749af6de79f3df32126d013aec7c

**Comment by garethrees** [comment]
I now get some different failures with this seed https://github.com/mysociety/alaveteli/issues/6474.
