### ISSUE TITLE
Transient spec failure in AlaveteliPro::BatchRequestAuthoritySearchesController#index

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4662]
```
Failures:
  1) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
     Failure/Error: expect(results.first[:model].name).to eq authority_1.name
       expected: "Example Public Body 2337"
            got: "Example Public Body 2338"
       (compared using ==)
     Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:115
     # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:8:in `block (2 levels) in <top (required)>'
Finished in 22 minutes 53 seconds (files took 27.03 seconds to load)
5540 examples, 1 failure, 7 pending
Failed examples:
rspec ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:4:1:1] # AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
Randomized with seed 52990
```

**Comment by gbp** [comment]
Still seeing this

```
Failures:
  1) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
     Failure/Error: expect(results.first[:model].name).to eq authority_1.name

       expected: "Example Public Body 4352"
            got: "Example Public Body 4354"

       (compared using ==)
     Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:106
     # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 20 minutes 38 seconds (files took 9.25 seconds to load)
7045 examples, 1 failure, 5 pending

Failed examples:

rspec './spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:4:1:1]' # AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search

Randomized with seed 8789
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
