### ISSUE TITLE
 [ERROR] one_time_passwords#create (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4667]
```
An ActionController::InvalidAuthenticityToken occurred in one_time_passwords#create:

ActionController::InvalidAuthenticityToken
lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/two_factor
* HTTP Method: POST
* IP address : REDACTED
* Parameters : {"authenticity_token"=>"REDACTED", "controller"=>"one_time_passwords", "action"=>"create"}
* Timestamp : 2018-06-06 11:07:31 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false,
"user_id"=>119967,
"ttl"=>"2018-06-06T11:01:56.796+01:00",
"post_redirect_token"=>"c99ms7left455lxtutw",
"_csrf_token"=>"REDACTED"}


-------------------------------
Backtrace:
-------------------------------

lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/4484

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
