### ISSUE TITLE
[ERROR] sessions#create (NoMethodError) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#4671]
Similar error to #3904 but this time on sign in.

```
A NoMethodError occurred in sessions#create:

  undefined method `[]' for nil:NilClass
  lib/alaveteli_pro/post_redirect_handler.rb:15:in `override_post_redirect_for_pro'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/profile/sign_in
  * HTTP Method: POST
  * IP address : [FILTERED]
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "user_signin"=>{"email"=>"[FILTERED]", "password"=>"[FILTERED]"}, "token"=>"bvd9moq2n9cqmgprizk", "modal"=>"", "commit"=>"Sign in", "controller"=>"users/sessions", "action"=>"create"}
  * Timestamp  : 2018-06-11 17:13:42 +0100
  * Server : [FILTERED]
  * Rails root : /[FILTERED]/www.whatdotheyknow.com/alaveteli-2018-05-31T13-01-51
  * Process: 17977

-------------------------------
Backtrace:
-------------------------------

  lib/alaveteli_pro/post_redirect_handler.rb:15:in `override_post_redirect_for_pro'
  app/controllers/application_controller.rb:330:in `do_post_redirect'
  app/controllers/users/sessions_controller.rb:47:in `create'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
This has been hit again, grabbing the post redirect while avaliable:

```
irb(main):001:0> pr = PostRedirect.find_by token: 'jc3q312yxgztrpimmhl'
=> #<PostRedirect id: 137173478, token: "jc3q312yxgztrpimmhl", uri: "/new", post_params_yaml: "--- {}\n", created_at: "2019-06-19 18:32:03", updated_at: "2019-06-19 18:32:03", email_token: "7wrfy20llacbhpf2h09", reason_params_yaml: "---\n:web: ''\n:email: Then you can sign in to WhatD...", user_id: nil, circumstance: "normal">
irb(main):002:0> pr.post_params
=> {}
irb(main):003:0> pr.reason_params
=> {:web=>"", :email=>"Then you can sign in to WhatDoTheyKnow", :email_subject=>"Confirm your account on WhatDoTheyKnow"}
```
