### ISSUE TITLE
[ERROR] draft_info_request_batches#update_bodies (NoMethodError) "undefined method `draft_info_request_batches' for nil:NilClass

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4734]
```
A NoMethodError occurred in draft_info_request_batches#update_bodies:

undefined method `draft_info_request_batches' for nil:NilClass
app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:22:in `update_bodies'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/draft_info_request_batches/update_bodies
* HTTP Method: PUT
* IP address : REDACTED
* Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"REDACTED", "authority_query"=>"lincoln", "page"=>"1", "mode"=>"search", "category_tag"=>"", "alaveteli_pro_draft_info_request_batch"=>{"draft_id"=>"", "public_body_id"=>"246", "action"=>"add"}, "controller"=>"alaveteli_pro/draft_info_request_batches", "action"=>"update_bodies"}
* Timestamp : 2018-07-17 17:55:32 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false,
"_csrf_token"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:22:in `update_bodies'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Had another two of these today.

```
A NoMethodError occurred in draft_info_request_batches#update_bodies:

undefined method `draft_info_request_batches' for nil:NilClass
app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:22:in `update_bodies'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/draft_info_request_batches/update_bodies
* HTTP Method: PUT
* Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"REDACTED", "authority_query"=>"Attorney", "page"=>"1", "mode"=>"search", "category_tag"=>"", "alaveteli_pro_draft_info_request_batch"=>{"draft_id"=>"", "public_body_id"=>"7906", "action"=>"add"}, "controller"=>"alaveteli_pro/draft_info_request_batches", "action"=>"update_bodies"}
* Timestamp : 2019-05-15 08:26:49 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2019-05-07T08-58-21


-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false,
"_csrf_token"=>"REDACTED"}
```

**Comment by garethrees** [comment]
Another:

```
A NoMethodError occurred in draft_info_request_batches#update_bodies:

undefined method `draft_info_request_batches' for nil:NilClass
app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:22:in `update_bodies'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/draft_info_request_batches/update_bodies
* HTTP Method: PUT
* Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"REDACTED", "authority_query"=>"trust", "page"=>"5", "mode"=>"search", "category_tag"=>"", "alaveteli_pro_draft_info_request_batch"=>{"draft_id"=>"1986", "public_body_id"=>"2291", "action"=>"add"}, "controller"=>"alaveteli_pro/draft_info_request_batches", "action"=>"update_bodies"}
* Timestamp : 2021-06-23 09:58:38 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"_csrf_token"=>"REDACTED",
"remember_me"=>false}

-------------------------------
Backtrace:
-------------------------------

app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:22:in `update_bodies'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Might be issue with being logged out but still on the page like #5219?

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
