### ISSUE TITLE
[ERROR] script/send-batch-requests (PG::UniqueViolation) "ERROR: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4749]
> `PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_request_summaries_summary_categories_unique" (ActiveRecord::RecordNotUnique)
DETAIL: Key (request_summary_id, request_summary_category_id)=(490925, 5) already exists.`

```
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared': PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_request_summaries_summary_categories_unique" (ActiveRecord::RecordNotUnique)
DETAIL: Key (request_summary_id, request_summary_category_id)=(490925, 5) already exists.
: INSERT INTO "request_summaries_summary_categories" ("request_summary_id", "request_summary_category_id") VALUES ($1, $2)
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation.rb:64:in `insert'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/globalize-5.0.1/lib/patches/active_record/persistence.rb:19:in `_create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/counter_cache.rb:139:in `_create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/locking/optimistic.rb:75:in `_create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:306:in `block in _create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:306:in `_create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/timestamp.rb:57:in `_create_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:504:in `create_or_update'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `block in create_or_update'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `create_or_update'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:142:in `save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `block in save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent.rb:647:in `with_database_metric_name'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_record_helper.rb:32:in `save!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:117:in `save_through_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:66:in `insert_record'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:574:in `block (2 levels) in concat_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:419:in `replace_on_target'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:414:in `add_to_target'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:573:in `block in concat_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:571:in `each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:571:in `concat_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_association.rb:180:in `concat_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:44:in `concat_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:179:in `block in concat'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:194:in `block in transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:193:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:179:in `concat'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:551:in `replace_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:384:in `block in replace'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:194:in `block in transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:193:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:384:in `replace'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:47:in `writer'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/builder/association.rb:123:in `request_summary_categories='
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `public_send'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:251:in `block in update'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:250:in `update'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/alaveteli_pro/request_summary.rb:69:in `update_from'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/alaveteli_pro/request_summary.rb:61:in `create_or_update_from'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/concerns/alaveteli_pro/request_summaries.rb:20:in `create_or_update_request_summary'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/concerns/alaveteli_pro/request_summaries.rb:23:in `create_or_update_request_summary'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/info_request_event.rb:88:in `block in <class:InfoRequestEvent>'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:446:in `instance_exec'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:446:in `block in make_lambda'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:253:in `block in conditional'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `block in call'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `call'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:314:in `committed!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/info_request_batch.rb:80:in `block in create_batch!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:46:in `each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:46:in `each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/info_request_batch.rb:77:in `create_batch!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/info_request_batch.rb:39:in `block in send_batches'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/app/models/info_request_batch.rb:38:in `send_batches'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `eval'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /data/vhost/www.whatdotheyknow.com/alaveteli-2018-07-16T13-52-20/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

**Comment by garethrees** [comment]
Had a few of these recently, similar to https://github.com/mysociety/alaveteli/issues/3035 and [a few others](https://github.com/mysociety/alaveteli/issues?utf8=%E2%9C%93&q=is%3Aissue+PG%3A%3AUniqueViolation+is%3Aopen+).

**Comment by garethrees** [comment]
Another one of these over the weekend; caused a breakage of the admin requests index and the requests index for the pro user who made the batch.

**Comment by garethrees** [comment]
I think one of these has caused a batch to be left in a partially-sent state:

```ruby
irb(main):001:0> batch = User.find(163278).info_request_batches.first
=> #<InfoRequestBatch id: 418, title: "FOI: Large Panel System (LPS) buildings", user_id: 163278, created_at: "2018-08-01 16:19:57", updated_at: "2018-08-01 16:25:26", body: "Dear [Authority name],\r\n\r\nFollowing the letter sen...", sent_at: "2018-08-01 16:25:26", embargo_duration: "6_months">
irb(main):002:0> batch.public_bodies.count
=> 330
irb(main):003:0> batch.info_requests.count
=> 40

```

**Comment by garethrees** [comment]
[This comment from the original introduction of request summaries](https://github.com/mysociety/alaveteli/pull/3923#discussion_r114821308) is interesting:

> If a batch request is created, and then the status of one of the requests in the batch is changed (for example, to 'successful'), I don't think that the RequestSummary for the batch is getting updated.

https://github.com/mysociety/alaveteli/commit/8f200070512e84af9ec08825a93e4279e820acf1 is listed as a fix for this, but I wonder if a case has been missed, a request in the batch has been updated and then the next request in the batch gets a clash? Might be an avenue to explore.

**Comment by garethrees** [comment]
Or, we're creating the request summary in an [`after_commit`](https://github.com/mysociety/alaveteli/blob/1351c02c2db6204577773efc0ca4b61808d0639e/app/models/info_request_event.rb#L88-L89) callback, but that's being called from [inside a transaction](https://github.com/mysociety/alaveteli/blob/1351c02c2db6204577773efc0ca4b61808d0639e/app/models/info_request_batch.rb#L80-L81) so there may be some sort of ordering issue?

**Comment by garethrees** [comment]
Just before [updating the `RequestSummary`](https://github.com/mysociety/alaveteli/blob/1351c02c2db6204577773efc0ca4b61808d0639e/app/models/alaveteli_pro/request_summary.rb#L69) we're trying to [update from an `InfoRequestBatch`](https://github.com/mysociety/alaveteli/blob/1351c02c2db6204577773efc0ca4b61808d0639e/app/models/alaveteli_pro/request_summary.rb#L61), rather than an `InfoRequest`. This sounds like it could be related to [the comment above](https://github.com/mysociety/alaveteli/issues/4749#issuecomment-409936858).
