### ISSUE TITLE
[ERROR] alaveteli_mail_poller (ActiveRecord::RecordNotUnique) "PG::UniqueViolation: ERROR: duplicate key value violates unique constraint…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4777]
Related to https://github.com/mysociety/alaveteli/issues/4749, as this request is part of a Batch.

```
An ActiveRecord::RecordNotUnique occurred in background at 2018-08-06 14:55:19 +0100 :

PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_request_summaries_summary_categories_unique"
DETAIL: Key (request_summary_id, request_summary_category_id)=(494129, 5) already exists.
: INSERT INTO "request_summaries_summary_categories" ("request_summary_id", "request_summary_category_id") VALUES ($1, $2)
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'

-------------------------------
Backtrace:
-------------------------------

/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/relation.rb:64:in `insert'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/globalize-5.0.1/lib/patches/active_record/persistence.rb:19:in `_create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/counter_cache.rb:139:in `_create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/locking/optimistic.rb:75:in `_create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:306:in `block in _create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:306:in `_create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/timestamp.rb:57:in `_create_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:504:in `create_or_update'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `create_or_update'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:142:in `save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `block in save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent.rb:647:in `with_database_metric_name'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_record_helper.rb:32:in `save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:117:in `save_through_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:66:in `insert_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:574:in `block (2 levels) in concat_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:419:in `replace_on_target'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:414:in `add_to_target'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:573:in `block in concat_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:571:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:571:in `concat_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_association.rb:180:in `concat_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:44:in `concat_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:179:in `block in concat'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:194:in `block in transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:193:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:179:in `concat'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:551:in `replace_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:384:in `block in replace'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:194:in `block in transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:193:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:384:in `replace'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:47:in `writer'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/associations/builder/association.rb:123:in `request_summary_categories='
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `public_send'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:251:in `block in update'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:250:in `update'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/models/alaveteli_pro/request_summary.rb:69:in `update_from'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/models/alaveteli_pro/request_summary.rb:61:in `create_or_update_from'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/models/concerns/alaveteli_pro/request_summaries.rb:20:in `create_or_update_request_summary'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/models/concerns/alaveteli_pro/request_summaries.rb:23:in `create_or_update_request_summary'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:253:in `block in conditional'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `block in call'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `call'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:314:in `committed!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:277:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/models/info_request.rb:1780:in `create_response!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/models/info_request.rb:895:in `receive'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/mailers/request_mailer.rb:254:in `block in receive'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/mailers/request_mailer.rb:246:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/mailers/request_mailer.rb:246:in `receive'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/app/mailers/request_mailer.rb:214:in `receive'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/lib/alaveteli_mail_poller.rb:62:in `get_mail'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/lib/alaveteli_mail_poller.rb:26:in `block (2 levels) in poll_for_incoming'
/opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:666:in `each'
/opt/rbenv/versions/2.3.5/lib/ruby/2.3.0/net/pop.rb:666:in `each_mail'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/lib/alaveteli_mail_poller.rb:25:in `block in poll_for_incoming'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/lib/alaveteli_mail_poller.rb:115:in `start'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `eval'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2018-08-03T10-22-50/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

-------------------------------
Data:
-------------------------------

* data: {:mail=> REDACTED}
```

See the [original cron email](https://groups.google.com/a/mysociety.org/forum/#!topic/cron-alaveteli/CLbcQHsXAG4) for redacted data. Its just an auto-acknowledgement.

**Comment by garethrees** [comment]
The request received the same response twice, 

```ruby
IncomingMessage.find(1204784).created_at
# => Mon, 06 Aug 2018 14:55:19 BST +01:00
IncomingMessage.find(1204883).created_at
# => Mon, 06 Aug 2018 15:25:20 BST +01:00
```

The message looks like its a duplicate, as the Date header in the raw email for both is `Date: Mon, 6 Aug 2018 13:55:15 +0000`.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
