### ISSUE TITLE
[ERROR] draft_info_request_batches#update_bodies (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4787]
An instance of https://github.com/mysociety/alaveteli/issues/4484.

```
An ActionController::InvalidAuthenticityToken occurred in draft_info_request_batches#update_bodies:

ActionController::InvalidAuthenticityToken
lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/draft_info_request_batches/update_bodies
* HTTP Method: PUT
* Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"7Brs7O3k4ZHX2h+TikttDsfEO7j6KC6wErulNoMadlE=", "mode"=>"browse", "category_tag"=>"university", "alaveteli_pro_draft_info_request_batch"=>{"draft_id"=>"", "public_body_id"=>"1139", "action"=>"add"}, "controller"=>"alaveteli_pro/draft_info_request_batches", "action"=>"update_bodies"}
* Timestamp : 2018-08-06 14:16:02 +0100

-------------------------------
Backtrace:
-------------------------------

lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
