### ISSUE TITLE
[ERROR] public_body#show (ActionController::RedirectBackError)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4834]
Only seen this on Belgium, but a few times recently:

```
An ActionController::RedirectBackError occurred in public_body#show:

No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].
app/controllers/public_body_controller.rb:36:in `block in show'


-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/nl_BE/body/ordre_des_architectes_conseil_francophone_et_germanophone
* HTTP Method: GET
* IP address : REDACTED
* Parameters : {"view"=>"all", "controller"=>"public_body", "action"=>"show", "url_name"=>"ordre_des_architectes_conseil_francophone_et_germanophone", "locale"=>"nl_BE"}
* Timestamp : 2018-08-30 03:35:53 +0200
* Rails root : /REDACTED/belgium.alaveteli.org/alaveteli-2018-08-21T14-44-20

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"nl_BE"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/public_body_controller.rb:36:in `block in show'
lib/alaveteli_localization.rb:43:in `with_locale'
app/controllers/public_body_controller.rb:31:in `show'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

Here's the code that's causing this:

```ruby
      @public_body = PublicBody.find_by_url_name_with_historic(params[:url_name])
      raise ActiveRecord::RecordNotFound.new("None found") if @public_body.nil?

      if @public_body.url_name.nil?
        redirect_to :back
        return
      end
```

I don't know how the `url_name` is `nil` given its just found a `PublicBody` when given the `url_name` parameter!

**Comment by lizconlan** [comment]
Possibly worth noting that so far these errors have been from webcrawlers:

`Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)`
`Mozilla/5.0 (compatible; Seekport Crawler; http://seekport.com/)`

**Comment by lizconlan** [comment]
Oh, hang on, that's a French `url_name` with a Dutch locale...

```rb
url_name = 'ordre_des_architectes_conseil_francophone_et_germanophone'
AlaveteliLocalization.locale
=> "nl_BE"
PublicBody.find_by(url_name: url_name).nil?
=> false

AlaveteliLocalization.set_session_locale("nl_BE")
=> "nl_BE"
PublicBody.find_by(url_name: url_name).nil?
=> true
```

**Comment by lizconlan** [comment]
Rails 5 introduces `redirect_back(fallback_location: fallback_location)` which should be helpful here

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
