### ISSUE TITLE
[ERROR] track#update (TypeError) "no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4871]
```
A TypeError occurred in track#update:

no implicit conversion of nil into String
app/controllers/track_controller.rb:212:in `+'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/track/update/81443
* HTTP Method: GET
* IP address : REDACTED
* Parameters : {"controller"=>"track", "action"=>"update", "track_id"=>"81443"}
* Timestamp : 2018-09-27 17:31:46 +0100
* Rails root : /REDACTED/alaveteli-2018-09-05T08-32-15

-------------------------------
Backtrace:
-------------------------------

app/controllers/track_controller.rb:212:in `+'
app/controllers/track_controller.rb:212:in `update'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
I expect what's happened here is someone has mistakenly "paused" a form submission (clicking "stop" or "back"?) and ended up on `https://www.whatdotheyknow.com/track/update/81443`. They've then hit reload and as the action responds to `GET` it submits with no params.
