### ISSUE TITLE
[ERROR] info_request_batch#show (NoMethodError) "undefined method `expiring_soon?' for nil

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4904]
```
A NoMethodError occurred in info_request_batch#show:

undefined method `expiring_soon?' for nil:NilClass
lib/themes/whatdotheyknow-theme/lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb:24:in `block in _lib_themes_whatdotheyknow_theme_lib_views_alaveteli_pro_info_request_batches__embargo_form_html_erb__3205621551862556109_69938341891640'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/info_request_batch/270
* HTTP Method: GET
* Parameters : {"controller"=>"info_request_batch", "action"=>"show", "id"=>"270"}
* Timestamp : 2018-10-17 09:38:52 +0100

-------------------------------
Backtrace:
-------------------------------

lib/themes/whatdotheyknow-theme/lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb:24:in `block in _lib_themes_whatdotheyknow_theme_lib_views_alaveteli_pro_info_request_batches__embargo_form_html_erb__3205621551862556109_69938341891640'
lib/themes/whatdotheyknow-theme/lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb:14:in `_lib_themes_whatdotheyknow_theme_lib_views_alaveteli_pro_info_request_batches__embargo_form_html_erb__3205621551862556109_69938341891640'
app/views/info_request_batch/show.html.erb:41:in `_app_views_info_request_batch_show_html_erb__3654219652506538539_69938333448920'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

There's a theme override in place, but I don't think that's anything to do with this bug.

The problem is that a now-public batch still has an `embargo_duration`:

https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb#L1

This means that we try to get an "example" embargo from an associated `InfoRequest`…

https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb#L7

…but that fails because now the InfoRequests belonging to the batch are public:

https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb#L24.

**Comment by garethrees** [comment]
The manual fix to this is to manually set `embargo_duration` to `nil`:

```ruby
InfoRequestBatch.find(270).update(embargo_duration: nil)
```

**Comment by garethrees** [comment]
This is getting really annoying.

**Comment by lizconlan** [comment]
Ah - I think this may be from `Embargo.expire_publishable` which iterates over individual requests
