### ISSUE TITLE
[ERROR] user#signup (ActiveRecord::RecordInvalid) "Validation failed: User|Email This email is already in use"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4947]
Might have just clicked "sign up" twice in quick succession and got served by a different processes?

```
An ActiveRecord::RecordInvalid occurred in user#signup:

Validation failed: User|Email This email is already in use
app/controllers/user_controller.rb:166:in `signup'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/sign_up
* HTTP Method: POST
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "user_signup"=>{"name"=>"REDACTED", "email"=>"REDACTED@aol.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "token"=>"7yr3h819kn90f3ghnvi", "modal"=>"", "commit"=>"Sign up", "controller"=>"user", "action"=>"signup"}
* Timestamp : 2018-11-08 08:27:37 +0000


-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false}


-------------------------------
Backtrace:
-------------------------------

app/controllers/user_controller.rb:166:in `signup'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
