### ISSUE TITLE
[ERROR] admin_public_body#import_csv (EncodingNormalizationError) "Couldn't find a valid character encoding for the string"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4988]
```
An EncodingNormalizationError occurred in admin_public_body#import_csv:

Couldn't find a valid character encoding for the string
lib/normalize_string.rb:57:in `normalize_string_to_utf8'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/bodies/import_csv
* HTTP Method: POST
* IP address : REDACTED
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"REDACTED", "csv_file"=>#<ActionDispatch::Http::UploadedFile:0x00007f4e46289218 @tempfile=#<Tempfile:/tmp/RackMultipart20181124-3918-176pxq0.csv>, @original_filename="ijb_hscp.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"csv_file\"; filename=\"ijb_hscp.csv\"\r\nContent-Type: text/csv\r\n">, "tag"=>"", "tag_behaviour"=>"add", "commit"=>"Dry run", "controller"=>"admin_public_body", "action"=>"import_csv"}
* Timestamp : 2018-11-24 20:43:00 +0000
* Rails root : /REDACTED/alaveteli-2018-11-23T10-21-07

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>true,
"_csrf_token"=>"REDACTED",
"request_game"=>"2018-10-22T05:11:20.588+01:00",
"user_id"=>2779,
"post_redirect_token"=>"aspsl2k7h3tro63aiy0",
"using_admin"=>1,
"admin_name"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

lib/normalize_string.rb:57:in `normalize_string_to_utf8'
app/controllers/admin_public_body_controller.rb:169:in `import_csv'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
A specific case of #4078.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
