### ISSUE TITLE
Mailer view paths broken, leading to misleading specs

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5006]
In the process of working on #4983 I got this far and ran the specs:

```diff
diff --git a/app/mailers/public_body_change_request_mailer.rb b/app/mailers/public_body_change_request_mailer.rb
new file mode 100644
index 000000000..03fa2136c
--- /dev/null
+++ b/app/mailers/public_body_change_request_mailer.rb
@@ -0,0 +1,29 @@
+# -*- encoding : utf-8 -*-
+# Emails about PublicBodyChangeRequests.
+class PublicBodyChangeRequestMailer < ApplicationMailer
+  # Send a request to the administrator to add an authority
+  def change_request_message(change_request, use_new_body_template)
+    @change_request = change_request
+    template =
+      if use_new_body_template
+        'add_public_body'
+      else
+        'update_public_body_email'
+      end
+
+    reply_to_address = MailHandler.address_from_name_and_email(
+      @change_request.get_user_name,
+      @change_request.get_user_email)
+
+    set_reply_to_headers(nil, 'Reply-To' => reply_to_address)
+
+    # From is an address we control so that strict DMARC senders don't get refused
+    mail(:from => MailHandler.address_from_name_and_email(
+                    @change_request.get_user_name,
+                    blackhole_email
+                  ),
+         :to => contact_from_name_and_email,
+         :subject => @change_request.request_subject,
+         :template_name => template)
+  end
+end

diff --git a/spec/mailers/public_body_change_request_mailer_spec.rb b/spec/mailers/public_body_change_request_mailer_spec.rb
new file mode 100644
index 000000000..07b24f5df
--- /dev/null
+++ b/spec/mailers/public_body_change_request_mailer_spec.rb
@@ -0,0 +1,61 @@
+# -*- encoding : utf-8 -*-
+require 'spec_helper'
+
+describe PublicBodyChangeRequestMailer do
+  describe '.change_request_message' do
+    context 'when use_new_body_template is true' do
+      it 'uses the add_public_body template' do
+        change_request = FactoryBot.create(:add_body_request)
+        mail = ContactMailer.change_request_message(change_request, true)
+        expect(mail.body.to_s).to match(/would like a new authority added to/)
+      end
+    end
+
+    context 'when use_new_body_template is false' do
+      it 'uses the update_public_body_email template' do
+        change_request = FactoryBot.create(:update_body_request)
+        mail = ContactMailer.change_request_message(change_request, false)
+        expect(mail.body.to_s).to match(/would like the email address for/)
+      end
+    end
+
+    it 'sets the Reply-To header to the change request user' do
+      user = FactoryBot.create(:user, name: 'Jim', email: 'jim@localhost')
+      change_request = FactoryBot.create(:add_body_request, user: user)
+      mail = ContactMailer.change_request_message(change_request, true)
+      expect(mail['Reply-To'].value).to include('Jim <jim@localhost>')
+    end
+
+    it 'sets the from address to the blackhole email' do
+      user = FactoryBot.create(:user, name: 'Bob')
+      change_request = FactoryBot.create(:add_body_request, user: user)
+      mail = ContactMailer.change_request_message(change_request, true)
+      expect(mail['From'].value).
+        to include('Bob <do-not-reply-to-this-address@localhost>')
+    end
+
+    it 'sends the mail to the admin team' do
+      change_request = FactoryBot.create(:add_body_request)
+      mail = ContactMailer.change_request_message(change_request, true)
+      expect(mail['To'].value).
+        to include('Alaveteli Webmaster <postmaster@localhost>')
+    end
+
+    it 'does not add HTMLEntities to an update public body email subject' do
+      public_body = FactoryBot.create(:public_body, :name => "Apostrophe's")
+      change_request = FactoryBot.create(:update_body_request,
+                                         :public_body => public_body)
+      expect(
+        ContactMailer.change_request_message(change_request, false).subject
+      ).to eq("Update email address - Apostrophe's")
+    end
+
+    it 'does not add HTMLEntities to an add public body email subject' do
+      change_request = FactoryBot.create(:add_body_request,
+                                         :public_body_name => "Apostrophe's")
+      expect(
+        ContactMailer.change_request_message(change_request, true).subject
+      ).to eq("Add authority - Apostrophe's")
+    end
+  end
+end
```

```
$ bin/rspec spec/mailers/public_body_change_request_mailer_spec.rb

Randomized with seed 8813
.......

Finished in 2.04 seconds (files took 16.46 seconds to load)
7 examples, 0 failures
```

All good – note that I'm testing the mail body in the first two specs.

I then write this, to actually start using the new mailer.

```diff
diff --git a/app/models/public_body_change_request.rb b/app/models/public_body_change_request.rb
index 87bbd7633..5822dc1df 100644
--- a/app/models/public_body_change_request.rb
+++ b/app/models/public_body_change_request.rb
@@ -81,7 +81,7 @@ class PublicBodyChangeRequest < ActiveRecord::Base
   end
 
   def send_message
-    ContactMailer.change_request_message(self, add_body_request?).deliver_now
+    PublicBodyChangeRequestMailer.change_request_message(self, add_body_request?).deliver_now
   end
 
   def thanks_notice
```

It breaks. It can't find the template, because I haven't moved them from `app/views/contact_mailer` yet.

```
Completed 500 Internal Server Error in 994ms (ActiveRecord: 23.8ms)

ActionView::MissingTemplate (Missing template public_body_change_request_mailer/add_public_body with "mailer". Searched in:
  * "public_body_change_request_mailer"
):
  app/mailers/public_body_change_request_mailer.rb:21:in `change_request_message'
  app/models/public_body_change_request.rb:84:in `send_message'
  app/controllers/public_body_change_requests_controller.rb:43:in `create'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Nope, I'm just an idiot and didn't `/s/ContactMailer/PublicBodyChangeRequestMailer/`.

Good example of why `described_class` is super helpful.
