### ISSUE TITLE
View raw email not working for holding pen messages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5010]
On clicking "View raw email" from an incoming message admin page for a message in the holding pen I get:

>Sorry, there was a problem processing this page

That's the case currently for all messages in the WhatDoTheyKnow.com holding pen. 

"View raw email" is working for new incoming messages on other threads.

**Comment by lizconlan** [comment]
Full stacktrace (reproduced locally):

```
NoMethodError (undefined method `url_name' for nil:NilClass):
  lib/themes/whatdotheyknow-theme/lib/model_patches.rb:43:in `email_subject_request'
  app/models/info_request.rb:892:in `email_subject_followup'
  app/models/info_request.rb:300:in `guess_by_incoming_subject'
  app/controllers/admin_raw_email_controller.rb:30:in `block (2 levels) in show'
  app/controllers/admin_raw_email_controller.rb:12:in `show'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
(Sorry for breaking this, should be working again now!)
