### ISSUE TITLE
controllers/alaveteli_pro/batch_request_authority_searches_controller_spec transient spec failure

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5024]
```
1) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
     Failure/Error: expect(results.first[:model].name).to eq authority_1.name
     
       expected: "Example Public Body 1043"
            got: "Example Public Body 1044"
     
       (compared using ==)
     Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:119
     # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by gbp** [comment]
Seeing this again on https://github.com/mysociety/alaveteli/runs/3532511578?check_suite_focus=true

```
  1) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
     Failure/Error: expect(results.first[:model].name).to eq authority_1.name

       expected: "Example Public Body 2628"
            got: "Example Public Body 2630"

       (compared using ==)
     Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:106
     # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:7:in `block (2 levels) in <top (required)>'

7080 examples, 1 failure, 5 pending

Failed examples:

rspec './spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:4:1:1]' # AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search

Randomized with seed 33365
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
