### ISSUE TITLE
[Rails 5] NoMethodError: undefined method `save_changed_attribute'

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5073]
Required by #3969 

```
NoMethodError:
  undefined method `save_changed_attribute' for #<MailServerLog:0x000000000b2d24f8>
  Did you mean?  cache_changed_attributes
# /home/vagrant/bundle/ruby/2.3.0/gems/activemodel-5.0.7/lib/active_model/attribute_methods.rb:433:in `method_missing'
# ./app/models/mail_server_log.rb:271:in `set_delivery_status'
# ./app/models/mail_server_log.rb:253:in `rescue in delivery_status'
# ./app/models/mail_server_log.rb:233:in `delivery_status'
# ./spec/models/mail_server_log_spec.rb:448:in `block (4 levels) in <top (required)>'
# ------------------
# --- Caused by: ---
# ArgumentError:
#   Invalid delivery status: message_arrival
#   ./app/models/mail_server_log/delivery_status.rb:78:in `assert_valid_status'

rspec ./spec/models/mail_server_log_spec.rb:431
```

Looks like the [`save_changed_attribute` method](https://apidock.com/rails/ActiveRecord/AttributeMethods/Dirty/save_changed_attribute) is no longer available from Rails 5.0 on. Need to work out the best thing to replace it with.

**Comment by lizconlan** [comment]
Removed here: https://github.com/rails/rails/commit/8e633e505880755e7e366ccec2210bbe2b5436e7

**Comment by lizconlan** [comment]
Further changes in 5.1 https://www.levups.com/en/blog/2017/undocumented-dirty-attributes-activerecord-changes-rails51.html

**Comment by lizconlan** [comment]
More interestingly, we rewrote our code to directly call methods from `ActiveRecord::AttributeMethods::Dirty` [to work around what appears to be an ActiveRecord bug](https://github.com/mysociety/alaveteli/commit/76bc3ce7c4a5a760659fa14fd9cc5655bd6b9073) so hopefully - once we no longer need to dual run 4.2 and 5.0 - we  might be able to massively simplify this bit of code.
