### ISSUE TITLE
[Rails 5] Fix Stripe spec failures

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5078]
Required by #3969

Not entirely sure what's happening here. `symbolize_keys` is being called on `payload` (which for the example given below is set on line 40)

```
AlaveteliPro::StripeWebhooksController#receive updating the Stripe charge description when a payment succeeds when there is no charge for an invoice does not attempt to update the nil charge
     Failure/Error: post :receive, params: payload

     NoMethodError:
       undefined method `symbolize_keys' for #<String:0x0000000004f16018>
     # /home/vagrant/bundle/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_controller/test_case.rb:523:in `process'
     # /home/vagrant/bundle/ruby/2.3.0/gems/rails-controller-testing-1.0.2/lib/rails/controller/testing/template_assertions.rb:61:in `process'
     # /home/vagrant/bundle/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_controller/test_case.rb:644:in `process_with_kwargs'
     # /home/vagrant/bundle/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_controller/test_case.rb:397:in `post'
     # /home/vagrant/bundle/ruby/2.3.0/gems/rails-controller-testing-1.0.2/lib/rails/controller/testing/integration.rb:12:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb:410:in `block (4 levels) in <top (required)>'
```

**Comment by lizconlan** [comment]
Possibly coincidentally - using `stripe-ruby-mock` > 2.5.4 adds the failure condition:

```
Stripe::InvalidRequestError Missing required param: product
```

**Comment by lizconlan** [comment]
ToDo: (subject to change)
  - [ ] Pin `stripe` (current seems fine) and `stripe-ruby-mock` (2.5.4) gems to avoid using versions too far ahead of the API version we rely on ('2017-01-27'), where we see things like `Stripe::InvalidRequestError Missing required param: product` that's most likely a requirement from a later Stripe API (possibly [introduced in 2018-02-05](https://stripe.com/docs/upgrades#2018-02-05)?)
 - [ ] Doing that seems to clear up some of the controller errors so...
   - [ ] Check whether the Stripe API works while running the app or if it's "just" the tests that are broken (at a guess, may be to do with the new parameters format and our payload mocks are in the wrong format)
