### ISSUE TITLE
[ERROR] user#signup (ArgumentError) "SMTP To address may not be blank: []"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5158]
Had a couple of these in quick succession yesterday. Note that the auth token is blank, so could be related to that.

```
An ArgumentError occurred in user#signup:

SMTP To address may not be blank: []
app/controllers/user_controller.rb:493:in `send_confirmation_mail'

-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/profile/sign_up
* HTTP Method: POST
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "user_signup"=>{"name"=>"Comité \"Les Amis du Crachet\"", "email"=>"FILTERED@gmail.com", "province"=>"Hainaut", "postcode"=>"", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "token"=>"FILTERED", "modal"=>"", "commit"=>"S'inscrire", "controller"=>"user", "action"=>"signup"}
* Timestamp : 2019-04-08 19:29:38 +0200
* Rails root : /FILTERED/alaveteli-2019-03-14T15-58-03

-------------------------------
Backtrace:
-------------------------------

app/controllers/user_controller.rb:493:in `send_confirmation_mail'
app/controllers/user_controller.rb:162:in `signup'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
