### ISSUE TITLE
[Rails 5] Failing specs against Travis

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5173]
There are 3 failing specs which i've not manage to replicate locally

```
Failures:


  1) When importing mail into the application should not produce any output and should return a 0 code on importing a plain email
     Got 1 failure and 1 other error:
     1.1) Failure/Error: expect(r.status).to eq(0)
          
            expected: 0
                 got: 75
          
            (compared using ==)
          # ./spec/script/mailin_spec.rb:31:in `block (2 levels) in <top (required)>'
     1.2) Failure/Error: incoming_message.destroy
          
          NoMethodError:
            undefined method `destroy' for nil:NilClass
          # ./spec/script/mailin_spec.rb:39:in `block (2 levels) in <top (required)>'
  2) When filtering when not in test mode should not fail handling a bounce mail
     Failure/Error: expect(xc.err).to eq("")
     
       expected: ""
            got: "LoadError: No such file to load -- spec_helper\n  /home/travis/build/mysociety/alaveteli/vendor/bund...\n  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:81:in `<top (required)>'\n"
     
       (compared using ==)
     
       Diff:
       @@ -1 +1,64 @@
       +LoadError: No such file to load -- spec_helper
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/spec/support/shared_examples_for_viewing_requests.rb:2:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/spec/spec_helper.rb:33:in `block in <top (required)>'
       +  /home/travis/build/mysociety/alaveteli/spec/spec_helper.rb:33:in `each'
       +  /home/travis/build/mysociety/alaveteli/spec/spec_helper.rb:33:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/lib/themes/alavetelitheme/spec/alavetelitheme_spec.rb:4:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:380:in `block in require_or_load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:37:in `block in load_interlock'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:37:in `load_interlock'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:358:in `require_or_load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:336:in `depend_on'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:252:in `require_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:475:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:475:in `block in eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:473:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:473:in `eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:354:in `eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:59:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `instance_exec'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `run'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:55:in `block in run_initializers'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:54:in `run_initializers'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application.rb:352:in `initialize!'
       +  /home/travis/build/mysociety/alaveteli/config/environment.rb:6:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:118:in `require'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:118:in `load_rails'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:122:in `record_bounce'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:49:in `block (2 levels) in main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:48:in `each'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:48:in `block in main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:33:in `chdir'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:33:in `main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:81:in `<top (required)>'
       
     # ./spec/script/handle-mail-replies_spec.rb:23:in `block (3 levels) in <top (required)>'
  3) HelpController GET #contact when requesting a page in a supported locale should render the locale-specific template if available
     Failure/Error: expect(response.body).to match('contáctenos theme one')
     
       expected "<!DOCTYPE html>\n<html lang=\"es\" class=\"no-js\">\n  <head>\n    <meta charset=\"utf-8\">\n    \n\...keyboard-focus-only skip-to-link\">\n      Volver al contenido XOXO\n    </a>\n  </body>\n</html>\n" to match "contáctenos theme one"
       Diff:
       @@ -1,2 +1,292 @@
       -contáctenos theme one
       +<!DOCTYPE html>
       +<html lang="es" class="no-js">
       +  <head>
       +    <meta charset="utf-8">
       +    
       +
       +    <title>
       +        Contact us - Alaveteli
       +    </title>
       +
       +    <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon-3e06c6d6cb34168fb0342ef3186f733b2c7d1c44422d1136013ad3cca6c4694f.ico" />
       +
       +
       +      <!--[if LTE IE 7]>
       +<link rel="stylesheet" media="all" href="/assets/responsive/application-lte-ie7-715475c1c563cfcd2d0c759e31361815a10021a7e75c91c2fc8b2aa346f02b22.css" title="Main" />
       +<![endif]-->
       +
       +<!--[if IE 8]>
       +<link rel="stylesheet" media="all" href="/assets/responsive/application-ie8-4e859d3c0337588c975f0a7c104b2ee29c2e86e511f0ef3c9d5ea2dc4e112416.css" title="Main" />
       +<![endif]-->
       +
       +<!--[if IE 8]>
       +<link rel="stylesheet" media="all" href="/assets/responsive/application-ie8-4e859d3c0337588c975f0a7c104b2ee29c2e86e511f0ef3c9d5ea2dc4e112416.css" title="Main" />
       +<![endif]-->
       +
       +<!--[if GT IE 8]><!-->
       +<link rel="stylesheet" media="all" href="/assets/responsive/application-620fb0dd746243cc5aaf30b65729c1e70c8d61ffc6fc48a743d6f7d9ef7ce8f7.css" title="Main" />
       +<!--<![endif]-->
       +
       +  <link rel="stylesheet" media="print" href="/assets/responsive/print-f382691f6b7273571ffb7f402fe142b58891fec1e115fe46abdd8e80a3c064cc.css" />
       +
       +
       +
       +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
       +    
       +<meta property="og:site_name" content="Alaveteli" />
       +
       +  <meta property="og:title" content="Contact us" />
       +  <meta property="og:type" content="article" />
       +
       +
       +
       +<meta property="og:image" content="http://test.host/assets/logo-opengraph-08651411c043245191b8b3957faebb49c8eb235fc04f4b71114d22334c630cf3.png" />
       +<meta property="og:url" content="http://test.host/help/contact?locale=es" />
       +<meta property="og:image:width" content="256" />
       +<meta property="og:image:height" content="256" />
       +
       +    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
       +
       +    <!-- Replace the html tag's no-js class with js -->
       +    <script>
       +      (function(H){
       +        H.className = H.className.replace(/\bno-js\b/,'js-loaded')
       +      })(document.documentElement);
       +    </script>
       +  </head>
       +  <body class=" ">
       +    <div class="entirebody">
       +
       +    <a href="#content" class="show-with-keyboard-focus-only skip-to-link" tabindex="0">Skip to content</a>
       +      <!-- begin popups -->
       +        
       +        <div id="country-message">
       +        </div>
       +      <!-- end popups -->
       +
       +      <div class="only-show-for-print">
       +  <p class="print-information">Printed from http://test.host/help/contact?locale=es on April 03, 2019 15:04</p>
       +</div>
       +<div id="banner" class="banner " role="banner">
       +  <div id="banner_inner" class="banner_inner">
       +    <div id="banner_content" class="banner_content">
       +      <div class="banner_site-title">
       +        <h1><a id="logo" class="site-title__logo" href="/">Alaveteli</a></h1>
       +      </div>
       +
       +      <div class="rsp_menu_button">
       +        <a href="#banner" class="open"> <i class="icon-menu"></i> Menu </a>
       +        <a href="#" class="close"> <i class="icon-menu"></i> Close </a>
       +      </div>
       +
       +      <div id="user_locale_switcher" class="locale-list">
       +    <p class="locale-list-trigger ">
       +      <strong class="current-locale">español</strong>
       +    </p>
       +
       +    <ul class="available-languages">
       +        <li class="available-languages__item">
       +          <a href="/help/contact?locale=en">English</a>
       +        </li>
       +        <li class="available-languages__item">
       +          <a href="/help/contact?locale=fr">français</a>
       +        </li>
       +        <li class="available-languages__item">
       +          <a href="/help/contact?locale=en_GB">English</a>
       +        </li>
       +    </ul>
       +  </div>
       +        <div id="logged_in_bar" class="logged_in_bar account-link-menu-item">
       +  <a class="sign_in_link" href="/profile/sign_in?r=%2Fhelp%2Fcontact%3Flocale%3Des">Iniciar sesión o registro</a>
       +</div>
       +
       +      <div id="navigation_search" class="navigation_search">
       +        <form id="navigation_search_form" class="navigation_search_form" method="get" action="/search" role="search">
       +          <label class="visually-hidden" for="navigation_search_button">
       +            Buscar
       +          </label>
       +          <input type="search" name="query" id="navigation_search_button" class="navigation_search_button" placeholder="Buscar" title="type your search term here" />
       +          <button type="submit">
       +            <span class="visually-hidden">
       +              Submit Search
       +            </span>
       +          </button>
       +        </form>
       +      </div>
       +    </div>
       +
       +    <div id="topnav" class="topnav ">
       +  <ul id="navigation" class="navigation" role="navigation">
       +
       +      <li class="">
       +  <a id="make-request-link" href="/select_authority">Enviar solicitud</a>
       +</li>
       +
       +<li class="">
       +  <a href="/list/successful">Browse requests</a>
       +</li>
       +
       +<li class="">
       +  <a href="/body/list/all">Ver organismos públicos</a>
       +</li>
       +
       +  <li class=""><a href="/blog">Leer el blogg</a></li>
       +
       +<li class="selected">
       +  <a href="/help/about">Ayuda</a>
       +</li>
       +
       +  </ul>
       +</div>
       +
       +  </div>
       +</div>
       +
       +
       +
       +      <div id="wrapper">
       +        <div id="content" role="main">
       +
       +          <div id="help_contact" class="controller_help">
       +            
       +
       +
       +<h1>Contact us</h1>
       +
       +<div id="contact_preamble" class="contact_preamble">
       +
       +    <h2>Contact an authority to get official information</h2>
       +    <ul>
       +      <li><a href="/new">Go here</a> to make a request, in public, for information
       +        from public authorities.</li>
       +
       +      <li>
       +        Asking for private information about yourself?
       +        Please read our
       +        <a href="/help/requesting#data_protection">help page</a>.
       +      </li>
       +    </ul>
       +
       +
       +  <h2>Contact the Alaveteli team</h2>
       +    <ul>
       +      <li>
       +        Please read the  <a href="/help/about">help page</a> first, as it may
       +        answer your question quicker.
       +      </li>
       +
       +      <li>We'd love to hear how you've found using this site.
       +        Either fill in this form, or send an email to <a
       +                            href="mailto:postmaster@localhost">postmaster@localhost</a>
       +      </li>
       +
       +      <li>We are a <strong>charity</strong> and not part of the
       +        Government.</li>
       +    </ul>
       +</div>
       +
       +<form action="/help/contact" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" />
       +
       +    <p>
       +      <label class="form_label" for="contact_name">Your name:</label>
       +      <input size="20" type="text" name="contact[name]" id="contact_name" />
       +      (or <a href="/profile/sign_in?r=%2Fhelp%2Fcontact%3Flocale%3Des">sign in</a>)
       +    </p>
       +
       +    <p>
       +      <label class="form_label" for="contact_email">Your email:</label>
       +      <input size="20" type="text" name="contact[email]" id="contact_email" />
       +    </p>
       +
       +  <p>
       +    <label class="form_label" for="contact_subject">Subject:</label>
       +    <input size="50" type="text" name="contact[subject]" id="contact_subject" />
       +  </p>
       +
       +  <p>
       +    <label class="form_label" for="contact_message">Message to website:</label>
       +    <textarea rows="10" cols="60" name="contact[message]" id="contact_message">
       +</textarea>
       +  </p>
       +
       +  <p style="display:none;">
       +    <label for="contact_comment">Do not fill in this field</label>
       +    <input type="text" name="contact[comment]" id="contact_comment" />
       +  </p>
       +
       +
       +  <p class="form_note">
       +    We can only help you with <strong>technical problems</strong>, or questions
       +    about Freedom of Information.
       +  </p>
       +
       +
       +  <div class="form_button">
       +    <input type="hidden" name="submitted_contact_form" id="submitted_contact_form" value="1" />
       +    <input type="submit" name="commit" value="Send message to the charity" data-disable-with="Sending..." />
       +    &lt;-- we run this site, not the Government!
       +  </div>
       +
       +</form>
       +          </div>
       +          <div style="clear:both"></div>
       +        </div>
       +      </div>
       +
       +      <div class="footer" id="footer" role="contentinfo">
       +  <div class="row">
       +    <div class="footer__about">
       +      <h2>Alaveteli</h2>
       +      <p>Basado en <a href="http://www.alaveteli.org/">Alaveteli</a>
       +</p>
       +
       +      <ul class="about__contact-links">
       +        <li>
       +          <a href="/help/contact">Contact us</a>
       +        </li>
       +        <li>
       +          <a href="/help">Ayuda</a>
       +        </li>
       +        <li>
       +          <a href="/help/privacy">Privacy and cookies</a>
       +        </li>
       +        <li>
       +          <a href="/help/api">API</a>
       +        </li>
       +      </ul>
       +    </div>
       +  </div>
       +  <div class="footer__final">
       +    <div class="row">
       +      <div class="final__social-links">
       +        <ul>
       +          <li>
       +            <a href="https://twitter.com/alaveteli_foi" class="social-link social-link--twitter" onclick="if (ga) { ga(&#39;send&#39;,&#39;event&#39;,&#39;Outbound Link&#39;,&#39;Twitter Exit&#39;,&#39;Footer link&#39;,1) };">@alaveteli_foi</a>
       +          </li>
       +        </ul>
       +      </div>
       +    </div>
       +  </div>
       +</div>
       +
       +    </div>
       +
       +    <script src="/assets/application-9a7413688b1cc16cc10c55a8832d49355443a371c6ad151279b19f6d1d0bf5df.js"></script>
       +
       +    
       +
       +    <script>
       +  jQuery('#user_locale_switcher').find('.locale-list-trigger').each(function() {
       +    jQuery(this).click(function(){
       +      jQuery(this).parent().toggleClass('active');
       +    });
       +  });
       +</script>
       +
       +
       +    <a href="#content" class="show-with-keyboard-focus-only skip-to-link">
       +      Volver al contenido XOXO
       +    </a>
       +  </body>
       +</html>
       
     # ./spec/controllers/help_controller_spec.rb:124:in `block (4 levels) in <top (required)>'

Finished in 23 minutes 31 seconds (files took 11.13 seconds to load)
5888 examples, 3 failures, 7 pending

Failed examples:

rspec ./spec/script/mailin_spec.rb:29 # When importing mail into the application should not produce any output and should return a 0 code on importing a plain email
rspec ./spec/script/handle-mail-replies_spec.rb:19 # When filtering when not in test mode should not fail handling a bounce mail
rspec ./spec/controllers/help_controller_spec.rb:122 # HelpController GET #contact when requesting a page in a supported locale should render the locale-specific template if available

Randomized with seed 14490
```

https://travis-ci.org/mysociety/alaveteli/jobs/515181607

Required by #3969

**Comment by garethrees** [comment]
Superseded by https://github.com/mysociety/alaveteli/issues/5174, https://github.com/mysociety/alaveteli/issues/5175 and https://github.com/mysociety/alaveteli/issues/5176.
