### ISSUE TITLE
[Rails 5] mailin_spec fail CI only

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5174]
```
  1) When importing mail into the application should not produce any output and should return a 0 code on importing a plain email
     Got 1 failure and 1 other error:
     1.1) Failure/Error: expect(r.status).to eq(0)
          
            expected: 0
                 got: 75
          
            (compared using ==)
          # ./spec/script/mailin_spec.rb:31:in `block (2 levels) in <top (required)>'
     1.2) Failure/Error: incoming_message.destroy
          
          NoMethodError:
            undefined method `destroy' for nil:NilClass
          # ./spec/script/mailin_spec.rb:39:in `block (2 levels) in <top (required)>'

rspec ./spec/script/mailin_spec.rb:29 # When importing mail into the application should not produce any output and should return a 0 code on importing a plain email

```

Required by #3969

**Comment by gbp** [comment]
This spec passed on Travis when running #5202 guessing commit 4450e198a734f2eb56143f18f4e08772738866be might be responsible?
