### ISSUE TITLE
[Rails 5] handle-mail-replies_spec fail CI only

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5175]
```
  2) When filtering when not in test mode should not fail handling a bounce mail
     Failure/Error: expect(xc.err).to eq("")
     
       expected: ""
            got: "LoadError: No such file to load -- spec_helper\n  /home/travis/build/mysociety/alaveteli/vendor/bund...\n  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:81:in `<top (required)>'\n"
     
       (compared using ==)
     
       Diff:
       @@ -1 +1,64 @@
       +LoadError: No such file to load -- spec_helper
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/spec/support/shared_examples_for_viewing_requests.rb:2:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/spec/spec_helper.rb:33:in `block in <top (required)>'
       +  /home/travis/build/mysociety/alaveteli/spec/spec_helper.rb:33:in `each'
       +  /home/travis/build/mysociety/alaveteli/spec/spec_helper.rb:33:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/lib/themes/alavetelitheme/spec/alavetelitheme_spec.rb:4:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:380:in `block in require_or_load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:37:in `block in load_interlock'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:37:in `load_interlock'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:358:in `require_or_load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:336:in `depend_on'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:252:in `require_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:475:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:475:in `block in eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:473:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:473:in `eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:354:in `eager_load!'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:59:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `instance_exec'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `run'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:55:in `block in run_initializers'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:54:in `run_initializers'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application.rb:352:in `initialize!'
       +  /home/travis/build/mysociety/alaveteli/config/environment.rb:6:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:118:in `require'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:118:in `load_rails'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:122:in `record_bounce'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:49:in `block (2 levels) in main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:48:in `each'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:48:in `block in main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:33:in `chdir'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:33:in `main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:81:in `<top (required)>'
       
     # ./spec/script/handle-mail-replies_spec.rb:23:in `block (3 levels) in <top (required)>'
```

Required by #3969

**Comment by garethrees** [comment]
Ah so if I'd have read the backtrace properly I'd have noticed this line:

```
       +  /home/travis/build/mysociety/alaveteli/lib/themes/alavetelitheme/spec/alavetelitheme_spec.rb:4:in `<top (required)>'
```

We seem to [pull in alavetelitheme](https://github.com/mysociety/alaveteli/blob/develop/config/test.yml#L55-L56) to run the core alaveteli specs. The former tries to [load the core `spec_helper`](https://github.com/mysociety/alavetelitheme/blob/master/spec/alavetelitheme_spec.rb#L4), which for some reason it can't find with Rails 5 on CI.

**Comment by garethrees** [comment]
ebe782bed29c7b17c8b7a8909a29a3e55feaca3b looks like a winner, but get a different error now:

```
  5) When filtering when not in test mode should not fail handling a bounce mail
     Failure/Error: expect(xc.err).to eq("")
     
       expected: ""
            got: "FactoryBot::DuplicateDefinitionError: Factory already registered: draft_info_request_batch\n  /home/...\n  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:81:in `<top (required)>'\n"
     
       (compared using ==)
     
       Diff:
       @@ -1 +1,54 @@
       +FactoryBot::DuplicateDefinitionError: Factory already registered: draft_info_request_batch
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/decorator.rb:10:in `method_missing'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/decorator/disallows_duplicates_registry.rb:6:in `register'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot.rb:94:in `block in register_factory'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot.rb:93:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot.rb:93:in `register_factory'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/syntax/default.rb:20:in `factory'
       +  /home/travis/build/mysociety/alaveteli/spec/factories/alaveteli_pro/draft_info_request_batches.rb:3:in `block in <top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/syntax/default.rb:49:in `instance_eval'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/syntax/default.rb:49:in `run'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/syntax/default.rb:7:in `define'
       +  /home/travis/build/mysociety/alaveteli/spec/factories/alaveteli_pro/draft_info_request_batches.rb:2:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:287:in `load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:287:in `block in load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:287:in `load'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/find_definitions.rb:20:in `block (2 levels) in find_definitions'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/find_definitions.rb:19:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/find_definitions.rb:19:in `block in find_definitions'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/find_definitions.rb:15:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot-4.10.0/lib/factory_bot/find_definitions.rb:15:in `find_definitions'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/factory_bot_rails-4.10.0/lib/factory_bot_rails/railtie.rb:21:in `block in <class:Railtie>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/lazy_load_hooks.rb:49:in `each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `instance_exec'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `run'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:55:in `block in run_initializers'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
       +  /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:54:in `run_initializers'
       +  /home/travis/build/mysociety/alaveteli/vendor/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application.rb:352:in `initialize!'
       +  /home/travis/build/mysociety/alaveteli/config/environment.rb:6:in `<top (required)>'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:118:in `require'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:118:in `load_rails'
       +  /home/travis/build/mysociety/alaveteli/lib/mail_handler/reply_handler.rb:122:in `record_bounce'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:49:in `block (2 levels) in main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:48:in `each'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:48:in `block in main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:33:in `chdir'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:33:in `main'
       +  /home/travis/build/mysociety/alaveteli/script/handle-mail-replies.rb:81:in `<top (required)>'
       
     # ./spec/script/handle-mail-replies_spec.rb:23:in `block (3 levels) in <top (required)>'
```

**Comment by garethrees** [comment]
I'm going to try to summarise what I think is happening here.

## Why do we use `script/handle-mail-replies`?

Since `team@` is the Reply-to address for informational messages sent by the site, it receives a number of unwanted Out-of-office messages. So we filter mail to `team@` through this script, which discards the OOFs and forwards the rest on to `team_delivery@`.

We do this for a couple of other addresses too, but the intent is the same.

`script/handle-mail-replies` just calls `script/handle-mail-replies.rb`, which is where all of the action happens.

## How does `script/handle-mail-replies.rb` work?

`script/handle-mail-replies.rb` is a _plain Ruby_ script – we execute it directly rather than through `rails runner`. It specifically cites not wanting to load rails unless we need to, presumably for performance reasons. Outright speed isn't important for this – memory is the main concern.

The script loads a minimal set of libraries and config files to operate.

It has a single `main` method which has some logic to delegate to the correct `MailHandler` or `MailHandler::ReplyHandler` method. There's a bit of extra logic for a "test mode" which I'll get back to later.

The only thing that requires the full Rails stack seems to be `MailHandler::ReplyHandler.record_bounce`. This is so that it can record a bounce against a specific `User` record. It loads Rails by requiring `config/boot` and `config/environment`.

## Test Mode

To test the script, we actually shell out and call it (via `ExternalCommand`) as if it were being used in production, but with an extra `--test` argument.

Setting `--test` mostly just prevents the message getting forwarded on to `team_delivery@`, which is `postmaster@localhost` in test mode.

> Aside: Travis uses `config/test.yml` as its `config/general.yml`. Is that true when running tests locally?

The interesting part of the failing spec for us is the `else` case here:

```ruby
pfas = MailHandler::ReplyHandler.permanently_failed_addresses(message)
if !pfas.empty?
  if in_test_mode
    puts pfas
  else
    pfas.each do |pfa|
      MailHandler::ReplyHandler.record_bounce(pfa, raw_message)
    end
  end
  return 1
end
```

As we haven't passed `--test` in, we actually end up loading Rails via `.record_bounce`. Presumably, because our `RAILS_ENV` is now `test`, this also ends up loading the test suite, re-loading the Factories in to the "original" context, so we get the `FactoryBot::DuplicateDefinitionError`.

**Comment by garethrees** [comment]
I've tried running the specs in a Xenial VM – they pass. Travis does use RVM, but I haven't ruled that out yet.

It's not immediately obvious to me how we could refactor the specs to avoid the problem.

We could pull most of the logic out of the script in to `lib`:

```ruby
# script
# Extract all logic to MailHandler and just use the script to read STDIN.
def main
  Dir.chdir($alaveteli_dir) do
    raw_message = $stdin.read
    MailHandler.handle_reply(raw_message)
  end
end

# lib
# Same behaviour as before
module MailHandler
  def handle_reply(raw_message)
    message = MailHandler.mail_from_raw_email(raw_message)

    # …

    pfas = MailHandler::ReplyHandler.permanently_failed_addresses(message)
    if !pfas.empty?
      if in_test_mode
        puts pfas
      else
        pfas.each do |pfa|
          MailHandler::ReplyHandler.record_bounce(pfa, raw_message)
        end
      end
      return 1
    end

    # …
  end
end

# spec/lib
# Stub out calls so that we don't call the underlying sendmail stuff – test
# all that elsewhere.
subject { handle_reply(raw_message) }

context 'with a bounce'
  let(:raw_message) { load_file_fixture('track-response-exim-bounce.email') }

  it 'records the bounce' do
    expect(ReplyHandler).to receive(:record_bounce).with('bounce@example.com', raw_message)
    subject
  end

  it 'returns 1' do
    expect(subject).to eq(1)
  end
end
```

However, at the end of the day we'd still want an "integration" test where we actually run the script and check that there are no errors. The specs for this wouldn't change, and we'd end up running effectively the same code.

```ruby
# spec/script
describe "when not in test mode" do

  it "should not fail handling a bounce mail" do
    xc = ExternalCommand.new("script/handle-mail-replies",
                             { :stdin_string => load_file_fixture("track-response-exim-bounce.email") })
    xc.run
    expect(xc.err).to eq("")
  end

  it 'should not fail handling a UTF8 encoded mail' do
    xc = ExternalCommand.new("script/handle-mail-replies",
                             { :stdin_string => load_file_fixture("russian.email") })
    xc.run
    expect(xc.err).to eq("")
  end

end
```

**Comment by gbp** [comment]
How about changing: https://github.com/mysociety/alaveteli/blob/develop/lib/mail_handler/reply_handler.rb#L122

To:
```ruby
self.load_rails unless Object.const_defined?('Rails')
```

Untested but should stop the environment from being reloaded when its not needed. And probably won't need to change the existing specs that more if at all.

**Comment by gbp** [comment]
This spec passed on Travis when running #5202 guessing commit 4450e198a734f2eb56143f18f4e08772738866be might be responsible?
