### ISSUE TITLE
[ERROR] sessions#new (ActionView::Template::Error) "Couldn't find TrackThing with 'id'=144315"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5204]
```
An ActionView::Template::Error occurred in sessions#new:

Couldn't find TrackThing with 'id'=144315
app/views/track/_already_tracking.html.erb:1:in `_app_views_track__already_tracking_html_erb__3382247029810049597_70122600881740'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/sign_in?token=REDACTED
* HTTP Method: GET
* Parameters : {"token"=>"REDACTED", "controller"=>"users/sessions", "action"=>"new"}
* Timestamp : 2019-05-24 09:21:24 +0100
* Rails root : /REDACTED/alaveteli-2019-05-21T08-47-40

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"flash"=>
{"discard"=>[],
"flashes"=>
{"notice"=>
{"partial"=>"track/already_tracking",
"locals"=>{"track_thing_id"=>144315}}}},
"remember_me"=>false}

-------------------------------
Backtrace:
-------------------------------

app/views/track/_already_tracking.html.erb:1:in `_app_views_track__already_tracking_html_erb__3382247029810049597_70122600881740'
app/helpers/application_helper.rb:140:in `render_flash'
app/views/layouts/default.html.erb:66:in `_app_views_layouts_default_html_erb___714772268680219854_70122727033600'
app/controllers/application_controller.rb:192:in `block (2 levels) in render_exception'
app/controllers/application_controller.rb:191:in `render_exception'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
