### ISSUE TITLE
[ERROR] request#get_attachment (ArgumentError) "string contains null byte"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5209]
```
An ArgumentError occurred in request#get_attachment:

string contains null byte
app/models/incoming_message.rb:540:in `block in extract_attachments!'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/request/217476/response/552184/attach/4/Canal%20River%20c%20365708.pdf
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"get_attachment", "id"=>"217476", "incoming_message_id"=>"552184", "part"=>"4", "file_name"=>"Canal River c 365708.pdf"}
* Timestamp : 2019-05-26 16:31:23 +0100
* Rails root : /REDACTED/alaveteli-2019-05-21T08-47-40

-------------------------------
Backtrace:
-------------------------------

app/models/incoming_message.rb:540:in `block in extract_attachments!'
app/models/incoming_message.rb:538:in `each'
app/models/incoming_message.rb:538:in `extract_attachments!'
app/models/incoming_message.rb:98:in `block in parse_raw_email!'
app/models/incoming_message.rb:97:in `parse_raw_email!'
app/models/foi_attachment.rb:92:in `rescue in body'
app/models/foi_attachment.rb:79:in `body'
app/models/foi_attachment.rb:107:in `default_body'
app/controllers/request_controller.rb:657:in `get_attachment'
app/controllers/request_controller.rb:629:in `cache_attachments'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/4339 and https://github.com/mysociety/alaveteli/issues/4339.

Loads of these recently – seems to have started on WDTK on 15 May 2019.

**Comment by garethrees** [comment]
Lots of the hits on URLs are from bingbot / baidu spider, but there look like some "genuine" attempts to access attachments that result in a `500`.

**Comment by garethrees** [comment]
Looking at https://www.whatdotheyknow.com/request/archived_inquiry_reports_for_200#incoming-532536 locally, I get:

```ruby
attrs[:filename]
# => "Tender Loving Care Trust (Europe).pdf\u0000"
```

Though interestingly [that attachment works fine](https://www.whatdotheyknow.com/request/201280/response/532536/attach/3/Tender%20Loving%20Care%20Trust%20Europe.pdf) in production; a [different attachment](https://www.whatdotheyknow.com/request/201280/response/532536/attach/11/Whitleigh%20Community%20Association.pdf) is failing.

Hacking this in locally fixed the error preventing the request page loading, and allowed the downloading of all attachments:

```diff
diff --git a/app/models/incoming_message.rb b/app/models/incoming_message.rb
index ab2c6beed..3553e8b7f 100644
--- a/app/models/incoming_message.rb
+++ b/app/models/incoming_message.rb
@@ -533,9 +533,12 @@ class IncomingMessage < ApplicationRecord
   def extract_attachments!
     force = true
     _mail = raw_email.mail!
     attachment_attributes = MailHandler.get_attachment_attributes(_mail)
     attachments = []
     attachment_attributes.each do |attrs|
+      attrs[:filename].try(:strip!)
       attachment = self.foi_attachments.find_or_create_by(:hexdigest => attrs[:hexdigest])
       attachment.update_attributes(attrs)
       attachment.save!
```

The best place to actually do this is probably in `FoiAttachment#filename=`, but I'm not sure that we want to call `strip`. The original attachment's filename may start with a space, so I think we should preserve that to avoid confusion when comparing against the raw email (even though its annoying).

It seems like we've fixed this problem for the attachment body in f18c5b9f.

**Comment by garethrees** [comment]
> Though interestingly [that attachment works fine](https://www.whatdotheyknow.com/request/201280/response/532536/attach/3/Tender%20Loving%20Care%20Trust%20Europe.pdf) in production; a [different attachment](https://www.whatdotheyknow.com/request/201280/response/532536/attach/11/Whitleigh%20Community%20Association.pdf) is failing.

Expanding on this a little…

I'd thought that the first attachment may have been cached some time ago, before null bytes in the filename were a problem, and the latter just hadn't been cached. Many of the filenames include a `"\u0000"`:

```
attachment_attributes.map { |h| h[:filename] }
=> [nil,
 "Tender Loving Care Trust (Europe).pdf\u0000",
 "Torbay Churches Homeless Trust.pdf",
 "Trustee Eligibility (IR Pub Date 02 06 05).pdf\u0000",
 "Union Chapel Project (IR Pub Date 02 06 05).pdf\u0000",
 "Unregistered organisation.pdf",
 "Wellingborough Afro-Caribbean Association.pdf",
 "Welsh Refugee Council.pdf",
 "Whipton Institute, The (IR Pub Date 07 07 05).pdf\u0000",
 "Whitleigh Community Association.pdf",
 "Wicksteed Village Trust (IR Pub Date 07 04 05).pdf\u0000",
 "WJEC CBAC Limited (IR Pub Date 07 07 05).pdf\u0000",
 "World Renewable Energy Network Limited.pdf"]
```

Though, it looks like all files were on 24 June 2014:

```
pp IncomingMessage.find(532536).foi_attachments.pluck(:id, :filename, :created_at);nil
[[988128, "attachment.html", Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988129,
  "Tender Loving Care Trust (Europe).pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988130,
  "Torbay Churches Homeless Trust.pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988131,
  "Trustee Eligibility (IR Pub Date 02 06 05).pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988132,
  "Union Chapel Project (IR Pub Date 02 06 05).pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988133,
  "Unregistered organisation.pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988134,
  "Wellingborough Afro-Caribbean Association.pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988135, "Welsh Refugee Council.pdf", Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988136,
  "Whipton Institute, The (IR Pub Date 07 07 05).pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988137,
  "Whitleigh Community Association.pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988138,
  "Wicksteed Village Trust (IR Pub Date 07 04 05).pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988139,
  "WJEC CBAC Limited (IR Pub Date 07 07 05).pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00],
 [988140,
  "World Renewable Energy Network Limited.pdf",
  Tue, 24 Jun 2014 14:05:57 BST +01:00]]
```

It looks like what's actually happened is that we've lost the cached file on disk (or, it was never successfully created, even though the digest was stored):

```
irb(main):007:0> FoiAttachment.find(988137).hexdigest
=> "7f428916b8bcd74b142f4965d77ff556"

foi@owl:/data/vhost/www.whatdotheyknow.com/alaveteli$ stat cache/attachments_production/7f4/7f428916b8bcd74b142f4965d77ff556
stat: cannot stat 'cache/attachments_production/7f4/7f428916b8bcd74b142f4965d77ff556': No such file or directory
```

So, when we try to download the attachment again we try to create the file on disk and this time we get an exception due to the null bytes in the filename.
