### ISSUE TITLE
[ERROR] draft_info_request_batches#update (NoMethodError) "undefined method `draft_info_request_batches' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5219]
```
A NoMethodError occurred in draft_info_request_batches#update:

undefined method `draft_info_request_batches' for nil:NilClass
app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:11:in `update'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/draft_info_request_batches/758
* HTTP Method: PUT
* Parameters : {"_method"=>"put", "alaveteli_pro_draft_info_request_batch"=>{"body"=>"Dear [Authority name],\r\n\r\nLetterText\r\n\r\nYours faithfully,\r\n\r\nNaomi", "embargo_duration"=>"3_months", "public_body_ids"=>["65"], "title"=>"Local Council Batch Test 1"}, "authenticity_token"=>"REDACTED", "preview"=>"false", "utf8"=>"✓", "controller"=>"alaveteli_pro/draft_info_request_batches", "action"=>"update", "id"=>"758"}
* Timestamp : 2019-05-30 05:11:29 +0100
* Rails root : /REDACTED/alaveteli-2019-05-29T14-46-13

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"en"}


-------------------------------
Backtrace:
-------------------------------

app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb:11:in `update'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Looks like an attempt to update a batch draft while logged out?

**Comment by garethrees** [comment]
Had another of these today – same deal; no user in the session.

**Comment by garethrees** [comment]
Another again today.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
