### ISSUE TITLE
[ERROR] info_requests#create (NoMethodError) "undefined method `title' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5220]
```
A NoMethodError occurred in info_requests#create:

undefined method `title' for nil:NilClass
app/models/info_request.rb:445:in `from_draft'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/info_requests
* HTTP Method: POST
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"REDACTED", "info_request"=>{"public_body_id"=>"54575", "title"=>"Test - no reply required"}, "outgoing_message"=>{"body"=>"Dear Llaneilian Community Council, Anglesey,\r\n\r\nTest\r\n\r\nYours faithfully,\r\n\r\nNaomi"}, "embargo"=>{"embargo_duration"=>"3_months"}, "preview"=>"false", "controller"=>"alaveteli_pro/info_requests", "action"=>"create"}
* Timestamp : 2019-05-30 04:10:46 +0100
* Rails root : /REDACTED/alaveteli-2019-05-29T14-46-13

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false,
"_csrf_token"=>"REDACTED",
"user_id"=>181548,
"ttl"=>"2019-05-30T03:48:15.234+01:00",
"post_redirect_token"=>"gbbrmvrwrb33z35za0e"}

-------------------------------
Backtrace:
-------------------------------

app/models/info_request.rb:445:in `from_draft'
app/controllers/alaveteli_pro/info_requests_controller.rb:98:in `load_data_from_draft'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
