### ISSUE TITLE
[Rails 5] Can't load AttachmentToHTML

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5234]
Part of https://github.com/mysociety/alaveteli/issues/3969

**Comment by gbp** [comment]
Exception: https://groups.google.com/a/mysociety.org/forum/#!topic/cron-alaveteli/ZImmawUO7SI

And running production locally:
```
❯ RAILS_ENV=production rails5 c
Loading production environment (Rails 5.0.7)
[1] pry(main)> cd AttachmentToHTML
Error: Bad object path: "AttachmentToHTML"
Failed trying to resolve: "AttachmentToHTML"
Exception: #<NameError: uninitialized constant AttachmentToHTML>
```

**Comment by gbp** [comment]
Reverting 64165e9 gets this working again so we may have to look at #5211 again.

**Comment by gbp** [comment]
I've confirmed the "fix" in #5211 only worked because it disabled eager loading of our ./lib directory.

### Problem

1. We have the Alaveteli theme installed in `./lib/themes`
2. Themes can include RSpec files and other files we don't want to load in production
3. RSpec shouldn't be loaded in development or production
4. Additionally, in production because `eager_load` is enabled, a `No such file to load -- spec_helper (LoadError)` is raised when trying to load the RSpec files.
5. For whatdotheyknow-theme, we also get a `uninitialized constant PublicBodyCategories (NameError)` exception due to us not following the [0.20 upgrade notes](https://github.com/mysociety/alaveteli/blob/master/doc/CHANGES.md#version-020).

Note: If running locally and using the `./script/switch-theme` the theme is symlinked and it doesn't seem the theme is eagerly loaded at all. This is probably why we thought #5211 worked.

### How eager loading works

Then I went through the Rails source to see why...
1. The eager loading process is described in a comment - https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/application.rb#L52
2. After the application has been initialised, if eager load is configured, it loops over the `eager_load_namespaces` and calls `eager_load!` for each namespace - https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/application/finisher.rb#L56-L61
3. Namespaces include the Rails modules (ActiveRecord, ActionController...) but also includes the Rails::Application class defined in our `./config/application.rb` - https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/engine.rb#L358
4. For Rails::Application class `#eager_load!` is defined as - https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/engine.rb#L472-L479
5. Looking at the method source we can tell it is expecting eager load paths to be strings and not globs
6. Finally `require_dependency` is called for each Ruby file found under the eager load path.

### Options

We need to ignore any `pubic_body_categories_[locale].rb` and RSpec files in the theme so they aren't eagerly loaded. I'm going to refer to these files as "non-production theme files" below.

1. ~Override `require_dependency` to ignore non-production theme files.~ Dismissed - This is too low level and would require us to patch an ActiveSupport class. the overridden method would be used when other namespaces our eagerly loaded so has a great risk of something going wrong.
2. Override `#eager_load!` in `./config/application.rb` to ignore all theme files. This would mean the theme wouldn't be eagerly loaded but give we have `./config/initializers/theme_loader.rb` there shouldn't be an noticeable impact: 
```diff
diff --git a/config/application.rb b/config/application.rb
index a2df3690b..9c6507bda 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -92,7 +92,12 @@ module Alaveteli
         config.eager_load_paths.each do |load_path|
           matcher = /\A#{Regexp.escape(load_path.to_s)}\/(.*)\.rb\Z/
           Dir.glob("#{load_path}/**/*.rb").sort.each do |file|
-            require_dependency file.sub(matcher, '\1')
+            dependency = file.sub(matcher, '\1')
+            if dependency =~ %r[\Athemes/]
+              #noop
+            else
+              require_dependency dependency
+            end
           end
         end
       end
```
3. Override `#eager_load!` in `./config/application.rb` to ignore just non-production theme files. As above but this also has the advantage of being able to display a deprecation warning for old `pubic_body_categories_[locale].rb` files
```diff
diff --git a/config/application.rb b/config/application.rb
index a2df3690b..3290b1c02 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -92,7 +92,17 @@ module Alaveteli
         config.eager_load_paths.each do |load_path|
           matcher = /\A#{Regexp.escape(load_path.to_s)}\/(.*)\.rb\Z/
           Dir.glob("#{load_path}/**/*.rb").sort.each do |file|
-            require_dependency file.sub(matcher, '\1')
+            dependency = file.sub(matcher, '\1')
+            if dependency =~ %r[\Athemes/.*?/public_body_categories_.*\Z]
+              warn %q([DEPRECATION] pubic_body_categories_[locale].rb files were
+                      deprecated in 0.20. Please follow the 0.20 upgrade notes
+                      and remove any references to PublicBodyCategories your
+                      theme).squish
+            elsif dependency =~ %r[\Athemes/.*?/spec/.*\Z]
+              #noop
+            else
+              require_dependency dependency
+            end
           end
         end
       end
```
4. Move the themes directory outside of `./lib`

Note: While override `#eager_load!` isn't ideal the method hasn't changed between [5.0](https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/engine.rb#L472-L479), [5.1](https://github.com/rails/rails/blob/5-1-stable/railties/lib/rails/engine.rb#L472-L479) and [5.2](https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/engine.rb#L474-L481)

**Comment by gbp** [comment]
@garethrees any thoughts on the options above?

**Comment by lizconlan** [comment]
Or - although possibly and option of last resort - we could bypass `eager_loading` by adding this to our config to reinstate the old behaviour:

```
config.enable_dependency_loading = true
```

h/t https://collectiveidea.com/blog/archives/2016/07/22/solutions-to-potential-upgrade-problems-in-rails-5

**Comment by garethrees** [comment]
Option 2, or setting `enable_dependency_loading = true` sound like the best options out of the suggestions above.

That said, I managed to "fix" the problem (in the sense of not getting the error above) by mimicking the `autoload_paths` for the `eager_load_paths`:

```diff
diff --git a/config/application.rb b/config/application.rb
index 5001e53fa..5be073d81 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -86,7 +86,11 @@ module Alaveteli
     config.autoload_paths << "#{Rails.root.to_s}/lib/health_checks"
 
     if rails5?
-      config.eager_load_paths << "#{Rails.root}/lib/**/*.rb"
+      config.eager_load_paths << "#{Rails.root}/app/controllers/concerns"
+      config.eager_load_paths << "#{Rails.root}/app/models/concerns"
+      config.eager_load_paths << "#{Rails.root}/lib/mail_handler"
+      config.eager_load_paths << "#{Rails.root}/lib/attachment_to_html"
+      config.eager_load_paths << "#{Rails.root}/lib/health_checks"
     end
 
     # See Rails::Configuration for more options
```

```
$ RAILS_ENV=production BUNDLE_GEMFILE="Gemfile.rails5" be rails c
Loading production environment (Rails 5.0.7)
irb(main):001:0> AttachmentToHTML.to_html
ArgumentError: wrong number of arguments (given 0, expected 1..2)
        from /home/vagrant/alaveteli/lib/attachment_to_html/attachment_to_html.rb:13:in `to_html'
        from (irb):2
        from /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
        from /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

There's some more checking to do here, as I'm not sure the two behave identically. I tried running the specs with this diff:

```diff
diff --git a/config/application.rb b/config/application.rb
index 5001e53fa..a04c09e10 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -86,7 +86,11 @@ module Alaveteli
     config.autoload_paths << "#{Rails.root.to_s}/lib/health_checks"
 
     if rails5?
-      config.eager_load_paths << "#{Rails.root}/lib/**/*.rb"
+      config.eager_load_paths << "#{Rails.root}/app/controllers/concerns"
+      config.eager_load_paths << "#{Rails.root}/app/models/concerns"
+      config.eager_load_paths << "#{Rails.root}/lib/mail_handler"
+      config.eager_load_paths << "#{Rails.root}/lib/attachment_to_html"
+      config.eager_load_paths << "#{Rails.root}/lib/health_checks"
     end
 
     # See Rails::Configuration for more options
diff --git a/config/environments/test.rb b/config/environments/test.rb
index e6424ddde..f5d46cfcd 100644
--- a/config/environments/test.rb
+++ b/config/environments/test.rb
@@ -11,7 +11,7 @@ Rails.application.configure do
   # Do not eager load code on boot. This avoids loading your whole application
   # just for the purpose of running a single test. If you are using a tool that
   # preloads Rails for running tests, you may have to set it to true.
-  config.eager_load = false
+  config.eager_load = true
 
   if rails5?
     # Configure public file server for tests with Cache-Control for performance.
```

```
$ BUNDLE_GEMFILE="Gemfile.rails5" be rspec spec/lib/attachment_to_html/attachment_to_html_spec.rb

An error occurred while loading ./spec/lib/attachment_to_html/attachment_to_html_spec.rb.
Failure/Error: include HealthChecks::HealthCheckable

LoadError:
  Unable to autoload constant HealthCheckable, expected /home/vagrant/alaveteli/lib/health_checks/health_checkable.rb to define it
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:513:in `load_missing_constant'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:203:in `const_missing'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:544:in `load_missing_constant'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:203:in `const_missing'
# ./lib/health_checks/checks/days_ago_check.rb:5:in `<class:DaysAgoCheck>'
# ./lib/health_checks/checks/days_ago_check.rb:4:in `<module:Checks>'
# ./lib/health_checks/checks/days_ago_check.rb:3:in `<module:HealthChecks>'
# ./lib/health_checks/checks/days_ago_check.rb:2:in `<top (required)>'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:380:in `block in require_or_load'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:37:in `block in load_interlock'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:37:in `load_interlock'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:358:in `require_or_load'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:336:in `depend_on'
# /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:252:in `require_dependency'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:475:in `each'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:475:in `block in eager_load!'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:473:in `each'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:473:in `eager_load!'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/engine.rb:354:in `eager_load!'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:59:in `each'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `instance_exec'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `run'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:55:in `block in run_initializers'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:54:in `run_initializers'
# /home/vagrant/bundle/ruby/2.3.0/gems/railties-5.0.7/lib/rails/application.rb:352:in `initialize!'
# ./config/environment.rb:6:in `<top (required)>'
# ./spec/spec_helper.rb:28:in `require'
# ./spec/spec_helper.rb:28:in `<top (required)>'
# ./spec/lib/attachment_to_html/attachment_to_html_spec.rb:2:in `require'
# ./spec/lib/attachment_to_html/attachment_to_html_spec.rb:2:in `<top (required)>'
No examples found.


Finished in 0.00211 seconds (files took 15.27 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Making the following change allowed the spec to pass:

```diff
-      config.eager_load_paths << "#{Rails.root}/lib/health_checks"
+      config.eager_load_paths << "#{Rails.root}/lib/health_checks/**/*.rb"
```
```
$ BUNDLE_GEMFILE="Gemfile.rails5" be rspec spec/lib/attachment_to_html/attachment_to_html_spec.rb

Randomized with seed 59552
.........

Finished in 0.96368 seconds (files took 18.44 seconds to load)
9 examples, 0 failures
```

So, I guess what I'm saying here is I wonder if we can solve the problem by being more specific about our `eager_load_paths`, rather than just trying to load everything in `lib`?

**Comment by gbp** [comment]
> Or - although possibly and option of last resort - we could bypass `eager_loading` by adding this to our config to reinstate the old behaviour:
> 
> ```
> config.enable_dependency_loading = true
> ```

Okay this appears to work too. I'm curious why Rails 5 switched this on by default and if there a benefit to using eager loading for lib which we might miss. Other than possible small performance boost when the files are loaded I can't see any obvious reason to use it for lib.

I have created #5235 if this is done then we can look at enabling eager load for lib.

> So, I guess what I'm saying here is I wonder if we can solve the problem by being more specific about our eager_load_paths, rather than just trying to load everything in lib?

This is an option for subdirectories in lib, but there doesn't seem to be a large amount of Ruby files to really make it worth the hassle maintaining a list of eager load paths.
