### ISSUE TITLE
[ERROR]  admin_raw_email#show (NoMethodError) "undefined method `gsub' for nil:NilClass"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5251]
This is the holding pen code breaking when there's no subject line. I've put a temporary fix in place on the live server. (The referenced message was junk and has been deleted.)

```
A NoMethodError occurred in admin_raw_email#show:

  undefined method `gsub' for nil:NilClass
  app/models/info_request.rb:301:in `guess_by_incoming_subject'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/raw_emails/1380663
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_raw_email", "action"=>"show", "id"=>"1380663"}
  * Timestamp  : 2019-06-11 16:29:59 +0100

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"[FILTERED]",
   "locale"=>"en",
   "remember_me"=>false,
   "_csrf_token"=>"[FILTERED]",
   "user_id"=>[FILTERED],
   "ttl"=>"2019-06-11T16:29:55.213+01:00",
   "post_redirect_token"=>"[FILTERED]",
   "using_admin"=>1,
   "admin_name"=>"liz_conlan"}

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request.rb:301:in `guess_by_incoming_subject'
  app/controllers/admin_raw_email_controller.rb:30:in `block (2 levels) in show'
  app/controllers/admin_raw_email_controller.rb:12:in `show'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
Suggested fix:

`app/models/info_request.rb`
```diff
  def self.guess_by_incoming_subject(subject_line)
+   return [] unless subject_line
    # try to find a match on InfoRequest#title
```
