### ISSUE TITLE
[ERROR] admin_request#show (ActionView::Template::Error) "undefined class/module TMail::"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5263]
```
An ActionView::Template::Error occurred in admin_request#show:

  undefined class/module TMail::
  app/models/info_request_event.rb:330:in `params'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/122
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_request", "action"=>"show", "id"=>"122"}
  * Timestamp  : 2019-06-20 12:53:39 +0100

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request_event.rb:330:in `params'
  app/models/info_request_event.rb:343:in `params_diff'
  app/views/admin_request/show.html.erb:250:in `block (2 levels) in _app_views_admin_request_show_html_erb__1851816233347213155_70224032218060'
  app/models/concerns/admin_column.rb:28:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:24:in `each'
  app/models/concerns/admin_column.rb:24:in `for_admin_column'
  app/views/admin_request/show.html.erb:243:in `block in _app_views_admin_request_show_html_erb__1851816233347213155_70224032218060'
  app/views/admin_request/show.html.erb:215:in `_app_views_admin_request_show_html_erb__1851816233347213155_70224032218060'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
Related to #5262 & #5264
