### ISSUE TITLE
[ERROR] admin_request#show (ActionView::Template::Error) "undefined class/module PublicBodyTag"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#5265]
```
An ActionView::Template::Error occurred in admin_request#show:

  undefined class/module PublicBodyTag
  app/models/info_request_event.rb:330:in `params'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/697
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_request", "action"=>"show", "id"=>"697"}
  * Timestamp  : 2019-06-20 15:49:30 +0100
  * Rails root : [FILTERED]/alaveteli-2019-06-20T14-41-00

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request_event.rb:330:in `params'
  app/models/info_request_event.rb:343:in `params_diff'
  app/views/admin_request/show.html.erb:250:in `block (2 levels) in _app_views_admin_request_show_html_erb__1929189359940310185_69951266522200'
  app/models/concerns/admin_column.rb:28:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:24:in `each'
  app/models/concerns/admin_column.rb:24:in `for_admin_column'
  app/views/admin_request/show.html.erb:243:in `block in _app_views_admin_request_show_html_erb__1929189359940310185_69951266522200'
  app/views/admin_request/show.html.erb:215:in `_app_views_admin_request_show_html_erb__1929189359940310185_69951266522200'
```

**Comment by lizconlan** [comment]
In this case, this is a request from 2008. And one of the events (InfoRequestEvent: 2355) has embedded `PublicBodyTag` and `TMail` objects

**Comment by lizconlan** [comment]
Issue appears to predate the Rails 5 changes
