### ISSUE TITLE
[ERROR] dashboard#index (NoMethodError) "undefined method `url_title' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5271]
Had a couple of these through on 2019-06-08 https://groups.google.com/a/mysociety.org/d/msg/cron-alaveteli/dKYeiRmjAXI/8X_S9E6zAgAJ

```
A NoMethodError occurred in dashboard#index:

undefined method `url_title' for nil:NilClass
app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/dashboard", "action"=>"index"}
* Timestamp : 2019-06-08 01:38:37 +0100
* Server : owl
* Rails root : /REDACTED/alaveteli-2019-05-29T14-46-13

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false,
"_csrf_token"=>"REDACTED",
"user_id"=>105039,
"ttl"=>"2019-06-08T01:28:38.587+01:00",
"post_redirect_token"=>"mkseyo69pgh4rb9xla4"}

-------------------------------
Backtrace:
-------------------------------

app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'
app/views/alaveteli_pro/dashboard/_to_do_item.html.erb:3:in `_app_views_alaveteli_pro_dashboard__to_do_item_html_erb__2527370035072031727_70166043681600'
app/views/alaveteli_pro/dashboard/_to_do_list.html.erb:7:in `_app_views_alaveteli_pro_dashboard__to_do_list_html_erb___1733141199699051590_70166032175860'
app/views/alaveteli_pro/dashboard/index.html.erb:29:in `_app_views_alaveteli_pro_dashboard_index_html_erb___2761001625685838149_70166039615980'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'

**Comment by garethrees** [comment]
Had some more of these yesterday:

```
An ActionView::Template::Error occurred in dashboard#index:

undefined method `url_title' for nil:NilClass
app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/dashboard", "action"=>"index"}
* Timestamp : 2020-02-16 21:34:55 +0000
* Rails root : /[FILTERED]/alaveteli-2020-02-12T11-37-00

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"[FILTERED]",
"locale"=>"en",
"remember_me"=>false,
"user_id"=>152602,
"ttl"=>"2020-02-16T21:34:55.217+00:00",
"post_redirect_token"=>"aic1ap3ezz3oe85y2tz"}

-------------------------------
Backtrace:
-------------------------------

app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'
app/views/alaveteli_pro/dashboard/_to_do_item.html.erb:3:in `_app_views_alaveteli_pro_dashboard__to_do_item_html_erb__4281347410184978190_69864569606700'
app/views/alaveteli_pro/dashboard/_to_do_list.html.erb:7:in `_app_views_alaveteli_pro_dashboard__to_do_list_html_erb___501398310198588606_69864556824060'
app/views/alaveteli_pro/dashboard/index.html.erb:29:in `_app_views_alaveteli_pro_dashboard_index_html_erb__3440226537559254547_69864648125760'
app/controllers/application_controller.rb:110:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Another today:

```
An ActionView::Template::Error occurred in dashboard#index:

undefined method `url_title' for nil:NilClass
app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/dashboard", "action"=>"index"}
* Timestamp : 2020-04-12 13:38:18 +0100
* Rails root : /FILTEREDalaveteli-2020-04-07T09-48-49

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"en",
"remember_me"=>false,
"user_id"=>152602,
"ttl"=>"2020-04-12T13:38:02.755+01:00",
"post_redirect_token"=>"FILTERED",
"_csrf_token"=>"FILTERED",
"using_admin"=>1,
"admin_name"=>"FILTERED"}


-------------------------------
Backtrace:
-------------------------------

app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'
app/views/alaveteli_pro/dashboard/_to_do_item.html.erb:3:in `_app_views_alaveteli_pro_dashboard__to_do_item_html_erb__1430039740885194982_70085272950140'
app/views/alaveteli_pro/dashboard/_to_do_list.html.erb:7:in `_app_views_alaveteli_pro_dashboard__to_do_list_html_erb__3537041086179935537_70085127492260'
app/views/alaveteli_pro/dashboard/index.html.erb:29:in `_app_views_alaveteli_pro_dashboard_index_html_erb__2881157513247977648_70085096476640'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
We're still getting these. I also had this local too, resovled by

```
u = User.find(8)
u.info_requests.includes(:request_summary, :embargo).find_each do |r|
  s = r.request_summary
  s.request_summary_categories = r.request_summary_categories
end

```

**Comment by gbp** [comment]
This seems to be due to summary categories getting out of sync - also effects batch summaries.

Resources which are out of sync
```ruby
resources = u.info_requests.select(&:should_summarise?) + u.info_request_batches
resources.select do |r|
  s = r.request_summary
  s.request_summary_categories != r.request_summary_categories
end
```

For the latest user (ID 152602) showing this problem a batch was out of sync. Fixed for this user by setting
```ruby
request_summary.request_summary_categories = info_request_batch.request_summary_categories
```

Confusing I see no difference in what is return by `request_summary.request_summary_categories`.

**Comment by garethrees** [comment]
Seeing this on Netherlands too:

```
An ActionView::Template::Error occurred in dashboard#index:

  undefined method `url_title' for nil:NilClass
  app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'


-------------------------------
Request:
-------------------------------

* URL        : https://www.wob-knop.nl/alaveteli_pro
* HTTP Method: GET
* IP address : FILTERED
* Parameters : {"controller"=>"alaveteli_pro/dashboard", "action"=>"index"}
* Timestamp  : 2020-05-25 17:04:53 +0200
* Server : FILTERED
* Rails root : /FILTERED/alaveteli-2020-05-07T10-56-02
* Process: 5348

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
 "locale"=>"nl",
 "remember_me"=>false,
 "_csrf_token"=>"FILTERED",
 "user_id"=>4,
 "ttl"=>"2020-05-25T17:04:53.365+02:00",
 "post_redirect_token"=>"FILTERED",
 "using_admin"=>1,
 "admin_name"=>"FILTERED"}

-------------------------------
Backtrace:
-------------------------------

app/models/alaveteli_pro/to_do_list/overdue_request.rb:26:in `url'
app/views/alaveteli_pro/dashboard/_to_do_item.html.erb:3:in `_app_views_alaveteli_pro_dashboard__to_do_item_html_erb___4558605711916680939_47092879045020'
app/views/alaveteli_pro/dashboard/_to_do_list.html.erb:7:in `_app_views_alaveteli_pro_dashboard__to_do_list_html_erb__4409870942343580907_47092879071520'
app/views/alaveteli_pro/dashboard/index.html.erb:29:in `_app_views_alaveteli_pro_dashboard_index_html_erb___205441158598252957_47092879697160'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
…and now on Belgium…

```
An ActionView::Template::Error occurred in dashboard#index:

undefined method `url_title' for nil:NilClass
app/models/alaveteli_pro/to_do_list/overdue_request.rb:25:in `url'


-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/alaveteli_pro
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/dashboard", "action"=>"index"}
* Timestamp : 2021-08-05 00:38:47 +0200
* Rails root : /data/vhost/belgium.alaveteli.org/alaveteli-2021-08-03T10-25-06

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"fr_BE",
"remember_me"=>false,
"_csrf_token"=>"tREDACTED",
"user_id"=>19,
"ttl"=>"2021-08-05T00:38:36.060+02:00",
"post_redirect_token"=>"REDACTED",
"using_admin"=>1,
"admin_name"=>"REDACTED",
"user_circumstance"=>"login_as"}

-------------------------------
Backtrace:
-------------------------------

app/models/alaveteli_pro/to_do_list/overdue_request.rb:25:in `url'
app/views/alaveteli_pro/dashboard/_to_do_item.html.erb:3:in `_app_views_alaveteli_pro_dashboard__to_do_item_html_erb___3780458359751341484_107860'
app/views/alaveteli_pro/dashboard/_to_do_list.html.erb:7:in `_app_views_alaveteli_pro_dashboard__to_do_list_html_erb__1243157874734284774_107840'
app/views/alaveteli_pro/dashboard/index.html.erb:29:in `_app_views_alaveteli_pro_dashboard_index_html_erb__4223575336444861833_107760'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by schlos** [comment]
I can reproduce same problem on imamopravoznati (HR):

```
An ActionView::Template::Error occurred in dashboard#index:

  undefined method `url_title' for nil:NilClass
  app/models/alaveteli_pro/to_do_list/new_response.rb:25:in `url'
```

It happens when user tries to open Pro Dashboard (i.e. https://imamopravoznati.org/alaveteli_pro).

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
