### ISSUE TITLE
[ERROR] general#frontpage (REXML::ParseException) "Missing end tag for 'content:encoded'

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5420]
```
A REXML::ParseException occurred in general#frontpage:

Missing end tag for 'content:encoded' (got "dc:creator")
Line: 252
Position: 33488
Last 80 unconsumed characters:

app/controllers/general_controller.rb:61:in `get_blog_content'

-------------------------------
Request:
-------------------------------

* URL : https://www.asktheeu.org/
* HTTP Method: GET
* Parameters : {"controller"=>"general", "action"=>"frontpage"}
* Timestamp : 2019-10-21 20:05:31 +0200
* Rails root : /REDACTED/eu.alaveteli.org/alaveteli-2019-09-02T14-31-54

-------------------------------
Backtrace:
-------------------------------

app/controllers/general_controller.rb:61:in `get_blog_content'
lib/themes/asktheeu-theme/lib/controller_patches.rb:64:in `blog_cache'
lib/themes/asktheeu-theme/lib/controller_patches.rb:21:in `frontpage'
app/controllers/application_controller.rb:120:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Looks like they've missed a closing tag on a blog post.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
