### ISSUE TITLE
[ERROR] services#other_country_message (NoMethodError) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5430]
```
A NoMethodError occurred in services#other_country_message:

undefined method `[]' for nil:NilClass
lib/alaveteli_geoip.rb:73:in `iso_code'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/country_message
* HTTP Method: GET
* Parameters : {"controller"=>"services", "action"=>"other_country_message"}
* Timestamp : 2019-10-24 22:20:41 +0100
* Rails root : /REDACTED/www.whatdotheyknow.com/alaveteli-2019-10-24T09-16-33

-------------------------------
Backtrace:
-------------------------------

lib/alaveteli_geoip.rb:73:in `iso_code'
lib/alaveteli_geoip.rb:68:in `country_code_from_geoip'
lib/alaveteli_geoip.rb:48:in `country_code_from_ip'
lib/alaveteli_geoip.rb:17:in `country_code_from_ip'
app/controllers/application_controller.rb:481:in `country_from_ip'
app/controllers/services_controller.rb:13:in `other_country_message'
app/controllers/application_controller.rb:110:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by gbp** [comment]
Loads of these errors today which resulted in the linked PR.
