### ISSUE TITLE
[ERROR] admin_public_body#update (ActionController::InvalidAuthenticityToken) 

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5435]
A strange instance of https://github.com/mysociety/alaveteli/issues/4484.

Note that we hit `app/controllers/admin_controller.rb:14:in `handle_unverified_request'`

```
An ActionController::InvalidAuthenticityToken occurred in admin_public_body#update:

ActionController::InvalidAuthenticityToken
app/controllers/admin_controller.rb:14:in `handle_unverified_request'

-------------------------------
Request:
-------------------------------

* URL : https://www.infoprovsechny.cz/admin/bodies/3352
* HTTP Method: PUT
* Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"REDACTED", "public_body"=>{"locale"=>"cs", "name"=>"Město Libáň", "short_name"=>"", "request_email"=>"REDACTED@REDACTED.cz", "publication_scheme"=>"", "notes"=>"", "tag_string"=>"", "home_page"=>"", "disclosure_log"=>"", "last_edit_comment"=>""}, "commit"=>"Save", "action"=>"update", "controller"=>"admin_public_body", "id"=>"3352"}
* Timestamp : 2019-10-30 11:41:33 +0100
* Rails root : /REDACTED/czechia.alaveteli.org/alaveteli-2019-10-28T12-46-20

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_controller.rb:14:in `handle_unverified_request'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by schlos** [comment]
Reproducible also in Croatian Alaveteli, details in: https://github.com/codeforcroatia/imamopravoznati/issues/80

**Comment by garethrees** [comment]
@schlos there a [quite a few different places](https://github.com/mysociety/alaveteli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ActionController%3A%3AInvalidAuthenticityToken) this happens; I'm not sure this particular issue is the same as yours, as this passes through  `handle_unverified_request`. Doesn't look like that line is included in your backtrace.

I think https://github.com/mysociety/alaveteli/issues/4484 is probably most relevant for you, which is an issue to collect all the different types of `InvalidAuthenticityToken` errors.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
