### ISSUE TITLE
[ERROR] admin_request#show (ActionView::Template::Error) "not delegated"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5463]
```
An ActionView::Template::Error occurred in admin_request#show:

  not delegated
  app/models/info_request_event.rb:340:in `params'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/553276
  * HTTP Method: GET
```

**Comment by gbp** [comment]
This was seen post deploy of #3970 when accessing certain requests in the Admin UI

Related to #5464 

Rails backtrace
```
ArgumentError:
  not delegated
# ruby/2.6.0/delegate.rb:395:in `__getobj__'
# ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/attribute.rb:59:in `changed_in_place?'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/attribute.rb:80:in `with_type'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/legacy_yaml_adapter.rb:25:in `block in convert'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/legacy_yaml_adapter.rb:21:in `each'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/legacy_yaml_adapter.rb:21:in `convert'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/legacy_yaml_adapter.rb:10:in `convert'
# ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/core.rb:358:in `init_with'
```

Inspecting closer this appears to be an issue with `ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter`
