### ISSUE TITLE
 [ERROR] track#track_list (RuntimeError) "unknown request list view all"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5466]
```
A RuntimeError occurred in track#track_list:

unknown request list view all
app/controllers/track_controller.rb:42:in `track_list'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/feed/list/all
* HTTP Method: GET
* Parameters : {"view"=>"all", "controller"=>"track", "action"=>"track_list", "feed"=>"feed"}
* Timestamp : 2019-11-09 09:34:53 +0000
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2019-11-07T14-53-37

-------------------------------
Backtrace:
-------------------------------

app/controllers/track_controller.rb:42:in `track_list'
app/controllers/application_controller.rb:110:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

Looks like this should 404 rather than 500?

**Comment by garethrees** [comment]
Still happens

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
