### ISSUE TITLE
[ERROR] request#download_entire_request (Errno::ENAMETOOLONG) "File name too long @ rb_sysopen…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5529]
```
An Errno::ENAMETOOLONG occurred in request#download_entire_request:

File name too long @ rb_sysopen - /data/vhost/www.whatdotheyknow.com/alaveteli-2019-12-19T10-05-17/cache/zips/production/download/619/619120/3cebf9fefd53cb887f107c8e7103929a92ca3f45/4_7_190131 conference on international student recruitment competition student experience immigration policy speakers HEPI Home Office Migration Advisory Committee Westminster Higher Education Forum Morning Thursday 7th February 2.html20200105-31564-e71hts
app/controllers/request_controller.rb:982:in `block (3 levels) in make_request_zip'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/request/foi_request_chinese_embassygover_16/download
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"download_entire_request", "url_title"=>"foi_request_chinese_embassygover_16"}
* Timestamp : 2020-01-05 21:43:55 +0000
* Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2019-12-19T10-05-17

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"FILTERED",
"locale"=>"en",
"remember_me"=>true,
"_csrf_token"=>"FILTERED",
"user_id"=>127453,
"post_redirect_token"=>"FILTERED"}


-------------------------------
Backtrace:
-------------------------------

app/controllers/request_controller.rb:982:in `block (3 levels) in make_request_zip'
app/controllers/request_controller.rb:980:in `each'
app/controllers/request_controller.rb:980:in `block (2 levels) in make_request_zip'
app/controllers/request_controller.rb:977:in `block in make_request_zip'
app/controllers/request_controller.rb:973:in `make_request_zip'
app/controllers/request_controller.rb:865:in `block in download_entire_request'
lib/alaveteli_localization.rb:43:in `with_locale'
app/controllers/request_controller.rb:844:in `download_entire_request'
app/controllers/application_controller.rb:110:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Had another of these today.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
