### ISSUE TITLE
[ERROR] request#show (Mail::Field::ParseError) "Mail::DateTimeElement can not parse

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5552]
```
A Mail::Field::ParseError occurred in request#show:

Mail::DateTimeElement can not parse ||
Reason was: nil is an invalid DateTime
app/models/incoming_message.rb:134:in `block in parse_raw_email!'


-------------------------------
Request:
-------------------------------

* URL : https://www.infoprovsechny.cz/request/holding_pen
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"holding_pen"}
* Timestamp : 2020-01-27 18:30:07 +0100


-------------------------------
Backtrace:
-------------------------------

app/models/incoming_message.rb:134:in `block in parse_raw_email!'
app/models/incoming_message.rb:132:in `parse_raw_email!'
app/models/incoming_message.rb:212:in `mail_from'
app/models/incoming_message.rb:231:in `safe_mail_from'
app/models/incoming_message.rb:254:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_request__incoming_correspondence_html_erb__1008437660562537681_47302974517980'
app/views/request/_correspondence.html.erb:4:in `_app_views_request__correspondence_html_erb__1509486228637496370_70036641157420'
app/views/request/show.html.erb:68:in `block in _app_views_request_show_html_erb___4211366195412322432_47303005018100'
app/views/request/show.html.erb:66:in `_app_views_request_show_html_erb___4211366195412322432_47303005018100'
app/controllers/request_controller.rb:134:in `block (3 levels) in show'
app/controllers/request_controller.rb:133:in `block in show'
lib/alaveteli_localization.rb:43:in `with_locale'
app/controllers/request_controller.rb:89:in `show'
app/controllers/application_controller.rb:120:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
In the holding pen, so could well be spam.

Though, does look like we should be rescuing from this to [fall back to `created_at`](https://github.com/mysociety/alaveteli/blob/0.29.0.7/app/models/incoming_message.rb#L134)

**Comment by gbp** [comment]
While upgrading to 0.38 I hit this issue. There was a scam email in the holding pen causing `/request/holding_pen` and `/admin` to break. Using the console I found the ID 13726 and deleted via `/admin/incoming_messages/13726/edit`.

**Comment by gbp** [comment]
The offending header in the email is `Date: Thu, 23 Jan 2020 26:29:17 +0600`

**Comment by gbp** [comment]
```
[1] pry(main)> contents = 'Date: Thu, 23 Jan 2020 26:29:17 +0600'
=> "Date: Thu, 23 Jan 2020 26:29:17 +0600"
[2] pry(main)> Mail.new(contents).date
Mail::Field::NilParseError: Mail::DateTimeElement can not parse ||: nil is invalid
from /Users/gbp/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/parsers/date_time_parser.rb:668:in `parse'
[3] pry(main)> Time.parse(contents)
=> 2020-01-24 02:29:17 +0600
```

**Comment by gbp** [comment]
As this was a scam email I'm goign to close this issue until we see a legitimate email with this issue.
