### ISSUE TITLE
[ERROR] admin_general#index (ActionView::Template::Error) "code converter not found (Windows-1258 to UTF-8)"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5609]
```
An ActionView::Template::Error occurred in admin_general#index:

  code converter not found (Windows-1258 to UTF-8)
  lib/normalize_string.rb:39:in `encode'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin
  * HTTP Method: GET
  * IP address : [snip]
  * Parameters : {"controller"=>"admin_general", "action"=>"index"}
  * Timestamp  : 2020-04-08 18:13:42 +0100
  * Server : owl
  * Rails root : alaveteli-2020-04-07T09-48-49
  * Process: 18547

-------------------------------
Backtrace:
-------------------------------

  lib/normalize_string.rb:39:in `encode'
  lib/normalize_string.rb:39:in `block in normalize_string_to_utf8'
  lib/normalize_string.rb:31:in `each'
  lib/normalize_string.rb:31:in `normalize_string_to_utf8'
  lib/normalize_string.rb:78:in `convert_string_to_utf8_or_binary'
  lib/mail_handler/backends/mail_backend.rb:87:in `get_part_body'
  lib/mail_handler/backends/mail_backend.rb:358:in `block in get_attachment_attributes'
  lib/mail_handler/backends/mail_backend.rb:357:in `each'
  lib/mail_handler/backends/mail_backend.rb:357:in `get_attachment_attributes'
  app/models/incoming_message.rb:536:in `extract_attachments!'
  app/models/incoming_message.rb:98:in `block in parse_raw_email!'
  app/models/incoming_message.rb:97:in `parse_raw_email!'
  app/models/incoming_message.rb:418:in `get_main_body_text_internal'
  app/models/incoming_message.rb:380:in `_cache_main_body_text'
  app/models/incoming_message.rb:406:in `get_main_body_text_folded'
  app/models/incoming_message.rb:627:in `get_body_for_quoting'
  app/views/admin_general/_to_do_list.html.erb:20:in `block in _app_views_admin_general__to_do_list_html_erb__1870195776768068887_70032678524480'
  app/views/admin_general/_to_do_list.html.erb:16:in `_app_views_admin_general__to_do_list_html_erb__1870195776768068887_70032678524480'
  app/views/admin_general/index.html.erb:17:in `_app_views_admin_general_index_html_erb___315293496877616397_70032496228040'
```

**Comment by gbp** [comment]
We're seeing the same error for a public URL.

```
An ActionView::Template::Error occurred in request#show:

  code converter not found (Windows-1258 to UTF-8)
  lib/normalize_string.rb:38:in `encode'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/when_are_the_covid_vaccine_harms
  * HTTP Method: GET
  * IP address : snip
  * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"when_are_the_covid_vaccine_harms"}
  * Timestamp  : 2021-08-08 21:44:59 +0100
  * Server : owl
  * Rails root : alaveteli-2021-08-04T11-59-57
  * Process: 4457

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"snip", "locale"=>"en"}
```

**Comment by garethrees** [comment]
Should be handled in mail as of 2.7 https://github.com/mikel/mail/issues/544#issuecomment-303080719

**Comment by gbp** [comment]
Steps to replicate

```
data = File.read('771645/1850301.eml')
mail = Mail.new(data)
leaf = MailHandler.get_attachment_leaves(mail).first
body = leaf.body.decoded

normalize_string_to_utf8(body, leaf.charset)
=> Encoding::ConverterNotFoundError: code converter not found (Windows-1258 to UTF-8)
   from /Users/gbp/Developer/work/alaveteli/lib/normalize_string.rb:40:in `encode'
```

Within `normalize_string_to_utf8` we use Charlock Holmes gem to guess the encoding, this differs to the charset:

```
CharlockHolmes::EncodingDetector.detect(body)
=> {:type=>:text, :encoding=>"ISO-8859-1", :ruby_encoding=>"ISO-8859-1", :confidence=>34, :language=>"en"}

leaf.charset
=> "windows-1258"
```

Stubbing this guessed encoding, allows us to see the error in a spec:
 
```diff
diff --git a/spec/lib/basic_encoding_spec.rb b/spec/lib/basic_encoding_spec.rb
index 9081bbadf..888ce602c 100644
--- a/spec/lib/basic_encoding_spec.rb
+++ b/spec/lib/basic_encoding_spec.rb
@@ -78,7 +78,10 @@ def bytes_to_binary_string( bytes, claimed_encoding = nil )
 
     it "should correctly convert it to UTF-8" do
 
-      normalized = normalize_string_to_utf8 windows_1252_string
+      allow(CharlockHolmes::EncodingDetector).to receive(:detect).
+        with(windows_1252_string).and_return(encoding: 'ISO-8859-1')
+
+      normalized = normalize_string_to_utf8 windows_1252_string, 'windows-1258'
 
       expect(normalized).to eq("DASH – DASH")
 
```

```
> rspec spec/lib/basic_encoding_spec.rb:79
Run options: include {:locations=>{"./spec/lib/basic_encoding_spec.rb"=>[79]}}

Randomized with seed 4304
F

Failures:

  1) normalize_string_to_utf8 when passed unlabelled Windows 1252 data should correctly convert it to UTF-8
     Failure/Error: return s.encode('UTF-8') if s.valid_encoding?

     Encoding::ConverterNotFoundError:
       code converter not found (Windows-1258 to UTF-8)
     # ./lib/normalize_string.rb:38:in `encode'
     # ./lib/normalize_string.rb:38:in `block in normalize_string_to_utf8'
     # ./lib/normalize_string.rb:30:in `each'
     # ./lib/normalize_string.rb:30:in `normalize_string_to_utf8'
     # ./spec/lib/basic_encoding_spec.rb:84:in `block (3 levels) in <top (required)>'
     # ./.direnv/gems/2.7.3p183/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 0.84034 seconds (files took 3.58 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/basic_encoding_spec.rb:79 # normalize_string_to_utf8 when passed unlabelled Windows 1252 data should correctly convert it to UTF-8

Randomized with seed 4304
```

**Comment by gbp** [comment]
Relevant Ruby core issue: https://bugs.ruby-lang.org/issues/7742

**Comment by gbp** [comment]
Windows 125**8** (different from 1252), doesn't have a converter defined https://github.com/ruby/ruby/tree/master/enc so the best we can do to catch the `Encoding::ConverterNotFoundError` exception.

**Comment by garethrees** [comment]
> Windows 125**8** (different from 1252), doesn't have a converter defined

Shouldn't this get handled by the [`BestEffortCharsetEncoder`](https://github.com/mikel/mail/issues/544#issuecomment-267197374)?

**Comment by gbp** [comment]
The mail gem could well be using that. It probably is for the email subject (which for the email I'm working with is in Windows 1258 encoding), as for the mail parts/leaves it returns binary data - we are pulling out the supposed charset and passing that to `#normalize_string_to_utf8` which forces the binary data into 'windows-1258' and then attempts to encode as 'utf-8' causing this error.

```ruby
leaf.body.decoded.encoding
=> #<Encoding:ASCII-8BIT>

leaf.charset
=> "windows-1258"
```
