### ISSUE TITLE
[ERROR] request#show (NoMethodError) "undefined method `in_time_zone' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5614]
```
A NoMethodError occurred in request#show:

undefined method `in_time_zone' for nil:NilClass
app/helpers/date_time_helper.rb:39:in `simple_date_html'

-------------------------------
Request:
-------------------------------

* URL : https://derechoapreguntar.org/request/planes_calidad_educacion
* Parameters: {"controller"=>"request", "action"=>"show", "url_title"=>"planes_calidad_educacion"}
* Rails root: /FILTERED/alaveteli-2019-09-16T16-29-39
* Timestamp : 2020-04-13 09:06:09 -0600

-------------------------------
Backtrace:
-------------------------------

app/helpers/date_time_helper.rb:39:in `simple_date_html'
app/helpers/date_time_helper.rb:26:in `simple_date'
app/views/request/_incoming_correspondence.html.erb:16:in `_app_views_request__incoming_correspondence_html_erb__1435839846954020883_46984193147820'
actionpack (3.2.22) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:165:in `block in instrument_with_newrelic'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:164:in `instrument_with_newrelic'
actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionpack (3.2.22) lib/action_view/renderer/renderer.rb:41:in `render_partial'
actionpack (3.2.22) lib/action_view/renderer/renderer.rb:15:in `render'
actionpack (3.2.22) lib/action_view/helpers/rendering_helper.rb:24:in `render'
app/views/request/_correspondence.html.erb:4:in `_app_views_request__correspondence_html_erb___3648065075774667387_46984156396740'
actionpack (3.2.22) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:165:in `block in instrument_with_newrelic'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:164:in `instrument_with_newrelic'
actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionpack (3.2.22) lib/action_view/renderer/renderer.rb:41:in `render_partial'
actionpack (3.2.22) lib/action_view/renderer/renderer.rb:15:in `render'
actionpack (3.2.22) lib/action_view/helpers/rendering_helper.rb:24:in `render'
app/views/request/show.html.erb:151:in `block in _app_views_request_show_html_erb___1960260189218699180_46984181512960'
activerecord (3.2.22) lib/active_record/associations/collection_proxy.rb:91:in `each'
activerecord (3.2.22) lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
app/views/request/show.html.erb:149:in `_app_views_request_show_html_erb___1960260189218699180_46984181512960'
actionpack (3.2.22) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:18:in `render'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:150:in `block in render_with_newrelic'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:149:in `render_with_newrelic'
actionpack (3.2.22) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.22) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.22) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.22) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.22) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.22) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.22) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.22) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.22) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.22) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (3.2.22) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:39:in `render'
app/controllers/request_controller.rb:126:in `block (3 levels) in show'
actionpack (3.2.22) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
app/controllers/request_controller.rb:125:in `block in show'
i18n (0.9.5) lib/i18n.rb:268:in `with_locale'
app/controllers/request_controller.rb:79:in `show'
actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.22) lib/active_support/callbacks.rb:591:in `block in _run__4308945685440028296__process_action__3274827981604953539__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1167'
app/controllers/application_controller.rb:117:in `record_memory'
activesupport (3.2.22) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1167'
activesupport (3.2.22) lib/active_support/callbacks.rb:590:in `_run__4308945685440028296__process_action__3274827981604953539__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:28:in `block in process_action'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:361:in `perform_action_with_newrelic_trace'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `process_action'
actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
exception_notification (3.0.1) lib/exception_notifier.rb:41:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/cookies.rb:341:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:15:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
activerecord (3.2.22) lib/active_record/query_cache.rb:64:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
activerecord (3.2.22) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `_run__3562016604651610514__call__2921984123701486684__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
railties (3.2.22) lib/rails/engine.rb:484:in `call'
railties (3.2.22) lib/rails/application.rb:231:in `call'
railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by garethrees** [comment]
We get a lot of these, so I looked in to this one.

We call [`simple_date_html`](https://github.com/mysociety/alaveteli/blob/0.22.4.12/app/helpers/date_time_helper.rb#L32-L41) (via `simple_date`)…

https://github.com/mysociety/alaveteli/blob/0.22.4.12/app/views/request/_incoming_correspondence.html.erb#L16

…but `IncomingMessage#sent_at` is `nil`.

I tried re-parsing the raw email but got an encoding error, which explains why we didn't end up parsing the sent at date from the email and storing it on the `IncomingMessage`.

```ruby
m = IncomingMessage.find 561
m.sent_at
# => nil
m.parse_raw_email! true
# Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
# snip…
```

To stop this request from erroring, I copied the value from the `Date` header on the raw email view of the admin interface and set `sent_at`:

```ruby
m.sent_at = Time.parse("Fri, 16 Aug 2019 13:01:40 -0600 (CST)")
m.save
# => true
```

This isn't a "fix" as such though, as this leaves the message body empty:

![Screenshot 2020-04-14 at 08 45 18](https://user-images.githubusercontent.com/282788/79199081-551f5900-7e2c-11ea-9f12-59c037bd2be1.png)

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
