### ISSUE TITLE
[ERROR] (Net::POPError) "-ERR Message 31 expunged."

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5697]
```
A Net::POPError occurred in background at 2020-06-02 17:16:30 +0200 :

-ERR Message 31 expunged.
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:1001:in `check_response'

-------------------------------
Backtrace:
-------------------------------

/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:1001:in `check_response'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:988:in `getok'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:954:in `block in retr'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:1013:in `critical'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:953:in `retr'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:807:in `pop'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-03-23T17-22-35/lib/alaveteli_mail_poller.rb:60:in `get_mail'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-03-23T17-22-35/lib/alaveteli_mail_poller.rb:26:in `block (2 levels) in poll_for_incoming'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:666:in `each'
/opt/rbenv/versions/2.3.8/lib/ruby/2.3.0/net/pop.rb:666:in `each_mail'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-03-23T17-22-35/lib/alaveteli_mail_poller.rb:25:in `block in poll_for_incoming'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-03-23T17-22-35/lib/alaveteli_mail_poller.rb:115:in `start'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-03-23T17-22-35/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-03-23T17-22-35/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-5.1.7/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-5.1.7/lib/rails/commands/runner/runner_command.rb:37:in `eval'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-5.1.7/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

-------------------------------
Data:
-------------------------------

* data: {:mail=>nil, :unique_id=>"0000005d5e78e622"}
```

**Comment by garethrees** [comment]
@sagepe any idea what might have caused an "ERR Message 31 expunged"?

**Comment by sagepe** [comment]
I'm guessing if the client tried to do retrieve or delete (or something) as message that has already been flagged to delete and expunged? Some kind of race condition?

There's nothing obvious in the logs, although I do note that we usually see at least two logins in a minute, and the log only shows one for 17:15 and none over 17:16 from the Netherlands on that date:

```
Jun  2 17:12:54 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14640, TLS, session=<v+IbLxynYNUuKyds>
Jun  2 17:12:57 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=7/159797, del=7/7, size=159666
Jun  2 17:12:57 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14660, TLS, session=<9OBKLxynytUuKyds>
Jun  2 17:12:57 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:12:59 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14665, TLS, session=<HcpbLxyn8NUuKyds>
Jun  2 17:12:59 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:13:01 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14674, TLS, session=<ZgN8LxynKNYuKyds>
Jun  2 17:13:01 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:13:05 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14691, TLS, session=<WJO6LxynINcuKyds>
Jun  2 17:13:05 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:13:13 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14709, TLS, session=<JUs2MByn7tguKyds>
Jun  2 17:13:13 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:13:29 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14762, TLS, session=<BjQsMRyn8NsuKyds>
Jun  2 17:13:29 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:14:01 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=14874, TLS, session=<uhIWMxynCuIuKyds>
Jun  2 17:14:01 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:14:44 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=15095, TLS, session=<T/adNRyncOkuKyds>
Jun  2 17:14:44 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:15:05 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=15287, TLS, session=<zFfoNhynUO0uKyds>
Jun  2 17:15:05 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:17:13 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16480, TLS, session=<aO+KPhyn5JUuKyds>
Jun  2 17:17:13 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:17:43 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16655, TLS, session=<OtlTQByngJwuKyds>
Jun  2 17:17:43 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:17:44 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16659, TLS, session=<x7BkQBynrpwuKyds>
Jun  2 17:17:44 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:17:46 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16710, TLS, session=<acyEQBynap0uKyds>
Jun  2 17:17:46 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:17:51 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16717, TLS, session=<YFvDQBynPJ4uKyds>
Jun  2 17:17:51 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:17:59 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16738, TLS, session=<gTI/QRynTp8uKyds>
Jun  2 17:17:59 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:18:15 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16805, TLS, session=<iPw0QhyneKIuKyds>
Jun  2 17:18:15 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:18:47 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16979, TLS, session=<AOoeRBynsKcuKyds>
Jun  2 17:18:48 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=1/18090, del=1/1, size=18070
Jun  2 17:18:48 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16984, TLS, session=<YXouRByn+KcuKyds>
Jun  2 17:18:48 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jun  2 17:18:49 pelican dovecot: pop3-login: Login: user=<foinetherlands>, method=PLAIN, rip=46.43.39.108, lip=46.43.39.107, mpid=16987, TLS, session=<KnI/RBynGqguKyds>
Jun  2 17:18:49 pelican dovecot: pop3(foinetherlands): Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
```

**Comment by garethrees** [comment]
Interesting. Probably nothing to worry about here then, so closing unless this comes up frequently.

**Comment by garethrees** [comment]
Came up again:

```
A Net::POPError occurred in background at 2022-03-15 21:21:07 +0100 :

 -ERR Message 2 expunged.
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:1002:in `check_response'

-------------------------------
Backtrace:
-------------------------------

 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:1002:in `check_response'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:989:in `getok'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:955:in `block in retr'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:1014:in `critical'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:954:in `retr'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:808:in `pop'
 /data/vhost/[netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:59:in](http://netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:59:in) `get_mail'
 /data/vhost/[netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:25:in](http://netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:25:in) `block (2 levels) in poll_for_incoming'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:667:in `each'
 /opt/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/pop.rb:667:in `each_mail'
 /data/vhost/[netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:24:in](http://netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:24:in) `block in poll_for_incoming'
 /data/vhost/[netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:114:in](http://netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:114:in) `start'
 /data/vhost/[netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:23:in](http://netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:23:in) `poll_for_incoming'
 /data/vhost/[netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:40:in](http://netherlands.alaveteli.org/alaveteli-2022-02-03T15-05-15/lib/alaveteli_mail_poller.rb:40:in) `poll_for_incoming_loop'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/runner/runner_command.rb:45:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/runner/runner_command.rb:45:in) `<main>'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/runner/runner_command.rb:45:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/runner/runner_command.rb:45:in) `eval'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/runner/runner_command.rb:45:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/runner/runner_command.rb:45:in) `perform'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in) `run'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in) `invoke_command'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in) `dispatch'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/command/base.rb:69:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/command/base.rb:69:in) `perform'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/command.rb:46:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/command.rb:46:in) `invoke'
 /data/vhost/[netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands.rb:18:in](http://netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.1/lib/rails/commands.rb:18:in) `<top (required)>'
 bin/rails:4:in `require'
 bin/rails:4:in `<main>'

-------------------------------
Data:
-------------------------------

 * data: {:mail=>nil, :unique_id=>"000004f05e78e622"}
 * ```
