### ISSUE TITLE
[ERROR] batch_downloads#show (ActionController::Live::ClientDisconnected) "client disconnected"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5781]
```
An ActionController::Live::ClientDisconnected occurred in batch_downloads#show:

client disconnected
app/controllers/alaveteli_pro/batch_downloads_controller.rb:39:in `block in download_zip'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/alaveteli_pro/info_request_batches/1016/download.zip
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/batch_downloads", "action"=>"show", "info_request_batch_id"=>"1016", "format"=>"zip"}
* Timestamp : 2020-06-30 17:55:30 +0100
* Rails root : /REDACTED/alaveteli-2020-06-26T07-15-10

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>true,
"user_id"=>197342,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/alaveteli_pro/batch_downloads_controller.rb:39:in `block in download_zip'
app/services/info_request_batch_zip.rb:42:in `block (2 levels) in stream'
app/services/info_request_batch_zip.rb:65:in `block (2 levels) in each'
app/services/info_request_batch_zip.rb:63:in `each'
app/services/info_request_batch_zip.rb:63:in `block in each'
app/services/info_request_batch_zip.rb:54:in `each'
app/services/info_request_batch_zip.rb:41:in `block in stream'
app/services/info_request_batch_zip.rb:37:in `stream'
app/controllers/alaveteli_pro/batch_downloads_controller.rb:38:in `download_zip'
app/controllers/alaveteli_pro/batch_downloads_controller.rb:13:in `block (2 levels) in show'
app/controllers/alaveteli_pro/batch_downloads_controller.rb:11:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
```

**Comment by garethrees** [comment]
Seen a few more of these recently.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
