### ISSUE TITLE
[ERROR] (Net::OpenTimeout) "execution expired"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5788]
```
A Net::OpenTimeout occurred in background at 2020-07-06 10:04:15 +0100 :

execution expired
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'

-------------------------------
Backtrace:
-------------------------------

/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:544:in `do_start'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:537:in `start'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-07-02T12-53-53/lib/alaveteli_mail_poller.rb:113:in `start'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-07-02T12-53-53/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-07-02T12-53-53/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

-------------------------------
Data:
-------------------------------

* data: {}
```

Seems similar to https://github.com/mysociety/alaveteli/issues/4221 but we're getting an exception notification rather than a cron output email.

In https://github.com/mysociety/alaveteli/pull/4392 we rescued from `Timeout::Error`. This should still cover `Net::OpenTimeout` in Ruby 2.6:

```ruby
Net::OpenTimeout.ancestors.take(3)
# => [Net::OpenTimeout, Timeout::Error, RuntimeError]
```

**Comment by garethrees** [comment]
Oh, durr, this is indeed getting rescued and we're now just getting the exception notification telling us it happened.

https://github.com/mysociety/alaveteli/blob/647bc3496f6c10d36e30dc98e449b67db1d61959/lib/alaveteli_mail_poller.rb#L116-L119

Going to close this and reopen if we start seeing more of them.

**Comment by garethrees** [comment]
Another

```
A Net::OpenTimeout occurred in background at 2020-07-21 15:48:33 +0200 :

execution expired
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:545:in `initialize'

-------------------------------
Backtrace:
-------------------------------

/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:545:in `initialize'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:545:in `open'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:545:in `block in do_start'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:544:in `do_start'
/opt/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/pop.rb:537:in `start'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-07-07T14-40-30/lib/alaveteli_mail_poller.rb:113:in `start'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-07-07T14-40-30/lib/alaveteli_mail_poller.rb:24:in `poll_for_incoming'
/data/vhost/netherlands.alaveteli.org/alaveteli-2020-07-07T14-40-30/lib/alaveteli_mail_poller.rb:41:in `poll_for_incoming_loop'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/commands/runner/runner_command.rb:37:in `eval'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
/data/vhost/netherlands.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

-------------------------------
Data:
-------------------------------

* data: {}
```
