### ISSUE TITLE
[ERROR] request search_typeahead (ArgumentError) "InvalidArgumentError: Key too long…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5815]
```
An ArgumentError occurred in request#search_typeahead:

InvalidArgumentError: Key too long: length was 260 bytes, maximum length of a key is 252 bytes
lib/acts_as_xapian/acts_as_xapian.rb:326:in `mset'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/request/search_ahead?q=We%20are%20a%20business%20meetings%20venue%20for%20team%20meetings,%20training%20and%20hybrid%20events.%20We%20do%20not%20fit%20into%20hospitality%20or%20Conference%20centre.%20Where%20can%20we%20get%20guidance%20on%20opening%20our%20city%20centre%20spaces.%20We%20have%20a%20good%20plan%20and%20maximum%20numbers%20could%20be%20easily%20set%20with%20social%20distancing%20and%20even%20enforcing%20the%20wedding%20of%20&requested_from=dcms&per_page=3
* HTTP Method: GET
* Parameters : {"q"=>"We are a business meetings venue for team meetings, training and hybrid events. We do not fit into hospitality or Conference centre. Where can we get guidance on opening our city centre spaces. We have a good plan and maximum numbers could be easily set with social distancing and even enforcing the wedding of ", "requested_from"=>"dcms", "per_page"=>"3", "controller"=>"request", "action"=>"search_typeahead"}
* Timestamp : 2020-07-09 11:34:01 +0100
* Rails root : /REDACTED/alaveteli-2020-07-08T12-53-53

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"flash"=>
{"discard"=>[],
"flashes"=>{"search_params"=>{"query"=>"Department for digital"}}}}

-------------------------------
Backtrace:
-------------------------------

lib/acts_as_xapian/acts_as_xapian.rb:326:in `mset'
lib/acts_as_xapian/acts_as_xapian.rb:326:in `block in initialize_query'
lib/acts_as_xapian/acts_as_xapian.rb:297:in `initialize_query'
lib/acts_as_xapian/acts_as_xapian.rb:492:in `initialize'
lib/typeahead_search.rb:68:in `new'
lib/typeahead_search.rb:68:in `run_query'
lib/typeahead_search.rb:22:in `xapian_search'
app/controllers/application_controller.rb:431:in `typeahead_search'
app/controllers/request_controller.rb:525:in `search_typeahead'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Been getting a few of these recently. Probably raising instead of swallowing the exception since #5720?
