### ISSUE TITLE
[ERROR] admin_public_body edit (ActionView::MissingTemplate) "Missing template admin_public_body_change_requests/update_accepted"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5816]
```
An ActionView::MissingTemplate occurred in admin_public_body#edit:

Missing template admin_public_body_change_requests/update_accepted with {:locale=>[:en], :formats=>[:text, :html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee]}. Searched in:
* "/data/vhost/www.whatdotheyknow.com/alaveteli-2020-06-16T11-05-01/lib/themes/whatdotheyknow-theme/lib/views"
* "/data/vhost/www.whatdotheyknow.com/alaveteli-2020-06-16T11-05-01/app/views"

app/controllers/admin_public_body_controller.rb:83:in `edit'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/bodies/8209/edit?change_request_id=4270
* HTTP Method: GET
* Parameters : {"change_request_id"=>"4270", "controller"=>"admin_public_body", "action"=>"edit", "id"=>"8209"}
* Timestamp : 2020-06-20 19:01:11 +0100
* Rails root : /REDACTED/alaveteli-2020-06-16T11-05-01

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>true,
"_csrf_token"=>"REDACTED",
"request_game"=>"2020-06-18T16:05:23.094+01:00",
"user_id"=>2779,
"post_redirect_token"=>"REDACTED",
"using_admin"=>1,
"admin_name"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_public_body_controller.rb:83:in `edit'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'

**Comment by gbp** [comment]
Funny enough this is occurred in the Rails 6 specs run I did and is fixed in #5817

**Comment by garethrees** [comment]
Is this now fixed because https://github.com/mysociety/alaveteli/pull/5817 is merged?

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
