### ISSUE TITLE
Unable to install newly forked theme

### ISSUE THREAD

**Issue by 1000camels** [mysociety/alaveteli#5845]
I have just folked a theme and assigned in general.yml, but when I try to install it, I receive the following error. Any help is appreciated.

```
vagrant@alaveteli:~/alaveteli$ bundle exec rake themes:install
rake aborted!
NoMethodError: undefined method `before_filter' for ActionController::Base:Class
Did you mean?  before_action
/home/vagrant/alaveteli/lib/themes/accessinfohktheme/lib/alavetelitheme.rb:11:in `<class:Base>'
/home/vagrant/alaveteli/lib/themes/accessinfohktheme/lib/alavetelitheme.rb:5:in `<top (required)>'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/home/vagrant/alaveteli/config/initializers/theme_loader.rb:11:in `require_theme'
/home/vagrant/alaveteli/config/initializers/theme_loader.rb:24:in `block in <top (required)>'
/home/vagrant/alaveteli/config/initializers/theme_loader.rb:23:in `each'
/home/vagrant/alaveteli/config/initializers/theme_loader.rb:23:in `<top (required)>'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/engine.rb:663:in `block in load_config_initializer'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:170:in `instrument'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/engine.rb:662:in `load_config_initializer'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/engine.rb:619:in `each'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:50:in `each'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
/home/vagrant/alaveteli/config/environment.rb:6:in `<top (required)>'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/application.rb:337:in `require_environment!'
/home/vagrant/bundle/ruby/2.3.0/gems/railties-5.2.4.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/vagrant/bundle/ruby/2.3.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => themes:install => environment
(See full trace by running task with --trace)
```

**Comment by gbp** [comment]
There are a couple of changes required to the theme to get it working with the more recent version of Alaveteli. The changes should be described in the upgrade notes.

For this case, you need to do something like: https://github.com/mysociety/alavetelitheme/commit/5417b988e276588883fbb416614a91f1b191f6ce

**Comment by garethrees** [comment]
Closing this as I think this should get resolved by the suggestion above. Note that the [developer mailing list](https://alaveteli.org/community/#project-mailing-lists) is the best place for advice on getting Alaveteli set up.
