### ISSUE TITLE
Mail ingess error - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5865]
Since #4896 we have started seeing

```
$ cat ~/Downloads/foi-mailin-output-QjR4zSQg
./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match': invalid byte sequence in UTF-8 (ArgumentError)
        from ./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `set_envelope_header'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2132:in `init_with_string'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:137:in `initialize'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
        from ./alaveteli-2020-08-13T10-02-54/lib/mail_handler/backends/mail_backend.rb:44:in `mail_from_raw_email'
        from ./alaveteli-2020-08-13T10-02-54/app/mailers/request_mailer.rb:223:in `receive'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
        from ./shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

This email appears to be encoded as `iso-8859-1`

```ruby
content = File.read 'foi-mailin-mail-tYFpDlYE.eml'
Mail.new content
# ArgumentError: invalid byte sequence in UTF-8
# from ~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
content.encoding
# => #<Encoding:UTF-8>
content.valid_encoding?
# => false
content.scan(/Content-Type.*/)
# => ["Content-Type: text/plain; charset=\"iso-8859-1\"\r"]
content.force_encoding("iso-8859-1").valid_encoding?
# => true
```

The mail gem handles the email if encoding as `iso-8859-1` prior to initialisation   

```ruby
Mail.new content.force_encoding("iso-8859-1")
# => #<Mail::Message:70253421823880 [snip]>
```

**Comment by gbp** [comment]
This seems to now resolved and pending mail now delivered.
