### ISSUE TITLE
[ERROR] script/update-xapian-index FrozenError: can't modify frozen object

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5869]
```
rake aborted!
FrozenError: can't modify frozen object
NoMethodError: undefined method `reject' for nil:NilClass
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/backtrace.rb:21:in `collapse'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:249:in `display_exception_backtrace'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:218:in `display_exception_details'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:208:in `display_error_message'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:195:in `rescue in standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:185:in `standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-13T10-02-54/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-13T10-02-54/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
```

**Comment by garethrees** [comment]
Had another of these today

**Comment by garethrees** [comment]
Another today.

```
rake aborted!
FrozenError: can't modify frozen object
NoMethodError: undefined method `reject' for nil:NilClass
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/backtrace.rb:21:in `collapse'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:249:in `display_exception_backtrace'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:218:in `display_exception_details'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:208:in `display_error_message'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:195:in `rescue in standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:185:in `standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2021-03-15T12-27-55/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
/data/vhost/www.whatdotheyknow.com/alaveteli-2021-03-15T12-27-55/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
