### ISSUE TITLE
[ERROR] user#show (TypeError) "no implicit conversion of false into Integer"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5870]
```
A TypeError occurred in user#show:

  no implicit conversion of false into Integer
  app/controllers/user_controller.rb:383:in `normalize_url_name'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/user/nathan_lang
  * HTTP Method: GET
  * Parameters : {"controller"=>"user", "action"=>"show", "url_name"=>"nathan_lang"}
  * Timestamp  : 2020-08-18 06:03:07 +0100
  * Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"de0ec30c6b7fae98e86a0a360ac2376f", "locale"=>"en"}

-------------------------------
Environment:
-------------------------------

* HTTP_ACCEPT : */*
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_FROM : bingbot(at)microsoft.com
* HTTP_HOST : www.whatdotheyknow.com
* HTTP_PRAGMA : no-cache
* HTTP_USER_AGENT : Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)

-------------------------------
Backtrace:
-------------------------------

app/controllers/user_controller.rb:383:in `normalize_url_name'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
The URL works for me.

**Comment by garethrees** [comment]
Backtrace after cdccd2a

```
-------------------------------
Backtrace:
-------------------------------

lib/alaveteli_format.rb:10:in `normalize_KD'
lib/alaveteli_format.rb:10:in `simplify_url_part'
app/controllers/user_controller.rb:383:in `normalize_url_name'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```
