### ISSUE TITLE
[ERROR] public_body#show (TypeError) "no implicit conversion of false into Integer"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5871]
```
A TypeError occurred in public_body#show:

no implicit conversion of false into Integer
app/controllers/public_body_controller.rb:24:in `show'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/body/king_edward_vi_grammar_school_chelmsford/unsuccessful
* HTTP Method: GET
* IP address : 114.119.167.151
* Parameters : {"view"=>"unsuccessful", "controller"=>"public_body", "action"=>"show", "url_name"=>"king_edward_vi_grammar_school_chelmsford"}
* Timestamp : 2020-08-18 06:00:30 +0100
* Server : owl
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29
* Process: 5790

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"0ee5c2158384e73fbdac0f8cb02c5cb4", "locale"=>"en"}

-------------------------------
Environment:
-------------------------------

* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_ACCEPT_LANGUAGE : en,zh;q=0.1
* HTTP_HOST : www.whatdotheyknow.com
* HTTP_USER_AGENT : Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://aspiegel.com/petalbot)
* HTTP_VERSION : HTTP/1.1
* HTTP_X_FORWARDED_PROTO : https

-------------------------------
Backtrace:
-------------------------------

app/controllers/public_body_controller.rb:24:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Similar to https://github.com/mysociety/alaveteli/issues/5870, the URL works for me.

**Comment by garethrees** [comment]
Backtrace after cdccd2a

```
-------------------------------
Backtrace:
-------------------------------

lib/alaveteli_format.rb:10:in `normalize_KD'
lib/alaveteli_format.rb:10:in `simplify_url_part'
app/controllers/public_body_controller.rb:24:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Closing after #5907
