### ISSUE TITLE
[ERROR] public_body#list (TypeError) "no implicit conversion of false into Integer"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5874]
```
A TypeError occurred in public_body#list:

no implicit conversion of false into Integer
app/controllers/public_body_controller.rb:120:in `upcase'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/cy/body/list/m?page=5
* HTTP Method: GET
* Parameters : {"page"=>"5", "controller"=>"public_body", "action"=>"list", "tag"=>"m", "locale"=>"cy"}
* Timestamp : 2020-08-19 10:10:45 +0100
* Server : owl
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29
* Process: 6960

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"30b86bcae4fad173cf9e6a1825efc3f6", "locale"=>"cy"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/public_body_controller.rb:120:in `upcase'
app/controllers/public_body_controller.rb:120:in `list'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
```ruby
# Passing false to upcase as the exception suggests is happening:
Unicode.upcase(false)
TypeError: wrong argument type false (expected String)

# Maybe its something else on the same line? Nope…
@tag = false
Unicode.upcase(@tag) if @tag.scan(/./mu).size == 1
# => NoMethodError: undefined method `scan' for false:FalseClass
```

**Comment by garethrees** [comment]
I think https://github.com/mysociety/alaveteli/issues/5871 might be the underlying cause of this one.

**Comment by garethrees** [comment]
Backtrace after cdccd2a

```
-------------------------------
Backtrace:
-------------------------------

  app/controllers/public_body_controller.rb:120:in `upcase'
  app/controllers/public_body_controller.rb:120:in `list'
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Out of the other similar issue I think this is the only one which might need more work to replace calls ([1](https://github.com/mysociety/alaveteli/blob/1773fff/app/helpers/public_body_helper.rb#L48) [2](https://github.com/mysociety/alaveteli/blob/1773fff/app/controllers/public_body_controller.rb#L120) [3](https://github.com/mysociety/alaveteli/blob/1773fff/app/models/concerns/public_body_derived_fields.rb#L35)) to `Unicode.upcase`. The Unicode gem can then be removed

**Comment by garethrees** [comment]
Nice!

**Comment by gbp** [comment]
Closing after #5907
