### ISSUE TITLE
[ERROR] public_body#show (NoMethodError) "undefined method `yield' for false:FalseClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5876]
```
A NoMethodError occurred in public_body#show:

undefined method `yield' for false:FalseClass
app/controllers/public_body_controller.rb:24:in `show'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/cy/body/gccni
* HTTP Method: GET
* Parameters : {"view"=>"all", "controller"=>"public_body", "action"=>"show", "url_name"=>"gccni", "locale"=>"cy"}
* Timestamp : 2020-08-27 08:08:44 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29

-------------------------------
Backtrace:
-------------------------------

app/controllers/public_body_controller.rb:24:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Backtrace after cdccd2a

```
-------------------------------
Backtrace:
-------------------------------

lib/alaveteli_format.rb:10:in `normalize_KD'
lib/alaveteli_format.rb:10:in `simplify_url_part'
app/controllers/public_body_controller.rb:24:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Closing after #5907
