### ISSUE TITLE
[ERROR] user#show (NoMethodError) "undefined method `yield' for false:FalseClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5877]
```
A NoMethodError occurred in user#show:

undefined method `yield' for false:FalseClass
app/controllers/user_controller.rb:383:in `normalize_url_name'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/user/dominika_kowalewska
* HTTP Method: GET
* Parameters : {"controller"=>"user", "action"=>"show", "url_name"=>"dominika_kowalewska"}
* Timestamp : 2020-08-27 08:03:30 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29

-------------------------------
Backtrace:
-------------------------------

app/controllers/user_controller.rb:383:in `normalize_url_name'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'

```

**Comment by garethrees** [comment]
Backtrace after cdccd2a

```
-------------------------------
Backtrace:
-------------------------------

lib/alaveteli_format.rb:10:in `normalize_KD'
lib/alaveteli_format.rb:10:in `simplify_url_part'
app/controllers/user_controller.rb:383:in `normalize_url_name'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Closing after #5907
