### ISSUE TITLE
[ERROR] request#new (NoMethodError) "undefined method `yield' for false:FalseClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5878]
```
A NoMethodError occurred in request#new:

undefined method `yield' for false:FalseClass
app/models/info_request/sluggable.rb:38:in `update_url_title'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/new
* HTTP Method: POST
* Parameters : {"utf8"=>"&#x2713;", "authenticity_token"=>"", "info_request"=>{"title"=>"Montblanc Johannes Brahms : Rabatt Mont Blanc Kugelschreiber Zum Verkauf, Mont Blanc Füllfederhalter .", "public_body_id"=>"228"}, "outgoing_message"=>{"body"=>"[b][url=http://www.meister [SPAM_SNIPPED]<br>\n"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Preview your public request", "controller"=>"request", "action"=>"new"}
* Timestamp : 2020-08-27 07:56:09 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29

-------------------------------
Backtrace:
-------------------------------

app/models/info_request/sluggable.rb:38:in `update_url_title'
app/models/info_request/sluggable.rb:16:in `block in title='
app/models/info_request/sluggable.rb:15:in `tap'
app/models/info_request/sluggable.rb:15:in `title='
app/models/info_request.rb:446:in `create_from_attributes'
app/controllers/request_controller.rb:332:in `new'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Backtrace after cdcc2a

```
-------------------------------
Backtrace:
-------------------------------

  lib/alaveteli_format.rb:10:in `normalize_KD'
  lib/alaveteli_format.rb:10:in `simplify_url_part'
  app/models/info_request/sluggable.rb:38:in `update_url_title'
  app/models/info_request/sluggable.rb:16:in `block in title='
  app/models/info_request/sluggable.rb:15:in `tap'
  app/models/info_request/sluggable.rb:15:in `title='
  app/models/info_request.rb:446:in `create_from_attributes'
  app/controllers/request_controller.rb:332:in `new'
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Closing after #5907
