### ISSUE TITLE
[ERROR] admin_raw_email#show (TypeError) "no implicit conversion of false into Integer"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5879]
```
A TypeError occurred in admin_raw_email#show:

  no implicit conversion of false into Integer
  app/models/info_request/sluggable.rb:38:in `update_url_title'

-------------------------------
Request:
-------------------------------

* URL        : https://www.whatdotheyknow.com/admin/raw_emails/1626467
* HTTP Method: GET
* Parameters : {"controller"=>"admin_raw_email", "action"=>"show", "id"=>"1626467"}
* Timestamp  : 2020-08-22 22:15:29 +0100
* Server : owl
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-08-14T14-54-29
* Process: 12656

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>150401,
"remember_me"=>true,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED",
"using_admin"=>1,
"admin_name"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/models/info_request/sluggable.rb:38:in `update_url_title'
app/models/info_request/sluggable.rb:16:in `block in title='
app/models/info_request/sluggable.rb:15:in `tap'
app/models/info_request/sluggable.rb:15:in `title='
app/models/info_request.rb:319:in `guess_by_incoming_subject'
app/controllers/admin_raw_email_controller.rb:30:in `block (2 levels) in show'
app/controllers/admin_raw_email_controller.rb:12:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Closing after #5907
