### ISSUE TITLE
[ERROR] request#upload_response (TypeError) "no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5895]
```
A TypeError occurred in request#upload_response:

no implicit conversion of nil into String
app/controllers/request_controller.rb:461:in `escapeHTML'


-------------------------------
Request:
-------------------------------

* URL : https://sobanukirwa.rw/rw/upload/request/iwould_like_to_ask_different_asp
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"upload_response", "url_title"=>"iwould_like_to_ask_different_asp", "locale"=>"rw"}
* Timestamp : 2020-09-24 02:38:24 +0200
* Rails root : /data/vhost/rwanda.alaveteli.org/alaveteli-2020-09-22T15-07-36

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"f4eb9f392cc085018650214171a5d4ab", "locale"=>"rw"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/request_controller.rb:461:in `escapeHTML'
app/controllers/request_controller.rb:461:in `block in upload_response'
lib/alaveteli_localization.rb:46:in `with_locale'
app/controllers/request_controller.rb:455:in `upload_response'
app/controllers/application_controller.rb:116:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Hitting the URL without the `rw` locale results in a redirect to sign in. For some reason that isn't happening here.

**Comment by garethrees** [comment]
Same problem as https://github.com/mysociety/alaveteli/issues/5382. We're calling `PublicBody#name` where we've found a PublicBody but aren't correctly falling back to the default locale translation.

https://github.com/mysociety/alaveteli/blob/0.38.1.1/app/controllers/request_controller.rb#L461
