### ISSUE TITLE
[ERROR] script/update-xapian-index (FrozenError) "can't modify frozen object"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5913]
```
rake aborted!
FrozenError: can't modify frozen object
NoMethodError: undefined method `reject' for nil:NilClass
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/backtrace.rb:21:in `collapse'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:249:in `display_exception_backtrace'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:218:in `display_exception_details'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:208:in `display_error_message'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:195:in `rescue in standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:185:in `standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-10-01T16-37-57/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-10-01T16-37-57/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
```

**Comment by garethrees** [comment]
Seems like this was a 1-off at 2020-10-06 16:10.

Duplicate of https://github.com/mysociety/alaveteli/issues/5869.
