### ISSUE TITLE
[Spec error] NoMethodError: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5927]
```
$ rspec './spec/integration/alaveteli_pro/batch_request_spec.rb[1:4,1:5]' --seed 1611
Run options: include {:ids=>{"./spec/integration/alaveteli_pro/batch_request_spec.rb"=>["1:4", "1:5"]}}

Randomized with seed 1611
.F

Failures:

  1) creating batch requests in alaveteli_pro allows the user to go back and edit the bodies in the batch
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end

     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:180:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:179:in `block (2 levels) in <top (required)>'

Finished in 7.77 seconds (files took 7.2 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:178 # creating batch requests in alaveteli_pro allows the user to go back and edit the bodies in the batch

Randomized with seed 1611
```

**Comment by gbp** [comment]
Also:

```
$ rspec './spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:4:1:1]' './spec/integration/alaveteli_pro/batch_request_spec.rb[1:5]' --seed 1611
Run options: include {:ids=>{"./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb"=>["1:1:4:1:1"], "./spec/integration/alaveteli_pro/batch_request_spec.rb"=>["1:5"]}}

Randomized with seed 1611
.F

Failures:

  1) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
     Failure/Error: expect(results.count).to eq 3

       expected: 3
            got: 0

       (compared using ==)
     Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:118
     # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 7.33 seconds (files took 9.29 seconds to load)
2 examples, 1 failure

Failed examples:

rspec './spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:4:1:1]' # AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search

Randomized with seed 1611
```

Spec in common is `spec/integration/alaveteli_pro/batch_request_spec.rb[1:5]`

**Comment by gbp** [comment]
`spec/integration/alaveteli_pro/batch_request_spec.rb[1:5]` releates to https://github.com/mysociety/alaveteli/blob/develop/spec/integration/alaveteli_pro/batch_request_spec.rb#L206-L237

**Comment by gbp** [comment]
Before I forgot, I worked out when I openning this issue that the following fixes:

```diff
diff --git a/spec/integration/alaveteli_pro/batch_request_spec.rb b/spec/integration/alaveteli_pro/batch_request_spec.rb
index 6ad2e1d8cb..13990b6d22 100644
--- a/spec/integration/alaveteli_pro/batch_request_spec.rb
+++ b/spec/integration/alaveteli_pro/batch_request_spec.rb
@@ -44,20 +44,16 @@ def search_results
 describe "creating batch requests in alaveteli_pro" do
   let(:pro_user) { FactoryBot.create(:pro_user) }
   let!(:pro_user_session) { login(pro_user) }
-  let!(:authorities) { FactoryBot.create_list(:public_body, 26) }
+  let(:authorities) { FactoryBot.create_list(:public_body, 26) }
 
   before do
     get_fixtures_xapian_index
-  end
-
-  before do
+    authorities.map(&:save)
     update_xapian_index
   end
 
   after do
-    authorities.each do |authority|
-      authority.destroy
-    end
+    authorities.map(&:destroy)
     update_xapian_index
   end
 
```

There are other places in the spec where we need to do the same sort of thing. Infact we should consider extracting out the xapian spec setup ala the feature flags https://github.com/mysociety/alaveteli/commit/b1f1a29cd897fa565f1f2a189e0f2b345a223fe3

**Comment by gbp** [comment]
This was fixed by 2cf1284a0f0e749af6de79f3df32126d013aec7c
