### ISSUE TITLE
Generate the source .pot is not working

### ISSUE THREAD

**Issue by schlos** [mysociety/alaveteli#5944]
Following guide:
https://github.com/mysociety/alaveteli/wiki/Generate-theme-translations

`bundle exec rake gettext:find_theme THEME=asktheeu-theme` is not generating app.pot in "locale-theme"

```
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli$ bundle exec rake gettext:find_theme THEME=imamopravoznati-theme
Warning: obsolete msgid exists.
         #~ msgid "simple_date_format"
Warning: obsolete msgid exists.
         #~ msgstr "%e %B %Y"
'gettext/utils.rb' is deprecated. Use gettext/tools.rb.
/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/pages/app.pot /data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/pages/app.pot .. done.
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme$ ls
en  hr  pages
```

Tried `find locale-theme/* -name *.po | xargs -I % msgattrib --no-obsolete -o % %` but again no app.pot file:

```
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli$ bundle exec rake gettext:find_theme THEME=imamopravoznati-theme
'gettext/utils.rb' is deprecated. Use gettext/tools.rb.
/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/pages/app.pot .. done.
/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/pages/app.pot .. done.
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli$ ls -al /data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme
total 20
drwxrwxr-x 5 alaveteli alaveteli 4096 Oct 28 20:10 .
drwxrwxr-x 8 alaveteli alaveteli 4096 Oct 28 19:57 ..
drwxrwxr-x 2 alaveteli alaveteli 4096 Mar 11  2020 en
drwxrwxr-x 2 alaveteli alaveteli 4096 Mar 11  2020 hr
drwxrwxr-x 2 alaveteli alaveteli 4096 Oct 28 20:10 pages
```

Alaveteli version 0.33.0.0 (https://imamopravoznati.org/version.json), Ubuntu 18.04 LTS

**Comment by garethrees** [comment]
Hmm, strange.

Maybe try `touch /data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/app.pot` to force the file to exist, and then maybe it'll get written to with `rake gettext:find_theme`.

**Comment by schlos** [comment]
So, I have tried by creating empty file with touch as you suggested, file `app.pot` is now there:

```
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme$ ls -alrt
total 20
drwxrwxr-x 2 alaveteli alaveteli 4096 Mar 11  2020 en
drwxrwxr-x 8 alaveteli alaveteli 4096 Oct 28 19:57 ..
drwxrwxr-x 2 alaveteli alaveteli 4096 Oct 28 20:10 pages
drwxrwxr-x 2 alaveteli alaveteli 4096 Oct 28 20:31 hr
-rw-r--r-- 1 alaveteli alaveteli    0 Nov  7 08:57 app.pot
```

And after I run `bundle exec rake gettext:find_theme THEME=imamopravoznati-theme`, app.pot is still 0 bytes:

```
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli$ bundle exec rake gettext:find_theme THEME=imamopravoznati-theme
Warning: obsolete msgid exists.
         #~ msgid "simple_date_format"
Warning: obsolete msgid exists.
         #~ msgstr "%e %B %Y"
'gettext/utils.rb' is deprecated. Use gettext/tools.rb.
/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/pages/app.pot .. done.
/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/pages/app.pot .. done.
alaveteli@imamopravoznati:/data/www/imamopravoznati.org/alaveteli$ ls -alrt /data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme
total 20
drwxrwxr-x 2 alaveteli alaveteli 4096 Mar 11  2020 en
drwxrwxr-x 8 alaveteli alaveteli 4096 Oct 28 19:57 ..
drwxrwxr-x 2 alaveteli alaveteli 4096 Oct 28 20:10 pages
drwxrwxr-x 2 alaveteli alaveteli 4096 Oct 28 20:31 hr
-rw-r--r-- 1 alaveteli alaveteli    0 Nov  7 08:57 app.pot
drwxrwxr-x 5 alaveteli alaveteli 4096 Nov  7 08:57 .
```

It doesn't try to write anything to app.pot, as last updated timestamp in the app.pot is from when it was actually created with touch.

**Comment by garethrees** [comment]
Couple of other questions to help debug:

* Which version of Alaveteli are you using?
* Which operating system (with versions)?
* Which version of Ruby?

**Comment by garethrees** [comment]
> It doesn't try to write anything to app.pot, as last updated timestamp in the app.pot is from when it was actually created with touch.

Pretty strange. I can't think of anything obvious that would be causing this.

> Alaveteli version 0.33.0.0 (https://imamopravoznati.org/version.json), Ubuntu 18.04 LTS

That's quite an old version of Alaveteli. We don't backport bugfixes, so I think the best bet is to try getting closer to the latest release to see if this problem gets fixed in a more up to date version.

**Comment by schlos** [comment]
This is still reproducible on Alaveteli v0.39.x.x on ImamoPravoZnati:

- before running I have checked that theme folder does not have app.po, then run rake then checked again if app.pot is there:

```
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli$ ls -alrt /data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme
total 16
drwxrwxr-x 4 alaveteli alaveteli 4096 Aug  2 15:16 .
drwxrwxr-x 2 alaveteli alaveteli 4096 Aug  2 15:17 hr
drwxrwxr-x 2 alaveteli alaveteli 4096 Aug  2 15:17 en
drwxrwxr-x 8 alaveteli alaveteli 4096 Aug  2 15:17 ..
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli$ bundle exec rake gettext:find_theme THEME=imamopravoznati-theme
Rails Error: Unable to access log file. Please ensure that /data/www/imamopravoznati.org/alaveteli/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /data/www/imamopravoznati.org/alaveteli/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
No database tables found for feature flags, you might need to set a backend explicitly if you don't want them stored in a database, or runrake db:migrate to create the table.
Using memory-based feature storage instead.
rake aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "alaveteli"
/home/alaveteli/bundle/ruby/2.5.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/alaveteli/bundle/ruby/2.5.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/alaveteli/bundle/ruby/2.5.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:90:in `connection'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/model_schema.rb:324:in `table_exists?'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/attribute_methods/primary_key.rb:99:in `get_primary_key'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/attribute_methods/primary_key.rb:87:in `reset_primary_key'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/attribute_methods/primary_key.rb:75:in `primary_key'
/home/alaveteli/bundle/ruby/2.5.0/bundler/gems/acts_as_versioned-63b1fc8529d0/lib/acts_as_versioned.rb:179:in `acts_as_versioned'
/data/www/imamopravoznati.org/alaveteli/app/models/public_body.rb:119:in `<class:PublicBody>'
/data/www/imamopravoznati.org/alaveteli/app/models/public_body.rb:37:in `<top (required)>'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:195:in `const_missing'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:283:in `const_get'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:283:in `block in constantize'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:281:in `each'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:281:in `inject'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:281:in `constantize'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:326:in `safe_constantize'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/core_ext/string/inflections.rb:79:in `safe_constantize'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/associations/builder/belongs_to.rb:78:in `add_counter_cache_callbacks'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/associations/builder/belongs_to.rb:19:in `define_callbacks'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/associations/builder/association.rb:33:in `build'
/home/alaveteli/bundle/ruby/2.5.0/gems/activerecord-5.2.6/lib/active_record/associations.rb:1654:in `belongs_to'
/data/www/imamopravoznati.org/alaveteli/app/models/info_request.rb:64:in `<class:InfoRequest>'
/data/www/imamopravoznati.org/alaveteli/app/models/info_request.rb:40:in `<top (required)>'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:195:in `const_missing'
/data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/lib/model_patches.rb:41:in `block in <top (required)>'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:426:in `instance_exec'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:605:in `catch'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:199:in `block in halting'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:513:in `each'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:89:in `prepare!'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
/data/www/imamopravoznati.org/alaveteli/config/environment.rb:5:in `<top (required)>'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/alaveteli/bundle/ruby/2.5.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/application.rb:337:in `require_environment!'
/home/alaveteli/bundle/ruby/2.5.0/gems/railties-5.2.6/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/alaveteli/bundle/ruby/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => gettext:find_theme => environment
(See full trace by running task with --trace)
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli$ ls -alrt /data/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme
total 16
drwxrwxr-x 4 alaveteli alaveteli 4096 Aug  2 15:16 .
drwxrwxr-x 2 alaveteli alaveteli 4096 Aug  2 15:17 hr
drwxrwxr-x 2 alaveteli alaveteli 4096 Aug  2 15:17 en
drwxrwxr-x 8 alaveteli alaveteli 4096 Aug  2 15:17 ..
```

**Comment by gbp** [comment]
This looks like you aren't the `alaveteli` user so Rails can't connect to the database.

Running this locally against your theme, I had:

```
> rake gettext:find_theme THEME=imamopravoznati-theme
Warning: obsolete msgid exists.
         #~ msgid "simple_date_format"
Warning: obsolete msgid exists.
         #~ msgstr "%e %B %Y"
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/gbp/Developer/work/alaveteli/lib/themes/imamopravoznati-theme/locale-theme/app.pot
po_parser.ry:317:in `detect_file_encoding'
po_parser.ry:308:in `parse_file'
/Users/gbp/Developer/work/alaveteli/.direnv/gems/2.7.3p183/gems/gettext-3.3.8/lib/gettext/tools/msgmerge.rb:56:in `run'
/Users/gbp/Developer/work/alaveteli/.direnv/gems/2.7.3p183/gems/gettext-3.3.8/lib/gettext/tools/msgmerge.rb:38:in `run'
/Users/gbp/Developer/work/alaveteli/lib/tasks/gettext.rake:8:in `msgmerge'
/Users/gbp/Developer/work/alaveteli/lib/tasks/gettext.rake:48:in `xgettext'
/Users/gbp/Developer/work/alaveteli/lib/tasks/gettext.rake:57:in `find'
/Users/gbp/Developer/work/alaveteli/lib/tasks/gettext.rake:78:in `block (2 levels) in <top (required)>'
Tasks: TOP => gettext:find_theme
(See full trace by running task with --trace)
```

So I ran:

```
touch lib/themes/imamopravoznati-theme/locale-theme/app.pot
```

And then the rake command worked as expected

**Comment by schlos** [comment]
Works as expected:

```
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme$ sudo -u alaveteli touch app.pot
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme$ ls -al
total 16
drwxrwxr-x 4 alaveteli alaveteli 4096 Sep 18 06:34 .
drwxrwxr-x 8 alaveteli alaveteli 4096 Aug  2 15:17 ..
-rw-r--r-- 1 alaveteli alaveteli    0 Sep 18 06:34 app.pot
drwxrwxr-x 2 alaveteli alaveteli 4096 Aug  2 15:17 en
drwxrwxr-x 2 alaveteli alaveteli 4096 Aug  2 15:17 hr
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme$ cd ../../../..
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli$ sudo -u alaveteli bundle exec rake gettext:find_theme THEME=imamopravoznati-theme
`/home/schlos` is not writable.
Bundler will use `/tmp/bundler/home/schlos' as your home directory temporarily.
Warning: obsolete msgid exists.
         #~ msgid "simple_date_format"
Warning: obsolete msgid exists.
         #~ msgstr "%e %B %Y"
Warning: obsolete msgid exists.
         #~ msgid "simple_date_format"
Warning: obsolete msgid exists.
         #~ msgstr "%e %B %Y"
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli$ cd lib/themes/imamopravoznati-theme/locale-theme/
schlos@imamopravoznati:/var/www/imamopravoznati.org/alaveteli/lib/themes/imamopravoznati-theme/locale-theme$ ls -al
total 32
drwxrwxr-x 4 alaveteli alaveteli  4096 Sep 18 06:34 .
drwxrwxr-x 8 alaveteli alaveteli  4096 Aug  2 15:17 ..
-rw-r--r-- 1 alaveteli alaveteli 14593 Sep 18 06:35 app.pot
drwxrwxr-x 2 alaveteli alaveteli  4096 Aug  2 15:17 en
drwxrwxr-x 2 alaveteli alaveteli  4096 Aug  2 15:17 hr
```
