### ISSUE TITLE
[ERROR] admin_holiday_imports#new (ArgumentError) "ArgumentError"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5947]
```
An ArgumentError occurred in admin_holiday_imports#new:

ArgumentError
app/models/holiday_import.rb:94:in `populate_from_suggestions'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/holiday_imports/new?utf8=%E2%9C%93&holiday_import%5Bstart_year%5D=2021&holiday_import%5Bend_year%5D=2020&holiday_import%5Bsource%5D=suggestions
* HTTP Method: GET
* Parameters : {"utf8"=>"✓", "holiday_import"=>{"start_year"=>"2021", "end_year"=>"2020", "source"=>"suggestions"}, "controller"=>"admin_holiday_imports", "action"=>"new"}
* Timestamp : 2020-11-01 12:42:45 +0000
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-10-15T14-44-42

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>802,
"ttl"=>"2020-11-01T12:41:53.897+00:00",
"remember_me"=>false,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED",
"using_admin"=>1,
"admin_name"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/models/holiday_import.rb:94:in `populate_from_suggestions'
app/models/holiday_import.rb:33:in `populate'
app/controllers/admin_holiday_imports_controller.rb:6:in `new'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
