### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "PG::CharacterNotInRepertoire"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5964]
Related to https://github.com/mysociety/alaveteli/issues/3468 and https://github.com/mysociety/alaveteli/issues/2512.

Previous issues fixed by https://github.com/mysociety/alaveteli/commit/58f77d8c63fe4c602c851fcbc42544acdbba4f59.

This issue relates to creating an `FoiAttachment` rather than `IncomingMessage` as in the previous issues.

Possibly caused by https://github.com/mysociety/alaveteli/issues/3155 – truncation splitting in a bad place causing an invalid character?

```
An ActionView::Template::Error occurred in request#show:

PG::CharacterNotInRepertoire: ERROR: invalid byte sequence for encoding "UTF8": 0x92
: INSERT INTO "foi_attachments" ("content_type", "filename", "charset", "display_size", "url_part_number", "within_rfc822_subject", "incoming_message_id", "hexdigest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"
app/models/incoming_message.rb:565:in `block in extract_attachments!'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/request/cycle_lanes_department_for_trans
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"cycle_lanes_department_for_trans"}
* Timestamp : 2020-11-09 20:31:17 +0000
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-10-15T14-44-42

-------------------------------
Backtrace:
-------------------------------

app/models/incoming_message.rb:565:in `block in extract_attachments!'
app/models/incoming_message.rb:563:in `each'
app/models/incoming_message.rb:563:in `extract_attachments!'
app/models/incoming_message.rb:98:in `block in parse_raw_email!'
app/models/incoming_message.rb:97:in `parse_raw_email!'
app/models/incoming_message.rb:178:in `mail_from'
app/models/incoming_message.rb:197:in `safe_mail_from'
app/models/incoming_message.rb:220:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_request__incoming_correspondence_html_erb__1309907130850446523_69948296001860'
app/views/request/events/_response.html.erb:1:in `_app_views_request_events__response_html_erb___1331334689555952126_69948295986440'
app/views/request/_correspondence.html.erb:5:in `_app_views_request__correspondence_html_erb___2980847104479304490_69948295399880'
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:45:in `block in _lib_themes_whatdotheyknow_theme_lib_views_request_show_html_erb__3882092831487054954_69948081669120'
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:43:in `_lib_themes_whatdotheyknow_theme_lib_views_request_show_html_erb__3882092831487054954_69948081669120'
app/controllers/request_controller.rb:125:in `block (3 levels) in show'
app/controllers/request_controller.rb:124:in `block in show'
lib/alaveteli_localization.rb:49:in `with_locale'
app/controllers/request_controller.rb:75:in `show'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Had a couple more exceptions for people trying to view this request over the last month.

**Comment by garethrees** [comment]
Another instance of this at `https://www.whatdotheyknow.com/request/noel_park_pods_feasibility_study`

```
-------------------------------
Backtrace:
-------------------------------

app/models/incoming_message.rb:566:in `block in extract_attachments!'
app/models/incoming_message.rb:564:in `each'
app/models/incoming_message.rb:564:in `extract_attachments!'
app/models/incoming_message.rb:99:in `block in parse_raw_email!'
app/models/incoming_message.rb:98:in `parse_raw_email!'
app/models/incoming_message.rb:179:in `mail_from'
app/models/incoming_message.rb:198:in `safe_mail_from'
app/models/incoming_message.rb:221:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_request__incoming_correspondence_html_erb___1217228347788478161_47303508994060'
app/views/request/events/_response.html.erb:1:in `_app_views_request_events__response_html_erb__3697731860206055193_47303508890020'
app/views/request/_correspondence.html.erb:5:in `_app_views_request__correspondence_html_erb___63858862101707169_70067365160560'
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:45:in `block in _lib_themes_whatdotheyknow_theme_lib_views_request_show_html_erb__610846727024926379_70067373434980'
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:43:in `_lib_themes_whatdotheyknow_theme_lib_views_request_show_html_erb__610846727024926379_70067373434980'
app/controllers/request_controller.rb:125:in `block (3 levels) in show'
app/controllers/request_controller.rb:124:in `block in show'
lib/alaveteli_localization.rb:49:in `with_locale'
app/controllers/request_controller.rb:78:in `show'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
In the most recent example it's actually the `within_rfc822_subject` key that's problematic:

```
[7] pry(#<IncomingMessage>)> attrs
=> {:url_part_number=>3,
 :content_type=>"text/html",
 :filename=>nil,
 :charset=>"UTF-8",
 :within_rfc822_subject=>"Freedom of Information request - Noel Park Pods \x97 Feasibility Study",
 :body=>
  "<html>…SNIP…</html>\n\n",
 :hexdigest=>"424506d74046f2b33cffdde78f3afbb0"}

[8] pry(#<IncomingMessage>)> attachment.update(attrs)
  FoiAttachment Create (2.4ms)  INSERT INTO "foi_attachments" ("content_type", "filename", "charset", "display_size", "url_part_number", "within_rfc822_subject", "incoming_message_id", "hexdigest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["content_type", "text/html"], ["filename", "Freedom of Information request - Noel Park Pods \x97 Feasibility Study.html"], ["charset", "UTF-8"], ["display_size", "1K"], ["url_part_number", 3], ["within_rfc822_subject", "Freedom of Information request - Noel Park Pods \x97 Feasibility Study"], ["incoming_message_id", 7], ["hexdigest", "424506d74046f2b33cffdde78f3afbb0"], ["created_at", "2021-01-11 10:42:52.963576"], ["updated_at", "2021-01-11 10:42:52.963576"]]
  ↳ (pry):10
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
: INSERT INTO "foi_attachments" ("content_type", "filename", "charset", "display_size", "url_part_number", "within_rfc822_subject", "incoming_message_id", "hexdigest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"
from /home/vagrant/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `exec_params'
Caused by PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

from /home/vagrant/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `exec_params'

**Comment by gbp** [comment]
Had a similar error over the weekend:

```
 PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0x97
: SELECT "foi_attachments".* FROM "foi_attachments" WHERE "foi_attachments"."incoming_message_id" = $1 ORDER BY id
  app/models/incoming_message.rb:491:in `get_main_body_text_part'
```

Basically a `SELECT` instead of the `INSERT`. Is there a cleanup task required after fix?

**Comment by garethrees** [comment]
Wasn't intending there to be a cleanup task, so best ticket the new thing up for now.
