### ISSUE TITLE
[ERROR] script/update-xapian-index warning: regular expression has ']' without escape

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5967]
```
[cron-alaveteli] Cron <foi@redacted> /usr/bin/env XAPIAN_MAX_CHANGESETS=10 run-with-lockfile -n /APP_ROOT/change-xapian-database.lock "/APP_ROOT/alaveteli/script/update-xapian-index verbose=true" >> /APP_ROOT/alaveteli/log/update-xapian-index.log || echo "stalled?"

/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:49: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:49: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:49: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape
/APP_ROOT/alaveteli-2020-10-15T14-44-42/app/models/censor_rule.rb:119: warning: regular expression has ']' without escape

```

**Comment by garethrees** [comment]
Argh. My first thought was, oh, let's just use `Regexp.escape`:

```diff
diff --git a/app/models/censor_rule.rb b/app/models/censor_rule.rb
index 15218171d..b3b4cde2b 100644
--- a/app/models/censor_rule.rb
+++ b/app/models/censor_rule.rb
@@ -116,7 +116,7 @@ def encoded_text(encoding)
   end
 
   def make_regexp(encoding)
-    Regexp.new(encoded_text(encoding), Regexp::MULTILINE)
+    Regexp.new(Regexp.escape(encoded_text(encoding)), Regexp::MULTILINE)
   end
 
 end
diff --git a/spec/models/censor_rule_spec.rb b/spec/models/censor_rule_spec.rb
index 166bf1451..08bbbd453 100644
--- a/spec/models/censor_rule_spec.rb
+++ b/spec/models/censor_rule_spec.rb
@@ -282,6 +282,13 @@
 
     end
 
+    describe 'if a regexp contains unescaped characters' do
+      it 'escapes the regexp and does not output a warning' do
+        @censor_rule.text = 'foo]'
+        expect { @censor_rule.valid? }.not_to output.to_stderr
+      end
+    end
+
     describe 'if no regexp error is produced' do
 
       it 'should not add any error message to the text field' do
```

…but ugh, we _don't_ want to escape most regexp strings since we _do_ want the special chars, `.*` for example, to be directly interpreted as regexp.

```
$ bin/rspec spec/models/censor_rule_spec.rb

Randomized with seed 50095
..F........F..F.............F...

Failures:

  1) CensorRule#apply_to_text replaces the regexp with the replacement text when applied to text
     Failure/Error:
             expect(rule.apply_to_text(text)).to eq <<-EOF.strip_heredoc
             Some public information
             --REMOVED
             Hidden private info
             --REMOVED
             EOF

       expected: "Some public information\n--REMOVED\nHidden private info\n--REMOVED\n"
            got: "Some public information\n--PRIVATE\nSome private information\n--PRIVATE\n"

       (compared using ==)

       Diff:
       @@ -1,5 +1,5 @@
        Some public information
       ---REMOVED
       -Hidden private info
       ---REMOVED
       +--PRIVATE
       +Some private information
       +--PRIVATE

     # ./spec/models/censor_rule_spec.rb:56:in `block (3 levels) in <top (required)>'
     # /home/vagrant/bundle/ruby/2.5.0/gems/webmock-3.9.5/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) CensorRule#apply_to_binary handles a UTF-8 rule with ASCII-8BIT text
     Failure/Error:
             expect(rule.apply_to_binary(text)).to eq <<-EOF.strip_heredoc
             Some public information
             xxxxxxxxx
             xxxxxxxxxxxxxxxxxxxxxxxx
             xxxxxxxxxxxx
             EOF

       expected: "Some public information\nxxxxxxxxx\nxxxxxxxxxxxxxxxxxxxxxxxx\nxxxxxxxxxxxx\n"
            got: "Some public information\n--PRIVATE\nSome private information\n--P\xE2\x80\x98RIVATE\n"

       (compared using ==)

       Diff:
       @@ -1,5 +1,5 @@
        Some public information
       -xxxxxxxxx
       -xxxxxxxxxxxxxxxxxxxxxxxx
       -xxxxxxxxxxxx
       +--PRIVATE
       +Some private information
       +--P???RIVATE

     # ./spec/models/censor_rule_spec.rb:151:in `block (3 levels) in <top (required)>'
     # /home/vagrant/bundle/ruby/2.5.0/gems/webmock-3.9.5/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  3) CensorRule#apply_to_binary replaces the regexp with the same number of 'x' characters as the text
        replaced when applied to binary
     Failure/Error:
             expect(rule.apply_to_binary(text)).to eq <<-EOF.strip_heredoc
             Some public information
             xxxxxxxxx
             xxxxxxxxxxxxxxxxxxxxxxxx
             xxxxxxxxx
             EOF

       expected: "Some public information\nxxxxxxxxx\nxxxxxxxxxxxxxxxxxxxxxxxx\nxxxxxxxxx\n"
            got: "Some public information\n--PRIVATE\nSome private information\n--PRIVATE\n"

       (compared using ==)

       Diff:
       @@ -1,5 +1,5 @@
        Some public information
       -xxxxxxxxx
       -xxxxxxxxxxxxxxxxxxxxxxxx
       -xxxxxxxxx
       +--PRIVATE
       +Some private information
       +--PRIVATE

     # ./spec/models/censor_rule_spec.rb:130:in `block (3 levels) in <top (required)>'
     # /home/vagrant/bundle/ruby/2.5.0/gems/webmock-3.9.5/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  4) when validating rules when validating a regexp rule should try to create a regexp from the text
     Failure/Error: Regexp.new(Regexp.escape(encoded_text(encoding)), Regexp::MULTILINE)

       #<Regexp (class)> received :new with unexpected arguments
         expected: ("*", 4)
              got: ("\\*", 4)
     # ./app/models/censor_rule.rb:119:in `make_regexp'
     # ./app/models/censor_rule.rb:104:in `require_valid_regexp'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `catch'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `block in default_terminator'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:409:in `run_validations!'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activemodel-5.2.4.4/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activemodel-5.2.4.4/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:339:in `valid?'
     # /home/vagrant/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:67:in `valid?'
     # ./spec/models/censor_rule_spec.rb:272:in `block (3 levels) in <top (required)>'
     # /home/vagrant/bundle/ruby/2.5.0/gems/webmock-3.9.5/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 3.19 seconds (files took 9.34 seconds to load)
32 examples, 4 failures

Failed examples:

rspec ./spec/models/censor_rule_spec.rb:44 # CensorRule#apply_to_text replaces the regexp with the replacement text when applied to text
rspec ./spec/models/censor_rule_spec.rb:138 # CensorRule#apply_to_binary handles a UTF-8 rule with ASCII-8BIT text
rspec ./spec/models/censor_rule_spec.rb:117 # CensorRule#apply_to_binary replaces the regexp with the same number of 'x' characters as the text
        replaced when applied to binary
rspec ./spec/models/censor_rule_spec.rb:270 # when validating rules when validating a regexp rule should try to create a regexp from the text

Randomized with seed 50095
```

**Comment by garethrees** [comment]
Overriding [`Warning.warn`](https://ruby-doc.org/core-2.6.6/Warning.html) does what we want (the error is a bit untidy, but no big deal for this edge case). 

```diff
diff --git a/app/models/censor_rule.rb b/app/models/censor_rule.rb
index 15218171d..b9c0dc779 100644
--- a/app/models/censor_rule.rb
+++ b/app/models/censor_rule.rb
@@ -116,6 +116,12 @@ def encoded_text(encoding)
   end
 
   def make_regexp(encoding)
+    Warning.instance_eval do
+      def warn(msg)
+        raise RegexpError, msg
+      end
+    end
+
     Regexp.new(encoded_text(encoding), Regexp::MULTILINE)
   end
 
diff --git a/spec/models/censor_rule_spec.rb b/spec/models/censor_rule_spec.rb
index 166bf1451..216e7d466 100644
--- a/spec/models/censor_rule_spec.rb
+++ b/spec/models/censor_rule_spec.rb
@@ -282,6 +282,14 @@
 
     end
 
+    describe 'if a regexp contains unescaped characters' do
+      it 'escapes the regexp and does not output a warning' do
+        @censor_rule.text = 'foo]'
+        expect { @censor_rule.valid? }.not_to output.to_stderr
+        expect(@censor_rule.errors[:text].first).to match /without escape/
+      end
+    end
+
     describe 'if no regexp error is produced' do
 
       it 'should not add any error message to the text field' do
```

<img width="982" alt="Screenshot 2020-11-12 at 10 31 25" src="https://user-images.githubusercontent.com/282788/98929007-73d4f380-24d2-11eb-932e-48f66ae98554.png">

Just need to figure out how to make this override temporary, otherwise all calls to `.warn` end up raising:


```ruby
r = CensorRule.new(text: 'foo]', regexp: true, replacement: 'foo')
# => #<CensorRule:0x0000561eaeedaa58…>

r.apply_to_text('foo')
# => RegexpError: /home/vagrant/alaveteli/app/models/censor_rule.rb:125: warning: regular expression has ']' without escape: /foo]/
# => from /home/vagrant/alaveteli/app/models/censor_rule.rb:121:in `warn'

Warning.warn('test')
# => RegexpError: test
# => from /home/vagrant/alaveteli/app/models/censor_rule.rb:121:in `warn'
```

**Comment by garethrees** [comment]
Okay, figured it out:

```diff
diff --git a/app/models/censor_rule.rb b/app/models/censor_rule.rb
index 15218171d..e46705774 100644
--- a/app/models/censor_rule.rb
+++ b/app/models/censor_rule.rb
@@ -22,6 +22,22 @@
 # Copyright (c) 2008 UK Citizens Online Democracy. All rights reserved.
 # Email: hello@mysociety.org; WWW: http://www.mysociety.org/
 
+Warning.module_eval do
+  class RaisedWarning < StandardError ; end
+
+  def self.with_raised_warnings(&block)
+    alias warn_original warn
+    alias warn raise_warning
+    block.call if block_given?
+  ensure
+    alias warn warn_original
+  end
+
+  def raise_warning(msg)
+    raise RaisedWarning, msg
+  end
+end
+
 class CensorRule < ApplicationRecord
   include AdminColumn
   belongs_to :info_request,
@@ -116,7 +132,10 @@ def encoded_text(encoding)
   end
 
   def make_regexp(encoding)
-    Regexp.new(encoded_text(encoding), Regexp::MULTILINE)
+    Warning.with_raised_warnings do
+      Regexp.new(encoded_text(encoding), Regexp::MULTILINE)
+    end
+  rescue RaisedWarning => e
+    raise RegexpError, e.message.split('warning: ').last.chomp
   end
-
 end
diff --git a/spec/models/censor_rule_spec.rb b/spec/models/censor_rule_spec.rb
index 166bf1451..f602db0e7 100644
--- a/spec/models/censor_rule_spec.rb
+++ b/spec/models/censor_rule_spec.rb
@@ -282,6 +282,20 @@
 
     end
 
+    describe 'if a regexp contains unescaped characters' do
+      before { @censor_rule.text = 'foo]' }
+
+      it 'escapes the regexp and does not output a warning' do
+        expect { @censor_rule.valid? }.not_to output.to_stderr
+      end
+
+      it 'adds an error to the admin' do
+        msg = "regular expression has ']' without escape: /foo]/"
+        @censor_rule.valid?
+        expect(@censor_rule.errors[:text]).to eq([msg])
+      end
+    end
+
     describe 'if no regexp error is produced' do
 
       it 'should not add any error message to the text field' do
```

This also makes it easier to provide a nicer error message:

<img width="969" alt="Screenshot 2020-11-12 at 11 16 13" src="https://user-images.githubusercontent.com/282788/98933563-b8fc2400-24d8-11eb-886a-ee69cea30fe2.png">
