### ISSUE TITLE
Transient spec failure in MailHandler::Backends::MailBackend.mail_from_raw_email

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5986]
Different `Mail::Message` object ID

```
Failures:
  1) MailHandler::Backends::MailBackend mail_from_raw_email when passed a mail returns a new mail instance of the email
     Failure/Error: is_expected.to eq Mail.read_from_string(raw_email)
     
       expected: #<Mail::Message:180409780, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
            got: #<Mail::Message:180612380, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -#<Mail::Message:180409780, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
       +#<Mail::Message:180612380, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
       
     # ./spec/lib/mail_handler/backends/mail_backend_spec.rb:62:in `block (4 levels) in <top (required)>'
Finished in 16 minutes 36 seconds (files took 8.46 seconds to load)
6703 examples, 1 failure, 5 pending
Failed examples:
rspec ./spec/lib/mail_handler/backends/mail_backend_spec.rb:61 # MailHandler::Backends::MailBackend mail_from_raw_email when passed a mail returns a new mail instance of the email
Randomized with seed 54294
```

**Comment by gbp** [comment]
I think my change https://github.com/mysociety/alaveteli/commit/38091abc294ca86459d2d95a1f9b61cc980d81ca could have caused additional transient errors - this could be the cause here too. I did start looking at this and leaving this comment as a way to remember next week

**Comment by gbp** [comment]
Still seeing this:

```
Failures:

  1) MailHandler::Backends::MailBackend mail_from_raw_email when passed a mail returns a new mail instance of the email
     Failure/Error: is_expected.to eq Mail.read_from_string(raw_email)

       expected: #<Mail::Message:439880, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
            got: #<Mail::Message:439900, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>

       (compared using ==)

       Diff:
       @@ -1 +1 @@
       -#<Mail::Message:439880, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
       +#<Mail::Message:439900, Multipart: false, Headers: <Content-Type: text/plain; charset=us-ascii>, <Content-Disposition: inline>>
     # ./spec/lib/mail_handler/backends/mail_backend_spec.rb:61:in `block (4 levels) in <top (required)>'


Finished in 22 minutes 1 second (files took 9.99 seconds to load)
7045 examples, 1 failure, 5 pending

Failed examples:

rspec ./spec/lib/mail_handler/backends/mail_backend_spec.rb:60 # MailHandler::Backends::MailBackend mail_from_raw_email when passed a mail returns a new mail instance of the email

Randomized with seed 15153
```

**Comment by gbp** [comment]
Saw this one again today. Had a quick go at replicating locally. It is possibly.

Running this might hit the error once or twice.
```
for i in {1..100}; do rspec spec/models/raw_email_spec.rb:155; done
```

Attempted to debug too. By adding:
```diff
diff --git a/spec/models/raw_email_spec.rb b/spec/models/raw_email_spec.rb
index 8595d698a..a39d710f1 100644
--- a/spec/models/raw_email_spec.rb
+++ b/spec/models/raw_email_spec.rb
@@ -153,6 +153,9 @@ def test_real(fixture_file, expected)
     end
 
     it 'parses the raw email data in to a structured mail object' do
+      m1 = raw_email.mail!
+      m2 = mock_mail
+      binding.pry if m1 != m2
       expect(raw_email.mail!).to eq(mock_mail)
     end
 
```

When dropped into `pry` the situation changes:
```
[1] pry(#<RSpec::ExampleGroups::RawEmail::Mail_2>)> m1 != m2
=> false
```

Looking at the comparison method at https://github.com/mikel/mail/blob/2.7.1/lib/mail/message.rb#L380-L389. Maybe the `#encode` method is changing the original raw mail data?

One solution would be to compare message ID here instead of the whole mail object.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
