### ISSUE TITLE
Replace the emergency user with a mechanism for adding the first admin roles

### ISSUE THREAD

**Issue by mlandauer** [mysociety/alaveteli#5996]
To reproduce:
* Take a fresh install running on vagrant (the latest released version)
* Go to http://10.10.10.30:3000/admin?emergency=1
* Enter the username and password in `config/general.yml`

The application then fails with the error:
```
undefined method `created_at' for nil:NilClass
```

Backtrace:
```
app/models/announcement.rb:48:in `block in <class:Announcement>'
app/controllers/admin_general_controller.rb:64:in `index'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

If you quickly hack the code to use something like safe navigation you get errors elsewhere too. It looks to me like `@user` is not getting set because the emergency admin login works by setting something in the session but doesn't go through the normal authorization path and the new roles code assumes that `@user` is getting set.

To be honest, I've never been particularly fond of the "emergency user" login process for new people setting up Alavetelli. I wouldn't mourn its passing if you were to get rid of it.

Two pretty simple replacement options could be:
* replace it with a simple rake task which would add admin privileges to an existing login
* or a rake task which creates an admin account (given an email address) and outputs a temporary password to the console.

Those two options would also provide just a little more security than the current option as there would be no chance, as there is now, of a user accidentally leaving the `ADMIN_USERNAME` and `ADMIN_PASSWORD` settings unchanged from the defaults.

**Comment by garethrees** [comment]
> It looks to me like `@user` is not getting set because the emergency admin login works by setting something in the session but doesn't go through the normal authorization path and the new roles code assumes that `@user` is getting set.

Yeah, I think this is essentially the same issue as https://github.com/mysociety/alaveteli/issues/5604.

> To be honest, I've never been particularly fond of the "emergency user" login process for new people setting up Alavetelli. I wouldn't mourn its passing if you were to get rid of it.

+1. (Noting https://github.com/mysociety/alaveteli/issues/810)

> replace it with a simple rake task which would add admin privileges to an existing login

I think this could be a good option. It would reduce complexity of the task by only needing to worry about adding given roles and not needing to duplicate the user creation steps.

```sh
# Could use the environment to set the particulars…
$ USER=foo@example.com ROLES="admin,pro_admin" rake users:add_roles

# Or a combination of the env and rake arguments
$ USER=foo@example.com rake users:add_roles[admin, pro_admin]
```

I like the above because it can be used on initial Alaveteli setup, or after enabling Pro and needing to [add the first `pro_admin` role](https://alaveteli.org/docs/pro/#assigning-your-first-pro-admin).

**Comment by garethrees** [comment]
I've renamed this issue to reflect the improvement proposal, since we have https://github.com/mysociety/alaveteli/issues/5604 to represent the existing setup and what would to happen to just fix the bug.

**Comment by mlandauer** [comment]
I think the suggested solution here is better than #810 which is a bit clunky and could easily lead to people having an admin account on their instance that they forget and is created in a bit of a roundabout and confusing way. The solution suggested here also removes two configuration variables and I think that in of itself is a great thing.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
