### ISSUE TITLE
ES6 syntax breaks asset compilation

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6008]
```
rake aborted!
Uglifier::Error: Unexpected token name «of», expected punc «;». To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
--
 19971         return false;
 19972       }
 19973
 19974       if (!showIfArray) {
 19975         wizard.log("MATCH:", this.block, "no show-if");
 19976         return true;
 19977       }
 19978
    =>       for (var showIf of showIfArray) {
 19980         // can't be a dependent if showIf is for a different question ID
 19981         // check showIf operator
 19982         if (
 19983           showIf.id === question.block &&
 19984           showIf.operator === "is" &&
 19985           question.values().indexOf(showIf.value) > -1
 19986         ) {
 19987           wizard.log("MATCH:", this.block, showIf, question.values());
==
/data/vhost/www.whatdotheyknow.com/alaveteli-2020-12-09T12-27-54/app/assets/config/manifest.js:2
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:388:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:357:in `block in link_paths'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:367:in `block in resolve_paths'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:363:in `each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:363:in `resolve_paths'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:356:in `link_paths'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:317:in `process_link_directory_directive'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:178:in `each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:178:in `process_directives'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:83:in `_call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:68:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/rbenv/versions/2.6.6/bin/bundle:23:in `load'
/opt/rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
in /data/servers: su -l foi -c cd "/data/vhost/www.whatdotheyknow.com/alaveteli-2020-12-09T12-27-54" && script/rails-deploy-before-down: system: exited with status 1 at /data/mysociety/bin/../perllib/mySociety/SystemMisc.pm line 332.
```

**Comment by garethrees** [comment]
Needs experimental "harmony mode" enabled https://github.com/lautis/uglifier#es6--es2015--harmony-mode
