### ISSUE TITLE
[ERROR] admin_raw_email#show (NoMethodError) "undefined method `params' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6012]
```
A NoMethodError occurred in admin_raw_email#show:

undefined method `params' for nil:NilClass
app/controllers/admin_raw_email_controller.rb:61:in `rejected_reason'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/raw_emails/1688121
* HTTP Method: GET
* Parameters : {"controller"=>"admin_raw_email", "action"=>"show", "id"=>"1688121"}
* Timestamp : 2020-12-10 03:08:44 +0000
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2020-12-09T13-13-03

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>184915,
"remember_me"=>true,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED",
"using_admin"=>1,
"admin_name"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_raw_email_controller.rb:61:in `rejected_reason'
app/controllers/admin_raw_email_controller.rb:35:in `block (2 levels) in show'
app/controllers/admin_raw_email_controller.rb:12:in `show'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
