### ISSUE TITLE
[ERROR] request#download_entire_request (NameError) "uninitialized constant Zip::ZipFile"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6014]
```
A NameError occurred in request#download_entire_request:

uninitialized constant Zip::ZipFile
lib/themes/ipvtheme/lib/controller_patches.rb:54:in `make_request_zip'

-------------------------------
Request:
-------------------------------

* URL : https://www.infoprovsechny.cz/request/dovoz_obytneho_privesu_z_usa/download
* HTTP Method: GET

* Parameters : {"controller"=>"request", "action"=>"download_entire_request", "url_title"=>"dovoz_obytneho_privesu_z_usa"}
* Timestamp : 2020-12-06 09:44:38 +0100
* Rails root : /data/vhost/czechia.alaveteli.org/alaveteli-2020-11-09T10-02-51

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"cs",
"user_id"=>1506,
"ttl"=>"2020-12-06T09:44:27.193+01:00",
"remember_me"=>false,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

lib/themes/ipvtheme/lib/controller_patches.rb:54:in `make_request_zip'
app/controllers/request_controller.rb:554:in `block in download_entire_request'
lib/alaveteli_localization.rb:49:in `with_locale'
app/controllers/request_controller.rb:533:in `download_entire_request'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Probably caused by https://github.com/mysociety/sysadmin/issues/1293.

The current release of Alaveteli uses [`Zip::File`](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/controllers/request_controller.rb#L654-L671) but the them has the old [`Zip::ZipFile`](https://github.com/mysociety/ipvtheme/blob/78347b91ac62dc1c50dd479915ad6bf3ffed3b3b/lib/controller_patches.rb#L54).

Quick look at the blame suggests https://github.com/mysociety/ipvtheme/commit/98d820638ce8ec89b99f72467be5f6cfcec234e7 was the reason for overriding `make_request_zip`. Need to re-reconcile the patch with the current release.

**Comment by garethrees** [comment]
Still getting the same error – only one instance of `Zip::ZipFile` got changed. I assume it needs:

```diff
- Zip::File.open(file_path, Zip::ZipFile::CREATE) do |zipfile|
+ Zip::File.open(file_path, Zip::File::CREATE) do |zipfile|
```

**Comment by gbp** [comment]
https://github.com/mysociety/ipvtheme/commit/2c11321659a10958ad15c3e4bf1cb1fe05e46bea
