### ISSUE TITLE
[ERROR] attachments#show_as_html (Encoding::InvalidByteSequenceError) "\"\\x92\" on ISO-2022-JP

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6046]
```
An Encoding::InvalidByteSequenceError occurred in attachments#show_as_html:

  "\x92" on ISO-2022-JP
  lib/normalize_string.rb:39:in `encode'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/180542/response/457167/attach/html/3/Response%20895%2013.pdf.html
  * HTTP Method: GET
  * Parameters : {"controller"=>"attachments", "action"=>"show_as_html", "id"=>"180542", "incoming_message_id"=>"457167", "part"=>"3", "file_name"=>"Response 895 13.pdf.html"}
  * Timestamp  : 2021-01-01 05:22:16 +0000
  * Rails root : /REDACTED/alaveteli-2020-12-17T11-58-46

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"REDACTED", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

  lib/normalize_string.rb:39:in `encode'
  lib/normalize_string.rb:39:in `block in normalize_string_to_utf8'
  lib/normalize_string.rb:31:in `each'
  lib/normalize_string.rb:31:in `normalize_string_to_utf8'
  lib/normalize_string.rb:78:in `convert_string_to_utf8_or_binary'
  lib/mail_handler/backends/mail_backend.rb:89:in `get_part_body'
  lib/mail_handler/backends/mail_backend.rb:371:in `block in get_attachment_attributes'
  lib/mail_handler/backends/mail_backend.rb:370:in `each'
  lib/mail_handler/backends/mail_backend.rb:370:in `get_attachment_attributes'
  app/models/incoming_message.rb:562:in `extract_attachments!'
  app/models/incoming_message.rb:99:in `block in parse_raw_email!'
  app/models/incoming_message.rb:98:in `parse_raw_email!'
  app/models/foi_attachment.rb:94:in `rescue in body'
  app/models/foi_attachment.rb:81:in `body'
  app/models/foi_attachment.rb:109:in `default_body'
  lib/attachment_to_html/adapter.rb:60:in `attachment_body'
  lib/attachment_to_html/adapters/pdf.rb:50:in `convert'
  lib/attachment_to_html/adapters/pdf.rb:32:in `parse_body'
  lib/attachment_to_html/adapter.rb:25:in `body'
  lib/attachment_to_html/adapters/pdf.rb:44:in `number_of_images_in_body'
  lib/attachment_to_html/adapters/pdf.rb:40:in `contains_too_many_images?'
  lib/attachment_to_html/adapters/pdf.rb:25:in `success?'
  lib/attachment_to_html/attachment_to_html.rb:16:in `to_html'
  app/models/foi_attachment.rb:311:in `body_as_html'
  app/controllers/attachments_controller.rb:40:in `show_as_html'
  app/controllers/attachments_controller.rb:137:in `cache_attachments'
  app/controllers/application_controller.rb:113:in `record_memory'
  lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Wonder if the fix for this will be similar to https://github.com/mysociety/alaveteli/pull/6451

**Comment by gbp** [comment]
Yes! This seems to work. I'll get a spec written for this.

```diff
diff --git a/lib/normalize_string.rb b/lib/normalize_string.rb
index 86e6946e4..8e1effb66 100644
--- a/lib/normalize_string.rb
+++ b/lib/normalize_string.rb
@@ -37,7 +37,8 @@ def normalize_string_to_utf8(s, suggested_character_encoding=nil)
         # We get this is there are invalid bytes when
         # interpreted as from_encoding at the point of
         # the encode('UTF-8'); move onto the next one...
-      rescue Encoding::ConverterNotFoundError => ex
+      rescue Encoding::ConverterNotFoundError,
+             Encoding::InvalidByteSequenceError => ex
         raise EncodingNormalizationError, ex.message
       end
     end
```
