### ISSUE TITLE
[ERROR] user#signup (Recaptcha::RecaptchaError) "Failed to open TCP connection to…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6047]
```
A Recaptcha::RecaptchaError occurred in user#signup:

Failed to open TCP connection to www.recaptcha.net:443 (getaddrinfo: Temporary failure in name resolution)
app/controllers/user_controller.rb:129:in `signup'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/sign_up
* HTTP Method: POST
* Parameters : {"remember_me"=>"1", "user_signin"=>{"email"=>"REDACTED", "password"=>"[FILTERED]"}, "query"=>"dANrqofxMlb", "g-recaptcha-response"=>"REDACTED", "user_signup"=>{"email"=>"REDACTED", "name"=>"rRmjJNbcdhgFMEvw", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "commit"=>"Sign in", "authenticity_token"=>"", "utf8"=>"✓", "token"=>"REDACTED", "modal"=>"", "controller"=>"user", "action"=>"signup"}
* Timestamp : 2020-12-18 15:46:24 +0000
* Rails root : /REDACTED/alaveteli-2020-12-17T11-58-46

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/user_controller.rb:129:in `signup'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Looks like spam (see the `user_signup``name` param), but worth noting as we should be more resilient to external service errors.

Noting that we're considering alternatives (#5995) so not something to immediately worry about.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
