### ISSUE TITLE
[ERROR] payment_methods#update (Stripe::InvalidRequestError) "Could not determine which URL to..."

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6171]
```
A Stripe::InvalidRequestError occurred in payment_methods#update:

Could not determine which URL to request: Stripe::Token instance has invalid ID: nil
app/controllers/alaveteli_pro/payment_methods_controller.rb:7:in `update'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/subscriptions/payment_method
* HTTP Method: PUT
* IP address : REDACTED
* Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"REDACTED", "controller"=>"alaveteli_pro/payment_methods", "action"=>"update"}
* Timestamp : 2021-03-19 10:53:13 +0000
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-03-15T12-27-55

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>84929,
"user_circumstance"=>"normal",
"post_redirect_token"=>"REDACTED",
"ttl"=>"2021-03-19T10:53:07.079+00:00",
"_csrf_token"=>"REDACTED"}


-------------------------------
Backtrace:
-------------------------------

app/controllers/alaveteli_pro/payment_methods_controller.rb:7:in `update'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
I've attempted to replicate this error but without any luck. The Stripe customer here looks to have a valid card information so am going to closes this until we see this again/ can replicate.
