### ISSUE TITLE
Disable project data extraction queue if there's no attached DataSet

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6188]
I just set up a new Project without yet adding a `DataSet`, but we still get the queue for doing this work.

![Screenshot 2021-04-07 at 10 06 02](https://user-images.githubusercontent.com/282788/113840763-ef3c8780-9788-11eb-8bbb-b0b046f6edaf.png)

```
[ERROR] extracts#show (ActionView::Template::Error) "'nil' is not an ActiveModel-compatible object.

An ActionView::Template::Error occurred in extracts#show:

'nil' is not an ActiveModel-compatible object. It must implement :to_partial_path.
app/views/projects/extracts/_form.html.erb:4:in `block in _app_views_projects_extracts__form_html_erb___1503711185813211192_69814260902500'

-------------------------------
Backtrace:
-------------------------------

app/views/projects/extracts/_form.html.erb:4:in `block in _app_views_projects_extracts__form_html_erb___1503711185813211192_69814260902500'
app/views/projects/extracts/_form.html.erb:2:in `_app_views_projects_extracts__form_html_erb___1503711185813211192_69814260902500'
app/views/projects/extracts/_sidebar.html.erb:5:in `_app_views_projects_extracts__sidebar_html_erb__782598002594671565_69814260862340'
app/views/projects/extracts/show.html.erb:32:in `_app_views_projects_extracts_show_html_erb___1087984926757545637_69814262012600'
app/controllers/application_controller.rb:116:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Projects are useful even just for classification.

Think we want to add something like the following:

```rb
class Project
  def extractable?
    key_set.present?
  end
end
```

Could disable the button…

```erb
<%= link_to project_extract_path(@project), class: 'button', disabled: !@project.extractable?  do %>
  <%= _('Start extracting') %>
<% end %>
```

…or hide the entire section:

```erb
<% if @project.extractable?  %>
  <%= render partial: 'extract' %>
<% end %>
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
