### ISSUE TITLE
[ERROR] script/update-public-body-stats (ActiveRecord::RecordInvalid)

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6197]
```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Url name URL name is already taken, Name Name is already taken
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/validations.rb:80:in `raise_validation_error'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/validations.rb:52:in `save!'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:315:in `block in save!'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:315:in `save!'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/suppressor.rb:48:in `save!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2021-03-15T12-27-55/lib/tasks/stats.rake:254:in `block (4 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/bundler/gems/acts_as_versioned-63b1fc8529d0/lib/acts_as_versioned.rb:466:in `without_revision'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/bundler/gems/acts_as_versioned-63b1fc8529d0/lib/acts_as_versioned.rb:373:in `without_revision'
/data/vhost/www.whatdotheyknow.com/alaveteli-2021-03-15T12-27-55/lib/tasks/stats.rake:253:in `block (3 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:70:in `each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:70:in `block in find_each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:222:in `loop'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:222:in `in_batches'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/batches.rb:69:in `find_each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/querying.rb:11:in `find_each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2021-03-15T12-27-55/lib/tasks/stats.rake:230:in `block (2 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/opt/rbenv/versions/2.6.6/bin/bundle:23:in `load'
/opt/rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => stats:update_public_bodies_stats
(See full trace by running task with --trace)
```

**Comment by garethrees** [comment]
Had another one of these – something seems broken here.

**Comment by garethrees** [comment]
Looks like two copies of the same body got created:

![Screenshot 2021-04-13 at 09 48 53](https://user-images.githubusercontent.com/282788/114525430-00c8d800-9c3e-11eb-8962-1c1f3a6b641d.png)

![Screenshot 2021-04-13 at 09 49 02](https://user-images.githubusercontent.com/282788/114525390-fad2f700-9c3d-11eb-82fd-f41358709e3d.png)

I don't know how this happened. It looks like they've been suggested through our update bodies form, and then they've been added via clicking the link in our email notification or via the admin UI.

I'm not sure how the second version would have been allowed to have got saved. Maybe clicking the link twice in quick succession and missing the validation?

I've now deleted the second copy of the authority.
