### ISSUE TITLE
[ERROR] help#unhappy (ActionView::Template::Error) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6246]
```
An ActionView::Template::Error occurred in help#unhappy:

undefined method `[]' for nil:NilClass
app/models/refusal_advice.rb:23:in `questions'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/help/unhappy/asbestos_question_3
* HTTP Method: GET
* Parameters : {"controller"=>"help", "action"=>"unhappy", "url_title"=>"asbestos_question_3"}
* Timestamp : 2021-05-14 11:04:55 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-05-07T10-14-32

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>181819,
"ttl"=>"2021-05-14T11:04:55.444+01:00",
"remember_me"=>false,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED",
"flash"=>
{"discard"=>[],
"flashes"=>
{"notice"=>
{"partial"=>"request/describe_notices/waiting_response_very_overdue",
"locals"=>{"info_request_id"=>706831, "annotations_enabled"=>true}}}}}

-------------------------------
Backtrace:
-------------------------------

app/models/refusal_advice.rb:23:in `questions'
app/views/help/_refusal_advice.html.erb:4:in `block in _app_views_help__refusal_advice_html_erb__782931655989036458_69977395820940'
app/views/help/_refusal_advice.html.erb:2:in `_app_views_help__refusal_advice_html_erb__782931655989036458_69977395820940'
lib/themes/whatdotheyknow-theme/lib/views/help/unhappy.html.erb:3:in `_lib_themes_whatdotheyknow_theme_lib_views_help_unhappy_html_erb___1122025999156432795_69977269275080'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'

**Comment by garethrees** [comment]
Might be similar to https://github.com/mysociety/alaveteli/pull/6209.

**Comment by garethrees** [comment]
Both requests are EIR:

```ruby
InfoRequest.find_by(url_title: 'asbestos_question_3').law_used
# => "eir"
InfoRequest.find_by(url_title: 'details_of_roadside_works_betwee').law_used
# => "eir"
```

`RefusalAdvice#questions` expects there to be questions for a `Legislation`.

https://github.com/mysociety/alaveteli/blob/bc3e40cacffb504584be2db59b0e5d2c210730df/app/models/refusal_advice.rb#L22-L25
