### ISSUE TITLE
[ERROR] user#signup (Recaptcha::RecaptchaError) "809: unexpected token at…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6296]
```
A Recaptcha::RecaptchaError occurred in user#signup:

809: unexpected token at '<html><head></head><body><pre>An error occurred:
An internal error occurred: 5C4565A9A6C27.A1C3CD7.810F98CD
</pre></body></html>'
app/controllers/user_controller.rb:129:in `signup'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/sign_up
* HTTP Method: POST
* IP address : REDACTED
* Parameters : {"query"=>"WExJpGgljOcC", "utf8"=>"✓", "authenticity_token"=>"", "user_signup"=>{"name"=>"LwbugNtdDxvj", "email"=>"REDACTED", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "token"=>"REDACTED", "modal"=>"", "commit"=>"Sign in", "user_signin"=>{"email"=>"REDACTED", "password"=>"[FILTERED]"}, "remember_me"=>"1", "g-recaptcha-response"=>"FEKzaeZPyhNW", "controller"=>"user", "action"=>"signup"}
* Timestamp : 2021-06-09 15:47:29 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-05-28T09-12-01

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"flash"=>
{"discard"=>[],
"flashes"=>
{"recaptcha_error"=>"reCAPTCHA verification failed, please try again."}}}

-------------------------------
Backtrace:
-------------------------------

app/controllers/user_controller.rb:129:in `signup'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Looks like a somewhat legit signup, but where they've just added junk to the `name` field. `authenticity_token` is blank though, so could be some sort of spam.

Similar to https://github.com/mysociety/alaveteli/pull/6277, should probably rescue `Recaptcha::RecaptchaError` and re-render the form and the provided error.

The recaptcha library has added `recaptcha_error` to the flashes, but we ought to provide a translated version:

```ruby
# …
rescue Recaptcha::RecaptchaError
  flash[:error] = _('reCAPTCHA verification failed, please try again.')
  render action: :sign
end
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
