### ISSUE TITLE
[ERROR] statistics#index (NoMethodError) "undefined method `to_date' for nil:NilClass

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6301]
```
A NoMethodError occurred in statistics#index:

undefined method `to_date' for nil:NilClass
Did you mean? to_d
app/models/statistics.rb:129:in `by_week_to_today_with_noughts'

-------------------------------
Request:
-------------------------------

* URL : https://www.arthro5a.gr/statistics
* HTTP Method: GET
* Parameters : {"controller"=>"statistics", "action"=>"index"}
* Timestamp : 2021-06-10 13:31:43 +0300

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"el",
"_csrf_token"=>"REDACTED",
"remember_me"=>false,
"request_game"=>"2021-06-10T13:18:47.923+03:00"}

-------------------------------
Backtrace:
-------------------------------

app/models/statistics.rb:129:in `by_week_to_today_with_noughts'
app/controllers/statistics_controller.rb:9:in `index'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
