### ISSUE TITLE
[ERROR] statistics#index (NoMethodError) "undefined method `to_date' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6302]
```
A NoMethodError occurred in statistics#index:

undefined method `to_date' for nil:NilClass
Did you mean? to_d
app/models/statistics.rb:129:in `by_week_to_today_with_noughts'

-------------------------------
Request:
-------------------------------

* URL : https://www.arthro5a.gr/statistics
* HTTP Method: GET
* Parameters : {"controller"=>"statistics", "action"=>"index"}
* Timestamp : 2021-06-10 13:31:43 +0300

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"el",
"_csrf_token"=>"REDACTED",
"remember_me"=>false,
"request_game"=>"2021-06-10T13:18:47.923+03:00"}

-------------------------------
Backtrace:
-------------------------------

app/models/statistics.rb:129:in `by_week_to_today_with_noughts'
app/controllers/statistics_controller.rb:9:in `index'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
We pass two values to [`Statistics.by_week_to_today_with_noughts`](https://github.com/mysociety/alaveteli/blob/0.38.4.2/app/models/statistics.rb#L128) to calculate the stats:

https://github.com/mysociety/alaveteli/blob/0.38.4.2/app/controllers/statistics_controller.rb#L9-L12

Currently, on Greece, we're passing these values:

```ruby
InfoRequestEvent.count_of_hides_by_week
# => [[Mon, 12 Apr 2021, 1]]

InfoRequest.is_public.order(:created_at).first&.created_at
# => nil

# created_at is nil because there are no public requests
InfoRequest.is_public.count
# => 0
```

I expect what has happened is that a test request has been created and then hidden, so we end up with a hide event but no public request to get the date. Public requests have since been created, so this issue only really affects new installs.

Presumably we use the first _visible_ request (added in https://github.com/mysociety/alaveteli/commit/79c4c4febcfa657d01ce9bdda217bbd462e4d112) so that all the test requests don't appear in the stats. I think the easy thing to do here is just return `[Date.current.to_s, 0]` if either `counts_by_week` or `start_date` are `nil`.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
