### ISSUE TITLE
[ERROR] refusal_advice#create (ActionController::ParameterMissing) "param is missing or the value is empty: refusal_advice"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6358]
```
An ActionController::ParameterMissing occurred in refusal_advice#create:

param is missing or the value is empty: refusal_advice
app/controllers/refusal_advice_controller.rb:86:in `refusal_advice_params'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/refusal_advice
* HTTP Method: POST
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "controller"=>"refusal_advice", "action"=>"create"}
* Timestamp : 2021-07-05 12:38:22 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-06-25T08-53-16

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/refusal_advice_controller.rb:86:in `refusal_advice_params'
app/controllers/refusal_advice_controller.rb:68:in `action'
app/controllers/refusal_advice_controller.rb:57:in `help_page_redirect'
app/controllers/refusal_advice_controller.rb:12:in `create'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
