### ISSUE TITLE
[ERROR] sessions#create (NoMethodError) "undefined method `+' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6359]
Looks like it was a [spam user](https://www.whatdotheyknow.com/user/ydmuphyronal) so I've banned them.

Definitely some weird edge case in unexpected params (e.g: `"authenticity_to <p>"=>""`) but probably shouldn't error out like this.

```
A NoMethodError occurred in sessions#create:

undefined method `+' for nil:NilClass
app/models/user/authentication.rb:39:in `sha1_password'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/sign_in
* HTTP Method: POST
* Parameters : {"utf8"=>"&#x2713;", "authenticity_to <p>"=>"", "user_signin"=>{"email"=>"REDACTED"}, "user_signin="=>"Ec900b83-", "commit"=>"Sign in", "controller"=>"users/sessions", "action"=>"create"}
* Timestamp : 2021-07-07 06:40:11 +0100

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"991e362557220cc0a7ed9673b97d7ef3", "locale"=>"en"}
-------------------------------
Backtrace:
-------------------------------

app/models/user/authentication.rb:39:in `sha1_password'
app/models/user/authentication.rb:61:in `has_this_password?'
app/models/user.rb:185:in `authenticate_from_form'
app/controllers/users/sessions_controller.rb:30:in `create'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
