### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "main body text more than 1 MB, need to implement clipping…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6379]
```
An ActionView::Template::Error occurred in request#show:

main body text more than 1 MB, need to implement clipping like for attachment text, or there is some other MIME decoding problem or similar
app/models/incoming_message.rb:411:in `_cache_main_body_text'


-------------------------------
Request:
-------------------------------

* URL : https://www.infoprovsechny.cz/request/zadost_o_informace_podle_zakona_29
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"zadost_o_informace_podle_zakona_29"}
* Timestamp : 2021-07-18 21:04:13 +0200
* Rails root : /data/vhost/czechia.alaveteli.org/alaveteli-2021-01-14T15-37-30

-------------------------------
Backtrace:
-------------------------------

app/models/incoming_message.rb:411:in `_cache_main_body_text'
app/models/incoming_message.rb:437:in `get_main_body_text_unfolded'
app/models/incoming_message.rb:606:in `get_body_for_html_display'
app/views/request/_incoming_correspondence.html.erb:23:in `_app_views_request__incoming_correspondence_html_erb___662750097204180468_47380644459360'
app/views/request/events/_response.html.erb:1:in `_app_views_request_events__response_html_erb__284836603346081549_47380644441100'
app/views/request/_correspondence.html.erb:5:in `_app_views_request__correspondence_html_erb___3050035676617109945_47380643999360'
app/views/request/show.html.erb:40:in `block in _app_views_request_show_html_erb__1861869834109364547_47380643045420'
app/views/request/show.html.erb:38:in `_app_views_request_show_html_erb__1861869834109364547_47380643045420'
app/controllers/request_controller.rb:125:in `block (3 levels) in show'
app/controllers/request_controller.rb:124:in `block in show'
lib/alaveteli_localization.rb:49:in `with_locale'
app/controllers/request_controller.rb:75:in `show'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Basically the same as https://github.com/mysociety/alaveteli/issues/4412 / https://github.com/mysociety/alaveteli/issues/3667  – cron errors from IPZ getting really annoying.

**Comment by garethrees** [comment]
Seeing these on a Belgian request.

**Comment by garethrees** [comment]
I was taking a look at this on incoming message `1633536`.

Initially it had a single `text/plain` attachment. It looked like we were identifying the main body part correctly, so I tried this:

```ruby
msg.foi_attachments.destroy_all
msg.extract_attachments!
```

The message is now parsed correctly and the [request page](https://www.whatdotheyknow.com/request/information_re_roadworks) loads.

I suspect a mail gem upgrade fixed some issue.

We should improve `IncomingMessage#parse_raw_email!` and `IncomingMessage#extract_attachments`. There's no option to destroy the `foi_attachment` records before reparsing, so I think this message couldn't get parsed because the extracted parts from mail weren't mapping to the incorrectly created `FoiAttachment` from a previous attempt. There might be some gotchas with this – mainly thinking a possible URL change – but that shouldn't matter when we haven't parsed the thing properly in the first place.

**Comment by garethrees** [comment]
Taking another similar case

```ruby
r = InfoRequest.find_by url_title: 'childrens_social_work_team_struc'

# Probably the last message that's causing the problem…
r.incoming_messages.size
# => 2
m = r.incoming_messages.last
m.id
# => 1686508
```

Single attachment:

<img width="998" alt="Screenshot 2021-11-26 at 09 51 00" src="https://user-images.githubusercontent.com/282788/143561681-1b36869d-f45a-4c65-b4a8-dbe9a6bc9e31.png">

```ruby
mail = m.raw_email.mail

# See what attrs we get – prevent output because its generally huge
attrs = MailHandler.get_attachment_attributes(mail) ; nil


# Looks like we have a main body then 2 PDF attachments – correct
attrs.map { |a| a[:filename] }
# => [nil, "Children's Services 20201127.pdf", "7507 - additional structure charts.pdf", "FOI-7507-2020.pdf"]

# But this time we've identified the body correctly as text/html
attrs.map { |a| a[:content_type] }
# => ["text/html", "application/pdf", "application/pdf", "application/pdf"]

# That looks better…
attrs.first[:body]
# => "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<style type=\"text/css\">html a:hover{text-decoration: underline;}</style>\r\n</head>\r\n<body style='font-family: Muli, \"Helvetica Neue\", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.4; color: #333333; overflow-wrap: break-word; word-wrap: break-word; -ms-word-break: break-all; word-break: break-word;'>\r\n<span style=\"font-family: Arial,Helvetica,sans-serif;\"><span style=\"font-size: 16px;\">Dear REDACTED <br><br><span style=\"font-size: 16px;\"><span style=\"font-family: Arial,Helvetica,sans-serif;\"><strong>Freedom of Information Act 2000, Reference: FOI-7507-2020</strong><br><br>Please see attached for a response to your request for information.</span></span><br><br>Many thanks <br><br>Information Governance Team<br>Corporate, Customer &amp; Community | Cumbria County Council<br>Service Centre | Parkhouse Building | Kingmoor Business Park | Carlisle | CA6 4SJ</span><br><span style=\"font-size: 16px;\"> <br>t: REDACTED <br><a class=\"\" href=\"https://cumbria.gov.uk\" style=\"color: #0088cc; font-weight: initial; text-decoration: none; white-space: nowrap; cursor: pointer;\">https://cumbria.gov.uk</a></span></span><br> </body>\r\n</html>\r\n\r\n"


m.foi_attachments.destroy_all
# => [#<FoiAttachment id: 3013781, content_type: "text/plain", filename: "attachment.txt", charset: nil, display_size: "1.6M", url_part_number: 1, within_rfc822_subject: nil, incoming_message_id: 1686508, hexdigest: "8719ad0b53f0d74da2b922baa7395d97", created_at: "2020-12-04 06:50:59", updated_at: "2020-12-04 06:50:59">]

m.extract_attachments!
# => []
```

<img width="1004" alt="Screenshot 2021-11-26 at 09 57 08" src="https://user-images.githubusercontent.com/282788/143562447-993bb26e-8451-4ccf-bdd6-64ef663691a0.png">

And now we have the correct attachments and a [working request](https://www.whatdotheyknow.com/request/childrens_social_work_team_struc#incoming-1686508).

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
