### ISSUE TITLE
[ERROR] request#download_entire_request (ActionView::Template::Error) "missing interpolation argument…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6380]
```
An ActionView::Template::Error occurred in request#download_entire_request:

missing interpolation argument "user_name" in {:username=>"Amanda-Jane"} ("Gadawodd {{user_name}} anodiad:" given)
lib/i18n_fixes.rb:35:in `block in gettext_interpolate'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/cy/request/do_we_have_a_bond_created_on_our/download
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"download_entire_request", "url_title"=>"do_we_have_a_bond_created_on_our", "locale"=>"cy"}
* Timestamp : 2021-07-16 16:07:45 +0100
* Server : owl
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-07-13T10-07-01

-------------------------------
Backtrace:
-------------------------------

lib/i18n_fixes.rb:35:in `block in gettext_interpolate'
lib/i18n_fixes.rb:31:in `gsub'
lib/i18n_fixes.rb:31:in `gettext_interpolate'
lib/i18n_fixes.rb:11:in `_'
app/views/comment/_single_comment.text.erb:1:in `_app_views_comment__single_comment_text_erb__222904051947525249_69829099122540'
app/views/request/show.text.erb:17:in `block in _app_views_request_show_text_erb___2075892599513164192_69829095735840'
app/views/request/show.text.erb:7:in `_app_views_request_show_text_erb___2075892599513164192_69829095735840'
app/controllers/request_controller.rb:697:in `make_request_summary_file'
app/controllers/request_controller.rb:653:in `block in make_request_zip'
app/controllers/request_controller.rb:652:in `make_request_zip'
app/controllers/request_controller.rb:551:in `block in download_entire_request'
lib/alaveteli_localization.rb:49:in `with_locale'
app/controllers/request_controller.rb:530:in `download_entire_request'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Broken Welsh translation by the looks of it.

**Comment by gbp** [comment]
Fixed in https://github.com/mysociety/alaveteli/commit/de822cd68b4315d6b3e67aa948ecfcf6afec3d7b
