### ISSUE TITLE
[ERROR] subscriptions#index (Stripe::RateLimitError) "This object cannot be accessed right now…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6405]
```
A Stripe::RateLimitError occurred in subscriptions#index:

This object cannot be accessed right now because another API request or Stripe process is currently accessing it. If you see this error intermittently, retry the request. If you see this error frequently and are making multiple concurrent requests to a single object, make your requests serially or at a lower rate.
app/models/pro_account.rb:67:in `stripe_customer!'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/profile/subscriptions
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/subscriptions", "action"=>"index"}
* Timestamp : 2021-07-21 13:02:08 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-07-13T10-07-01

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>233522,
"ttl"=>"2021-07-21T13:02:04.088+01:00",
"remember_me"=>false,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED",
"flash"=>
{"discard"=>[],
"flashes"=>{"notice"=>"Your payment details have been updated"}}}

-------------------------------
Backtrace:
-------------------------------

app/models/pro_account.rb:67:in `stripe_customer!'
app/models/pro_account.rb:36:in `stripe_customer'
app/models/pro_account.rb:31:in `subscriptions'
app/models/pro_account.rb:26:in `subscription?'
app/controllers/alaveteli_pro/subscriptions_controller.rb:194:in `check_has_current_subscription'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Had another of these today

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
