### ISSUE TITLE
[ERROR] pages#show (ActionView::Template::Error) "missing interpolation argument…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6406]
```
An ActionView::Template::Error occurred in pages#show:

missing interpolation argument "Authority_count" in {:authority_count=>2887} ("Vous aurez accès à notre carnet d'adresses des {{Authority_count}} autorités soumises à la liberté d'accès à l'information." given)
lib/i18n_fixes.rb:34:in `block in gettext_interpolate'


-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/pro/pages/journalists
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/pages", "action"=>"show", "id"=>"journalists"}
* Timestamp : 2021-07-23 05:11:37 +0200
* Rails root : /data/vhost/belgium.alaveteli.org/alaveteli-2021-07-22T08-47-09

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"fr_BE"}

-------------------------------
Backtrace:
-------------------------------

lib/i18n_fixes.rb:34:in `block in gettext_interpolate'
lib/i18n_fixes.rb:30:in `gsub'
lib/i18n_fixes.rb:30:in `gettext_interpolate'
lib/i18n_fixes.rb:10:in `_'
app/views/alaveteli_pro/pages/marketing_roles/generic/features/_database.html.erb:10:in `_app_views_alaveteli_pro_pages_marketing_roles_generic_features__database_html_erb___3854534015775395020_128560'
app/views/alaveteli_pro/pages/marketing_roles/journalists/_marketing_features.html.erb:4:in `_app_views_alaveteli_pro_pages_marketing_roles_journalists__marketing_features_html_erb__4021460635898583990_128520'
app/views/alaveteli_pro/pages/journalists.html.erb:3:in `_app_views_alaveteli_pro_pages_journalists_html_erb__3962593240864047312_128480'
app/controllers/alaveteli_pro/pages_controller.rb:13:in `show'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Fixed in https://github.com/mysociety/alaveteli/commit/de822cd68b4315d6b3e67aa948ecfcf6afec3d7b
