### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "can't modify frozen String…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6407]
```
An ActionView::Template::Error occurred in request#show:

can't modify frozen String: ""
lib/normalize_string.rb:37:in `force_encoding'


-------------------------------
Request:
-------------------------------

* URL : https://www.infoprovsechny.cz/request/dotace_firmam_skupiny_agrofert_h
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"dotace_firmam_skupiny_agrofert_h"}
* Timestamp : 2021-07-24 21:38:10 +0200
* Rails root : /data/vhost/czechia.alaveteli.org/alaveteli-2021-07-22T08-56-56

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"cs"}

-------------------------------
Backtrace:
-------------------------------

lib/normalize_string.rb:37:in `force_encoding'
lib/normalize_string.rb:37:in `block in normalize_string_to_utf8'
lib/normalize_string.rb:30:in `each'
lib/normalize_string.rb:30:in `normalize_string_to_utf8'
lib/normalize_string.rb:77:in `convert_string_to_utf8_or_binary'
lib/mail_handler/backends/mail_backend.rb:95:in `get_part_body'
lib/mail_handler/backends/mail_backend.rb:376:in `block in get_attachment_attributes'
lib/mail_handler/backends/mail_backend.rb:375:in `map'
lib/mail_handler/backends/mail_backend.rb:375:in `get_attachment_attributes'
app/models/incoming_message.rb:562:in `extract_attachments!'
app/models/incoming_message.rb:99:in `block in parse_raw_email!'
app/models/incoming_message.rb:98:in `parse_raw_email!'
app/models/incoming_message.rb:179:in `mail_from'
app/models/incoming_message.rb:198:in `safe_mail_from'
app/models/incoming_message.rb:221:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_request__incoming_correspondence_html_erb__755026761101139310_69280'
app/views/request/events/_response.html.erb:1:in `_app_views_request_events__response_html_erb__3105272045367006103_69260'
app/views/request/_correspondence.html.erb:5:in `_app_views_request__correspondence_html_erb__3424039284734449526_68980'
app/views/request/show.html.erb:40:in `block in _app_views_request_show_html_erb___390786003448312491_68740'
app/views/request/show.html.erb:38:in `_app_views_request_show_html_erb___390786003448312491_68740'
app/controllers/request_controller.rb:123:in `block (3 levels) in show'
app/controllers/request_controller.rb:122:in `block in show'
lib/alaveteli_localization.rb:48:in `with_locale'
app/controllers/request_controller.rb:76:in `show'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
This seems to be a edge case where the email has to be 8bit content transfer encoding and have an empty body. EG:

```eml
Subject: Foo
Content-Transfer-Encoding: 8bit

```

```ruby
Mail.new(data).body.decoded.frozen?
=> true
```

But using 7bit, the body isn't frozen 

```eml
Subject: Foo
Content-Transfer-Encoding: 7bit

```

```ruby
Mail.new(data).body.decoded.frozen?
=> false
```

And 8bit with a content, the body isn't frozen either.

```eml
Subject: Foo
Content-Transfer-Encoding: 8bit

Hello world

```

```ruby
Mail.new(data).body.decoded.frozen?
=> false
```

**Comment by gbp** [comment]
In this case the content type needs to also be `text/*` so we attempt the normalise the string into UTF-8
