### ISSUE TITLE
[ERROR] sessions#new (ActionView::MissingTemplate) "Missing template user/sign…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6408]
```
An ActionView::MissingTemplate occurred in sessions#new:

Missing template user/sign with {:locale=>[:"en-UG", :en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
* "/data/vhost/uganda.alaveteli.org/alaveteli-2021-07-22T10-22-20/lib/themes/askyourgovug-theme/lib/views"
* "/data/vhost/uganda.alaveteli.org/alaveteli-2021-07-22T10-22-20/app/views"

app/controllers/users/sessions_controller.rb:23:in `new'

-------------------------------
Request:
-------------------------------

* URL : https://askyourgov.ug/profile/sign_in?token=REDACTED
* HTTP Method: GET
* Parameters : {"token"=>"REDACTED", "controller"=>"users/sessions", "action"=>"new"}
* Timestamp : 2021-07-28 09:08:34 +0300
* Rails root : /data/vhost/uganda.alaveteli.org/alaveteli-2021-07-22T10-22-20

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED", "locale"=>"en_UG"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/users/sessions_controller.rb:23:in `new'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
This is a request for /profile/sign_in.json 

Also seeing exceptions for this on WDTK.

**Comment by gbp** [comment]
Related issue https://github.com/mysociety/alaveteli/issues/4228
