### ISSUE TITLE
Xapian ENV error on Vagrant provisioning

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6420]
I am seeing:

```
    bionic: rake aborted!
    bionic: NoMethodError: undefined method `[]' for nil:NilClass
    bionic: /home/vagrant/alaveteli/lib/acts_as_xapian/acts_as_xapian.rb:121:in `prepare_environment'
    bionic: /home/vagrant/alaveteli/lib/acts_as_xapian/acts_as_xapian.rb:800:in `destroy_and_rebuild_index'
    bionic: /home/vagrant/alaveteli/lib/acts_as_xapian/tasks/xapian.rake:43:in `block (2 levels) in <top (required)>'
    bionic: /home/vagrant/bundle/ruby/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
    bionic: /home/vagrant/.rbenv/versions/2.5.8/bin/bundle:23:in `load'
    bionic: /home/vagrant/.rbenv/versions/2.5.8/bin/bundle:23:in `<main>'
    bionic: Tasks: TOP => xapian:destroy_and_rebuild_index
    bionic: (See full trace by running task with --trace)
```

Since #6401 we create a `config/xapian.yml` file with test env config. This now means, when in a non-test env, we can't prepare the Xapian environment.

https://github.com/mysociety/alaveteli/blob/4404241d298f3f16ac096ad8f203db068cf5dd55/lib/acts_as_xapian/acts_as_xapian.rb#L118 Evals to `nil` - the Xapian config file exists but there is no non-test env in the config file.

**Comment by garethrees** [comment]
Ugh, sorry. Probably removed the xapian config before running any development tasks.

Guess we want something like

```diff
- @@config = File.exist?(config_file) ? YAML.load_file(config_file)[environment] : {} 
+ @@config = File.exist?(config_file) ? YAML.load_file(config_file)&.fetch(environment) : {} 
```
