### ISSUE TITLE
Transient spec failure in views/notification_mailer/info_request_batches/_info_request_batch.text.erb

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6427]
https://github.com/mysociety/alaveteli/pull/6425/checks?check_run_id=3239459192

```
# snip...

InfoRequestBatchController ...............
notification_mailer/info_request_batches/_info_request_batch.text.erb F..

  1) notification_mailer/info_request_batches/_info_request_batch.text.erb renders the authority list partial
     Failure/Error:
       expect(response).
         to render_template(partial: expected_partial, locals: expected_locals)

       expecting alaveteli_pro/info_request_batches/authority_list to be rendered with {:public_bodies=>[#<PublicBody id: 382, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2021-08-04 08:41:40", updated_at: "2021-08-04 08:41:40", home_page: nil, api_key: "AxNcWMe7A7z6YKyMUg8o+UbYs9pGZd073AxA1ltPMybz", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: nil, info_requests_not_held_count: nil, info_requests_overdue_count: nil, info_requests_visible_classified_count: nil, info_requests_visible_count: 0, name: "Example Public Body 999", short_name: "Example Body 1022", request_email: "request@example.com", url_name: "example_body_1022", notes: nil, first_letter: "E", publication_scheme: nil>, #<PublicBody id: 383, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2021-08-04 08:41:40", updated_at: "2021-08-04 08:41:40", home_page: nil, api_key: "K/GwfsFHf4lXnfxWx8PGdS5iJ7q+7NTTjQnhEEcS56Lq", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: nil, info_requests_not_held_count: nil, info_requests_overdue_count: nil, info_requests_visible_classified_count: nil, info_requests_visible_count: 0, name: "Example Public Body 1000", short_name: "Example Body 1023", request_email: "request@example.com", url_name: "example_body_1023", notes: nil, first_letter: "E", publication_scheme: nil>]} but was with [{:public_bodies=>#<ActiveRecord::Associations::CollectionProxy [#<PublicBody id: 383, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2021-08-04 08:41:40", updated_at: "2021-08-04 08:41:40", home_page: nil, api_key: "K/GwfsFHf4lXnfxWx8PGdS5iJ7q+7NTTjQnhEEcS56Lq", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: nil, info_requests_visible_classified_count: 1, info_requests_visible_count: 1, name: "Example Public Body 1000", short_name: "Example Body 1023", request_email: "request@example.com", url_name: "example_body_1023", notes: nil, first_letter: "E", publication_scheme: nil>, #<PublicBody id: 382, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2021-08-04 08:41:40", updated_at: "2021-08-04 08:41:40", home_page: nil, api_key: "AxNcWMe7A7z6YKyMUg8o+UbYs9pGZd073AxA1ltPMybz", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: nil, info_requests_visible_classified_count: 1, info_requests_visible_count: 1, name: "Example Public Body 999", short_name: "Example Body 1022", request_email: "request@example.com", url_name: "example_body_1022", notes: nil, first_letter: "E", publication_scheme: nil>]>}]
     # ./spec/views/notification_mailer/info_request_batches/_info_request_batch.text.erb_spec.rb:50:in `block (2 levels) in <top (required)>'

# snip...

Finished in 20 minutes 38 seconds (files took 10.28 seconds to load)
7039 examples, 1 failure, 5 pending

Failed examples:

rspec ./spec/views/notification_mailer/info_request_batches/_info_request_batch.text.erb_spec.rb:47 # notification_mailer/info_request_batches/_info_request_batch.text.erb renders the authority list partial

Randomized with seed 40402

```

[Re-ran](https://github.com/mysociety/alaveteli/pull/6425/checks?check_run_id=3239907284) the jobs and the run passed.

**Comment by gbp** [comment]
Can't replicate locally when using the same seed

**Comment by gbp** [comment]
Looks like this might be the same issue

```
$ rspec --seed 61613 --fail-fast

Randomized with seed 61613
........................F

Failures:

  1) notification_mailer/info_request_batches/_info_request_batch renders the authority list partial
     Failure/Error:
       expect(response).
         to render_template(partial: expected_partial, locals: expected_locals)

       expecting alaveteli_pro/info_request_batches/authority_list to be rendered with {:public_bodies=>[#<PublicBody id: 16, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2023-02-16 16:38:56.555442000 +0000", updated_at: "2023-02-16 16:38:56.555442000 +0000", home_page: nil, api_key: "51Tw8NmxX9wBYxg/WN1Qwehl66NW1u35HlEpZjemp69E", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: nil, info_requests_not_held_count: nil, info_requests_overdue_count: nil, info_requests_visible_classified_count: nil, info_requests_visible_count: 0, name: "Example Public Body 9", short_name: "Example Body 9", request_email: "request@example.com", url_name: "example_body_9", first_letter: "E", publication_scheme: nil>, #<PublicBody id: 17, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2023-02-16 16:38:56.558776000 +0000", updated_at: "2023-02-16 16:38:56.558776000 +0000", home_page: nil, api_key: "FppMeIuWu9U/bjMWcBlraa9OnAGrCvoo0V6A+SlA61U2", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: nil, info_requests_not_held_count: nil, info_requests_overdue_count: nil, info_requests_visible_classified_count: nil, info_requests_visible_count: 0, name: "Example Public Body 10", short_name: "Example Body 10", request_email: "request@example.com", url_name: "example_body_10", first_letter: "E", publication_scheme: nil>]} but was with [{:public_bodies=>#<ActiveRecord::Associations::CollectionProxy [#<PublicBody id: 17, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2023-02-16 16:38:56.558776000 +0000", updated_at: "2023-02-16 16:38:56.558776000 +0000", home_page: nil, api_key: "FppMeIuWu9U/bjMWcBlraa9OnAGrCvoo0V6A+SlA61U2", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: nil, info_requests_visible_classified_count: 1, info_requests_visible_count: 1, name: "Example Public Body 10", short_name: "Example Body 10", request_email: "request@example.com", url_name: "example_body_10", first_letter: "E", publication_scheme: nil>, #<PublicBody id: 16, version: 1, last_edit_editor: "admin user", last_edit_comment: "Making an edit", created_at: "2023-02-16 16:38:56.555442000 +0000", updated_at: "2023-02-16 16:38:56.555442000 +0000", home_page: nil, api_key: "51Tw8NmxX9wBYxg/WN1Qwehl66NW1u35HlEpZjemp69E", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: nil, info_requests_visible_classified_count: 1, info_requests_visible_count: 1, name: "Example Public Body 9", short_name: "Example Body 9", request_email: "request@example.com", url_name: "example_body_9", first_letter: "E", publication_scheme: nil>]>}]
     # ./spec/views/notification_mailer/info_request_batches/_info_request_batch.text.erb_spec.rb:51:in `block (2 levels) in <top (required)>'
     # ./.direnv/gems/84sil4v5jqmf6vsm28mrdsxa658gcwvv-ruby-3.2.0-arm64/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 0.92279 seconds (files took 5.54 seconds to load)
25 examples, 1 failure

Failed examples:

rspec ./spec/views/notification_mailer/info_request_batches/_info_request_batch.text.erb_spec.rb:48 # notification_mailer/info_request_batches/_info_request_batch renders the authority list partial

Randomized with seed 61613
```

**Comment by gbp** [comment]
Same with seed 55931

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
