### ISSUE TITLE
[ERROR] request#show (ActionDispatch::Http::MimeNegotiation::InvalidType) "*" is not a valid MIME type

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6553]
```
An ActionDispatch::Http::MimeNegotiation::InvalidType occurred in request#show:

"*" is not a valid MIME type
lib/deeply_nested_params.rb:15:in `call'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/cy/request/merthy_road_whitchurch_cardiff
* HTTP Method: GET
* IP address : 20.49.247.14
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"merthy_road_whitchurch_cardiff", "locale"=>"cy"}
* Timestamp : 2021-10-04 11:18:07 +0100
* Server : owl
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-09-29T12-58-40
* Process: 5439

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {}

-------------------------------
Environment:
-------------------------------

* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip
* HTTP_ACCEPT_LANGUAGE : en-us, en; q=0.5

-------------------------------
Backtrace:
-------------------------------

lib/deeply_nested_params.rb:15:in `call'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by garethrees** [comment]
Getting loads of these on WDTK since #5159 was deployed.

**Comment by garethrees** [comment]
Looks like some info on this at https://gitlab.com/gitlab-org/gitlab/-/issues/200097

**Comment by gbp** [comment]
This was added between Rails 5.2 and 6.0: https://github.com/rails/rails/blob/1b5658b562b29f8aab7e80cbab8adbd2ddea5447/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L15

From https://github.com/rails/rails/pull/35604 and https://github.com/rails/rails/pull/40353

So current under Rails 6, in development a 406 HTTP status is returned:
```
> curl -I -H "Content-Type: *" http://localhost:3000
HTTP/1.1 406 Not Acceptable
...
```

In production, we also get a 406:
```
> curl -I -H "Content-Type: *" https://www.whatdotheyknow.com/cy/request/merthy_road_whitchurch_cardiff
HTTP/2 406
...
```

I think this is the correct behaviour and indeed in the PRs above the Rails core team suggest ignoring these exceptions. https://github.com/rails/rails/pull/35604#issuecomment-835274505

So I think the action needed is to update: https://github.com/mysociety/alaveteli/blob/develop/config/environments/production.rb#L129
