### ISSUE TITLE
[ERROR] statistics#index (NoMethodError) undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6566]
```
A NoMethodError occurred in statistics#index:

  undefined method `each' for nil:NilClass
  app/models/statistics.rb:112:in `user_json_for_api'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/statistics.json
  * HTTP Method: GET
  * Parameters : {"controller"=>"statistics", "action"=>"index", "format"=>"json"}
  * Timestamp  : 2021-10-11 11:58:58 +0100
  * Process: 10205

-------------------------------
Backtrace:
-------------------------------

  app/models/statistics.rb:112:in `user_json_for_api'
  app/controllers/statistics_controller.rb:21:in `block (2 levels) in index'
  app/controllers/statistics_controller.rb:16:in `index'
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'

```

**Comment by gbp** [comment]
Since #6523 ?
