### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "No such file or directory @ rb_sysopen"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6682]
```
An ActionView::Template::Error occurred in request#show:

No such file or directory @ rb_sysopen - /data/vhost/www.whatdotheyknow.com/raw_emails/807/807523/1918157
app/models/raw_email.rb:106:in `initialize'

-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/request/guards_on_your_london_overground
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"guards_on_your_london_overground"}
* Timestamp : 2021-11-22 09:12:52 +0000
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-11-16T15-30-27

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"remember_me"=>false,
"_csrf_token"=>"REDACTED",
"projects"=>
{"1"=>
{"extractable"=>{"current"=>nil, "skipped"=>[]},
"classifiable"=>{"current"=>"662875", "skipped"=>[]}},
"2"=>
{"classifiable"=>{"current"=>"493754", "skipped"=>[]},
"extractable"=>{"current"=>"494127", "skipped"=>["494141"]}},
"4"=>{"extractable"=>{"current"=>"607342", "skipped"=>[]}},
"3"=>{"extractable"=>{"current"=>"752014", "skipped"=>[]}}},
"request_game"=>"2021-11-12T09:53:04.108+00:00",
"announcement_dismissals"=>[15, 6, 22, 25]}


-------------------------------
Backtrace:
-------------------------------

app/models/raw_email.rb:106:in `initialize'
app/models/raw_email.rb:106:in `open'
app/models/raw_email.rb:106:in `data'
app/models/raw_email.rb:94:in `mail!'
app/models/incoming_message.rb:560:in `extract_attachments!'
app/models/incoming_message.rb:98:in `block in parse_raw_email!'
app/models/incoming_message.rb:97:in `parse_raw_email!'
app/models/incoming_message.rb:178:in `mail_from'
app/models/incoming_message.rb:197:in `safe_mail_from'
app/models/incoming_message.rb:220:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4
app/views/request/events/_response.html.erb:1
app/views/request/_correspondence.html.erb:5
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:45
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:43
app/controllers/request_controller.rb:129:in `block (3 levels) in show'
app/controllers/request_controller.rb:128:in `block in show'
lib/alaveteli_localization.rb:46:in `with_locale'
app/controllers/request_controller.rb:79:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/deeply_nested_params.rb:15:in `call'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by garethrees** [comment]
For some reason there's no `RawEmail` record associated with the `IncomingMessage`:

```
r = InfoRequest.where(url_title: 'guards_on_your_london_overground').first

r.incoming_messages.size
# => 1

m = r.incoming_messages.first
# => #<IncomingMessage id: 1918157, …>

m.parse_raw_email!(true)
Traceback (most recent call last):
        8: from (irb):5
        7: from app/models/incoming_message.rb:97:in `parse_raw_email!'
        6: from app/models/incoming_message.rb:98:in `block in parse_raw_email!'
        5: from app/models/incoming_message.rb:560:in `extract_attachments!'
        4: from app/models/raw_email.rb:94:in `mail!'
        3: from app/models/raw_email.rb:106:in `data'
        2: from app/models/raw_email.rb:106:in `open'
        1: from app/models/raw_email.rb:106:in `initialize'
Errno::ENOENT (No such file or directory @ rb_sysopen - /data/vhost/www.whatdotheyknow.com/raw_emails/807/807523/1918157)
```

**Comment by garethrees** [comment]
The `RawEmail` database record does exist, but the underlying file doesn't…

```
e = m.raw_email
# => #<RawEmail id: 1918005, created_at: "2021-11-19 09:49:45", updated_at: "2021-11-19 09:49:45">

irb(main):008:0> e.data
Traceback (most recent call last):
        4: from (irb):8
        3: from app/models/raw_email.rb:106:in `data'
        2: from app/models/raw_email.rb:106:in `open'
        1: from app/models/raw_email.rb:106:in `initialize'
Errno::ENOENT (No such file or directory @ rb_sysopen - /data/vhost/www.whatdotheyknow.com/raw_emails/807/807523/1918157)

```

**Comment by gbp** [comment]
Possible relevant lines in the app log:

```
W, [2021-11-19T09:49:45.854764 #16229]  WARN -- : Scoped order is ignored, it's forced to be batch order.
I, [2021-11-19T09:49:45.880607 #16229]  INFO -- :   Rendering request_mailer/new_response.text.erb within layouts/default_mailer
I, [2021-11-19T09:49:45.883745 #16229]  INFO -- :   Rendered request_mailer/new_response.text.erb within layouts/default_mailer (Duration: 3.0ms | Allocations: 775)
I, [2021-11-19T09:49:45.885506 #16229]  INFO -- :   Rendered lib/themes/whatdotheyknow-theme/lib/views/general/_default_footer.text.erb (Duration: 0.7ms | Allocations: 167)
I, [2021-11-19T09:49:45.923419 #16229]  INFO -- : Delivered mail 61977339d8b3e_3f65fc8922b5@owl.mail (37.0ms)
```

**Comment by garethrees** [comment]
Possibly related to https://github.com/mysociety/sysadmin/issues/1535. Need to figure out where that "Scoped order is ignored" is coming from.

**Comment by gbp** [comment]
I have restored this email from the mail spool backup

**Comment by gbp** [comment]
This seems to be related to an NFS issue we saw on the 19th. 

Remaining tasks:

- [ ] verify no other raw email is missing
- [ ] check where we write to emails to disk and see if there is a good place for better error logging

**Comment by gbp** [comment]
No other files are missing:

```
irb(main):008:0> RawEmail.where(created_at: Date.new(2021, 11, 19)..Date.new(2021, 11, 20)).to_a.reject { |re| File.exist?(re.filepath) }
=> []
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
