### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "PG::CharacterNotInRepertoire"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6867]
Similar to #5964

```
An ActionView::Template::Error occurred in request#show:

  PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0x97

  app/models/incoming_message.rb:519:in `get_main_body_text_part'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/cy/request/noel_park_pods_feasibility_study
  * HTTP Method: GET
  * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"noel_park_pods_feasibility_study", "locale"=>"cy"}


-------------------------------
Backtrace:
-------------------------------

  app/models/incoming_message.rb:519:in `get_main_body_text_part'
  app/models/incoming_message.rb:578:in `get_attachments_for_display'
  app/views/request/_incoming_correspondence.html.erb:30
  app/views/request/events/_response.html.erb:1
  app/views/request/_correspondence.html.erb:5
  lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:45
  lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:43
  app/controllers/request_controller.rb:129:in `block (3 levels) in show'
  app/controllers/request_controller.rb:128:in `block in show'
  lib/alaveteli_localization.rb:46:in `with_locale'
  app/controllers/request_controller.rb:79:in `show'
```

**Comment by gbp** [comment]
From the console this can be replicated by:

```
irb(main):014:0> FoiAttachment.where(incoming_message_id: 1698765).pluck(:filename)
Traceback (most recent call last):
        1: from (irb):14
ActiveRecord::StatementInvalid (PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0x97)
```

**Comment by gbp** [comment]
Also happens outside of Rails:

```
foi=> SELECT filename FROM foi_attachments WHERE incoming_message_id = 1698765;
ERROR:  invalid byte sequence for encoding "UTF8": 0x97
```

**Comment by gbp** [comment]
The raw email (ID `1698613`) contains the header:

```
Content-Disposition: attachment;
	filename="=?Windows-1252?Q?Freedom_of_Information_request_-_snip_=97_snip?=
```

Looks like it contains an Windows 1252 encoded em dash (`=97`) which appears to be saved into the database but can't be read out of the database as UTF-8.

This filename looks to been generate from the request title, the user including an em dash in the title of the request.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
