### ISSUE TITLE
[ERROR] admin_public_body#show (ActionView::Template::Error) "undefined method `prominence' for nil:NilClass"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#6875]
```
An ActionView::Template::Error occurred in admin_public_body#show:

  undefined method `prominence' for nil:NilClass
  app/helpers/admin_helper.rb:36:in `user_both_links'


-------------------------------
Request:
-------------------------------

  * URL        : https://staging.alaveteli.org/admin/bodies/2
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_public_body", "action"=>"show", "id"=>"2"}


-------------------------------
Backtrace:
-------------------------------

  app/helpers/admin_helper.rb:36:in `user_both_links'
  app/views/admin_request/_some_requests.html.erb:14
  app/views/admin_request/_some_requests.html.erb:2
  app/views/admin_public_body/show.html.erb:118
  app/controllers/admin_public_body_controller.rb:28:in `block in show'
  lib/alaveteli_localization.rb:46:in `with_locale'
  app/controllers/admin_public_body_controller.rb:19:in `show'
```

**Comment by gbp** [comment]
Seeing these since #6820

**Comment by gbp** [comment]
@garethrees I think you mentioned a new issues with external users in standup - was it this?

**Comment by garethrees** [comment]
Yeah, that looks about right. I assume body 2 has an external request (which has a `nil` user)?

**Comment by garethrees** [comment]
Closing this as we've now removed all external requests from WDTK and complete removal of the code is underway in #6893.
