### ISSUE TITLE
[ERROR] track#track_request (ActionController::RespondToMismatchError) "respond_to was called multiple times…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6978]
```
-------------------------------
Request:
-------------------------------

 * URL        : https://www.whatdotheyknow.com/feed/request/minimum_mileage_claim
 * HTTP Method: GET
 * Parameters : {"controller"=>"track", "action"=>"track_request", "feed"=>"feed", "url_title"=>"minimum_mileage_claim", "format"=>"xml"}
 * Timestamp  : 2022-04-08 21:40:26 +0100
 * Server : mstrwdtkhexa.srv.mysociety.org
   * Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2022-04-07T14-32-40
 * Process: 3079077

-------------------------------
Session:
-------------------------------

 * session id: [FILTERED]
 * data: {"session_id"=>"REDACTED", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

 app/controllers/application_controller.rb:197:in `render_exception'
 lib/deeply_nested_params.rb:15:in `call'
 lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
