### ISSUE TITLE
[ERROR] Uncaught TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7124]
```
application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:19685 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at updateCount (application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:19685:33)
    at HTMLDocument.<anonymous> (application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:19703:5)
    at fire (application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:3233:31)
    at Object.fireWith [as resolveWith] (application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:3363:7)
    at Function.ready (application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:3583:13)
    at HTMLDocument.completed (application-be40a21bfaaa92d20becb3d44369ac641f46aeb4268c6260e5f3d00326dd1820.js:3618:10)
```

<img width="460" alt="Screenshot 2022-06-24 at 16 36 16" src="https://user-images.githubusercontent.com/282788/175569200-589832e9-f4db-4f37-aa40-be8f0d4fad0f.png">

Breaks the logged in nav – can't expand it.

Looks like it was caused by something in https://github.com/mysociety/alaveteli/pull/7117.

**Comment by gbp** [comment]
The `messageTemplate*` variables here are `undefined` so we can't call `#replace`, this is caused when there is no `$count` element in the DOM.
