### ISSUE TITLE
missing tables

### ISSUE THREAD

**Issue by jpatters** [mysociety/alaveteli#7154]
Getting an error after installing via the [installation script](http://alaveteli.org/docs/installing/script/)
```
[d8853db9-58bf-4c9c-9399-2569b3cebf9f] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "flipper_features" does not exist
LINE 1: ...lipper_gates"."key", "flipper_gates"."value" FROM "flipper_f...
                                                             ^
):
[d8853db9-58bf-4c9c-9399-2569b3cebf9f]
[d8853db9-58bf-4c9c-9399-2569b3cebf9f] lib/deeply_nested_params.rb:15:in `call'
[d8853db9-58bf-4c9c-9399-2569b3cebf9f] lib/strip_empty_sessions.rb:14:in `call'
```

Found an [old issue](https://github.com/mysociety/alaveteli/issues/4280) saying this was fixed. I can see that the fix mentioned in the issue has been merged and is present in my fresh install however I am still experiencing the same issue.

Thanks in advance!

**Comment by jpatters** [comment]
It looks like this was due to migrations running against development during the install.

**Comment by jpatters** [comment]
I'm just getting into this project but it looks like it could be due to this: https://github.com/mysociety/alaveteli/blob/master/config/general.yml-example#L497:L497

`STAGING_SITE` is set to 1 and that file is just copied without being modified. 

I'm unsure of the relationship between `STAGING_SITE` and the `DEVELOPMENT_INSTALL` env var in the install script though. It looks like maybe they should be connected but are not.

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
