### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "undefined method `prominence' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7423]
```
An ActionView::Template::Error occurred in request#show:

 undefined method `prominence' for nil:NilClass
 app/helpers/prominence_helper.rb:7:in `conceled_prominence?'


-------------------------------
Request:
-------------------------------

 * URL        : https://www.whatdotheyknow.com/request/amount_of_payday_loan_companies_6
 * HTTP Method: GET
 * IP address : REDACTED
 * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"amount_of_payday_loan_companies_6"}
 * Timestamp  : 2022-11-08 13:37:42 +0000
 * Server : [REDACTED)
   * Rails root : /data/vhost/[www.whatdotheyknow.com/alaveteli-2022-11-08T09-04-26](http://www.whatdotheyknow.com/alaveteli-2022-11-08T09-04-26)

-------------------------------
Backtrace:
-------------------------------

 app/helpers/prominence_helper.rb:7:in `conceled_prominence?'
 app/views/request/_attachments.html.erb:48
 app/views/request/_attachments.html.erb:46
 app/views/request/_incoming_correspondence.html.erb:26
 app/views/request/events/_response.html.erb:1
 app/views/request/_correspondence.html.erb:5
 lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:47
 lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:45
 app/controllers/request_controller.rb:100:in `block (3 levels) in show'
 app/controllers/request_controller.rb:99:in `block in show'
 lib/alaveteli_localization.rb:46:in `with_locale'
 app/controllers/request_controller.rb:50:in `show'
 app/controllers/application_controller.rb:111:in `record_memory'
 lib/deeply_nested_params.rb:15:in `call'
 lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by garethrees** [comment]
I think this is likely being caused by incoming message 356442 of request ID 146833 – it's one with "[ Email has no body, please see attachments ]"
