### ISSUE TITLE
[ERROR] PG::FeatureNotSupported: ERROR:  conversion between UTF8 and SQL_ASCII is not supported

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7478]
Since #6949 if an admin edits and messages with some unicode characters can error. Sending requests with these characters works fine.

```
An ActiveRecord::StatementInvalid occurred in admin_outgoing_message#update:

  PG::FeatureNotSupported: ERROR:  conversion between UTF8 and SQL_ASCII is not supported

  app/models/info_request.rb:1145:in `log_event'


-------------------------------
Request:
-------------------------------

  * URL        : /admin/outgoing_messages/123
  * HTTP Method: PUT
  * Parameters : {"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"p0gTXC+iSE1mRzQhUR5CxCT+W4wZgrPSqrd4N9BR/MmB0Fb5NtXll4iNUPVkhTeQYHP6e3RONtGjiC2r4IHKIg==", "outgoing_message"=>{"tag_string"=>"", "prominence"=>"requester_only", "prominence_reason"=>"", "body"=>"... snip ... \u2028\u2028\r\n ... snip ..."}, "commit"=>"Save", "controller"=>"admin_outgoing_message", "action"=>"update", "id"=>"123"}

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request.rb:1145:in `log_event'
  app/controllers/admin_outgoing_message_controller.rb:32:in `update'
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Conversation on Slack

@garethrees 
local db might be created as utf8 rather than sql_ascii columns?

@garethrees 
Can’t remember the exact history with all  this,  but i vaguely remember WDTK doing something we’d have preferred it not to be doing. Can only find https://github.com/mysociety/alaveteli/pull/1576 from a quick look.

**Comment by garethrees** [comment]
https://github.com/mysociety/alaveteli/issues/1493#issuecomment-45904241 also possibly relevant

**Comment by garethrees** [comment]
Pretty sure [`lib/normalize_string.rb`](https://github.com/mysociety/alaveteli/blob/cdd70a3832402e8ed40156d209079fd799e00a3b/lib/normalize_string.rb) exists in relation to some of these issues.

**Comment by gbp** [comment]
Seen this when editing a comment from the admin:

https://groups.google.com/a/mysociety.org/g/cron-alaveteli/c/uChCR60JCIg/m/Vvgso1nGDQAJ

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
