### ISSUE TITLE
[ERROR] (ActionView::Template::Error) "Couldn't find OutgoingMessage with 'id'=0"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7682]
```
An ActionView::Template::Error occurred in admin_general#timeline:

  Couldn't find OutgoingMessage with 'id'=0
  app/views/admin_general/_edit_outgoing.html.erb:1


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/timeline
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_general", "action"=>"timeline"}
  * Timestamp  : 2023-01-31 17:38:31 +0000
  * Process: 1327817

-------------------------------
Session:
-------------------------------

  * data: {"session_id"=>snip,
   "locale"=>"en",
   "remember_me"=>true,
   "_csrf_token"=>snip,
   "user_id"=>snip,
   "user_login_token"=>snip,
   "using_admin"=>snip,
   "admin_name"=>snip}


-------------------------------
Backtrace:
-------------------------------

  app/views/admin_general/_edit_outgoing.html.erb:1
  app/views/admin_general/timeline.html.erb:59
  app/views/admin_general/timeline.html.erb:30:in `each'
  app/views/admin_general/timeline.html.erb:30
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
This is still an issue, looks like the PR above actually fixed a different event type.
