### ISSUE TITLE
[ERROR] admin_request#show (ActionView::Template::Error) "invalid email passed to address_from_name_and_email"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7693]
```
An ActionView::Template::Error occurred in admin_request#show:

  invalid email  passed to address_from_name_and_email
  lib/mail_handler/backends/mail_backend.rb:380:in `address_from_name_and_email'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/856713

-------------------------------
Backtrace:
-------------------------------

  lib/mail_handler/backends/mail_backend.rb:380:in `address_from_name_and_email'
  app/models/info_request.rb:1230:in `recipient_name_and_email'
  app/models/outgoing_message.rb:150:in `to'
  app/models/concerns/admin_column.rb:52:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:52:in `each'
  app/models/concerns/admin_column.rb:52:in `for_admin_column'
  app/views/admin_outgoing_message/_admin_columns.html.erb:3
  app/views/admin_request/show.html.erb:311
  app/views/admin_request/show.html.erb:284
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Outgoing messages, when displayed in the admin (via [admin columns](https://github.com/mysociety/alaveteli/blob/29b555af8dfb9d69a3c193814980d627c4a3dd20/app/models/outgoing_message.rb#L72)), shows the [`#to`](https://github.com/mysociety/alaveteli/blob/29b555af8dfb9d69a3c193814980d627c4a3dd20/app/models/outgoing_message.rb#L144-L152) method.

This doesn't load the address the outgoing message was sent to from the associated `InfoRequestEvent` rather the current to address of the `PublicBody`.

If the current address is empty then this error is raised.

We should look to change the admin column to pull the `to` from the event params.
