### ISSUE TITLE
Adding new locale to preexisting installation causes editing of authority to fail in admin interface

### ISSUE THREAD

**Issue by mlandauer** [mysociety/alaveteli#797]
To reproduce, setup a test installation with the test data by doing:

```
bundle exec rake db:drop
bundle exec rake db:setup
bundle exec ./script/load-sample-data
```

In `config/general.yml`:

```
AVAILABLE_LOCALES: 'en es'
DEFAULT_LOCALE: 'en'
```

Start the server:
`bundle exec ./script/server`

Go to the admin interface and edit the short name field of one of the authorities and hit save.

Things should work fine.

Now edit `config/general.yml`:

```
AVAILABLE_LOCALES: 'en es cy'
DEFAULT_LOCALE: 'en'
```

And restart the server and then do the same kind of edit in the admin interface. The server will throw a 500.

```
Completed in 162ms (View: 123, DB: 4) | 200 OK [http://localhost/en/admin/body/edit/3]
/!\ FAILSAFE /!\  Mon Feb 11 16:36:52 +1100 2013
  Status: 500 Internal Server Error
  expected Array (got Hash) for param `translated_versions'
    /Users/matthew/git/alaveteli/lib/rack_quote_monkeypatch.rb:49:in `normalize_params'
    /Users/matthew/git/alaveteli/lib/rack_quote_monkeypatch.rb:58:in `normalize_params'
```

**Comment by garethrees** [comment]
Similar issue reported at https://github.com/mysociety/alaveteli/issues/5903

**Comment by HelenWDTK** [comment]
This issue has been automatically closed due to a lack of discussion or resolution for over 12 months.
Should we decide to revisit this issue in the future, it can be reopened.
