### ISSUE TITLE
[ERROR] request#show "undefined method `unmasked_body' for nil:NilClass

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7971]
```
An ActionView::Template::Error occurred in request#show:

undefined method `unmasked_body' for nil:NilClass
app/jobs/foi_attachment_mask_job.rb:38:in `mask'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/request/snip
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"snip"}
* Timestamp : 2023-10-06 17:10:35 +0100
* Process: 3758574

-------------------------------
Backtrace:
-------------------------------

app/jobs/foi_attachment_mask_job.rb:38:in `mask'
app/jobs/foi_attachment_mask_job.rb:31:in `rescue in perform'
app/jobs/foi_attachment_mask_job.rb:18:in `perform'
app/jobs/foi_attachment_mask_job/uniqueness.rb:19:in `perform_once_now'
app/models/foi_attachment.rb:110:in `body'
app/models/foi_attachment.rb:121:in `body_as_text'
app/models/incoming_message.rb:358:in `_convert_part_body_to_text'
app/models/incoming_message.rb:349:in `get_main_body_text_internal'
app/models/incoming_message.rb:313:in `_cache_main_body_text'
app/models/incoming_message.rb:342:in `get_main_body_text_unfolded'
app/models/incoming_message.rb:493:in `get_body_for_html_display'
app/views/request/_attachments.html.erb:53
app/views/request/_attachments.html.erb:46
app/views/request/_incoming_correspondence.html.erb:26
app/views/request/events/_response.html.erb:1
app/views/request/_correspondence.html.erb:5
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:42
lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:40
app/controllers/request_controller.rb:100:in `block (3 levels) in show'
app/controllers/request_controller.rb:97:in `block in show'
lib/alaveteli_localization.rb:46:in `with_locale'
app/controllers/request_controller.rb:50:in `show'
app/controllers/application_controller.rb:111:in `record_memory'
lib/deeply_nested_params.rb:15:in `call'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Issue happens when old incoming messages haven't had their main body part cached in the `IncomingMessage#cache_main_body_text_*` columns.

The exception is caused by `FoiAttachmentMaskJob` can call `IncomingMessage#parse_raw_email!(true)` as the original attachment body couldn't be found. This can also means the old attachment is dropped from the database and new attachments created which is when the exception occurs.

This does means when reloading the page the issue has already been fixed.

Seems like it would be a WDTK only problem given the age of the site and amount old requests we have which aren't cached in the database.
