### ISSUE TITLE
[ERROR] ActiveStorage::FileNotFoundError app/models/foi_attachment.rb:140:in `rescue in unmasked_body'

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#8040]
```
-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/search/A%20name%20/requests?utf8=%E2%9C%93&sortby=&latest_status%5B%5D=awaiting&request_variety%5B%5D=sent&request_variety%5B%5D=response&request_variety%5B%5D=comment&request_date_after=&request_date_before=&commit=Filter
* HTTP Method: GET
* Parameters : {"utf8"=>"✓", "sortby"=>"", "latest_status"=>["awaiting"], "request_variety"=>["sent", "response", "comment"], "request_date_after"=>"", "request_date_before"=>"", "commit"=>"Filter", "controller"=>"general", "action"=>"search", "combined"=>"A name /requests"}
* Timestamp : 2023-11-11 08:43:59 +0000

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"[FILTERED]", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

app/models/foi_attachment.rb:140:in `rescue in unmasked_body'
app/models/foi_attachment.rb:132:in `unmasked_body'
app/jobs/foi_attachment_mask_job.rb:38:in `mask'
app/jobs/foi_attachment_mask_job.rb:20:in `perform'
app/jobs/foi_attachment_mask_job/uniqueness.rb:19:in `perform_once_now'
app/models/foi_attachment.rb:110:in `body'
app/models/foi_attachment.rb:121:in `body_as_text'
app/models/incoming_message.rb:363:in `_convert_part_body_to_text'
app/models/incoming_message.rb:349:in `get_main_body_text_internal'
app/models/incoming_message.rb:313:in `_cache_main_body_text'
app/models/incoming_message.rb:338:in `get_main_body_text_folded'
app/models/incoming_message.rb:544:in `get_body_for_quoting'
app/models/incoming_message.rb:538:in `get_body_for_indexing'
app/models/incoming_message.rb:601:in `get_text_for_indexing_clipped'
app/models/info_request_event.rb:516:in `get_clipped_response_efficiently'
app/models/info_request_event.rb:181:in `search_text_main'
app/views/request/_request_listing_via_event.html.erb:35
app/views/general/search.html.erb:211
app/views/general/search.html.erb:210:in `each'
app/views/general/search.html.erb:210
app/controllers/application_controller.rb:111:in `record_memory'
lib/deeply_nested_params.rb:15:in `call'
lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Also seeing:

```
-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/1/response/2/attach/3/filename.txt?cookie_passthrough=1
  * HTTP Method: GET
  * Parameters : {"cookie_passthrough"=>"1", "controller"=>"attachments", "action"=>"show", "id"=>"1", "incoming_message_id"=>"2", "part"=>"3", "file_name"=>"filename.txt"}

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"[FILTERED]",
   "locale"=>"en",
   "user_id"=>[FILTERED],
   "post_redirect_token"=>"[FILTERED]",
   "ttl"=>"[FILTERED]",
   "_csrf_token"=>"[FILTERED]"}

-------------------------------
Backtrace:
-------------------------------

  app/models/foi_attachment.rb:108:in `body'
  app/controllers/attachments_controller.rb:23:in `show'
  app/controllers/attachments_controller.rb:123:in `ensure_masked'
  app/controllers/application_controller.rb:112:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```
