### ISSUE TITLE
[ERROR] Could not determine which URL to request: Stripe::Charge instance has invalid ID: nil

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#8344]
```
An ActionView::Template::Error occurred in invoices#index:

  Could not determine which URL to request: Stripe::Charge instance has invalid ID: nil
  app/models/alaveteli_pro/invoice.rb:23:in `charge'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/profile/invoices
  * HTTP Method: GET
  * Parameters : {"controller"=>"alaveteli_pro/invoices", "action"=>"index"}
  * Timestamp  : 2024-07-29 14:42:02 +0100

-------------------------------
Session:
-------------------------------


  * data: {"session_id"=>"snip",
   "locale"=>"en",
   "user_id"=>snip,
   "remember_me"=>true,
   "post_redirect_token"=>"snip",
   "_csrf_token"=>"snip"}

-------------------------------
Backtrace:
-------------------------------

  app/models/alaveteli_pro/invoice.rb:23:in `charge'
  app/models/alaveteli_pro/invoice.rb:26:in `receipt_url'
  app/views/alaveteli_pro/invoices/_invoice.html.erb:9
  app/views/alaveteli_pro/invoices/index.html.erb:28
  app/controllers/application_controller.rb:126:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Happens when viewing invoices when there hasn't been a charge - ie when 100% discounted.
