### ISSUE TITLE
[ERROR] request#new (ActionView::Template::Error) "missing interpolation argument \" can_make_another_request".

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#8467]
```
An ActionView::Template::Error occurred in request#new:

  missing interpolation argument " can_make_another_request" in {:max_requests_per_user_per_day=>10, :can_make_another_request=>"tua 24 awr"} ("Rydych chi wedi cyrraedd y terfyn cyfradd ar geisiadau newydd. Fel arfer cyfyngir defnyddwyr i {{max_requests_per_user_per_day}}  cais mewn unrhyw gyfnod treigl 24-awr. Byddwch yn gallu gwneud cais arall ymhen {{ can_make_another_request}}." given)
  lib/i18n_fixes.rb:36:in `block in gettext_interpolate'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new/...?post_redirect=1
  * HTTP Method: GET
  * Parameters : {"post_redirect"=>"1", "controller"=>"request", "action"=>"new", "url_name"=>"..."}

-------------------------------
Backtrace:
-------------------------------

  lib/i18n_fixes.rb:36:in `block in gettext_interpolate'
  lib/i18n_fixes.rb:31:in `gsub'
  lib/i18n_fixes.rb:31:in `gettext_interpolate'
  lib/i18n_fixes.rb:10:in `_'
  app/views/user/rate_limited.html.erb:5
  app/controllers/request_controller.rb:202:in `new'
  app/controllers/application_controller.rb:126:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Extra space in the translated string - corrected in Transifex. Will need to patch the Welsh PO file until the next translation hotfix.
