### ISSUE TITLE
intermittent failures of /spec/models/purge_request_spec tests

### ISSUE THREAD

**Issue by mhl** [mysociety/alaveteli#916]
The tests in `/spec/models/purge_request_spec` seem to fail sporadically, and in a way which is dependent on the network one is on - for example (on `rails-3-develop`):

```
Failures:

  1) PurgeRequest purging things should fail silently for a misconfigured server
     Failure/Error: PurgeRequest.purge_all()
     Errno::EINVAL:
       Invalid argument - connect(2)
     # ./lib/quiet_opener.rb:22:in `quietly_try_to_purge'
     # ./lib/quiet_opener.rb:20:in `quietly_try_to_purge'
     # ./lib/quiet_opener.rb:19:in `quietly_try_to_purge'
     # ./app/models/purge_request.rb:45:in `purge'
     # ./app/models/purge_request.rb:24:in `purge_all'
     # ./app/models/purge_request.rb:23:in `each'
     # ./app/models/purge_request.rb:23:in `purge_all'
     # ./spec/models/purge_request_spec.rb:29

  2) PurgeRequest purging things should issue purge requests to the server
     Failure/Error: PurgeRequest.purge_all()
    Errno::EINVAL:
      Invalid argument - connect(2)
     # ./lib/quiet_opener.rb:22:in `quietly_try_to_purge'
     # ./lib/quiet_opener.rb:20:in `quietly_try_to_purge'
     # ./lib/quiet_opener.rb:19:in `quietly_try_to_purge'
     # ./app/models/purge_request.rb:45:in `purge'
     # ./app/models/purge_request.rb:24:in `purge_all'
     # ./app/models/purge_request.rb:23:in `each'
     # ./app/models/purge_request.rb:23:in `purge_all'
     # ./spec/models/purge_request_spec.rb:16

Failed examples:

rspec ./spec/models/purge_request_spec.rb:20 # PurgeRequest purging things should fail silently for a misconfigured server
rspec ./spec/models/purge_request_spec.rb:10 # PurgeRequest purging things should issue purge requests to the server
```

There's at least one oddity in these tests - it appears that FakeWeb is set up to match `brokenv`, but I don't see why the purge request should match that.

**Comment by garethrees** [comment]
Closing because we no longer use PurgeRequest https://github.com/mysociety/alaveteli/issues/4025
